import type { Situation } from '../../types/content';

export const SITUATIONS: Situation[] = [
  // ══ BUURT ════════════════════════════════════════════════════════════════
  // A1
  {
    id: 'sit-a1-buurt-01',
    scenario: 'Je ontmoet je nieuwe buur voor het eerst.',
    roleA: 'Nieuwe buur',
    roleB: 'Buur',
    levels: ['A1'],
    category: 'Buurt',
    tips: ['Zeg je naam.', 'Vraag hoe lang de ander hier woont.'],
  },
  {
    id: 'sit-a1-buurt-02',
    scenario: 'Je bent verdwaald en vraagt de weg naar het station.',
    roleA: 'Voorbijganger',
    roleB: 'Bewoner',
    levels: ['A1'],
    category: 'Buurt',
    tips: ['Zeg waar je heen wilt.', 'Bedank de ander.'],
  },
  {
    id: 'sit-a1-buurt-03',
    scenario: 'Je vraagt bij de bushalte welke bus naar het centrum gaat.',
    roleA: 'Reiziger',
    roleB: 'Medereiziger',
    levels: ['A1'],
    category: 'Buurt',
    tips: ['Vraag naar het busnummer.', 'Vraag waar je moet wachten.'],
  },
  {
    id: 'sit-a1-buurt-04',
    scenario: 'Je vraagt in een winkel hoe laat ze sluiten.',
    roleA: 'Klant',
    roleB: 'Verkoper',
    levels: ['A1'],
    category: 'Buurt',
    tips: ['Vraag de sluitingstijd.', 'Bedank de verkoper.'],
  },
  {
    id: 'sit-a1-buurt-05',
    scenario: 'Je buurman heeft een pakketje voor je en je haalt het op.',
    roleA: 'Bewoner',
    roleB: 'Buurman',
    levels: ['A1'],
    category: 'Buurt',
    tips: ['Vraag naar het pakketje.', 'Zeg bedankt.'],
  },
  {
    id: 'sit-a1-buurt-06',
    scenario: 'Je fiets is kapot en je vraagt waar een fietsenmaker is.',
    roleA: 'Voorbijganger',
    roleB: 'Bewoner',
    levels: ['A1'],
    category: 'Buurt',
    tips: ['Leg uit wat er kapot is.', 'Vraag waar de fietsenmaker is.'],
  },
  {
    id: 'sit-a1-buurt-07',
    scenario: 'Je vraagt of je de hond van iemand mag aaien.',
    roleA: 'Voorbijganger',
    roleB: 'Hondenbezitter',
    levels: ['A1'],
    category: 'Buurt',
    tips: ['Vraag het vriendelijk.', 'Vraag hoe de hond heet.'],
  },
  {
    id: 'sit-a1-buurt-08',
    scenario: 'Je bent je sleutel kwijt en vraagt de buurman om hulp.',
    roleA: 'Bewoner',
    roleB: 'Buurman',
    levels: ['A1'],
    category: 'Buurt',
    tips: ['Leg het probleem uit.', 'Vraag vriendelijk om hulp.'],
  },
  {
    id: 'sit-a1-buurt-09',
    scenario: 'Je vraagt op de markt waar de groentekraam staat.',
    roleA: 'Klant',
    roleB: 'Marktverkoper',
    levels: ['A1'],
    category: 'Buurt',
    tips: ['Vraag naar de kraam.', 'Bedank de verkoper.'],
  },
  {
    id: 'sit-a1-buurt-10',
    scenario: 'Je vraagt of je naast iemand op de parkbank mag zitten.',
    roleA: 'Wandelaar',
    roleB: 'Bezoeker',
    levels: ['A1'],
    category: 'Buurt',
    tips: ['Vraag het beleefd.', 'Maak een praatje over het weer.'],
  },
  // A2
  {
    id: 'sit-a2-buurt-01',
    scenario: 'Je vraagt je buren vriendelijk om wat zachter te doen.',
    roleA: 'Bewoner',
    roleB: 'Buurman',
    levels: ['A2'],
    category: 'Buurt',
    tips: ['Blijf vriendelijk.', 'Leg uit waarom je het vraagt.'],
  },
  {
    id: 'sit-a2-buurt-02',
    scenario: 'Je nodigt een buur uit voor het buurtfeest.',
    roleA: 'Organisator',
    roleB: 'Buur',
    levels: ['A2'],
    category: 'Buurt',
    tips: ['Zeg wanneer het is.', 'Vertel wat er te doen is.'],
  },
  {
    id: 'sit-a2-buurt-03',
    scenario: 'Je vraagt je buur of hij kan helpen met verhuizen.',
    roleA: 'Bewoner',
    roleB: 'Buurman',
    levels: ['A2'],
    category: 'Buurt',
    tips: ['Zeg wanneer je hulp nodig hebt.', 'Bedank alvast.'],
  },
  {
    id: 'sit-a2-buurt-04',
    scenario: 'Je vraagt in de bibliotheek hoe je lid kunt worden.',
    roleA: 'Bezoeker',
    roleB: 'Medewerker',
    levels: ['A2'],
    category: 'Buurt',
    tips: ['Vraag wat je nodig hebt.', 'Vraag wat het kost.'],
  },
  {
    id: 'sit-a2-buurt-05',
    scenario: 'Je krijgt een pakket dat niet van jou is en regelt het met de bezorger.',
    roleA: 'Bewoner',
    roleB: 'Bezorger',
    levels: ['A2'],
    category: 'Buurt',
    tips: ['Leg uit dat het niet klopt.', 'Vraag wat je moet doen.'],
  },
  {
    id: 'sit-a2-buurt-06',
    scenario: 'Je meldt bij de wijkagent dat je fiets is gestolen.',
    roleA: 'Bewoner',
    roleB: 'Wijkagent',
    levels: ['A2'],
    category: 'Buurt',
    tips: ['Beschrijf de fiets.', 'Vertel waar het gebeurde.'],
  },
  {
    id: 'sit-a2-buurt-07',
    scenario: 'Je vraagt een andere ouder in de speeltuin hoe oud hun kind is.',
    roleA: 'Ouder',
    roleB: 'Andere ouder',
    levels: ['A2'],
    category: 'Buurt',
    tips: ['Maak een praatje.', 'Vertel ook over je eigen kind.'],
  },
  {
    id: 'sit-a2-buurt-08',
    scenario: 'Je vraagt bij de gemeentebalie hoe je je adres kunt wijzigen.',
    roleA: 'Inwoner',
    roleB: 'Baliemedewerker',
    levels: ['A2'],
    category: 'Buurt',
    tips: ['Leg uit wat je wilt.', 'Vraag welke papieren je nodig hebt.'],
  },
  {
    id: 'sit-a2-buurt-09',
    scenario: 'Een buur vertelt je over leuke plekken in de wijk.',
    roleA: 'Nieuwkomer',
    roleB: 'Buur',
    levels: ['A2'],
    category: 'Buurt',
    tips: ['Stel vragen over de wijk.', 'Vraag naar tips.'],
  },
  {
    id: 'sit-a2-buurt-10',
    scenario: 'Je vraagt een buur op welke dag het afval wordt opgehaald.',
    roleA: 'Nieuwkomer',
    roleB: 'Buur',
    levels: ['A2'],
    category: 'Buurt',
    tips: ['Vraag naar de dagen.', 'Vraag hoe het afval scheiden werkt.'],
  },
  // B1
  {
    id: 'sit-b1-buurt-01',
    scenario: 'Je bespreekt met je buur een conflict over de gedeelde tuin.',
    roleA: 'Bewoner',
    roleB: 'Buurman',
    levels: ['B1'],
    category: 'Buurt',
    tips: ['Blijf rustig.', 'Zoek samen een oplossing.'],
  },
  {
    id: 'sit-b1-buurt-02',
    scenario: 'Je probeert buren te overtuigen om samen de straat op te knappen.',
    roleA: 'Initiatiefnemer',
    roleB: 'Buurtbewoner',
    levels: ['B1'],
    category: 'Buurt',
    tips: ['Leg je plan uit.', 'Vraag wat de ander kan bijdragen.'],
  },
  {
    id: 'sit-b1-buurt-03',
    scenario: 'Je legt bij de gemeente uit dat de straatverlichting kapot en gevaarlijk is.',
    roleA: 'Inwoner',
    roleB: 'Ambtenaar',
    levels: ['B1'],
    category: 'Buurt',
    tips: ['Beschrijf het probleem.', 'Vraag wanneer het wordt opgelost.'],
  },
  {
    id: 'sit-b1-buurt-04',
    scenario: 'Je heet een nieuwkomer welkom en legt de buurtgewoonten uit.',
    roleA: 'Buur',
    roleB: 'Nieuwkomer',
    levels: ['B1'],
    category: 'Buurt',
    tips: ['Vertel over de buurt.', 'Bied je hulp aan.'],
  },
  {
    id: 'sit-b1-buurt-05',
    scenario: 'Je spreekt een buur aan op rommel die hij steeds laat staan.',
    roleA: 'Bewoner',
    roleB: 'Buurman',
    levels: ['B1'],
    category: 'Buurt',
    tips: ['Wees beleefd maar duidelijk.', 'Stel een oplossing voor.'],
  },
  {
    id: 'sit-b1-buurt-06',
    scenario: 'Je meldt je aan als vrijwilliger bij het buurthuis.',
    roleA: 'Vrijwilliger',
    roleB: 'Coördinator',
    levels: ['B1'],
    category: 'Buurt',
    tips: ['Vertel wat je kunt.', 'Vraag wat er nodig is.'],
  },
  {
    id: 'sit-b1-buurt-07',
    scenario: "Je bespreekt met de wijkagent dat je je 's avonds onveilig voelt.",
    roleA: 'Bewoner',
    roleB: 'Wijkagent',
    levels: ['B1'],
    category: 'Buurt',
    tips: ['Leg uit waarom.', 'Vraag wat eraan gedaan kan worden.'],
  },
  {
    id: 'sit-b1-buurt-08',
    scenario: 'Je bespreekt met een buur het tekort aan parkeerplekken.',
    roleA: 'Bewoner',
    roleB: 'Buurman',
    levels: ['B1'],
    category: 'Buurt',
    tips: ['Deel je zorgen.', 'Bedenk samen ideeën.'],
  },
  {
    id: 'sit-b1-buurt-09',
    scenario: 'Je legt een oudere buur uit hoe de buurtapp werkt.',
    roleA: 'Bewoner',
    roleB: 'Oudere buur',
    levels: ['B1'],
    category: 'Buurt',
    tips: ['Leg het stap voor stap uit.', 'Vraag of het duidelijk is.'],
  },
  {
    id: 'sit-b1-buurt-10',
    scenario: 'Je waarschuwt je buren dat je gaat verbouwen en bespreekt de overlast.',
    roleA: 'Bewoner',
    roleB: 'Buurman',
    levels: ['B1'],
    category: 'Buurt',
    tips: ['Zeg wanneer het begint.', 'Bied excuses aan voor het lawaai.'],
  },
  // B2
  {
    id: 'sit-b2-buurt-01',
    scenario: 'Je geeft op een inspraakavond je mening over een nieuw bouwplan.',
    roleA: 'Bewoner',
    roleB: 'Projectontwikkelaar',
    levels: ['B2'],
    category: 'Buurt',
    tips: ['Onderbouw je mening.', 'Stel concrete vragen.'],
  },
  {
    id: 'sit-b2-buurt-02',
    scenario: 'Je bemiddelt tussen twee buren die ruzie hebben.',
    roleA: 'Bemiddelaar',
    roleB: 'Buurtbewoner',
    levels: ['B2'],
    category: 'Buurt',
    tips: ['Laat beide kanten praten.', 'Zoek een compromis.'],
  },
  {
    id: 'sit-b2-buurt-03',
    scenario: 'Je bespreekt met een ambtenaar je zorgen dat de buurt te duur wordt.',
    roleA: 'Bewoner',
    roleB: 'Ambtenaar',
    levels: ['B2'],
    category: 'Buurt',
    tips: ['Geef voorbeelden.', 'Vraag naar mogelijke maatregelen.'],
  },
  {
    id: 'sit-b2-buurt-04',
    scenario: 'Je overtuigt buren om samen actie te voeren tegen het kappen van bomen.',
    roleA: 'Activist',
    roleB: 'Buurtbewoner',
    levels: ['B2'],
    category: 'Buurt',
    tips: ['Leg je argumenten uit.', 'Vraag om steun.'],
  },
  {
    id: 'sit-b2-buurt-05',
    scenario: 'Je bespreekt met een buurtwerker hoe je de wijk meer kunt verbinden.',
    roleA: 'Bewoner',
    roleB: 'Buurtwerker',
    levels: ['B2'],
    category: 'Buurt',
    tips: ['Deel je ideeën.', 'Bespreek wat haalbaar is.'],
  },
  {
    id: 'sit-b2-buurt-06',
    scenario: 'Je bespreekt met een buur jullie verschillende ideeën over de buurt.',
    roleA: 'Bewoner',
    roleB: 'Buurman',
    levels: ['B2'],
    category: 'Buurt',
    tips: ['Luister naar de ander.', 'Leg je eigen kijk rustig uit.'],
  },
  {
    id: 'sit-b2-buurt-07',
    scenario: 'Je houdt een kort betoog in de gemeenteraad over leefbaarheid.',
    roleA: 'Inwoner',
    roleB: 'Raadslid',
    levels: ['B2'],
    category: 'Buurt',
    tips: ['Houd het kort en helder.', 'Doe een concreet voorstel.'],
  },
  {
    id: 'sit-b2-buurt-08',
    scenario: 'Je presenteert een plan om buurtbudget te besteden aan groen.',
    roleA: 'Initiatiefnemer',
    roleB: 'Commissielid',
    levels: ['B2'],
    category: 'Buurt',
    tips: ['Leg de kosten uit.', 'Noem de voordelen.'],
  },
  {
    id: 'sit-b2-buurt-09',
    scenario: 'Je beargumenteert waarom de buurt een nieuwe speelplek nodig heeft.',
    roleA: 'Bewoner',
    roleB: 'Ambtenaar',
    levels: ['B2'],
    category: 'Buurt',
    tips: ['Onderbouw met voorbeelden.', 'Vraag naar de procedure.'],
  },
  {
    id: 'sit-b2-buurt-10',
    scenario: 'Je praat met een oude bewoner over hoe de buurt is veranderd.',
    roleA: 'Onderzoeker',
    roleB: 'Bewoner',
    levels: ['B2'],
    category: 'Buurt',
    tips: ['Stel open vragen.', 'Vraag door op herinneringen.'],
  },

  // ══ FAMILIE ══════════════════════════════════════════════════════════════
  // A1
  {
    id: 'sit-a1-familie-01',
    scenario: 'Je stelt je voor aan de moeder van een vriend.',
    roleA: 'Bezoeker',
    roleB: 'Moeder',
    levels: ['A1'],
    category: 'Familie',
    tips: ['Zeg je naam.', 'Wees vriendelijk.'],
  },
  {
    id: 'sit-a1-familie-02',
    scenario: 'Je feliciteert iemand met zijn verjaardag.',
    roleA: 'Gast',
    roleB: 'Jarige',
    levels: ['A1'],
    category: 'Familie',
    tips: ['Zeg gefeliciteerd.', 'Vraag hoe hij viert.'],
  },
  {
    id: 'sit-a1-familie-03',
    scenario: 'Je laat een foto van je familie zien en vertelt wie wie is.',
    roleA: 'Verteller',
    roleB: 'Luisteraar',
    levels: ['A1'],
    category: 'Familie',
    tips: ['Noem de namen.', 'Vertel wie wie is.'],
  },
  {
    id: 'sit-a1-familie-04',
    scenario: 'Je geeft een cadeau aan een familielid.',
    roleA: 'Gever',
    roleB: 'Ontvanger',
    levels: ['A1'],
    category: 'Familie',
    tips: ['Zeg waarom je het geeft.', 'Reageer blij.'],
  },
  {
    id: 'sit-a1-familie-05',
    scenario: 'Je belt je moeder om te vragen hoe het gaat.',
    roleA: 'Beller',
    roleB: 'Moeder',
    levels: ['A1'],
    category: 'Familie',
    tips: ['Vraag hoe het gaat.', 'Vertel over je dag.'],
  },
  {
    id: 'sit-a1-familie-06',
    scenario: 'Je vraagt een familielid of die koffie of thee wil.',
    roleA: 'Gastheer',
    roleB: 'Gast',
    levels: ['A1'],
    category: 'Familie',
    tips: ['Bied iets te drinken aan.', 'Vraag wat de ander wil.'],
  },
  {
    id: 'sit-a1-familie-07',
    scenario: 'Je vraagt of je het kind van een vriend mag ophalen van school.',
    roleA: 'Ouder',
    roleB: 'Vriend',
    levels: ['A1'],
    category: 'Familie',
    tips: ['Zeg hoe laat.', 'Vraag waar de school is.'],
  },
  {
    id: 'sit-a1-familie-08',
    scenario: 'Je vraagt hoe de broer van je vriend heet.',
    roleA: 'Vrager',
    roleB: 'Vriend',
    levels: ['A1'],
    category: 'Familie',
    tips: ['Stel een korte vraag.', 'Vraag hoe oud hij is.'],
  },
  {
    id: 'sit-a1-familie-09',
    scenario: 'Je nodigt je buurvrouw uit om langs te komen.',
    roleA: 'Gastheer',
    roleB: 'Buurvrouw',
    levels: ['A1'],
    category: 'Familie',
    tips: ['Zeg wanneer.', 'Wees vriendelijk.'],
  },
  {
    id: 'sit-a1-familie-10',
    scenario: 'Je vraagt je familie wat ze willen eten vanavond.',
    roleA: 'Kok',
    roleB: 'Familielid',
    levels: ['A1'],
    category: 'Familie',
    tips: ['Geef twee keuzes.', 'Vraag wat ze lekker vinden.'],
  },
  // A2
  {
    id: 'sit-a2-familie-01',
    scenario: 'Je plant samen een verjaardagsfeest.',
    roleA: 'Familielid',
    roleB: 'Familielid',
    levels: ['A2'],
    category: 'Familie',
    tips: ['Bespreek wie je uitnodigt.', 'Verdeel de taken.'],
  },
  {
    id: 'sit-a2-familie-02',
    scenario: 'Je stelt een nieuwe vriend voor aan je familie.',
    roleA: 'Gastheer',
    roleB: 'Vriend',
    levels: ['A2'],
    category: 'Familie',
    tips: ['Vertel iets over je vriend.', 'Help het gesprek op gang.'],
  },
  {
    id: 'sit-a2-familie-03',
    scenario: 'Je maakt het goed met een vriend na een kleine ruzie.',
    roleA: 'Vriend',
    roleB: 'Vriend',
    levels: ['A2'],
    category: 'Familie',
    tips: ['Zeg sorry.', 'Leg uit hoe je je voelde.'],
  },
  {
    id: 'sit-a2-familie-04',
    scenario: 'Je vraagt een familielid om hulp met een formulier.',
    roleA: 'Vrager',
    roleB: 'Familielid',
    levels: ['A2'],
    category: 'Familie',
    tips: ['Leg uit wat moeilijk is.', 'Bedank voor de hulp.'],
  },
  {
    id: 'sit-a2-familie-05',
    scenario: 'Je spreekt af om op te passen op de kinderen van een vriend.',
    roleA: 'Oppas',
    roleB: 'Ouder',
    levels: ['A2'],
    category: 'Familie',
    tips: ['Vraag naar de regels.', 'Bespreek de tijden.'],
  },
  {
    id: 'sit-a2-familie-06',
    scenario: 'Je belt familie om te zeggen dat je langskomt.',
    roleA: 'Beller',
    roleB: 'Familielid',
    levels: ['A2'],
    category: 'Familie',
    tips: ['Zeg wanneer je komt.', 'Vraag of het uitkomt.'],
  },
  {
    id: 'sit-a2-familie-07',
    scenario: 'Je maakt een praatje met iemand om vrienden te worden.',
    roleA: 'Nieuwkomer',
    roleB: 'Buurtgenoot',
    levels: ['A2'],
    category: 'Familie',
    tips: ['Stel vragen.', 'Vertel iets over jezelf.'],
  },
  {
    id: 'sit-a2-familie-08',
    scenario: 'Je overlegt met een familielid welk cadeau jullie kopen.',
    roleA: 'Familielid',
    roleB: 'Familielid',
    levels: ['A2'],
    category: 'Familie',
    tips: ['Geef ideeën.', 'Bespreek het budget.'],
  },
  {
    id: 'sit-a2-familie-09',
    scenario: 'Je vertelt een familielid over een leuke herinnering.',
    roleA: 'Verteller',
    roleB: 'Familielid',
    levels: ['A2'],
    category: 'Familie',
    tips: ['Vertel wat er gebeurde.', 'Vertel hoe je je voelde.'],
  },
  {
    id: 'sit-a2-familie-10',
    scenario: 'Je maakt een afspraak om met een vriend af te spreken.',
    roleA: 'Vriend',
    roleB: 'Vriend',
    levels: ['A2'],
    category: 'Familie',
    tips: ['Stel een dag voor.', 'Bespreek wat jullie gaan doen.'],
  },
  // B1
  {
    id: 'sit-b1-familie-01',
    scenario: 'Je vertelt een vriend dat je je zorgen maakt over iets.',
    roleA: 'Verteller',
    roleB: 'Vriend',
    levels: ['B1'],
    category: 'Familie',
    tips: ['Leg uit wat je dwarszit.', 'Vraag om een luisterend oor.'],
  },
  {
    id: 'sit-b1-familie-02',
    scenario: 'Je vraagt een familielid om advies over een moeilijke keuze.',
    roleA: 'Vrager',
    roleB: 'Familielid',
    levels: ['B1'],
    category: 'Familie',
    tips: ['Leg de keuze uit.', 'Vraag naar hun ervaring.'],
  },
  {
    id: 'sit-b1-familie-03',
    scenario: 'Je legt een vriend uit hoe jouw familie een feestdag viert.',
    roleA: 'Verteller',
    roleB: 'Vriend',
    levels: ['B1'],
    category: 'Familie',
    tips: ['Beschrijf de gewoonten.', 'Vertel waarom het belangrijk is.'],
  },
  {
    id: 'sit-b1-familie-04',
    scenario: 'Je bespreekt met een ouder een verschil van mening.',
    roleA: 'Kind',
    roleB: 'Ouder',
    levels: ['B1'],
    category: 'Familie',
    tips: ['Blijf respectvol.', 'Leg je eigen kant uit.'],
  },
  {
    id: 'sit-b1-familie-05',
    scenario: 'Je troost een vriend die een moeilijke tijd heeft.',
    roleA: 'Vriend',
    roleB: 'Vriend',
    levels: ['B1'],
    category: 'Familie',
    tips: ['Luister goed.', 'Bied je hulp aan.'],
  },
  {
    id: 'sit-b1-familie-06',
    scenario: 'Je legt een familielid vriendelijk uit dat je iets niet kunt doen.',
    roleA: 'Verteller',
    roleB: 'Familielid',
    levels: ['B1'],
    category: 'Familie',
    tips: ['Wees eerlijk.', 'Leg de reden uit.'],
  },
  {
    id: 'sit-b1-familie-07',
    scenario: 'Je probeert twee familieleden weer met elkaar te laten praten.',
    roleA: 'Bemiddelaar',
    roleB: 'Familielid',
    levels: ['B1'],
    category: 'Familie',
    tips: ['Blijf neutraal.', 'Benoem wat ze gemeen hebben.'],
  },
  {
    id: 'sit-b1-familie-08',
    scenario: 'Je vertelt je familie dat je gaat verhuizen.',
    roleA: 'Verteller',
    roleB: 'Familielid',
    levels: ['B1'],
    category: 'Familie',
    tips: ['Leg uit waarom.', 'Stel ze gerust over contact.'],
  },
  {
    id: 'sit-b1-familie-09',
    scenario: 'Je biedt een vriend aan om te helpen in een moeilijke periode.',
    roleA: 'Vriend',
    roleB: 'Vriend',
    levels: ['B1'],
    category: 'Familie',
    tips: ['Vraag wat hij nodig heeft.', 'Doe een concreet aanbod.'],
  },
  {
    id: 'sit-b1-familie-10',
    scenario: 'Je spreekt met familie in het buitenland over hoe het gaat.',
    roleA: 'Beller',
    roleB: 'Familielid',
    levels: ['B1'],
    category: 'Familie',
    tips: ['Deel je nieuws.', 'Vraag naar hun leven.'],
  },
  // B2
  {
    id: 'sit-b2-familie-01',
    scenario: 'Je bespreekt met een ouder familielid jullie verschillende ideeën over opvoeding.',
    roleA: 'Jonger familielid',
    roleB: 'Ouder familielid',
    levels: ['B2'],
    category: 'Familie',
    tips: ['Respecteer hun ervaring.', 'Leg je eigen visie uit.'],
  },
  {
    id: 'sit-b2-familie-02',
    scenario: 'Je voert een eerlijk gesprek met een vriend over iets wat je dwarszit.',
    roleA: 'Vriend',
    roleB: 'Vriend',
    levels: ['B2'],
    category: 'Familie',
    tips: ['Spreek vanuit jezelf.', 'Blijf rustig en open.'],
  },
  {
    id: 'sit-b2-familie-03',
    scenario: 'Je bespreekt met je familie dat hun verwachtingen je onder druk zetten.',
    roleA: 'Verteller',
    roleB: 'Familielid',
    levels: ['B2'],
    category: 'Familie',
    tips: ['Benoem je gevoelens.', 'Stel een grens.'],
  },
  {
    id: 'sit-b2-familie-04',
    scenario: 'Je zoekt verzoening na een lang conflict in de familie.',
    roleA: 'Familielid',
    roleB: 'Familielid',
    levels: ['B2'],
    category: 'Familie',
    tips: ['Erken het verleden.', 'Doe een stap vooruit.'],
  },
  {
    id: 'sit-b2-familie-05',
    scenario: 'Je legt je familie uit waarom je een onverwachte levenskeuze maakt.',
    roleA: 'Verteller',
    roleB: 'Familielid',
    levels: ['B2'],
    category: 'Familie',
    tips: ['Onderbouw je keuze.', 'Luister naar hun zorgen.'],
  },
  {
    id: 'sit-b2-familie-06',
    scenario: 'Je bespreekt met je partner een eerlijkere verdeling van taken.',
    roleA: 'Partner',
    roleB: 'Partner',
    levels: ['B2'],
    category: 'Familie',
    tips: ['Geef concrete voorbeelden.', 'Zoek samen een oplossing.'],
  },
  {
    id: 'sit-b2-familie-07',
    scenario: 'Je neemt afscheid van een familielid dat terug naar het buitenland gaat.',
    roleA: 'Familielid',
    roleB: 'Familielid',
    levels: ['B2'],
    category: 'Familie',
    tips: ['Deel wat je voelt.', 'Maak afspraken over contact.'],
  },
  {
    id: 'sit-b2-familie-08',
    scenario: 'Je bespreekt met een vriend dat jullie uit elkaar zijn gegroeid.',
    roleA: 'Vriend',
    roleB: 'Vriend',
    levels: ['B2'],
    category: 'Familie',
    tips: ['Wees eerlijk maar mild.', 'Waardeer wat er was.'],
  },
  {
    id: 'sit-b2-familie-09',
    scenario: 'Je geeft een jonger familielid advies over een belangrijke beslissing.',
    roleA: 'Mentor',
    roleB: 'Jonger familielid',
    levels: ['B2'],
    category: 'Familie',
    tips: ['Stel vragen in plaats van te oordelen.', 'Deel je ervaring.'],
  },
  {
    id: 'sit-b2-familie-10',
    scenario: 'Je bespreekt met een vriend hoe cultuurverschillen jullie vriendschap beïnvloeden.',
    roleA: 'Vriend',
    roleB: 'Vriend',
    levels: ['B2'],
    category: 'Familie',
    tips: ['Wees nieuwsgierig.', 'Benoem wat je waardeert.'],
  },

  // ══ WERK ═════════════════════════════════════════════════════════════════
  // A1
  {
    id: 'sit-a1-werk-01',
    scenario: 'Je stelt jezelf voor bij een werkgever.',
    roleA: 'Sollicitant',
    roleB: 'Werkgever',
    levels: ['A1'],
    category: 'Werk',
    tips: ['Zeg je naam.', 'Vertel wat je kunt.'],
  },
  {
    id: 'sit-a1-werk-02',
    scenario: 'Je begroet een nieuwe collega op je eerste werkdag.',
    roleA: 'Nieuwe collega',
    roleB: 'Collega',
    levels: ['A1'],
    category: 'Werk',
    tips: ['Zeg je naam.', 'Wees vriendelijk.'],
  },
  {
    id: 'sit-a1-werk-03',
    scenario: 'Je vraagt je collega mee om koffie te drinken in de pauze.',
    roleA: 'Collega',
    roleB: 'Collega',
    levels: ['A1'],
    category: 'Werk',
    tips: ['Vraag het vriendelijk.', 'Stel een tijd voor.'],
  },
  {
    id: 'sit-a1-werk-04',
    scenario: 'Je vraagt de docent om iets nog een keer uit te leggen.',
    roleA: 'Cursist',
    roleB: 'Docent',
    levels: ['A1'],
    category: 'Werk',
    tips: ['Zeg wat je niet snapt.', 'Bedank voor de uitleg.'],
  },
  {
    id: 'sit-a1-werk-05',
    scenario: 'Je belt je werk om te zeggen dat je iets later bent.',
    roleA: 'Werknemer',
    roleB: 'Baas',
    levels: ['A1'],
    category: 'Werk',
    tips: ['Zeg hoe laat je er bent.', 'Zeg sorry.'],
  },
  {
    id: 'sit-a1-werk-06',
    scenario: 'Je vraagt je baas wat je vandaag moet doen.',
    roleA: 'Werknemer',
    roleB: 'Baas',
    levels: ['A1'],
    category: 'Werk',
    tips: ['Stel een duidelijke vraag.', 'Vraag door als iets onduidelijk is.'],
  },
  {
    id: 'sit-a1-werk-07',
    scenario: 'Je belt je werk om te zeggen dat je ziek bent.',
    roleA: 'Werknemer',
    roleB: 'Baas',
    levels: ['A1'],
    category: 'Werk',
    tips: ['Zeg dat je ziek bent.', 'Zeg dat je niet kunt komen.'],
  },
  {
    id: 'sit-a1-werk-08',
    scenario: 'Je vraagt een klasgenoot of je een pen mag lenen.',
    roleA: 'Cursist',
    roleB: 'Cursist',
    levels: ['A1'],
    category: 'Werk',
    tips: ['Vraag het beleefd.', 'Zeg bedankt.'],
  },
  {
    id: 'sit-a1-werk-09',
    scenario: 'Je vraagt je baas of je een dag vrij mag.',
    roleA: 'Werknemer',
    roleB: 'Baas',
    levels: ['A1'],
    category: 'Werk',
    tips: ['Zeg welke dag.', 'Vraag of het kan.'],
  },
  {
    id: 'sit-a1-werk-10',
    scenario: 'Je vraagt een collega waar de kantine is.',
    roleA: 'Nieuwe collega',
    roleB: 'Collega',
    levels: ['A1'],
    category: 'Werk',
    tips: ['Stel een korte vraag.', 'Bedank de collega.'],
  },
  // A2
  {
    id: 'sit-a2-werk-01',
    scenario: 'Je vertelt in een gesprek over je werkervaring.',
    roleA: 'Sollicitant',
    roleB: 'Werkgever',
    levels: ['A2'],
    category: 'Werk',
    tips: ['Noem je vorige werk.', 'Vertel wat je goed kunt.'],
  },
  {
    id: 'sit-a2-werk-02',
    scenario: 'Je legt een nieuwe collega uit hoe een taak werkt.',
    roleA: 'Collega',
    roleB: 'Nieuwe collega',
    levels: ['A2'],
    category: 'Werk',
    tips: ['Leg het stap voor stap uit.', 'Vraag of het duidelijk is.'],
  },
  {
    id: 'sit-a2-werk-03',
    scenario: 'Je vertelt je baas dat je een fout hebt gemaakt.',
    roleA: 'Werknemer',
    roleB: 'Baas',
    levels: ['A2'],
    category: 'Werk',
    tips: ['Wees eerlijk.', 'Stel een oplossing voor.'],
  },
  {
    id: 'sit-a2-werk-04',
    scenario: 'Je vraagt je baas of je een cursus mag volgen.',
    roleA: 'Werknemer',
    roleB: 'Baas',
    levels: ['A2'],
    category: 'Werk',
    tips: ['Leg uit wat je wilt leren.', 'Noem het voordeel voor het werk.'],
  },
  {
    id: 'sit-a2-werk-05',
    scenario: 'Je bespreekt met je baas je werktijden.',
    roleA: 'Werknemer',
    roleB: 'Baas',
    levels: ['A2'],
    category: 'Werk',
    tips: ['Zeg welke tijden je wilt.', 'Leg uit waarom.'],
  },
  {
    id: 'sit-a2-werk-06',
    scenario: 'Je biedt een collega aan om te helpen met een drukke taak.',
    roleA: 'Collega',
    roleB: 'Collega',
    levels: ['A2'],
    category: 'Werk',
    tips: ['Vraag waar hulp nodig is.', 'Doe een concreet aanbod.'],
  },
  {
    id: 'sit-a2-werk-07',
    scenario: 'Je bespreekt met de docent je voortgang in de cursus.',
    roleA: 'Cursist',
    roleB: 'Docent',
    levels: ['A2'],
    category: 'Werk',
    tips: ['Vraag hoe je het doet.', 'Vraag wat je kunt verbeteren.'],
  },
  {
    id: 'sit-a2-werk-08',
    scenario: 'Je stelt jezelf voor aan het team.',
    roleA: 'Nieuwe collega',
    roleB: 'Teamlid',
    levels: ['A2'],
    category: 'Werk',
    tips: ['Vertel iets over jezelf.', 'Stel een vraag aan het team.'],
  },
  {
    id: 'sit-a2-werk-09',
    scenario: 'Je vraagt of een werkafspraak verzet kan worden.',
    roleA: 'Werknemer',
    roleB: 'Collega',
    levels: ['A2'],
    category: 'Werk',
    tips: ['Leg uit waarom.', 'Stel een nieuwe tijd voor.'],
  },
  {
    id: 'sit-a2-werk-10',
    scenario: 'Je vraagt je baas hoe je het doet op je werk.',
    roleA: 'Werknemer',
    roleB: 'Baas',
    levels: ['A2'],
    category: 'Werk',
    tips: ['Vraag om feedback.', 'Vraag wat beter kan.'],
  },
  // B1
  {
    id: 'sit-b1-werk-01',
    scenario: 'Je bespreekt met je baas een hoger salaris.',
    roleA: 'Werknemer',
    roleB: 'Baas',
    levels: ['B1'],
    category: 'Werk',
    tips: ['Noem je prestaties.', 'Wees duidelijk over je wens.'],
  },
  {
    id: 'sit-b1-werk-02',
    scenario: 'Je bespreekt een meningsverschil met een collega.',
    roleA: 'Collega',
    roleB: 'Collega',
    levels: ['B1'],
    category: 'Werk',
    tips: ['Blijf rustig.', 'Zoek een oplossing.'],
  },
  {
    id: 'sit-b1-werk-03',
    scenario: 'Je legt uit waarom jij geschikt bent voor de baan.',
    roleA: 'Sollicitant',
    roleB: 'Werkgever',
    levels: ['B1'],
    category: 'Werk',
    tips: ['Noem je sterke kanten.', 'Geef voorbeelden.'],
  },
  {
    id: 'sit-b1-werk-04',
    scenario: 'Je legt je baas uit dat je werkdruk te hoog is.',
    roleA: 'Werknemer',
    roleB: 'Baas',
    levels: ['B1'],
    category: 'Werk',
    tips: ['Geef voorbeelden.', 'Stel een oplossing voor.'],
  },
  {
    id: 'sit-b1-werk-05',
    scenario: 'Je geeft een collega opbouwende feedback.',
    roleA: 'Collega',
    roleB: 'Collega',
    levels: ['B1'],
    category: 'Werk',
    tips: ['Wees concreet.', 'Benoem ook iets positiefs.'],
  },
  {
    id: 'sit-b1-werk-06',
    scenario: 'Je vertelt je baas dat je ontslag wilt nemen.',
    roleA: 'Werknemer',
    roleB: 'Baas',
    levels: ['B1'],
    category: 'Werk',
    tips: ['Wees duidelijk.', 'Leg je reden rustig uit.'],
  },
  {
    id: 'sit-b1-werk-07',
    scenario: 'Je presenteert een idee om het werk te verbeteren.',
    roleA: 'Werknemer',
    roleB: 'Baas',
    levels: ['B1'],
    category: 'Werk',
    tips: ['Leg het probleem uit.', 'Noem de voordelen van je idee.'],
  },
  {
    id: 'sit-b1-werk-08',
    scenario: 'Je bespreekt met een begeleider wat je wilt leren tijdens je stage.',
    roleA: 'Stagiair',
    roleB: 'Begeleider',
    levels: ['B1'],
    category: 'Werk',
    tips: ['Noem je leerdoelen.', 'Vraag om begeleiding.'],
  },
  {
    id: 'sit-b1-werk-09',
    scenario: 'Je spreekt een collega aan op een fout zonder ruzie te maken.',
    roleA: 'Collega',
    roleB: 'Collega',
    levels: ['B1'],
    category: 'Werk',
    tips: ['Blijf vriendelijk.', 'Bied je hulp aan.'],
  },
  {
    id: 'sit-b1-werk-10',
    scenario: 'Je bespreekt met een coach welke baan bij je past.',
    roleA: 'Werkzoekende',
    roleB: 'Loopbaancoach',
    levels: ['B1'],
    category: 'Werk',
    tips: ['Vertel over je interesses.', 'Stel vragen over mogelijkheden.'],
  },
  // B2
  {
    id: 'sit-b2-werk-01',
    scenario: 'Je onderhandelt over je arbeidsvoorwaarden.',
    roleA: 'Werknemer',
    roleB: 'Werkgever',
    levels: ['B2'],
    category: 'Werk',
    tips: ['Ken je waarde.', 'Wees bereid tot compromis.'],
  },
  {
    id: 'sit-b2-werk-02',
    scenario: 'Je leidt een gesprek over een probleem in het team.',
    roleA: 'Teamleider',
    roleB: 'Teamlid',
    levels: ['B2'],
    category: 'Werk',
    tips: ['Benoem het probleem helder.', 'Vraag om ideeën.'],
  },
  {
    id: 'sit-b2-werk-03',
    scenario: 'Je reageert professioneel op kritiek van je leidinggevende.',
    roleA: 'Werknemer',
    roleB: 'Leidinggevende',
    levels: ['B2'],
    category: 'Werk',
    tips: ['Luister zonder te onderbreken.', 'Vraag om concrete voorbeelden.'],
  },
  {
    id: 'sit-b2-werk-04',
    scenario: "Je bemiddelt tussen twee collega's die ruzie hebben.",
    roleA: 'Bemiddelaar',
    roleB: 'Collega',
    levels: ['B2'],
    category: 'Werk',
    tips: ['Blijf neutraal.', 'Zoek een gezamenlijk doel.'],
  },
  {
    id: 'sit-b2-werk-05',
    scenario: 'Je beargumenteert waarom je een promotie verdient.',
    roleA: 'Werknemer',
    roleB: 'Werkgever',
    levels: ['B2'],
    category: 'Werk',
    tips: ['Onderbouw met resultaten.', 'Toon je ambitie.'],
  },
  {
    id: 'sit-b2-werk-06',
    scenario: 'Je bespreekt met je baas iets wat je oneerlijk vindt op het werk.',
    roleA: 'Werknemer',
    roleB: 'Baas',
    levels: ['B2'],
    category: 'Werk',
    tips: ['Blijf zakelijk.', 'Doe een voorstel voor verbetering.'],
  },
  {
    id: 'sit-b2-werk-07',
    scenario: 'Je legt je team uit waarom er iets gaat veranderen.',
    roleA: 'Leidinggevende',
    roleB: 'Teamlid',
    levels: ['B2'],
    category: 'Werk',
    tips: ['Leg de reden uit.', 'Geef ruimte voor vragen.'],
  },
  {
    id: 'sit-b2-werk-08',
    scenario: 'Je overtuigt een werkgever van je visie op het werk.',
    roleA: 'Sollicitant',
    roleB: 'Werkgever',
    levels: ['B2'],
    category: 'Werk',
    tips: ['Wees concreet.', 'Koppel je visie aan het bedrijf.'],
  },
  {
    id: 'sit-b2-werk-09',
    scenario: 'Je bespreekt met je leidinggevende dat je overbelast bent.',
    roleA: 'Werknemer',
    roleB: 'Leidinggevende',
    levels: ['B2'],
    category: 'Werk',
    tips: ['Wees eerlijk over je grenzen.', 'Vraag om steun.'],
  },
  {
    id: 'sit-b2-werk-10',
    scenario: 'Je voert een functioneringsgesprek over je ontwikkeling.',
    roleA: 'Werknemer',
    roleB: 'Leidinggevende',
    levels: ['B2'],
    category: 'Werk',
    tips: ['Benoem je successen.', 'Bespreek je leerdoelen.'],
  },

  // ══ ETEN ═════════════════════════════════════════════════════════════════
  // A1
  {
    id: 'sit-a1-eten-01',
    scenario: 'Je koopt een brood bij de bakker.',
    roleA: 'Klant',
    roleB: 'Bakker',
    levels: ['A1'],
    category: 'Eten',
    tips: ['Zeg welk brood je wilt.', 'Vraag wat het kost.'],
  },
  {
    id: 'sit-a1-eten-02',
    scenario: 'Je vraagt een medewerker waar de melk staat.',
    roleA: 'Klant',
    roleB: 'Medewerker',
    levels: ['A1'],
    category: 'Eten',
    tips: ['Zeg wat je zoekt.', 'Bedank de medewerker.'],
  },
  {
    id: 'sit-a1-eten-03',
    scenario: 'Je bestelt een kopje koffie in een café.',
    roleA: 'Klant',
    roleB: 'Ober',
    levels: ['A1'],
    category: 'Eten',
    tips: ['Zeg wat je wilt.', 'Vraag wat het kost.'],
  },
  {
    id: 'sit-a1-eten-04',
    scenario: 'Je koopt fruit op de markt.',
    roleA: 'Klant',
    roleB: 'Marktverkoper',
    levels: ['A1'],
    category: 'Eten',
    tips: ['Zeg hoeveel je wilt.', 'Vraag de prijs.'],
  },
  {
    id: 'sit-a1-eten-05',
    scenario: 'Je biedt een gast thee of koffie aan.',
    roleA: 'Gastheer',
    roleB: 'Gast',
    levels: ['A1'],
    category: 'Eten',
    tips: ['Geef twee keuzes.', 'Vraag of de gast suiker wil.'],
  },
  {
    id: 'sit-a1-eten-06',
    scenario: 'Je bestelt een ijsje bij de ijssalon.',
    roleA: 'Klant',
    roleB: 'Verkoper',
    levels: ['A1'],
    category: 'Eten',
    tips: ['Zeg welke smaak.', 'Zeg hoeveel bolletjes.'],
  },
  {
    id: 'sit-a1-eten-07',
    scenario: 'Je vraagt je huisgenoot wat hij op brood wil.',
    roleA: 'Huisgenoot',
    roleB: 'Huisgenoot',
    levels: ['A1'],
    category: 'Eten',
    tips: ['Noem wat er is.', 'Vraag wat hij lekker vindt.'],
  },
  {
    id: 'sit-a1-eten-08',
    scenario: 'Je vraagt in een restaurant om een glas water.',
    roleA: 'Klant',
    roleB: 'Ober',
    levels: ['A1'],
    category: 'Eten',
    tips: ['Vraag het beleefd.', 'Zeg bedankt.'],
  },
  {
    id: 'sit-a1-eten-09',
    scenario: 'Je vraagt hoeveel de appels kosten.',
    roleA: 'Klant',
    roleB: 'Verkoper',
    levels: ['A1'],
    category: 'Eten',
    tips: ['Stel een korte vraag.', 'Zeg hoeveel je wilt.'],
  },
  {
    id: 'sit-a1-eten-10',
    scenario: 'Je vraagt een collega of die mee gaat lunchen.',
    roleA: 'Collega',
    roleB: 'Collega',
    levels: ['A1'],
    category: 'Eten',
    tips: ['Vraag het vriendelijk.', 'Stel een tijd voor.'],
  },
  // A2
  {
    id: 'sit-a2-eten-01',
    scenario: 'Je bestelt een maaltijd in een restaurant.',
    roleA: 'Klant',
    roleB: 'Ober',
    levels: ['A2'],
    category: 'Eten',
    tips: ['Vraag naar het menu.', 'Bestel duidelijk.'],
  },
  {
    id: 'sit-a2-eten-02',
    scenario: 'Je vraagt een vriend hoe hij een gerecht maakt.',
    roleA: 'Vrager',
    roleB: 'Vriend',
    levels: ['A2'],
    category: 'Eten',
    tips: ['Vraag naar de ingrediënten.', 'Vraag naar de stappen.'],
  },
  {
    id: 'sit-a2-eten-03',
    scenario: 'Je maakt samen een boodschappenlijst.',
    roleA: 'Huisgenoot',
    roleB: 'Huisgenoot',
    levels: ['A2'],
    category: 'Eten',
    tips: ['Noem wat je nodig hebt.', 'Bespreek wat jullie eten.'],
  },
  {
    id: 'sit-a2-eten-04',
    scenario: 'Je vertelt de ober dat je iets niet mag eten.',
    roleA: 'Klant',
    roleB: 'Ober',
    levels: ['A2'],
    category: 'Eten',
    tips: ['Zeg duidelijk wat je niet mag.', 'Vraag wat je wel kunt nemen.'],
  },
  {
    id: 'sit-a2-eten-05',
    scenario: 'Je spreekt met een vriend af om uit eten te gaan.',
    roleA: 'Vriend',
    roleB: 'Vriend',
    levels: ['A2'],
    category: 'Eten',
    tips: ['Stel een restaurant voor.', 'Spreek een tijd af.'],
  },
  {
    id: 'sit-a2-eten-06',
    scenario: 'Je overlegt wat je kookt voor gasten.',
    roleA: 'Gastheer',
    roleB: 'Huisgenoot',
    levels: ['A2'],
    category: 'Eten',
    tips: ['Geef ideeën.', 'Houd rekening met de gasten.'],
  },
  {
    id: 'sit-a2-eten-07',
    scenario: 'Je vertelt vriendelijk dat je eten koud is.',
    roleA: 'Klant',
    roleB: 'Ober',
    levels: ['A2'],
    category: 'Eten',
    tips: ['Blijf beleefd.', 'Vraag of het warm gemaakt kan worden.'],
  },
  {
    id: 'sit-a2-eten-08',
    scenario: 'Je vraagt op de markt of iets goedkoper kan.',
    roleA: 'Klant',
    roleB: 'Marktverkoper',
    levels: ['A2'],
    category: 'Eten',
    tips: ['Vraag het vriendelijk.', 'Noem hoeveel je koopt.'],
  },
  {
    id: 'sit-a2-eten-09',
    scenario: 'Je legt een vriend uit hoe een gerecht uit jouw land smaakt.',
    roleA: 'Verteller',
    roleB: 'Vriend',
    levels: ['A2'],
    category: 'Eten',
    tips: ['Beschrijf de smaak.', 'Vertel wanneer je het eet.'],
  },
  {
    id: 'sit-a2-eten-10',
    scenario: 'Je nodigt een buur uit om te komen eten.',
    roleA: 'Gastheer',
    roleB: 'Buur',
    levels: ['A2'],
    category: 'Eten',
    tips: ['Zeg wanneer.', 'Vertel wat je kookt.'],
  },
  // B1
  {
    id: 'sit-b1-eten-01',
    scenario: 'Je bespreekt met vrienden hoe je de rekening verdeelt.',
    roleA: 'Gast',
    roleB: 'Gast',
    levels: ['B1'],
    category: 'Eten',
    tips: ['Stel een eerlijke verdeling voor.', 'Blijf flexibel.'],
  },
  {
    id: 'sit-b1-eten-02',
    scenario: 'Je legt uit waarom je bepaald eten niet eet.',
    roleA: 'Gast',
    roleB: 'Gastheer',
    levels: ['B1'],
    category: 'Eten',
    tips: ['Leg het rustig uit.', 'Bedank voor het begrip.'],
  },
  {
    id: 'sit-b1-eten-03',
    scenario: 'Je bespreekt met een kookdocent wat je wilt leren koken.',
    roleA: 'Cursist',
    roleB: 'Kookdocent',
    levels: ['B1'],
    category: 'Eten',
    tips: ['Noem je wensen.', 'Vraag naar de mogelijkheden.'],
  },
  {
    id: 'sit-b1-eten-04',
    scenario: 'Je legt in een restaurant uit waarom je gerecht niet klopt.',
    roleA: 'Klant',
    roleB: 'Ober',
    levels: ['B1'],
    category: 'Eten',
    tips: ['Beschrijf het probleem.', 'Vraag om een oplossing.'],
  },
  {
    id: 'sit-b1-eten-05',
    scenario: 'Je overlegt hoe jullie gezonder kunnen eten.',
    roleA: 'Huisgenoot',
    roleB: 'Huisgenoot',
    levels: ['B1'],
    category: 'Eten',
    tips: ['Geef concrete ideeën.', 'Maak samen een plan.'],
  },
  {
    id: 'sit-b1-eten-06',
    scenario: 'Je vertelt over de eetcultuur in jouw land.',
    roleA: 'Verteller',
    roleB: 'Luisteraar',
    levels: ['B1'],
    category: 'Eten',
    tips: ['Beschrijf typische gerechten.', 'Vertel over gewoonten bij het eten.'],
  },
  {
    id: 'sit-b1-eten-07',
    scenario: 'Je bespreekt het eten voor een feest met een cateraar.',
    roleA: 'Klant',
    roleB: 'Cateraar',
    levels: ['B1'],
    category: 'Eten',
    tips: ['Noem het aantal gasten.', 'Bespreek het budget.'],
  },
  {
    id: 'sit-b1-eten-08',
    scenario: 'Je biedt buren aan om eten te delen dat overblijft.',
    roleA: 'Bewoner',
    roleB: 'Buur',
    levels: ['B1'],
    category: 'Eten',
    tips: ['Leg uit wat je hebt.', 'Wees vriendelijk.'],
  },
  {
    id: 'sit-b1-eten-09',
    scenario: 'Je vraagt een marktverkoper advies over verse producten.',
    roleA: 'Klant',
    roleB: 'Marktverkoper',
    levels: ['B1'],
    category: 'Eten',
    tips: ['Vraag wat vandaag goed is.', 'Vraag hoe je het bewaart.'],
  },
  {
    id: 'sit-b1-eten-10',
    scenario: 'Je verdeelt taken voor een gezamenlijk etentje.',
    roleA: 'Organisator',
    roleB: 'Gast',
    levels: ['B1'],
    category: 'Eten',
    tips: ['Vraag wat ieder meeneemt.', 'Maak duidelijke afspraken.'],
  },
  // B2
  {
    id: 'sit-b2-eten-01',
    scenario: 'Je overtuigt huisgenoten om minder eten weg te gooien.',
    roleA: 'Bewoner',
    roleB: 'Huisgenoot',
    levels: ['B2'],
    category: 'Eten',
    tips: ['Geef praktische tips.', 'Noem de voordelen.'],
  },
  {
    id: 'sit-b2-eten-02',
    scenario: 'Je voert een gesprek met de manager over een slechte ervaring.',
    roleA: 'Klant',
    roleB: 'Manager',
    levels: ['B2'],
    category: 'Eten',
    tips: ['Blijf zakelijk.', 'Vraag om een passende oplossing.'],
  },
  {
    id: 'sit-b2-eten-03',
    scenario: 'Je bespreekt met een vriend de voor- en nadelen van vegetarisch eten.',
    roleA: 'Vriend',
    roleB: 'Vriend',
    levels: ['B2'],
    category: 'Eten',
    tips: ['Geef argumenten.', 'Luister naar de andere kant.'],
  },
  {
    id: 'sit-b2-eten-04',
    scenario: 'Je bespreekt met een gast verschillende eetgewoonten zonder iemand te kwetsen.',
    roleA: 'Gastheer',
    roleB: 'Gast',
    levels: ['B2'],
    category: 'Eten',
    tips: ['Wees nieuwsgierig.', 'Toon respect.'],
  },
  {
    id: 'sit-b2-eten-05',
    scenario: 'Je bespreekt als vrijwilliger met een bezoeker hoe de voedselbank werkt.',
    roleA: 'Vrijwilliger',
    roleB: 'Bezoeker',
    levels: ['B2'],
    category: 'Eten',
    tips: ['Leg de regels uit.', 'Wees vriendelijk en geduldig.'],
  },
  {
    id: 'sit-b2-eten-06',
    scenario: 'Je bespreekt met een verkoper waarom biologisch eten duurder is.',
    roleA: 'Klant',
    roleB: 'Verkoper',
    levels: ['B2'],
    category: 'Eten',
    tips: ['Stel goede vragen.', 'Weeg de voor- en nadelen af.'],
  },
  {
    id: 'sit-b2-eten-07',
    scenario: 'Je bespreekt met je gezin verschillende eetwensen.',
    roleA: 'Gezinslid',
    roleB: 'Gezinslid',
    levels: ['B2'],
    category: 'Eten',
    tips: ['Luister naar elkaar.', 'Zoek een compromis.'],
  },
  {
    id: 'sit-b2-eten-08',
    scenario: 'Je bespreekt met een vriend hoe reclame ons eetgedrag beïnvloedt.',
    roleA: 'Vriend',
    roleB: 'Vriend',
    levels: ['B2'],
    category: 'Eten',
    tips: ['Geef voorbeelden.', 'Deel je eigen ervaring.'],
  },
  {
    id: 'sit-b2-eten-09',
    scenario: 'Je houdt een lastig familie-etentje gezellig.',
    roleA: 'Gastheer',
    roleB: 'Familielid',
    levels: ['B2'],
    category: 'Eten',
    tips: ['Kies veilige gespreksonderwerpen.', 'Betrek iedereen.'],
  },
  {
    id: 'sit-b2-eten-10',
    scenario: 'Je vertelt waarom een gerecht belangrijk is voor je identiteit.',
    roleA: 'Verteller',
    roleB: 'Luisteraar',
    levels: ['B2'],
    category: 'Eten',
    tips: ['Vertel het verhaal erachter.', 'Beschrijf je gevoelens.'],
  },

  // ══ REIZEN ═══════════════════════════════════════════════════════════════
  // A1
  {
    id: 'sit-a1-reizen-01',
    scenario: 'Je koopt een treinkaartje bij de balie.',
    roleA: 'Reiziger',
    roleB: 'Baliemedewerker',
    levels: ['A1'],
    category: 'Reizen',
    tips: ['Zeg waar je heen wilt.', 'Vraag de prijs.'],
  },
  {
    id: 'sit-a1-reizen-02',
    scenario: 'Je vraagt de weg naar het station.',
    roleA: 'Reiziger',
    roleB: 'Voorbijganger',
    levels: ['A1'],
    category: 'Reizen',
    tips: ['Vraag het beleefd.', 'Bedank de ander.'],
  },
  {
    id: 'sit-a1-reizen-03',
    scenario: 'Je vraagt of de bus naar het centrum gaat.',
    roleA: 'Reiziger',
    roleB: 'Buschauffeur',
    levels: ['A1'],
    category: 'Reizen',
    tips: ['Zeg waar je heen wilt.', 'Vraag wat het kost.'],
  },
  {
    id: 'sit-a1-reizen-04',
    scenario: 'Je vraagt of de stoel naast iemand vrij is.',
    roleA: 'Reiziger',
    roleB: 'Medepassagier',
    levels: ['A1'],
    category: 'Reizen',
    tips: ['Vraag het vriendelijk.', 'Zeg bedankt.'],
  },
  {
    id: 'sit-a1-reizen-05',
    scenario: 'Je checkt in bij een hotel.',
    roleA: 'Gast',
    roleB: 'Receptionist',
    levels: ['A1'],
    category: 'Reizen',
    tips: ['Zeg je naam.', 'Vraag naar je kamer.'],
  },
  {
    id: 'sit-a1-reizen-06',
    scenario: 'Je vertelt dat je je koffer niet kunt vinden.',
    roleA: 'Reiziger',
    roleB: 'Medewerker',
    levels: ['A1'],
    category: 'Reizen',
    tips: ['Beschrijf de koffer.', 'Vraag om hulp.'],
  },
  {
    id: 'sit-a1-reizen-07',
    scenario: 'Je vraagt hoeveel een kaartje kost.',
    roleA: 'Reiziger',
    roleB: 'Loketmedewerker',
    levels: ['A1'],
    category: 'Reizen',
    tips: ['Stel een korte vraag.', 'Zeg waar je heen wilt.'],
  },
  {
    id: 'sit-a1-reizen-08',
    scenario: 'Je vraagt hoe laat de trein vertrekt.',
    roleA: 'Reiziger',
    roleB: 'Conducteur',
    levels: ['A1'],
    category: 'Reizen',
    tips: ['Vraag naar de tijd.', 'Vraag naar het spoor.'],
  },
  {
    id: 'sit-a1-reizen-09',
    scenario: 'Je vraagt een taxi om naar een adres te gaan.',
    roleA: 'Reiziger',
    roleB: 'Taxichauffeur',
    levels: ['A1'],
    category: 'Reizen',
    tips: ['Zeg het adres.', 'Vraag wat het kost.'],
  },
  {
    id: 'sit-a1-reizen-10',
    scenario: 'Je vraagt op het station waar het toilet is.',
    roleA: 'Reiziger',
    roleB: 'Medewerker',
    levels: ['A1'],
    category: 'Reizen',
    tips: ['Stel een korte vraag.', 'Bedank de medewerker.'],
  },
  // A2
  {
    id: 'sit-a2-reizen-01',
    scenario: 'Je boekt een reis bij een reisbureau.',
    roleA: 'Klant',
    roleB: 'Reisagent',
    levels: ['A2'],
    category: 'Reizen',
    tips: ['Zeg waar je heen wilt.', 'Vraag naar de prijs.'],
  },
  {
    id: 'sit-a2-reizen-02',
    scenario: 'Je vertelt bij de receptie dat er iets mis is met je kamer.',
    roleA: 'Gast',
    roleB: 'Receptionist',
    levels: ['A2'],
    category: 'Reizen',
    tips: ['Beschrijf het probleem.', 'Vraag om een oplossing.'],
  },
  {
    id: 'sit-a2-reizen-03',
    scenario: 'Je vraagt een uitgebreide routebeschrijving.',
    roleA: 'Toerist',
    roleB: 'Bewoner',
    levels: ['A2'],
    category: 'Reizen',
    tips: ['Zeg waar je naartoe wilt.', 'Vraag door als iets onduidelijk is.'],
  },
  {
    id: 'sit-a2-reizen-04',
    scenario: 'Je vraagt informatie over een vertraagde trein.',
    roleA: 'Reiziger',
    roleB: 'Medewerker',
    levels: ['A2'],
    category: 'Reizen',
    tips: ['Vraag hoe lang de vertraging is.', 'Vraag naar een alternatief.'],
  },
  {
    id: 'sit-a2-reizen-05',
    scenario: 'Je plant samen een vakantie.',
    roleA: 'Reisgenoot',
    roleB: 'Reisgenoot',
    levels: ['A2'],
    category: 'Reizen',
    tips: ['Bespreek de bestemming.', 'Bespreek wat jullie gaan doen.'],
  },
  {
    id: 'sit-a2-reizen-06',
    scenario: 'Je vraagt advies over wat je kunt bezoeken.',
    roleA: 'Toerist',
    roleB: 'Gids',
    levels: ['A2'],
    category: 'Reizen',
    tips: ['Vertel wat je leuk vindt.', 'Vraag om tips.'],
  },
  {
    id: 'sit-a2-reizen-07',
    scenario: 'Je overlegt met een reisgenoot wat jullie meenemen.',
    roleA: 'Reisgenoot',
    roleB: 'Reisgenoot',
    levels: ['A2'],
    category: 'Reizen',
    tips: ['Noem wat nodig is.', 'Bespreek wie wat meeneemt.'],
  },
  {
    id: 'sit-a2-reizen-08',
    scenario: 'Je huurt een fiets en vraagt naar de regels.',
    roleA: 'Toerist',
    roleB: 'Verhuurder',
    levels: ['A2'],
    category: 'Reizen',
    tips: ['Vraag de prijs.', 'Vraag wanneer je hem terugbrengt.'],
  },
  {
    id: 'sit-a2-reizen-09',
    scenario: 'Je legt uit dat je het verkeerde kaartje hebt gekocht.',
    roleA: 'Reiziger',
    roleB: 'Medewerker',
    levels: ['A2'],
    category: 'Reizen',
    tips: ['Leg de fout uit.', 'Vraag wat je nu moet doen.'],
  },
  {
    id: 'sit-a2-reizen-10',
    scenario: 'Je vertelt een vriend over je vakantieplannen.',
    roleA: 'Verteller',
    roleB: 'Vriend',
    levels: ['A2'],
    category: 'Reizen',
    tips: ['Vertel waar je heen gaat.', 'Vertel wat je gaat doen.'],
  },
  // B1
  {
    id: 'sit-b1-reizen-01',
    scenario: 'Je bespreekt met een reisgenoot verschillende wensen voor de reis.',
    roleA: 'Reisgenoot',
    roleB: 'Reisgenoot',
    levels: ['B1'],
    category: 'Reizen',
    tips: ['Noem je wensen.', 'Zoek een compromis.'],
  },
  {
    id: 'sit-b1-reizen-02',
    scenario: 'Je legt uit waarom je ontevreden bent over een geboekte reis.',
    roleA: 'Klant',
    roleB: 'Reisagent',
    levels: ['B1'],
    category: 'Reizen',
    tips: ['Beschrijf het probleem.', 'Vraag om een oplossing.'],
  },
  {
    id: 'sit-b1-reizen-03',
    scenario: 'Je bespreekt met een gids de gewoonten van een land.',
    roleA: 'Toerist',
    roleB: 'Gids',
    levels: ['B1'],
    category: 'Reizen',
    tips: ['Stel open vragen.', 'Vraag wat je beter wel of niet doet.'],
  },
  {
    id: 'sit-b1-reizen-04',
    scenario: 'Je legt aan een medewerker uit dat je je vlucht hebt gemist.',
    roleA: 'Reiziger',
    roleB: 'Medewerker',
    levels: ['B1'],
    category: 'Reizen',
    tips: ['Blijf rustig.', 'Vraag naar de mogelijkheden.'],
  },
  {
    id: 'sit-b1-reizen-05',
    scenario: 'Je geeft een toerist tips over jouw stad.',
    roleA: 'Bewoner',
    roleB: 'Toerist',
    levels: ['B1'],
    category: 'Reizen',
    tips: ['Noem leuke plekken.', 'Geef een persoonlijke tip.'],
  },
  {
    id: 'sit-b1-reizen-06',
    scenario: 'Je praat met een vriend over heimwee tijdens een lange reis.',
    roleA: 'Reiziger',
    roleB: 'Vriend',
    levels: ['B1'],
    category: 'Reizen',
    tips: ['Benoem je gevoelens.', 'Vraag hoe de ander ermee omgaat.'],
  },
  {
    id: 'sit-b1-reizen-07',
    scenario: 'Je overlegt hoe jullie de reis betaalbaar houden.',
    roleA: 'Reisgenoot',
    roleB: 'Reisgenoot',
    levels: ['B1'],
    category: 'Reizen',
    tips: ['Bespreek het budget.', 'Bedenk waar je kunt besparen.'],
  },
  {
    id: 'sit-b1-reizen-08',
    scenario: 'Je bespreekt met een medewerker een reisverzekering.',
    roleA: 'Klant',
    roleB: 'Medewerker',
    levels: ['B1'],
    category: 'Reizen',
    tips: ['Vraag wat gedekt is.', 'Vraag naar de prijs.'],
  },
  {
    id: 'sit-b1-reizen-09',
    scenario: 'Je lost samen een probleem op tijdens de reis.',
    roleA: 'Reisgenoot',
    roleB: 'Reisgenoot',
    levels: ['B1'],
    category: 'Reizen',
    tips: ['Blijf kalm.', 'Bedenk samen oplossingen.'],
  },
  {
    id: 'sit-b1-reizen-10',
    scenario: 'Je vertelt uitgebreid over een bijzondere reiservaring.',
    roleA: 'Verteller',
    roleB: 'Luisteraar',
    levels: ['B1'],
    category: 'Reizen',
    tips: ['Vertel wat er gebeurde.', 'Vertel waarom het bijzonder was.'],
  },
  // B2
  {
    id: 'sit-b2-reizen-01',
    scenario: 'Je bespreekt met een reisgenoot een meningsverschil over de reis.',
    roleA: 'Reisgenoot',
    roleB: 'Reisgenoot',
    levels: ['B2'],
    category: 'Reizen',
    tips: ['Luister naar de ander.', 'Zoek een oplossing voor beiden.'],
  },
  {
    id: 'sit-b2-reizen-02',
    scenario: 'Je voert een gesprek met een manager over een mislukte reis.',
    roleA: 'Klant',
    roleB: 'Manager',
    levels: ['B2'],
    category: 'Reizen',
    tips: ['Onderbouw je klacht.', 'Vraag om compensatie.'],
  },
  {
    id: 'sit-b2-reizen-03',
    scenario: 'Je bespreekt met een vriend de milieu-impact van vliegen.',
    roleA: 'Vriend',
    roleB: 'Vriend',
    levels: ['B2'],
    category: 'Reizen',
    tips: ['Geef argumenten.', 'Bespreek alternatieven.'],
  },
  {
    id: 'sit-b2-reizen-04',
    scenario: 'Je praat met een vriend over wennen aan een ander land.',
    roleA: 'Reiziger',
    roleB: 'Vriend',
    levels: ['B2'],
    category: 'Reizen',
    tips: ['Beschrijf wat moeilijk was.', 'Vertel wat hielp.'],
  },
  {
    id: 'sit-b2-reizen-05',
    scenario: 'Je vertelt over je ervaring van verhuizen naar een ander land.',
    roleA: 'Verteller',
    roleB: 'Luisteraar',
    levels: ['B2'],
    category: 'Reizen',
    tips: ['Vertel over de uitdagingen.', 'Deel wat je hebt geleerd.'],
  },
  {
    id: 'sit-b2-reizen-06',
    scenario: 'Je bespreekt met een bewoner de invloed van toerisme op zijn stad.',
    roleA: 'Onderzoeker',
    roleB: 'Bewoner',
    levels: ['B2'],
    category: 'Reizen',
    tips: ['Stel open vragen.', 'Vraag naar voor- en nadelen.'],
  },
  {
    id: 'sit-b2-reizen-07',
    scenario: 'Je adviseert iemand die voor het eerst ver gaat reizen.',
    roleA: 'Ervaren reiziger',
    roleB: 'Beginnende reiziger',
    levels: ['B2'],
    category: 'Reizen',
    tips: ['Geef praktische tips.', 'Stel de ander gerust.'],
  },
  {
    id: 'sit-b2-reizen-08',
    scenario: 'Je handelt een noodsituatie af op reis.',
    roleA: 'Reiziger',
    roleB: 'Hulpverlener',
    levels: ['B2'],
    category: 'Reizen',
    tips: ['Leg de situatie helder uit.', 'Vraag om concrete hulp.'],
  },
  {
    id: 'sit-b2-reizen-09',
    scenario: "Je bespreekt met een vriend wat 'thuis' betekent als je veel reist.",
    roleA: 'Vriend',
    roleB: 'Vriend',
    levels: ['B2'],
    category: 'Reizen',
    tips: ['Deel je eigen gevoel.', 'Vraag naar de visie van de ander.'],
  },
  {
    id: 'sit-b2-reizen-10',
    scenario: 'Je bespreekt wat een reis je heeft geleerd over jezelf.',
    roleA: 'Verteller',
    roleB: 'Luisteraar',
    levels: ['B2'],
    category: 'Reizen',
    tips: ['Beschrijf een keerpunt.', 'Vertel wat er is veranderd.'],
  },

  // ══ VRIJE TIJD ═══════════════════════════════════════════════════════════
  // A1
  {
    id: 'sit-a1-vrij-01',
    scenario: 'Je legt een vriend een eenvoudig spel uit.',
    roleA: 'Verteller',
    roleB: 'Vriend',
    levels: ['A1'],
    category: 'Vrije tijd',
    tips: ['Leg de regels kort uit.', 'Vraag of het duidelijk is.'],
  },
  {
    id: 'sit-a1-vrij-02',
    scenario: 'Je vraagt een vriend mee om te wandelen.',
    roleA: 'Vriend',
    roleB: 'Vriend',
    levels: ['A1'],
    category: 'Vrije tijd',
    tips: ['Stel een tijd voor.', 'Zeg waar jullie lopen.'],
  },
  {
    id: 'sit-a1-vrij-03',
    scenario: 'Je kiest samen een film om te kijken.',
    roleA: 'Vriend',
    roleB: 'Vriend',
    levels: ['A1'],
    category: 'Vrije tijd',
    tips: ['Noem twee films.', 'Vraag wat de ander wil.'],
  },
  {
    id: 'sit-a1-vrij-04',
    scenario: 'Je laat een vriend je favoriete muziek horen.',
    roleA: 'Verteller',
    roleB: 'Vriend',
    levels: ['A1'],
    category: 'Vrije tijd',
    tips: ['Zeg wat voor muziek het is.', 'Vraag of hij het mooi vindt.'],
  },
  {
    id: 'sit-a1-vrij-05',
    scenario: 'Je vertelt over je hobby.',
    roleA: 'Verteller',
    roleB: 'Luisteraar',
    levels: ['A1'],
    category: 'Vrije tijd',
    tips: ['Zeg wat je doet.', 'Zeg waarom je het leuk vindt.'],
  },
  {
    id: 'sit-a1-vrij-06',
    scenario: 'Je vraagt een vriend om in het weekend af te spreken.',
    roleA: 'Vriend',
    roleB: 'Vriend',
    levels: ['A1'],
    category: 'Vrije tijd',
    tips: ['Stel een dag voor.', 'Bespreek wat jullie doen.'],
  },
  {
    id: 'sit-a1-vrij-07',
    scenario: 'Je vraagt bij het zwembad hoe laat het opengaat.',
    roleA: 'Bezoeker',
    roleB: 'Medewerker',
    levels: ['A1'],
    category: 'Vrije tijd',
    tips: ['Vraag naar de tijd.', 'Vraag de prijs.'],
  },
  {
    id: 'sit-a1-vrij-08',
    scenario: 'Je vraagt of je mee mag doen met een spel.',
    roleA: 'Nieuwkomer',
    roleB: 'Speler',
    levels: ['A1'],
    category: 'Vrije tijd',
    tips: ['Vraag het vriendelijk.', 'Vraag hoe het spel werkt.'],
  },
  {
    id: 'sit-a1-vrij-09',
    scenario: 'Je vraagt bij een tekenclub of je mee mag doen.',
    roleA: 'Bezoeker',
    roleB: 'Begeleider',
    levels: ['A1'],
    category: 'Vrije tijd',
    tips: ['Zeg dat je het leuk vindt.', 'Vraag wanneer het is.'],
  },
  {
    id: 'sit-a1-vrij-10',
    scenario: 'Je vertelt wat je in het weekend hebt gedaan.',
    roleA: 'Verteller',
    roleB: 'Luisteraar',
    levels: ['A1'],
    category: 'Vrije tijd',
    tips: ['Vertel kort wat je deed.', 'Zeg of het leuk was.'],
  },
  // A2
  {
    id: 'sit-a2-vrij-01',
    scenario: 'Je vraagt bij een sportclub hoe je lid kunt worden.',
    roleA: 'Bezoeker',
    roleB: 'Trainer',
    levels: ['A2'],
    category: 'Vrije tijd',
    tips: ['Vraag wat het kost.', 'Vraag wanneer er getraind wordt.'],
  },
  {
    id: 'sit-a2-vrij-02',
    scenario: 'Je plant samen een dagje uit.',
    roleA: 'Vriend',
    roleB: 'Vriend',
    levels: ['A2'],
    category: 'Vrije tijd',
    tips: ['Stel een plek voor.', 'Bespreek hoe jullie reizen.'],
  },
  {
    id: 'sit-a2-vrij-03',
    scenario: 'Je nodigt een vriend uit voor een concert.',
    roleA: 'Vriend',
    roleB: 'Vriend',
    levels: ['A2'],
    category: 'Vrije tijd',
    tips: ['Vertel over het concert.', 'Spreek een tijd af.'],
  },
  {
    id: 'sit-a2-vrij-04',
    scenario: 'Je legt uit hoe je hobby werkt.',
    roleA: 'Verteller',
    roleB: 'Luisteraar',
    levels: ['A2'],
    category: 'Vrije tijd',
    tips: ['Leg de stappen uit.', 'Vertel wat je nodig hebt.'],
  },
  {
    id: 'sit-a2-vrij-05',
    scenario: 'Je meldt je aan voor een creatieve cursus.',
    roleA: 'Cursist',
    roleB: 'Begeleider',
    levels: ['A2'],
    category: 'Vrije tijd',
    tips: ['Zeg waarom je meedoet.', 'Vraag naar de tijden.'],
  },
  {
    id: 'sit-a2-vrij-06',
    scenario: 'Je bespreekt hoe je je verjaardag wilt vieren.',
    roleA: 'Jarige',
    roleB: 'Vriend',
    levels: ['A2'],
    category: 'Vrije tijd',
    tips: ['Geef ideeën.', 'Vraag wat de ander leuk vindt.'],
  },
  {
    id: 'sit-a2-vrij-07',
    scenario: 'Je vraagt advies over welke sport bij je past.',
    roleA: 'Bezoeker',
    roleB: 'Trainer',
    levels: ['A2'],
    category: 'Vrije tijd',
    tips: ['Vertel wat je leuk vindt.', 'Vraag om een advies.'],
  },
  {
    id: 'sit-a2-vrij-08',
    scenario: 'Je bespreekt een film die je hebt gezien.',
    roleA: 'Vriend',
    roleB: 'Vriend',
    levels: ['A2'],
    category: 'Vrije tijd',
    tips: ['Vertel waar de film over ging.', 'Zeg wat je ervan vond.'],
  },
  {
    id: 'sit-a2-vrij-09',
    scenario: 'Je plant een wandeling met een groep.',
    roleA: 'Organisator',
    roleB: 'Deelnemer',
    levels: ['A2'],
    category: 'Vrije tijd',
    tips: ['Stel een route voor.', 'Spreek een tijd af.'],
  },
  {
    id: 'sit-a2-vrij-10',
    scenario: 'Je bespreekt hoe je tijd vindt voor een hobby.',
    roleA: 'Verteller',
    roleB: 'Vriend',
    levels: ['A2'],
    category: 'Vrije tijd',
    tips: ['Leg uit wat je wilt doen.', 'Vraag om tips.'],
  },
  // B1
  {
    id: 'sit-b1-vrij-01',
    scenario: 'Je probeert een vriend enthousiast te maken voor je hobby.',
    roleA: 'Verteller',
    roleB: 'Vriend',
    levels: ['B1'],
    category: 'Vrije tijd',
    tips: ['Vertel wat het leuk maakt.', 'Nodig hem uit om mee te doen.'],
  },
  {
    id: 'sit-b1-vrij-02',
    scenario: 'Je bespreekt met anderen hoe je een clubactiviteit organiseert.',
    roleA: 'Organisator',
    roleB: 'Lid',
    levels: ['B1'],
    category: 'Vrije tijd',
    tips: ['Verdeel de taken.', 'Maak duidelijke afspraken.'],
  },
  {
    id: 'sit-b1-vrij-03',
    scenario: 'Je bespreekt een meningsverschil binnen je sportteam.',
    roleA: 'Teamlid',
    roleB: 'Teamlid',
    levels: ['B1'],
    category: 'Vrije tijd',
    tips: ['Blijf rustig.', 'Zoek een oplossing voor het team.'],
  },
  {
    id: 'sit-b1-vrij-04',
    scenario: 'Je bespreekt hoe je werk en vrije tijd in balans houdt.',
    roleA: 'Verteller',
    roleB: 'Vriend',
    levels: ['B1'],
    category: 'Vrije tijd',
    tips: ['Leg je situatie uit.', 'Vraag hoe de ander het doet.'],
  },
  {
    id: 'sit-b1-vrij-05',
    scenario: 'Je bespreekt hoe je vrijwilliger kunt worden bij een vereniging.',
    roleA: 'Belangstellende',
    roleB: 'Coördinator',
    levels: ['B1'],
    category: 'Vrije tijd',
    tips: ['Vertel wat je kunt.', 'Vraag wat er nodig is.'],
  },
  {
    id: 'sit-b1-vrij-06',
    scenario: 'Je overlegt met een begeleider hoe je een nieuwe hobby leert.',
    roleA: 'Beginner',
    roleB: 'Begeleider',
    levels: ['B1'],
    category: 'Vrije tijd',
    tips: ['Stel vragen.', 'Vraag om tips voor beginners.'],
  },
  {
    id: 'sit-b1-vrij-07',
    scenario: 'Je organiseert een uitje voor een groep met verschillende wensen.',
    roleA: 'Organisator',
    roleB: 'Deelnemer',
    levels: ['B1'],
    category: 'Vrije tijd',
    tips: ['Vraag naar ieders wensen.', 'Zoek een goede middenweg.'],
  },
  {
    id: 'sit-b1-vrij-08',
    scenario: 'Je moedigt iemand aan om iets met zijn talent te doen.',
    roleA: 'Verteller',
    roleB: 'Vriend',
    levels: ['B1'],
    category: 'Vrije tijd',
    tips: ['Benoem wat hij goed kan.', 'Geef een concrete suggestie.'],
  },
  {
    id: 'sit-b1-vrij-09',
    scenario: 'Je stelt een nieuwe activiteit voor aan een vereniging.',
    roleA: 'Lid',
    roleB: 'Bestuurslid',
    levels: ['B1'],
    category: 'Vrije tijd',
    tips: ['Leg je idee uit.', 'Noem de voordelen.'],
  },
  {
    id: 'sit-b1-vrij-10',
    scenario: 'Je geeft een gestreste vriend tips om te ontspannen.',
    roleA: 'Vriend',
    roleB: 'Vriend',
    levels: ['B1'],
    category: 'Vrije tijd',
    tips: ['Luister eerst.', 'Geef praktische tips.'],
  },
  // B2
  {
    id: 'sit-b2-vrij-01',
    scenario: "Je bespreekt met een vriend de druk om je vrije tijd 'nuttig' te besteden.",
    roleA: 'Vriend',
    roleB: 'Vriend',
    levels: ['B2'],
    category: 'Vrije tijd',
    tips: ['Deel je eigen gevoel.', 'Vraag naar de visie van de ander.'],
  },
  {
    id: 'sit-b2-vrij-02',
    scenario: 'Je bespreekt in een bestuursvergadering de toekomst van de club.',
    roleA: 'Bestuurslid',
    roleB: 'Bestuurslid',
    levels: ['B2'],
    category: 'Vrije tijd',
    tips: ['Onderbouw je standpunt.', 'Zoek draagvlak.'],
  },
  {
    id: 'sit-b2-vrij-03',
    scenario: 'Je bemiddelt bij een conflict binnen een vereniging.',
    roleA: 'Bemiddelaar',
    roleB: 'Lid',
    levels: ['B2'],
    category: 'Vrije tijd',
    tips: ['Blijf neutraal.', 'Zoek een gezamenlijk belang.'],
  },
  {
    id: 'sit-b2-vrij-04',
    scenario: 'Je bespreekt hoe vrije tijd verschilt per cultuur.',
    roleA: 'Vriend',
    roleB: 'Vriend',
    levels: ['B2'],
    category: 'Vrije tijd',
    tips: ['Geef voorbeelden.', 'Wees nieuwsgierig.'],
  },
  {
    id: 'sit-b2-vrij-05',
    scenario: 'Je bespreekt met een vriend de invloed van schermen op vrije tijd.',
    roleA: 'Vriend',
    roleB: 'Vriend',
    levels: ['B2'],
    category: 'Vrije tijd',
    tips: ['Deel je ervaring.', 'Bespreek voor- en nadelen.'],
  },
  {
    id: 'sit-b2-vrij-06',
    scenario: 'Je overtuigt iemand van het belang van vrijwilligerswerk.',
    roleA: 'Verteller',
    roleB: 'Twijfelaar',
    levels: ['B2'],
    category: 'Vrije tijd',
    tips: ['Geef argumenten.', 'Deel een persoonlijk voorbeeld.'],
  },
  {
    id: 'sit-b2-vrij-07',
    scenario: 'Je bespreekt met een vriend wat een leven betekenisvol maakt.',
    roleA: 'Vriend',
    roleB: 'Vriend',
    levels: ['B2'],
    category: 'Vrije tijd',
    tips: ['Deel je eigen visie.', 'Stel verdiepende vragen.'],
  },
  {
    id: 'sit-b2-vrij-08',
    scenario: 'Je verdedigt een omstreden plan voor een buurtactiviteit.',
    roleA: 'Initiatiefnemer',
    roleB: 'Criticus',
    levels: ['B2'],
    category: 'Vrije tijd',
    tips: ['Onderbouw je plan.', 'Neem de bezwaren serieus.'],
  },
  {
    id: 'sit-b2-vrij-09',
    scenario: 'Je bespreekt of verveling goed of slecht is.',
    roleA: 'Vriend',
    roleB: 'Vriend',
    levels: ['B2'],
    category: 'Vrije tijd',
    tips: ['Geef argumenten.', 'Luister naar het tegengeluid.'],
  },
  {
    id: 'sit-b2-vrij-10',
    scenario: "Je bespreekt hoe je hobby's veranderen naarmate je ouder wordt.",
    roleA: 'Vriend',
    roleB: 'Vriend',
    levels: ['B2'],
    category: 'Vrije tijd',
    tips: ['Vergelijk vroeger en nu.', 'Vraag naar de ervaring van de ander.'],
  },

  // ══ WONEN ════════════════════════════════════════════════════════════════
  // A1
  {
    id: 'sit-a1-wonen-01',
    scenario: 'Je laat een gast je huis zien.',
    roleA: 'Bewoner',
    roleB: 'Gast',
    levels: ['A1'],
    category: 'Wonen',
    tips: ['Noem de kamers.', 'Vraag wat de gast vindt.'],
  },
  {
    id: 'sit-a1-wonen-02',
    scenario: 'Je vraagt de huisbaas om een extra sleutel.',
    roleA: 'Huurder',
    roleB: 'Huisbaas',
    levels: ['A1'],
    category: 'Wonen',
    tips: ['Leg uit waarom.', 'Vraag wanneer het kan.'],
  },
  {
    id: 'sit-a1-wonen-03',
    scenario: 'Je vertelt dat een lamp kapot is.',
    roleA: 'Huurder',
    roleB: 'Huisbaas',
    levels: ['A1'],
    category: 'Wonen',
    tips: ['Zeg wat er kapot is.', 'Vraag of het gemaakt kan worden.'],
  },
  {
    id: 'sit-a1-wonen-04',
    scenario: 'Je vraagt je buur iets zachter te doen.',
    roleA: 'Bewoner',
    roleB: 'Buur',
    levels: ['A1'],
    category: 'Wonen',
    tips: ['Vraag het vriendelijk.', 'Zeg bedankt.'],
  },
  {
    id: 'sit-a1-wonen-05',
    scenario: 'Je bespreekt met een huisgenoot wie welke kamer krijgt.',
    roleA: 'Huisgenoot',
    roleB: 'Huisgenoot',
    levels: ['A1'],
    category: 'Wonen',
    tips: ['Zeg welke kamer je wilt.', 'Vraag wat de ander wil.'],
  },
  {
    id: 'sit-a1-wonen-06',
    scenario: 'Je verdeelt schoonmaaktaken met een huisgenoot.',
    roleA: 'Huisgenoot',
    roleB: 'Huisgenoot',
    levels: ['A1'],
    category: 'Wonen',
    tips: ['Noem de taken.', 'Bespreek wie wat doet.'],
  },
  {
    id: 'sit-a1-wonen-07',
    scenario: 'Je vraagt hoe de verwarming werkt.',
    roleA: 'Nieuwe bewoner',
    roleB: 'Huisbaas',
    levels: ['A1'],
    category: 'Wonen',
    tips: ['Stel een korte vraag.', 'Vraag het na als iets onduidelijk is.'],
  },
  {
    id: 'sit-a1-wonen-08',
    scenario: 'Je vraagt een buur om je planten water te geven.',
    roleA: 'Bewoner',
    roleB: 'Buur',
    levels: ['A1'],
    category: 'Wonen',
    tips: ['Zeg hoe lang je weg bent.', 'Bedank de buur.'],
  },
  {
    id: 'sit-a1-wonen-09',
    scenario: 'Je vraagt een vriend om te helpen met een kast.',
    roleA: 'Bewoner',
    roleB: 'Vriend',
    levels: ['A1'],
    category: 'Wonen',
    tips: ['Zeg wanneer je hulp nodig hebt.', 'Bedank alvast.'],
  },
  {
    id: 'sit-a1-wonen-10',
    scenario: 'Je geeft je nieuwe adres door aan een vriend.',
    roleA: 'Bewoner',
    roleB: 'Vriend',
    levels: ['A1'],
    category: 'Wonen',
    tips: ['Zeg je straat en nummer.', 'Vraag of hij langskomt.'],
  },
  // A2
  {
    id: 'sit-a2-wonen-01',
    scenario: 'Je bekijkt een huurwoning en stelt vragen.',
    roleA: 'Kandidaat-huurder',
    roleB: 'Verhuurder',
    levels: ['A2'],
    category: 'Wonen',
    tips: ['Vraag naar de huur.', 'Vraag wat er bij zit.'],
  },
  {
    id: 'sit-a2-wonen-02',
    scenario: 'Je vraagt de huisbaas iets te repareren.',
    roleA: 'Huurder',
    roleB: 'Huisbaas',
    levels: ['A2'],
    category: 'Wonen',
    tips: ['Beschrijf het probleem.', 'Vraag wanneer het kan.'],
  },
  {
    id: 'sit-a2-wonen-03',
    scenario: 'Je bespreekt huisregels met een nieuwe huisgenoot.',
    roleA: 'Huisgenoot',
    roleB: 'Nieuwe huisgenoot',
    levels: ['A2'],
    category: 'Wonen',
    tips: ['Noem de belangrijkste regels.', 'Vraag of het duidelijk is.'],
  },
  {
    id: 'sit-a2-wonen-04',
    scenario: 'Je plant een verhuizing met een vriend.',
    roleA: 'Bewoner',
    roleB: 'Vriend',
    levels: ['A2'],
    category: 'Wonen',
    tips: ['Zeg wanneer je verhuist.', 'Verdeel de taken.'],
  },
  {
    id: 'sit-a2-wonen-05',
    scenario: 'Je bespreekt overlast vriendelijk met je buur.',
    roleA: 'Bewoner',
    roleB: 'Buur',
    levels: ['A2'],
    category: 'Wonen',
    tips: ['Blijf vriendelijk.', 'Stel een oplossing voor.'],
  },
  {
    id: 'sit-a2-wonen-06',
    scenario: 'Je bespreekt met de huisbaas wanneer je de huur betaalt.',
    roleA: 'Huurder',
    roleB: 'Huisbaas',
    levels: ['A2'],
    category: 'Wonen',
    tips: ['Vraag naar de datum.', 'Vraag hoe je betaalt.'],
  },
  {
    id: 'sit-a2-wonen-07',
    scenario: 'Je overlegt met een huisgenoot hoe je de woonkamer inricht.',
    roleA: 'Huisgenoot',
    roleB: 'Huisgenoot',
    levels: ['A2'],
    category: 'Wonen',
    tips: ['Geef ideeën.', 'Luister naar de ander.'],
  },
  {
    id: 'sit-a2-wonen-08',
    scenario: 'Je belt om internet te laten aansluiten.',
    roleA: 'Bewoner',
    roleB: 'Medewerker',
    levels: ['A2'],
    category: 'Wonen',
    tips: ['Geef je adres door.', 'Vraag wanneer het klaar is.'],
  },
  {
    id: 'sit-a2-wonen-09',
    scenario: 'Je bespreekt met een buur het gebruik van een gedeelde tuin.',
    roleA: 'Bewoner',
    roleB: 'Buur',
    levels: ['A2'],
    category: 'Wonen',
    tips: ['Bespreek de afspraken.', 'Wees redelijk.'],
  },
  {
    id: 'sit-a2-wonen-10',
    scenario: 'Je vraagt hulp bij het zoeken van een woning.',
    roleA: 'Woningzoekende',
    roleB: 'Adviseur',
    levels: ['A2'],
    category: 'Wonen',
    tips: ['Vertel wat je zoekt.', 'Vraag naar de mogelijkheden.'],
  },
  // B1
  {
    id: 'sit-b1-wonen-01',
    scenario: 'Je bespreekt met de huisbaas een probleem met de woning.',
    roleA: 'Huurder',
    roleB: 'Huisbaas',
    levels: ['B1'],
    category: 'Wonen',
    tips: ['Beschrijf het probleem helder.', 'Vraag om een oplossing.'],
  },
  {
    id: 'sit-b1-wonen-02',
    scenario: 'Je bespreekt afspraken over het huishouden.',
    roleA: 'Huisgenoot',
    roleB: 'Huisgenoot',
    levels: ['B1'],
    category: 'Wonen',
    tips: ['Wees duidelijk.', 'Zoek een eerlijke verdeling.'],
  },
  {
    id: 'sit-b1-wonen-03',
    scenario: 'Je legt uit waarom je gaat verhuizen.',
    roleA: 'Verteller',
    roleB: 'Luisteraar',
    levels: ['B1'],
    category: 'Wonen',
    tips: ['Geef je redenen.', 'Vertel over je plannen.'],
  },
  {
    id: 'sit-b1-wonen-04',
    scenario: 'Je bespreekt aanhoudende overlast met je buur.',
    roleA: 'Bewoner',
    roleB: 'Buur',
    levels: ['B1'],
    category: 'Wonen',
    tips: ['Blijf rustig.', 'Geef concrete voorbeelden.'],
  },
  {
    id: 'sit-b1-wonen-05',
    scenario: 'Je dringt aan op een reparatie die te lang duurt.',
    roleA: 'Huurder',
    roleB: 'Huisbaas',
    levels: ['B1'],
    category: 'Wonen',
    tips: ['Wees beleefd maar duidelijk.', 'Vraag om een datum.'],
  },
  {
    id: 'sit-b1-wonen-06',
    scenario: 'Je bespreekt met een makelaar wat voor woning je zoekt.',
    roleA: 'Woningzoekende',
    roleB: 'Makelaar',
    levels: ['B1'],
    category: 'Wonen',
    tips: ['Noem je wensen.', 'Wees duidelijk over je budget.'],
  },
  {
    id: 'sit-b1-wonen-07',
    scenario: 'Je bespreekt met je partner of jullie gaan samenwonen.',
    roleA: 'Partner',
    roleB: 'Partner',
    levels: ['B1'],
    category: 'Wonen',
    tips: ['Deel je wensen.', 'Luister naar de ander.'],
  },
  {
    id: 'sit-b1-wonen-08',
    scenario: 'Je bespreekt een eerlijkere taakverdeling thuis.',
    roleA: 'Huisgenoot',
    roleB: 'Huisgenoot',
    levels: ['B1'],
    category: 'Wonen',
    tips: ['Geef voorbeelden.', 'Stel een nieuw plan voor.'],
  },
  {
    id: 'sit-b1-wonen-09',
    scenario: 'Je vraagt buren om hulp bij een probleem in huis.',
    roleA: 'Bewoner',
    roleB: 'Buur',
    levels: ['B1'],
    category: 'Wonen',
    tips: ['Leg de situatie uit.', 'Vraag concreet om hulp.'],
  },
  {
    id: 'sit-b1-wonen-10',
    scenario: 'Je bespreekt met de huisbaas verbeteringen aan de woning.',
    roleA: 'Huurder',
    roleB: 'Huisbaas',
    levels: ['B1'],
    category: 'Wonen',
    tips: ['Noem wat beter kan.', 'Onderbouw je verzoek.'],
  },
  // B2
  {
    id: 'sit-b2-wonen-01',
    scenario: 'Je voert een lastig gesprek over een huurverhoging.',
    roleA: 'Huurder',
    roleB: 'Huisbaas',
    levels: ['B2'],
    category: 'Wonen',
    tips: ['Blijf zakelijk.', 'Vraag om onderbouwing.'],
  },
  {
    id: 'sit-b2-wonen-02',
    scenario: 'Je bespreekt met een ambtenaar je problemen op de woningmarkt.',
    roleA: 'Woningzoekende',
    roleB: 'Ambtenaar',
    levels: ['B2'],
    category: 'Wonen',
    tips: ['Leg je situatie uit.', 'Vraag naar hulp en regels.'],
  },
  {
    id: 'sit-b2-wonen-03',
    scenario: 'Je bespreekt een diep meningsverschil met een huisgenoot.',
    roleA: 'Huisgenoot',
    roleB: 'Huisgenoot',
    levels: ['B2'],
    category: 'Wonen',
    tips: ['Luister echt.', 'Zoek een compromis.'],
  },
  {
    id: 'sit-b2-wonen-04',
    scenario: 'Je weegt met je partner af of jullie verhuizen.',
    roleA: 'Partner',
    roleB: 'Partner',
    levels: ['B2'],
    category: 'Wonen',
    tips: ['Bespreek voor- en nadelen.', 'Neem samen een besluit.'],
  },
  {
    id: 'sit-b2-wonen-05',
    scenario: 'Je bespreekt met familie het idee om samen te wonen.',
    roleA: 'Familielid',
    roleB: 'Familielid',
    levels: ['B2'],
    category: 'Wonen',
    tips: ['Benoem de voordelen.', 'Bespreek mogelijke zorgen.'],
  },
  {
    id: 'sit-b2-wonen-06',
    scenario: 'Je overtuigt een huisbaas om de woning te verduurzamen.',
    roleA: 'Huurder',
    roleB: 'Huisbaas',
    levels: ['B2'],
    category: 'Wonen',
    tips: ['Noem de voordelen.', 'Doe een concreet voorstel.'],
  },
  {
    id: 'sit-b2-wonen-07',
    scenario: 'Je bespreekt met een vriend wat een plek tot een thuis maakt.',
    roleA: 'Vriend',
    roleB: 'Vriend',
    levels: ['B2'],
    category: 'Wonen',
    tips: ['Deel je eigen gevoel.', 'Stel verdiepende vragen.'],
  },
  {
    id: 'sit-b2-wonen-08',
    scenario: 'Je bemiddelt bij een slepend burenconflict.',
    roleA: 'Bemiddelaar',
    roleB: 'Bewoner',
    levels: ['B2'],
    category: 'Wonen',
    tips: ['Blijf neutraal.', 'Laat beide kanten aan het woord.'],
  },
  {
    id: 'sit-b2-wonen-09',
    scenario: 'Je bespreekt met een raadslid wat de gemeente aan wonen moet doen.',
    roleA: 'Inwoner',
    roleB: 'Raadslid',
    levels: ['B2'],
    category: 'Wonen',
    tips: ['Onderbouw je standpunt.', 'Doe een concreet voorstel.'],
  },
  {
    id: 'sit-b2-wonen-10',
    scenario: 'Je bespreekt de uitdagingen van wonen in een nieuw land.',
    roleA: 'Verteller',
    roleB: 'Luisteraar',
    levels: ['B2'],
    category: 'Wonen',
    tips: ['Vertel over je ervaringen.', 'Deel wat hielp.'],
  },

  // ══ GEZONDHEID ═══════════════════════════════════════════════════════════
  // A1
  {
    id: 'sit-a1-gezond-01',
    scenario: 'Je belt de huisarts voor een afspraak.',
    roleA: 'Patiënt',
    roleB: 'Assistent',
    levels: ['A1'],
    category: 'Gezondheid',
    tips: ['Zeg je naam.', 'Zeg wat er aan de hand is.'],
  },
  {
    id: 'sit-a1-gezond-02',
    scenario: 'Je haalt een medicijn op bij de apotheek.',
    roleA: 'Klant',
    roleB: 'Apotheker',
    levels: ['A1'],
    category: 'Gezondheid',
    tips: ['Zeg je naam.', 'Vraag hoe je het gebruikt.'],
  },
  {
    id: 'sit-a1-gezond-03',
    scenario: 'Je vertelt dat je je niet lekker voelt.',
    roleA: 'Patiënt',
    roleB: 'Vriend',
    levels: ['A1'],
    category: 'Gezondheid',
    tips: ['Zeg wat er mis is.', 'Vraag om hulp.'],
  },
  {
    id: 'sit-a1-gezond-04',
    scenario: 'Je vraagt bij de sportschool naar de openingstijden.',
    roleA: 'Bezoeker',
    roleB: 'Medewerker',
    levels: ['A1'],
    category: 'Gezondheid',
    tips: ['Vraag naar de tijden.', 'Vraag de prijs.'],
  },
  {
    id: 'sit-a1-gezond-05',
    scenario: 'Je vertelt de dokter waar je pijn hebt.',
    roleA: 'Patiënt',
    roleB: 'Dokter',
    levels: ['A1'],
    category: 'Gezondheid',
    tips: ['Wijs de plek aan.', 'Zeg sinds wanneer.'],
  },
  {
    id: 'sit-a1-gezond-06',
    scenario: 'Je vraagt of je even mag uitrusten.',
    roleA: 'Persoon',
    roleB: 'Vriend',
    levels: ['A1'],
    category: 'Gezondheid',
    tips: ['Zeg dat je moe bent.', 'Vraag het beleefd.'],
  },
  {
    id: 'sit-a1-gezond-07',
    scenario: 'Je vraagt om een glas water omdat je je niet goed voelt.',
    roleA: 'Persoon',
    roleB: 'Vriend',
    levels: ['A1'],
    category: 'Gezondheid',
    tips: ['Zeg hoe je je voelt.', 'Vraag vriendelijk.'],
  },
  {
    id: 'sit-a1-gezond-08',
    scenario: 'Je vraagt hoe laat je afspraak bij de dokter is.',
    roleA: 'Patiënt',
    roleB: 'Assistent',
    levels: ['A1'],
    category: 'Gezondheid',
    tips: ['Zeg je naam.', 'Vraag naar de tijd.'],
  },
  {
    id: 'sit-a1-gezond-09',
    scenario: 'Je vraagt een vriend mee voor een gezonde wandeling.',
    roleA: 'Vriend',
    roleB: 'Vriend',
    levels: ['A1'],
    category: 'Gezondheid',
    tips: ['Stel een tijd voor.', 'Zeg waar jullie lopen.'],
  },
  {
    id: 'sit-a1-gezond-10',
    scenario: 'Je maakt een afspraak bij de tandarts.',
    roleA: 'Patiënt',
    roleB: 'Assistent',
    levels: ['A1'],
    category: 'Gezondheid',
    tips: ['Zeg waarom je komt.', 'Vraag naar een datum.'],
  },
  // A2
  {
    id: 'sit-a2-gezond-01',
    scenario: 'Je legt de huisarts uit welke klachten je hebt.',
    roleA: 'Patiënt',
    roleB: 'Huisarts',
    levels: ['A2'],
    category: 'Gezondheid',
    tips: ['Beschrijf je klachten.', 'Zeg sinds wanneer.'],
  },
  {
    id: 'sit-a2-gezond-02',
    scenario: 'Je vraagt de apotheker hoe je een medicijn moet gebruiken.',
    roleA: 'Klant',
    roleB: 'Apotheker',
    levels: ['A2'],
    category: 'Gezondheid',
    tips: ['Vraag hoe vaak per dag.', 'Vraag of het bij eten moet.'],
  },
  {
    id: 'sit-a2-gezond-03',
    scenario: 'Je vraagt een trainer welke oefeningen goed zijn.',
    roleA: 'Sporter',
    roleB: 'Trainer',
    levels: ['A2'],
    category: 'Gezondheid',
    tips: ['Zeg wat je wilt bereiken.', 'Vraag om advies.'],
  },
  {
    id: 'sit-a2-gezond-04',
    scenario: 'Je bespreekt met een vriend hoe je gezonder kunt eten.',
    roleA: 'Vriend',
    roleB: 'Vriend',
    levels: ['A2'],
    category: 'Gezondheid',
    tips: ['Geef ideeën.', 'Maak een klein plan.'],
  },
  {
    id: 'sit-a2-gezond-05',
    scenario: 'Je verzet een afspraak bij de dokter.',
    roleA: 'Patiënt',
    roleB: 'Assistent',
    levels: ['A2'],
    category: 'Gezondheid',
    tips: ['Leg uit waarom.', 'Stel een nieuwe tijd voor.'],
  },
  {
    id: 'sit-a2-gezond-06',
    scenario: 'Je bespreekt met een vriend dat je je vaak moe voelt.',
    roleA: 'Verteller',
    roleB: 'Vriend',
    levels: ['A2'],
    category: 'Gezondheid',
    tips: ['Beschrijf hoe je je voelt.', 'Vraag om advies.'],
  },
  {
    id: 'sit-a2-gezond-07',
    scenario: 'Je biedt aan om een zieke buur te helpen.',
    roleA: 'Bewoner',
    roleB: 'Buur',
    levels: ['A2'],
    category: 'Gezondheid',
    tips: ['Vraag wat de buur nodig heeft.', 'Doe een concreet aanbod.'],
  },
  {
    id: 'sit-a2-gezond-08',
    scenario: 'Je vertelt een vriend dat je je gestrest voelt.',
    roleA: 'Verteller',
    roleB: 'Vriend',
    levels: ['A2'],
    category: 'Gezondheid',
    tips: ['Leg uit waarom.', 'Vraag om een luisterend oor.'],
  },
  {
    id: 'sit-a2-gezond-09',
    scenario: 'Je bespreekt een nieuwe gezonde gewoonte.',
    roleA: 'Vriend',
    roleB: 'Vriend',
    levels: ['A2'],
    category: 'Gezondheid',
    tips: ['Zeg wat je wilt veranderen.', 'Vraag de ander om mee te doen.'],
  },
  {
    id: 'sit-a2-gezond-10',
    scenario: 'Je legt aan een fysiotherapeut uit wat er mis is.',
    roleA: 'Patiënt',
    roleB: 'Fysiotherapeut',
    levels: ['A2'],
    category: 'Gezondheid',
    tips: ['Beschrijf de pijn.', 'Zeg wat je niet kunt doen.'],
  },
  // B1
  {
    id: 'sit-b1-gezond-01',
    scenario: 'Je legt de dokter uitgebreid je gezondheidsklachten uit.',
    roleA: 'Patiënt',
    roleB: 'Huisarts',
    levels: ['B1'],
    category: 'Gezondheid',
    tips: ['Beschrijf je klachten goed.', 'Stel ook zelf vragen.'],
  },
  {
    id: 'sit-b1-gezond-02',
    scenario: 'Je bespreekt met een vriend hoe je met stress omgaat.',
    roleA: 'Vriend',
    roleB: 'Vriend',
    levels: ['B1'],
    category: 'Gezondheid',
    tips: ['Deel wat jou helpt.', 'Vraag naar de ervaring van de ander.'],
  },
  {
    id: 'sit-b1-gezond-03',
    scenario: 'Je vraagt om hulp bij een moeilijke periode.',
    roleA: 'Verteller',
    roleB: 'Vriend',
    levels: ['B1'],
    category: 'Gezondheid',
    tips: ['Wees eerlijk over hoe je je voelt.', 'Zeg wat je nodig hebt.'],
  },
  {
    id: 'sit-b1-gezond-04',
    scenario: 'Je bespreekt met een coach hoe je gezonder kunt leven.',
    roleA: 'Cliënt',
    roleB: 'Coach',
    levels: ['B1'],
    category: 'Gezondheid',
    tips: ['Noem je doelen.', 'Maak een concreet plan.'],
  },
  {
    id: 'sit-b1-gezond-05',
    scenario: 'Je vertelt een vriend dat je je zorgen maakt om zijn gezondheid.',
    roleA: 'Vriend',
    roleB: 'Vriend',
    levels: ['B1'],
    category: 'Gezondheid',
    tips: ['Spreek vanuit zorg.', 'Oordeel niet.'],
  },
  {
    id: 'sit-b1-gezond-06',
    scenario: 'Je bespreekt met de dokter dat je twijfelt over een advies.',
    roleA: 'Patiënt',
    roleB: 'Huisarts',
    levels: ['B1'],
    category: 'Gezondheid',
    tips: ['Stel je vragen.', 'Vraag om uitleg.'],
  },
  {
    id: 'sit-b1-gezond-07',
    scenario: 'Je bespreekt hoe je werk en gezondheid in balans houdt.',
    roleA: 'Verteller',
    roleB: 'Vriend',
    levels: ['B1'],
    category: 'Gezondheid',
    tips: ['Leg je situatie uit.', 'Vraag om tips.'],
  },
  {
    id: 'sit-b1-gezond-08',
    scenario: 'Je bespreekt met een trainer een blessure.',
    roleA: 'Sporter',
    roleB: 'Trainer',
    levels: ['B1'],
    category: 'Gezondheid',
    tips: ['Beschrijf de blessure.', 'Vraag wat je wel kunt doen.'],
  },
  {
    id: 'sit-b1-gezond-09',
    scenario: 'Je bespreekt slaapproblemen met de huisarts.',
    roleA: 'Patiënt',
    roleB: 'Huisarts',
    levels: ['B1'],
    category: 'Gezondheid',
    tips: ['Beschrijf je slaappatroon.', 'Vraag om advies.'],
  },
  {
    id: 'sit-b1-gezond-10',
    scenario: 'Je bespreekt hoe je voor een ziek familielid zorgt.',
    roleA: 'Mantelzorger',
    roleB: 'Hulpverlener',
    levels: ['B1'],
    category: 'Gezondheid',
    tips: ['Leg de situatie uit.', 'Vraag welke hulp er is.'],
  },
  // B2
  {
    id: 'sit-b2-gezond-01',
    scenario: 'Je voert een gesprek over een vervelende diagnose.',
    roleA: 'Patiënt',
    roleB: 'Arts',
    levels: ['B2'],
    category: 'Gezondheid',
    tips: ['Stel je vragen.', 'Vraag naar de mogelijkheden.'],
  },
  {
    id: 'sit-b2-gezond-02',
    scenario: 'Je bespreekt met een hulpverlener hoe je je mentaal voelt.',
    roleA: 'Cliënt',
    roleB: 'Hulpverlener',
    levels: ['B2'],
    category: 'Gezondheid',
    tips: ['Wees eerlijk.', 'Beschrijf je gevoelens.'],
  },
  {
    id: 'sit-b2-gezond-03',
    scenario: 'Je bespreekt met familie de zorg voor een oudere.',
    roleA: 'Familielid',
    roleB: 'Familielid',
    levels: ['B2'],
    category: 'Gezondheid',
    tips: ['Verdeel de taken.', 'Luister naar elkaar.'],
  },
  {
    id: 'sit-b2-gezond-04',
    scenario: 'Je bespreekt met je leidinggevende dat je overbelast bent.',
    roleA: 'Werknemer',
    roleB: 'Leidinggevende',
    levels: ['B2'],
    category: 'Gezondheid',
    tips: ['Wees eerlijk over je grenzen.', 'Vraag om steun.'],
  },
  {
    id: 'sit-b2-gezond-05',
    scenario: 'Je bespreekt met een vriend gevoelens van eenzaamheid.',
    roleA: 'Vriend',
    roleB: 'Vriend',
    levels: ['B2'],
    category: 'Gezondheid',
    tips: ['Wees open.', 'Vraag naar de ervaring van de ander.'],
  },
  {
    id: 'sit-b2-gezond-06',
    scenario: 'Je bespreekt met een ambtenaar problemen met de zorg.',
    roleA: 'Inwoner',
    roleB: 'Ambtenaar',
    levels: ['B2'],
    category: 'Gezondheid',
    tips: ['Onderbouw je verhaal.', 'Vraag naar oplossingen.'],
  },
  {
    id: 'sit-b2-gezond-07',
    scenario: 'Je overtuigt een familielid om gezonder te gaan leven.',
    roleA: 'Verteller',
    roleB: 'Familielid',
    levels: ['B2'],
    category: 'Gezondheid',
    tips: ['Spreek vanuit zorg.', 'Geef haalbare tips.'],
  },
  {
    id: 'sit-b2-gezond-08',
    scenario: 'Je legt uit dat je rust nodig hebt en grenzen stelt.',
    roleA: 'Verteller',
    roleB: 'Vriend',
    levels: ['B2'],
    category: 'Gezondheid',
    tips: ['Wees duidelijk.', 'Blijf vriendelijk.'],
  },
  {
    id: 'sit-b2-gezond-09',
    scenario: 'Je bespreekt met een familielid het ouder worden en de zorg.',
    roleA: 'Familielid',
    roleB: 'Familielid',
    levels: ['B2'],
    category: 'Gezondheid',
    tips: ['Wees respectvol.', 'Bespreek wensen voor de toekomst.'],
  },
  {
    id: 'sit-b2-gezond-10',
    scenario: 'Je bespreekt met een coach hoe je veerkrachtiger wordt.',
    roleA: 'Cliënt',
    roleB: 'Coach',
    levels: ['B2'],
    category: 'Gezondheid',
    tips: ['Vertel over een moeilijke ervaring.', 'Bespreek wat je wilt leren.'],
  },
];
