import type { Situation } from '../../types/content';

export const SITUATIONS: Situation[] = [
  // ── A1 ──────────────────────────────────────────────────────────────────
  {
    id: 'sit-a1-bakker',
    scenario: 'Je wilt een brood kopen bij de bakker.',
    roleA: 'Klant',
    roleB: 'Bakker',
    levels: ['A1'],
    tips: ['Vraag welke broden er zijn.', 'Zeg hoeveel je wilt.', 'Vraag wat het kost.'],
  },
  {
    id: 'sit-a1-buur',
    scenario: 'Je ontmoet je nieuwe buur voor het eerst en stelt jezelf voor.',
    roleA: 'Nieuwe buur',
    roleB: 'Buur',
    levels: ['A1'],
    tips: [
      'Zeg je naam.',
      'Vertel waar je vandaan komt.',
      'Vraag hoe lang de ander hier al woont.',
    ],
  },
  {
    id: 'sit-a1-supermarkt',
    scenario: 'Je kan iets niet vinden in de supermarkt en vraagt een medewerker om hulp.',
    roleA: 'Klant',
    roleB: 'Medewerker',
    levels: ['A1'],
    tips: ['Zeg wat je zoekt.', 'Bedank de medewerker.'],
  },
  {
    id: 'sit-a1-bus',
    scenario: 'Je wilt weten of de stoel naast iemand vrij is in de bus.',
    roleA: 'Reiziger',
    roleB: 'Medepassagier',
    levels: ['A1'],
    tips: ['Vraag of de plek vrij is.', 'Bedank de persoon.'],
  },
  {
    id: 'sit-a1-klas',
    scenario: 'Je begrijpt iets niet in de les en vraagt de leraar om uitleg.',
    roleA: 'Student',
    roleB: 'Leraar',
    levels: ['A1'],
    tips: ['Zeg welk woord of welke zin je niet begrijpt.', 'Vraag of de leraar het wil herhalen.'],
  },
  {
    id: 'sit-a1-cafe-bestellen',
    scenario: 'Je bestelt een koffie en een broodje in een café.',
    roleA: 'Klant',
    roleB: 'Barista',
    levels: ['A1', 'A2'],
    tips: ['Vraag wat er is.', 'Bestel iets.', 'Vraag de prijs.'],
  },
  {
    id: 'sit-a1-adres',
    scenario: 'Je bent de weg kwijt en vraagt iemand op straat hoe je bij het station komt.',
    roleA: 'Voorbijganger',
    roleB: 'Buurtbewoner',
    levels: ['A1', 'A2'],
    tips: ['Zeg dat je verdwaald bent.', 'Vraag de weg naar het station.', 'Bedank de persoon.'],
  },
  {
    id: 'sit-a1-bibliotheek',
    scenario: 'Je wilt een boek lenen in de bibliotheek maar je hebt nog geen pas.',
    roleA: 'Bezoeker',
    roleB: 'Bibliotheekmedewerker',
    levels: ['A1', 'A2'],
    tips: ['Vraag hoe je een pas kunt aanvragen.', 'Geef je naam en adres op.'],
  },

  // ── A2 ──────────────────────────────────────────────────────────────────
  {
    id: 'sit-a2-dokter',
    scenario: 'Je voelt je ziek en vertelt de dokter wat er aan de hand is.',
    roleA: 'Patiënt',
    roleB: 'Dokter',
    levels: ['A2'],
    tips: ['Beschrijf je klachten.', 'Zeg hoe lang je al ziek bent.', 'Vraag wat je moet doen.'],
  },
  {
    id: 'sit-a2-afspraak',
    scenario: 'Je belt naar een tandarts om een afspraak te maken.',
    roleA: 'Patiënt',
    roleB: 'Receptionist',
    levels: ['A2'],
    tips: ['Zeg waarom je belt.', 'Geef aan wanneer je kunt.', 'Bevestig datum en tijd.'],
  },
  {
    id: 'sit-a2-collega',
    scenario: 'Je vraagt een collega om hulp bij een taak op het werk.',
    roleA: 'Werknemer',
    roleB: 'Collega',
    levels: ['A2', 'B1'],
    tips: ['Leg uit wat het probleem is.', 'Vraag of de collega tijd heeft.', 'Bedank je collega.'],
  },
  {
    id: 'sit-a2-restaurant',
    scenario:
      'Je bent in een restaurant. Het eten is koud — je vraagt de ober hier wat aan te doen.',
    roleA: 'Gast',
    roleB: 'Ober',
    levels: ['A2', 'B1'],
    tips: [
      'Wees vriendelijk maar duidelijk.',
      'Beschrijf het probleem.',
      'Vraag om een oplossing.',
    ],
  },
  {
    id: 'sit-a2-huur',
    scenario: 'Je wil een kamer huren en belt de verhuurder met vragen.',
    roleA: 'Huurder',
    roleB: 'Verhuurder',
    levels: ['A2', 'B1'],
    tips: [
      'Vraag naar de huurprijs.',
      'Vraag wat er inbegrepen is.',
      'Vraag wanneer je kunt bezichtigen.',
    ],
  },
  {
    id: 'sit-a2-kinderopvang',
    scenario: 'Je vraagt informatie over de kinderopvang in de buurt.',
    roleA: 'Ouder',
    roleB: 'Medewerker kinderopvang',
    levels: ['A2'],
    tips: [
      'Vraag naar openingstijden.',
      'Vraag wat het kost.',
      'Vraag hoe je je kind kunt aanmelden.',
    ],
  },
  {
    id: 'sit-a2-boodschappenlijst',
    scenario:
      'Je vraagt je taalmaatje te helpen je boodschappenlijst in het Nederlands te schrijven.',
    roleA: 'Deelnemer',
    roleB: 'Taalmaatje',
    levels: ['A2'],
    tips: ['Noem de producten die je nodig hebt.', 'Vraag hoe je ze schrijft.'],
  },

  // ── B1 ──────────────────────────────────────────────────────────────────
  {
    id: 'sit-b1-klacht',
    scenario: 'Je hebt een product gekocht dat kapot is en wil het terugbrengen naar de winkel.',
    roleA: 'Klant',
    roleB: 'Winkelmedewerker',
    levels: ['B1'],
    tips: [
      'Leg uit wat er kapot is.',
      'Vraag om je geld terug of een nieuw product.',
      'Wees vriendelijk maar standvastig.',
    ],
  },
  {
    id: 'sit-b1-sollicitatie',
    scenario: 'Je hebt een sollicitatiegesprek voor een bijbaan als supermarktmedewerker.',
    roleA: 'Sollicitant',
    roleB: 'Manager',
    levels: ['B1', 'B2'],
    tips: [
      'Vertel iets over jezelf.',
      'Leg uit waarom je deze baan wil.',
      'Vraag wat de verwachtingen zijn.',
    ],
  },
  {
    id: 'sit-b1-gevoel',
    scenario: 'Je vertelt een vriend dat je je eenzaam voelt in Nederland.',
    roleA: 'Jij',
    roleB: 'Vriend',
    levels: ['B1'],
    tips: ['Beschrijf hoe je je voelt.', 'Vertel wat je mist.', 'Vraag om advies of begrip.'],
  },
  {
    id: 'sit-b1-misverstand',
    scenario: 'Er is een misverstand ontstaan tussen jou en je buur over parkeren.',
    roleA: 'Bewoner A',
    roleB: 'Bewoner B',
    levels: ['B1'],
    tips: ['Leg kalm je situatie uit.', 'Luister naar de ander.', 'Zoek samen een oplossing.'],
  },
  {
    id: 'sit-b1-formulier',
    scenario: 'Je begrijpt een officieel formulier niet en vraagt iemand om hulp.',
    roleA: 'Deelnemer',
    roleB: 'Vrijwilliger',
    levels: ['B1'],
    tips: ['Wijs aan wat je niet begrijpt.', 'Vraag om een uitleg in gewone taal.'],
  },
  {
    id: 'sit-b1-vergadering',
    scenario: 'Je hebt een vergadering op het werk en wil je mening geven over een plan.',
    roleA: 'Medewerker',
    roleB: 'Teamlid',
    levels: ['B1', 'B2'],
    tips: ['Zeg dat je iets wil zeggen.', 'Geef je mening duidelijk.', 'Vraag wat de ander denkt.'],
  },

  // ── B2 ──────────────────────────────────────────────────────────────────
  {
    id: 'sit-b2-onderhandelen',
    scenario: 'Je wil onderhandelen over je salaris met je werkgever.',
    roleA: 'Werknemer',
    roleB: 'Werkgever',
    levels: ['B2'],
    tips: [
      'Noem je huidige situatie.',
      'Vraag om een verhoging met een reden.',
      'Reageer op tegenargumenten.',
    ],
  },
  {
    id: 'sit-b2-discussie',
    scenario: 'Je hebt een andere mening dan je collega over werken vanuit huis.',
    roleA: 'Collega A',
    roleB: 'Collega B',
    levels: ['B2'],
    tips: [
      'Vertel jouw standpunt en geef redenen.',
      'Reageer respectvol op de mening van de ander.',
      'Probeer tot een compromis te komen.',
    ],
  },
  {
    id: 'sit-b2-slechtnieuws',
    scenario: 'Je moet een vriend vertellen dat je zijn verjaardag vergeten bent.',
    roleA: 'Jij',
    roleB: 'Vriend',
    levels: ['B2'],
    tips: ['Bied je excuses aan.', 'Leg uit wat er is gebeurd.', 'Maak het goed.'],
  },
  {
    id: 'sit-b2-uitzondering',
    scenario: 'Je was ziek en vraagt je docent om een uitzondering op de deadline.',
    roleA: 'Student',
    roleB: 'Docent',
    levels: ['B1', 'B2'],
    tips: [
      'Leg de situatie uit.',
      'Vraag vriendelijk om meer tijd.',
      'Stel zelf een nieuwe deadline voor.',
    ],
  },
  {
    id: 'sit-b2-buurtoverleg',
    scenario: 'Op een buurtoverleg wil jij een overlastprobleem aankaarten.',
    roleA: 'Bewoner',
    roleB: 'Buurtbewoner',
    levels: ['B2'],
    tips: [
      'Beschrijf het probleem concreet.',
      'Vraag anderen om steun.',
      'Doe een voorstel voor een oplossing.',
    ],
  },
];
