import type { Topic } from '../../types/content';

export const TOPICS: Topic[] = [
  // ══ BUURT ════════════════════════════════════════════════════════════════
  // A1
  { id: 't-a1-buurt-01', text: 'Hoe heet jouw straat?', levels: ['A1'], category: 'Buurt' },
  {
    id: 't-a1-buurt-02',
    text: 'Woon je in een huis of een flat?',
    levels: ['A1'],
    category: 'Buurt',
  },
  {
    id: 't-a1-buurt-03',
    text: 'Is er een winkel dichtbij jouw huis?',
    levels: ['A1'],
    category: 'Buurt',
  },
  { id: 't-a1-buurt-04', text: 'Heb je een park in de buurt?', levels: ['A1'], category: 'Buurt' },
  { id: 't-a1-buurt-05', text: 'Hoe heet jouw stad of dorp?', levels: ['A1'], category: 'Buurt' },
  { id: 't-a1-buurt-06', text: 'Ken je je buren?', levels: ['A1'], category: 'Buurt' },
  { id: 't-a1-buurt-07', text: 'Is jouw buurt rustig of druk?', levels: ['A1'], category: 'Buurt' },
  { id: 't-a1-buurt-08', text: 'Waar koop je brood?', levels: ['A1'], category: 'Buurt' },
  {
    id: 't-a1-buurt-09',
    text: 'Is er een school in jouw buurt?',
    levels: ['A1'],
    category: 'Buurt',
  },
  { id: 't-a1-buurt-10', text: 'Hoe ga je naar het centrum?', levels: ['A1'], category: 'Buurt' },
  { id: 't-a1-buurt-11', text: 'Heb je een bushalte dichtbij?', levels: ['A1'], category: 'Buurt' },
  {
    id: 't-a1-buurt-12',
    text: 'Wat zie je als je uit het raam kijkt?',
    levels: ['A1'],
    category: 'Buurt',
  },
  {
    id: 't-a1-buurt-13',
    text: 'Is er een speeltuin in de buurt?',
    levels: ['A1'],
    category: 'Buurt',
  },
  {
    id: 't-a1-buurt-14',
    text: 'Hoe ver woon je van de taalles?',
    levels: ['A1'],
    category: 'Buurt',
  },
  {
    id: 't-a1-buurt-15',
    text: 'Welke winkel vind je fijn in de buurt?',
    levels: ['A1'],
    category: 'Buurt',
  },
  { id: 't-a1-buurt-16', text: 'Is er een markt in jouw stad?', levels: ['A1'], category: 'Buurt' },
  { id: 't-a1-buurt-17', text: 'Loop je vaak door je buurt?', levels: ['A1'], category: 'Buurt' },
  {
    id: 't-a1-buurt-18',
    text: 'Heb je een supermarkt dichtbij?',
    levels: ['A1'],
    category: 'Buurt',
  },
  { id: 't-a1-buurt-19', text: 'Wat is mooi in jouw buurt?', levels: ['A1'], category: 'Buurt' },
  {
    id: 't-a1-buurt-20',
    text: 'Is er water of een gracht bij jou in de buurt?',
    levels: ['A1'],
    category: 'Buurt',
  },
  // A2
  {
    id: 't-a2-buurt-01',
    text: 'Beschrijf je buurt: hoe ziet het eruit?',
    levels: ['A2'],
    category: 'Buurt',
  },
  {
    id: 't-a2-buurt-02',
    text: 'Wat doe je het liefst in jouw buurt?',
    levels: ['A2'],
    category: 'Buurt',
  },
  {
    id: 't-a2-buurt-03',
    text: 'Welke plek in jouw stad vind je fijn?',
    levels: ['A2'],
    category: 'Buurt',
  },
  {
    id: 't-a2-buurt-04',
    text: 'Hoe is het verkeer in jouw buurt?',
    levels: ['A2'],
    category: 'Buurt',
  },
  {
    id: 't-a2-buurt-05',
    text: 'Praat je weleens met je buren?',
    levels: ['A2'],
    category: 'Buurt',
  },
  { id: 't-a2-buurt-06', text: 'Wat mis je in jouw buurt?', levels: ['A2'], category: 'Buurt' },
  {
    id: 't-a2-buurt-07',
    text: 'Is jouw buurt veranderd sinds je er woont?',
    levels: ['A2'],
    category: 'Buurt',
  },
  {
    id: 't-a2-buurt-08',
    text: 'Waar ga je naartoe als je rust wil?',
    levels: ['A2'],
    category: 'Buurt',
  },
  {
    id: 't-a2-buurt-09',
    text: 'Hoe vier je een feest in de buurt?',
    levels: ['A2'],
    category: 'Buurt',
  },
  {
    id: 't-a2-buurt-10',
    text: 'Welke winkels gebruik je het meest?',
    levels: ['A2'],
    category: 'Buurt',
  },
  {
    id: 't-a2-buurt-11',
    text: 'Is er genoeg groen in jouw buurt?',
    levels: ['A2'],
    category: 'Buurt',
  },
  {
    id: 't-a2-buurt-12',
    text: 'Hoe vind je het openbaar vervoer in je stad?',
    levels: ['A2'],
    category: 'Buurt',
  },
  {
    id: 't-a2-buurt-13',
    text: 'Wat doe je op een zonnige dag in de buurt?',
    levels: ['A2'],
    category: 'Buurt',
  },
  {
    id: 't-a2-buurt-14',
    text: 'Ken je een leuk café of restaurant dichtbij?',
    levels: ['A2'],
    category: 'Buurt',
  },
  {
    id: 't-a2-buurt-15',
    text: 'Hoe veilig voel je je in jouw buurt?',
    levels: ['A2'],
    category: 'Buurt',
  },
  {
    id: 't-a2-buurt-16',
    text: 'Wat zou je willen veranderen aan je buurt?',
    levels: ['A2'],
    category: 'Buurt',
  },
  {
    id: 't-a2-buurt-17',
    text: 'Welke plek in Leiden moet iedereen zien?',
    levels: ['A2'],
    category: 'Buurt',
  },
  {
    id: 't-a2-buurt-18',
    text: 'Hoe leerde je je buurt kennen toen je er kwam?',
    levels: ['A2'],
    category: 'Buurt',
  },
  {
    id: 't-a2-buurt-19',
    text: 'Waar speel je of sport je buiten?',
    levels: ['A2'],
    category: 'Buurt',
  },
  {
    id: 't-a2-buurt-20',
    text: 'Wat is het verschil tussen jouw buurt nu en vroeger?',
    levels: ['A2'],
    category: 'Buurt',
  },
  // B1
  {
    id: 't-b1-buurt-01',
    text: 'Wat maakt een buurt prettig om in te wonen?',
    levels: ['B1'],
    category: 'Buurt',
  },
  {
    id: 't-b1-buurt-02',
    text: 'Hoe goed ken je je buren, en hoe komt dat?',
    levels: ['B1'],
    category: 'Buurt',
  },
  {
    id: 't-b1-buurt-03',
    text: 'Wat zou je veranderen aan jouw stad als je dat kon?',
    levels: ['B1'],
    category: 'Buurt',
  },
  {
    id: 't-b1-buurt-04',
    text: 'Welke rol speelt de buurt in jouw dagelijkse leven?',
    levels: ['B1'],
    category: 'Buurt',
  },
  {
    id: 't-b1-buurt-05',
    text: 'Hoe ga je om met overlast in de buurt?',
    levels: ['B1'],
    category: 'Buurt',
  },
  {
    id: 't-b1-buurt-06',
    text: 'Wat vind je van het openbaar vervoer in Nederland?',
    levels: ['B1'],
    category: 'Buurt',
  },
  {
    id: 't-b1-buurt-07',
    text: 'Hoe belangrijk is contact met buren voor jou?',
    levels: ['B1'],
    category: 'Buurt',
  },
  {
    id: 't-b1-buurt-08',
    text: 'Welk advies geef je iemand die net in jouw stad komt wonen?',
    levels: ['B1'],
    category: 'Buurt',
  },
  {
    id: 't-b1-buurt-09',
    text: 'Hoe verschilt jouw huidige buurt van waar je opgroeide?',
    levels: ['B1'],
    category: 'Buurt',
  },
  {
    id: 't-b1-buurt-10',
    text: 'Wat doe je om je thuis te voelen in een nieuwe buurt?',
    levels: ['B1'],
    category: 'Buurt',
  },
  {
    id: 't-b1-buurt-11',
    text: 'Hoe kan een buurt mensen samenbrengen?',
    levels: ['B1'],
    category: 'Buurt',
  },
  {
    id: 't-b1-buurt-12',
    text: 'Wat vind je van de drukte in Nederlandse steden?',
    levels: ['B1'],
    category: 'Buurt',
  },
  {
    id: 't-b1-buurt-13',
    text: 'Welke voorzieningen mist jouw buurt?',
    levels: ['B1'],
    category: 'Buurt',
  },
  {
    id: 't-b1-buurt-14',
    text: 'Hoe ga je om met buren die je niet aardig vindt?',
    levels: ['B1'],
    category: 'Buurt',
  },
  {
    id: 't-b1-buurt-15',
    text: 'Wat betekent een goede buur voor jou?',
    levels: ['B1'],
    category: 'Buurt',
  },
  {
    id: 't-b1-buurt-16',
    text: 'Hoe veilig vind je Nederland vergeleken met je thuisland?',
    levels: ['B1'],
    category: 'Buurt',
  },
  {
    id: 't-b1-buurt-17',
    text: 'Wat zou jij organiseren voor je buurt?',
    levels: ['B1'],
    category: 'Buurt',
  },
  {
    id: 't-b1-buurt-18',
    text: 'Hoe verandert een buurt door nieuwe bewoners?',
    levels: ['B1'],
    category: 'Buurt',
  },
  {
    id: 't-b1-buurt-19',
    text: 'Welke plek in jouw stad heeft een bijzondere betekenis voor jou?',
    levels: ['B1'],
    category: 'Buurt',
  },
  {
    id: 't-b1-buurt-20',
    text: 'Hoe belangrijk is groen en natuur in een stad?',
    levels: ['B1'],
    category: 'Buurt',
  },
  // B2
  {
    id: 't-b2-buurt-01',
    text: 'Welk verschil tussen Nederland en je geboorteland valt je in de stad het meest op?',
    levels: ['B2'],
    category: 'Buurt',
  },
  {
    id: 't-b2-buurt-02',
    text: 'Hoe denk je dat jouw stad er over twintig jaar uitziet?',
    levels: ['B2'],
    category: 'Buurt',
  },
  {
    id: 't-b2-buurt-03',
    text: 'Wat betekent een gemeenschap voor jou?',
    levels: ['B2'],
    category: 'Buurt',
  },
  {
    id: 't-b2-buurt-04',
    text: 'Hoe beïnvloedt de inrichting van een buurt het gedrag van mensen?',
    levels: ['B2'],
    category: 'Buurt',
  },
  {
    id: 't-b2-buurt-05',
    text: 'Welke maatschappelijke kwestie in jouw stad houdt je bezig?',
    levels: ['B2'],
    category: 'Buurt',
  },
  {
    id: 't-b2-buurt-06',
    text: 'Wat vind je van hoe Nederlandse steden omgaan met diversiteit?',
    levels: ['B2'],
    category: 'Buurt',
  },
  {
    id: 't-b2-buurt-07',
    text: 'Hoe verandert een stad door migratie?',
    levels: ['B2'],
    category: 'Buurt',
  },
  {
    id: 't-b2-buurt-08',
    text: 'Welke verantwoordelijkheid heeft de overheid voor een leefbare buurt?',
    levels: ['B2'],
    category: 'Buurt',
  },
  {
    id: 't-b2-buurt-09',
    text: 'Hoe zou de ideale stad eruitzien volgens jou?',
    levels: ['B2'],
    category: 'Buurt',
  },
  {
    id: 't-b2-buurt-10',
    text: 'Wat zijn de voor- en nadelen van wonen in een grote stad?',
    levels: ['B2'],
    category: 'Buurt',
  },
  {
    id: 't-b2-buurt-11',
    text: 'Hoe ga je om met anonimiteit in een stad?',
    levels: ['B2'],
    category: 'Buurt',
  },
  {
    id: 't-b2-buurt-12',
    text: 'Welke rol moeten bewoners zelf spelen in hun buurt?',
    levels: ['B2'],
    category: 'Buurt',
  },
  {
    id: 't-b2-buurt-13',
    text: 'Hoe beïnvloedt woningnood het samenleven in een stad?',
    levels: ['B2'],
    category: 'Buurt',
  },
  {
    id: 't-b2-buurt-14',
    text: 'Wat vind je van het veranderen van oude buurten door nieuwkomers met geld?',
    levels: ['B2'],
    category: 'Buurt',
  },
  {
    id: 't-b2-buurt-15',
    text: 'Hoe belangrijk is cultureel erfgoed voor een stad?',
    levels: ['B2'],
    category: 'Buurt',
  },
  {
    id: 't-b2-buurt-16',
    text: 'Hoe kan een stad zowel modern als gezellig blijven?',
    levels: ['B2'],
    category: 'Buurt',
  },
  {
    id: 't-b2-buurt-17',
    text: 'Welke invloed heeft toerisme op een stad als Leiden?',
    levels: ['B2'],
    category: 'Buurt',
  },
  {
    id: 't-b2-buurt-18',
    text: 'Hoe denk je over de balans tussen privacy en gemeenschap?',
    levels: ['B2'],
    category: 'Buurt',
  },
  {
    id: 't-b2-buurt-19',
    text: "Wat maakt een stad voor jou echt 'thuis'?",
    levels: ['B2'],
    category: 'Buurt',
  },
  {
    id: 't-b2-buurt-20',
    text: 'Welke verantwoordelijkheid hebben we voor het milieu in onze buurt?',
    levels: ['B2'],
    category: 'Buurt',
  },

  // ══ FAMILIE ══════════════════════════════════════════════════════════════
  // A1
  { id: 't-a1-familie-01', text: 'Hoe groot is je familie?', levels: ['A1'], category: 'Familie' },
  { id: 't-a1-familie-02', text: 'Heb je broers of zussen?', levels: ['A1'], category: 'Familie' },
  { id: 't-a1-familie-03', text: 'Heb je kinderen?', levels: ['A1'], category: 'Familie' },
  { id: 't-a1-familie-04', text: 'Hoe heet je moeder?', levels: ['A1'], category: 'Familie' },
  {
    id: 't-a1-familie-05',
    text: 'Woont je familie dichtbij?',
    levels: ['A1'],
    category: 'Familie',
  },
  { id: 't-a1-familie-06', text: 'Met wie woon je samen?', levels: ['A1'], category: 'Familie' },
  {
    id: 't-a1-familie-07',
    text: 'Heb je een grote of kleine familie?',
    levels: ['A1'],
    category: 'Familie',
  },
  { id: 't-a1-familie-08', text: 'Wie kookt er thuis?', levels: ['A1'], category: 'Familie' },
  { id: 't-a1-familie-09', text: "Heb je opa's en oma's?", levels: ['A1'], category: 'Familie' },
  { id: 't-a1-familie-10', text: 'Wie helpt jou thuis?', levels: ['A1'], category: 'Familie' },
  {
    id: 't-a1-familie-11',
    text: 'Hoe heet je beste vriend of vriendin?',
    levels: ['A1'],
    category: 'Familie',
  },
  {
    id: 't-a1-familie-12',
    text: 'Speel je met kinderen in je familie?',
    levels: ['A1'],
    category: 'Familie',
  },
  {
    id: 't-a1-familie-13',
    text: 'Bel je vaak met je familie?',
    levels: ['A1'],
    category: 'Familie',
  },
  {
    id: 't-a1-familie-14',
    text: 'Wie is het oudst in jouw familie?',
    levels: ['A1'],
    category: 'Familie',
  },
  {
    id: 't-a1-familie-15',
    text: 'Eet je samen met je familie?',
    levels: ['A1'],
    category: 'Familie',
  },
  { id: 't-a1-familie-16', text: 'Heb je een neef of nicht?', levels: ['A1'], category: 'Familie' },
  {
    id: 't-a1-familie-17',
    text: 'Wat doe je samen met je familie?',
    levels: ['A1'],
    category: 'Familie',
  },
  {
    id: 't-a1-familie-18',
    text: 'Wie lijkt op jou in je familie?',
    levels: ['A1'],
    category: 'Familie',
  },
  {
    id: 't-a1-familie-19',
    text: 'Hoe noem je je vader thuis?',
    levels: ['A1'],
    category: 'Familie',
  },
  {
    id: 't-a1-familie-20',
    text: 'Heb je foto’s van je familie?',
    levels: ['A1'],
    category: 'Familie',
  },
  // A2
  {
    id: 't-a2-familie-01',
    text: 'Vertel over een goede vriend of vriendin.',
    levels: ['A2'],
    category: 'Familie',
  },
  {
    id: 't-a2-familie-02',
    text: 'Hoe vier jij je verjaardag?',
    levels: ['A2'],
    category: 'Familie',
  },
  {
    id: 't-a2-familie-03',
    text: 'Wie staat jou het meest na?',
    levels: ['A2'],
    category: 'Familie',
  },
  {
    id: 't-a2-familie-04',
    text: 'Wat doe je graag samen met je familie?',
    levels: ['A2'],
    category: 'Familie',
  },
  {
    id: 't-a2-familie-05',
    text: 'Hoe houd je contact met familie ver weg?',
    levels: ['A2'],
    category: 'Familie',
  },
  {
    id: 't-a2-familie-06',
    text: 'Vertel over iemand in je familie die je bewondert.',
    levels: ['A2'],
    category: 'Familie',
  },
  {
    id: 't-a2-familie-07',
    text: 'Hoe zag een gewone dag met je familie eruit vroeger?',
    levels: ['A2'],
    category: 'Familie',
  },
  {
    id: 't-a2-familie-08',
    text: 'Wat is een leuke herinnering met je familie?',
    levels: ['A2'],
    category: 'Familie',
  },
  {
    id: 't-a2-familie-09',
    text: 'Hoe vier je feestdagen met je familie?',
    levels: ['A2'],
    category: 'Familie',
  },
  {
    id: 't-a2-familie-10',
    text: 'Wie in je familie lijkt het meest op jou?',
    levels: ['A2'],
    category: 'Familie',
  },
  {
    id: 't-a2-familie-11',
    text: 'Hoe leerde je je beste vriend kennen?',
    levels: ['A2'],
    category: 'Familie',
  },
  {
    id: 't-a2-familie-12',
    text: 'Wat doe je als een vriend hulp nodig heeft?',
    levels: ['A2'],
    category: 'Familie',
  },
  {
    id: 't-a2-familie-13',
    text: 'Vertel over een familielid dat ver weg woont.',
    levels: ['A2'],
    category: 'Familie',
  },
  {
    id: 't-a2-familie-14',
    text: 'Wat eet je familie graag samen?',
    levels: ['A2'],
    category: 'Familie',
  },
  {
    id: 't-a2-familie-15',
    text: 'Hoe vaak zie je je familie?',
    levels: ['A2'],
    category: 'Familie',
  },
  {
    id: 't-a2-familie-16',
    text: 'Wie heeft jou veel geleerd in je leven?',
    levels: ['A2'],
    category: 'Familie',
  },
  {
    id: 't-a2-familie-17',
    text: 'Wat is belangrijk in een vriendschap voor jou?',
    levels: ['A2'],
    category: 'Familie',
  },
  {
    id: 't-a2-familie-18',
    text: 'Heb je hier in Nederland nieuwe vrienden gemaakt?',
    levels: ['A2'],
    category: 'Familie',
  },
  {
    id: 't-a2-familie-19',
    text: 'Vertel over een trouwerij of feest in je familie.',
    levels: ['A2'],
    category: 'Familie',
  },
  {
    id: 't-a2-familie-20',
    text: 'Welke familietraditie vind je leuk?',
    levels: ['A2'],
    category: 'Familie',
  },
  // B1
  {
    id: 't-b1-familie-01',
    text: 'Wat vind je belangrijk in vriendschap?',
    levels: ['B1'],
    category: 'Familie',
  },
  {
    id: 't-b1-familie-02',
    text: 'Vertel over een traditie in jouw familie.',
    levels: ['B1'],
    category: 'Familie',
  },
  {
    id: 't-b1-familie-03',
    text: 'Vertel over iemand die jou heeft geïnspireerd.',
    levels: ['B1'],
    category: 'Familie',
  },
  {
    id: 't-b1-familie-04',
    text: 'Hoe heb je je eerste vrienden in Nederland leren kennen?',
    levels: ['B1'],
    category: 'Familie',
  },
  {
    id: 't-b1-familie-05',
    text: 'Hoe belangrijk is familie in jouw dagelijkse leven?',
    levels: ['B1'],
    category: 'Familie',
  },
  {
    id: 't-b1-familie-06',
    text: 'Wat mis je het meest aan je familie?',
    levels: ['B1'],
    category: 'Familie',
  },
  {
    id: 't-b1-familie-07',
    text: 'Hoe houd je een vriendschap goed?',
    levels: ['B1'],
    category: 'Familie',
  },
  {
    id: 't-b1-familie-08',
    text: 'Wat heb je van je ouders geleerd?',
    levels: ['B1'],
    category: 'Familie',
  },
  {
    id: 't-b1-familie-09',
    text: 'Hoe gaan jullie in je familie om met ruzie?',
    levels: ['B1'],
    category: 'Familie',
  },
  {
    id: 't-b1-familie-10',
    text: 'Wat zou je je kinderen willen meegeven?',
    levels: ['B1'],
    category: 'Familie',
  },
  {
    id: 't-b1-familie-11',
    text: 'Hoe verandert vriendschap als je ouder wordt?',
    levels: ['B1'],
    category: 'Familie',
  },
  {
    id: 't-b1-familie-12',
    text: 'Vertel over een feestdag die jij viert.',
    levels: ['B1'],
    category: 'Familie',
  },
  {
    id: 't-b1-familie-13',
    text: "Wat betekent 'familie' voor jou?",
    levels: ['B1'],
    category: 'Familie',
  },
  {
    id: 't-b1-familie-14',
    text: 'Hoe blijf je verbonden met familie in een ander land?',
    levels: ['B1'],
    category: 'Familie',
  },
  {
    id: 't-b1-familie-15',
    text: 'Welke rol speelt respect in jouw familie?',
    levels: ['B1'],
    category: 'Familie',
  },
  {
    id: 't-b1-familie-16',
    text: 'Hoe ga je om met verschillen tussen generaties?',
    levels: ['B1'],
    category: 'Familie',
  },
  {
    id: 't-b1-familie-17',
    text: 'Wat is de mooiste les die een familielid je leerde?',
    levels: ['B1'],
    category: 'Familie',
  },
  {
    id: 't-b1-familie-18',
    text: 'Hoe zou je een goede ouder beschrijven?',
    levels: ['B1'],
    category: 'Familie',
  },
  {
    id: 't-b1-familie-19',
    text: 'Wat doe je om vriendschappen te onderhouden ondanks afstand?',
    levels: ['B1'],
    category: 'Familie',
  },
  {
    id: 't-b1-familie-20',
    text: 'Hoe belangrijk is het om vrienden van je eigen cultuur te hebben?',
    levels: ['B1'],
    category: 'Familie',
  },
  // B2
  {
    id: 't-b2-familie-01',
    text: 'Wanneer was je voor het laatst echt verrast door iemand?',
    levels: ['B2'],
    category: 'Familie',
  },
  {
    id: 't-b2-familie-02',
    text: 'Welke eigenschap waardeer je het meest in mensen?',
    levels: ['B2'],
    category: 'Familie',
  },
  {
    id: 't-b2-familie-03',
    text: 'Beschrijf een moment waarop je je echt begrepen voelde.',
    levels: ['B2'],
    category: 'Familie',
  },
  {
    id: 't-b2-familie-04',
    text: 'Hoe zou je jezelf beschrijven in drie woorden?',
    levels: ['B2'],
    category: 'Familie',
  },
  {
    id: 't-b2-familie-05',
    text: 'Wat is het verschil tussen eerlijk zijn en kwetsend zijn?',
    levels: ['B2'],
    category: 'Familie',
  },
  {
    id: 't-b2-familie-06',
    text: 'Hoe verandert de rol van familie als je migreert?',
    levels: ['B2'],
    category: 'Familie',
  },
  {
    id: 't-b2-familie-07',
    text: 'Hoe beïnvloedt afstand de band met je familie?',
    levels: ['B2'],
    category: 'Familie',
  },
  {
    id: 't-b2-familie-08',
    text: 'Wat betekent loyaliteit voor jou?',
    levels: ['B2'],
    category: 'Familie',
  },
  {
    id: 't-b2-familie-09',
    text: 'Hoe ga je om met verwachtingen van je familie?',
    levels: ['B2'],
    category: 'Familie',
  },
  {
    id: 't-b2-familie-10',
    text: 'Welke familiewaarden wil je doorgeven, en welke niet?',
    levels: ['B2'],
    category: 'Familie',
  },
  {
    id: 't-b2-familie-11',
    text: 'Hoe verandert een mens door ouder te worden?',
    levels: ['B2'],
    category: 'Familie',
  },
  {
    id: 't-b2-familie-12',
    text: 'Wat maakt een relatie sterk op de lange termijn?',
    levels: ['B2'],
    category: 'Familie',
  },
  {
    id: 't-b2-familie-13',
    text: 'Hoe ga je om met een conflict met iemand die je liefhebt?',
    levels: ['B2'],
    category: 'Familie',
  },
  {
    id: 't-b2-familie-14',
    text: 'Welke invloed heeft je opvoeding op wie je nu bent?',
    levels: ['B2'],
    category: 'Familie',
  },
  {
    id: 't-b2-familie-15',
    text: 'Hoe denk je over de rol van mannen en vrouwen in een gezin?',
    levels: ['B2'],
    category: 'Familie',
  },
  {
    id: 't-b2-familie-16',
    text: 'Wat betekent vergeven voor jou?',
    levels: ['B2'],
    category: 'Familie',
  },
  {
    id: 't-b2-familie-17',
    text: 'Hoe vind je een balans tussen je eigen wensen en die van je familie?',
    levels: ['B2'],
    category: 'Familie',
  },
  {
    id: 't-b2-familie-18',
    text: 'Hoe verandert vriendschap door cultuurverschillen?',
    levels: ['B2'],
    category: 'Familie',
  },
  {
    id: 't-b2-familie-19',
    text: 'Wat zou je tegen je jongere zelf willen zeggen?',
    levels: ['B2'],
    category: 'Familie',
  },
  {
    id: 't-b2-familie-20',
    text: 'Hoe belangrijk is het om je wortels te kennen?',
    levels: ['B2'],
    category: 'Familie',
  },

  // ══ WERK ═════════════════════════════════════════════════════════════════
  // A1
  { id: 't-a1-werk-01', text: 'Werk je nu?', levels: ['A1'], category: 'Werk' },
  { id: 't-a1-werk-02', text: 'Wat voor werk wil je doen?', levels: ['A1'], category: 'Werk' },
  {
    id: 't-a1-werk-03',
    text: 'Hoe ga je naar je werk of school?',
    levels: ['A1'],
    category: 'Werk',
  },
  {
    id: 't-a1-werk-04',
    text: 'Werk je liever binnen of buiten?',
    levels: ['A1'],
    category: 'Werk',
  },
  { id: 't-a1-werk-05', text: 'Wat heb je vandaag geleerd?', levels: ['A1'], category: 'Werk' },
  { id: 't-a1-werk-06', text: 'Vind je de taalles leuk?', levels: ['A1'], category: 'Werk' },
  {
    id: 't-a1-werk-07',
    text: 'Wat is moeilijk aan Nederlands leren?',
    levels: ['A1'],
    category: 'Werk',
  },
  {
    id: 't-a1-werk-08',
    text: 'Hoe laat begin je met werken of leren?',
    levels: ['A1'],
    category: 'Werk',
  },
  {
    id: 't-a1-werk-09',
    text: 'Werk je liever alleen of met anderen?',
    levels: ['A1'],
    category: 'Werk',
  },
  { id: 't-a1-werk-10', text: 'Welk werk deden je ouders?', levels: ['A1'], category: 'Werk' },
  { id: 't-a1-werk-11', text: 'Wat wil je goed kunnen?', levels: ['A1'], category: 'Werk' },
  { id: 't-a1-werk-12', text: 'Heb je een diploma?', levels: ['A1'], category: 'Werk' },
  {
    id: 't-a1-werk-13',
    text: 'Werk je met je handen of met de computer?',
    levels: ['A1'],
    category: 'Werk',
  },
  { id: 't-a1-werk-14', text: 'Wat doe je graag goed?', levels: ['A1'], category: 'Werk' },
  {
    id: 't-a1-werk-15',
    text: 'Hoe lang doe je over je werk per dag?',
    levels: ['A1'],
    category: 'Werk',
  },
  { id: 't-a1-werk-16', text: 'Wil je een nieuwe baan?', levels: ['A1'], category: 'Werk' },
  {
    id: 't-a1-werk-17',
    text: 'Welk beroep vind je interessant?',
    levels: ['A1'],
    category: 'Werk',
  },
  { id: 't-a1-werk-18', text: 'Wat leer je nu?', levels: ['A1'], category: 'Werk' },
  { id: 't-a1-werk-19', text: 'Heb je collega’s?', levels: ['A1'], category: 'Werk' },
  {
    id: 't-a1-werk-20',
    text: 'Wat doe je in de pauze op werk of les?',
    levels: ['A1'],
    category: 'Werk',
  },
  // A2
  { id: 't-a2-werk-01', text: 'Wat heb je deze week geleerd?', levels: ['A2'], category: 'Werk' },
  { id: 't-a2-werk-02', text: 'Wat zou je graag willen leren?', levels: ['A2'], category: 'Werk' },
  {
    id: 't-a2-werk-03',
    text: 'Wat vind je moeilijk aan het Nederlands?',
    levels: ['A2'],
    category: 'Werk',
  },
  {
    id: 't-a2-werk-04',
    text: 'Vertel over een baan die je ooit had.',
    levels: ['A2'],
    category: 'Werk',
  },
  {
    id: 't-a2-werk-05',
    text: 'Hoe ziet jouw ideale werkdag eruit?',
    levels: ['A2'],
    category: 'Werk',
  },
  {
    id: 't-a2-werk-06',
    text: 'Wat voor werk zou je later willen doen?',
    levels: ['A2'],
    category: 'Werk',
  },
  {
    id: 't-a2-werk-07',
    text: 'Werk je liever in een team of alleen?',
    levels: ['A2'],
    category: 'Werk',
  },
  { id: 't-a2-werk-08', text: 'Wat vind je leuk aan leren?', levels: ['A2'], category: 'Werk' },
  { id: 't-a2-werk-09', text: 'Hoe leer jij het beste?', levels: ['A2'], category: 'Werk' },
  {
    id: 't-a2-werk-10',
    text: 'Wat is een goede collega voor jou?',
    levels: ['A2'],
    category: 'Werk',
  },
  {
    id: 't-a2-werk-11',
    text: 'Hoe ga je om met een moeilijke taak?',
    levels: ['A2'],
    category: 'Werk',
  },
  {
    id: 't-a2-werk-12',
    text: 'Wat heb je geleerd van een vorige baan?',
    levels: ['A2'],
    category: 'Werk',
  },
  {
    id: 't-a2-werk-13',
    text: 'Welke vaardigheid wil je verbeteren?',
    levels: ['A2'],
    category: 'Werk',
  },
  {
    id: 't-a2-werk-14',
    text: 'Hoe vier je het als iets lukt op je werk?',
    levels: ['A2'],
    category: 'Werk',
  },
  {
    id: 't-a2-werk-15',
    text: 'Wat is het verschil tussen werk hier en in je thuisland?',
    levels: ['A2'],
    category: 'Werk',
  },
  {
    id: 't-a2-werk-16',
    text: 'Wat doe je als je iets niet begrijpt op je werk?',
    levels: ['A2'],
    category: 'Werk',
  },
  { id: 't-a2-werk-17', text: 'Welk beroep bewonder je?', levels: ['A2'], category: 'Werk' },
  {
    id: 't-a2-werk-18',
    text: 'Hoe belangrijk is werk voor jou?',
    levels: ['A2'],
    category: 'Werk',
  },
  { id: 't-a2-werk-19', text: 'Wat zou je willen studeren?', levels: ['A2'], category: 'Werk' },
  {
    id: 't-a2-werk-20',
    text: 'Hoe ziet jouw weg naar werk in Nederland eruit?',
    levels: ['A2'],
    category: 'Werk',
  },
  // B1
  {
    id: 't-b1-werk-01',
    text: 'Hoe leer je het beste een nieuwe taal?',
    levels: ['B1'],
    category: 'Werk',
  },
  {
    id: 't-b1-werk-02',
    text: 'Wat verwacht jij van de toekomst?',
    levels: ['B1'],
    category: 'Werk',
  },
  {
    id: 't-b1-werk-03',
    text: 'Hoe denk jij over werk en vrije tijd: is de balans goed?',
    levels: ['B1'],
    category: 'Werk',
  },
  {
    id: 't-b1-werk-04',
    text: 'Hoe is het schoolsysteem hier anders dan in jouw thuisland?',
    levels: ['B1'],
    category: 'Werk',
  },
  { id: 't-b1-werk-05', text: 'Wat motiveert jou om te werken?', levels: ['B1'], category: 'Werk' },
  {
    id: 't-b1-werk-06',
    text: 'Hoe ga je om met kritiek op je werk?',
    levels: ['B1'],
    category: 'Werk',
  },
  {
    id: 't-b1-werk-07',
    text: 'Wat maakt een baan zinvol voor jou?',
    levels: ['B1'],
    category: 'Werk',
  },
  {
    id: 't-b1-werk-08',
    text: 'Hoe belangrijk is geld bij het kiezen van werk?',
    levels: ['B1'],
    category: 'Werk',
  },
  {
    id: 't-b1-werk-09',
    text: 'Wat zou je doen als je je baan zou verliezen?',
    levels: ['B1'],
    category: 'Werk',
  },
  {
    id: 't-b1-werk-10',
    text: 'Hoe vind je werk in een nieuw land?',
    levels: ['B1'],
    category: 'Werk',
  },
  {
    id: 't-b1-werk-11',
    text: 'Welke vaardigheden heb je nodig voor jouw droombaan?',
    levels: ['B1'],
    category: 'Werk',
  },
  {
    id: 't-b1-werk-12',
    text: 'Hoe ga je om met stress op je werk?',
    levels: ['B1'],
    category: 'Werk',
  },
  {
    id: 't-b1-werk-13',
    text: 'Wat is een goede leidinggevende volgens jou?',
    levels: ['B1'],
    category: 'Werk',
  },
  {
    id: 't-b1-werk-14',
    text: 'Hoe belangrijk is samenwerken op je werk?',
    levels: ['B1'],
    category: 'Werk',
  },
  {
    id: 't-b1-werk-15',
    text: 'Wat heb je geleerd van een fout op je werk?',
    levels: ['B1'],
    category: 'Werk',
  },
  {
    id: 't-b1-werk-16',
    text: 'Hoe blijf je leren als je ouder wordt?',
    levels: ['B1'],
    category: 'Werk',
  },
  {
    id: 't-b1-werk-17',
    text: 'Welk advies geef je iemand die werk zoekt?',
    levels: ['B1'],
    category: 'Werk',
  },
  {
    id: 't-b1-werk-18',
    text: 'Wat vind je van vrijwilligerswerk?',
    levels: ['B1'],
    category: 'Werk',
  },
  {
    id: 't-b1-werk-19',
    text: 'Hoe belangrijk is een diploma voor succes?',
    levels: ['B1'],
    category: 'Werk',
  },
  {
    id: 't-b1-werk-20',
    text: 'Hoe zou jouw leven eruitzien zonder werk?',
    levels: ['B1'],
    category: 'Werk',
  },
  // B2
  {
    id: 't-b2-werk-01',
    text: 'Welke uitvinding heeft de wereld het meest veranderd?',
    levels: ['B2'],
    category: 'Werk',
  },
  {
    id: 't-b2-werk-02',
    text: 'Hoe beïnvloedt taal de manier waarop je denkt?',
    levels: ['B2'],
    category: 'Werk',
  },
  {
    id: 't-b2-werk-03',
    text: 'Wat verlies je als je een nieuwe taal leert — en wat win je?',
    levels: ['B2'],
    category: 'Werk',
  },
  {
    id: 't-b2-werk-04',
    text: 'Wat wil je bereiken in de komende vijf jaar?',
    levels: ['B2'],
    category: 'Werk',
  },
  {
    id: 't-b2-werk-05',
    text: 'Hoe verandert technologie de manier waarop we werken?',
    levels: ['B2'],
    category: 'Werk',
  },
  { id: 't-b2-werk-06', text: 'Wat betekent succes voor jou?', levels: ['B2'], category: 'Werk' },
  {
    id: 't-b2-werk-07',
    text: 'Hoe denk je over de balans tussen werk en privé?',
    levels: ['B2'],
    category: 'Werk',
  },
  {
    id: 't-b2-werk-08',
    text: 'Welke rol zou werk moeten spelen in een mensenleven?',
    levels: ['B2'],
    category: 'Werk',
  },
  { id: 't-b2-werk-09', text: 'Hoe ga je om met mislukking?', levels: ['B2'], category: 'Werk' },
  {
    id: 't-b2-werk-10',
    text: 'Wat vind je van automatisering en het verdwijnen van banen?',
    levels: ['B2'],
    category: 'Werk',
  },
  {
    id: 't-b2-werk-11',
    text: 'Hoe belangrijk is passie bij het kiezen van een beroep?',
    levels: ['B2'],
    category: 'Werk',
  },
  {
    id: 't-b2-werk-12',
    text: 'Wat maakt iemand een goede leider?',
    levels: ['B2'],
    category: 'Werk',
  },
  {
    id: 't-b2-werk-13',
    text: 'Hoe verandert de arbeidsmarkt voor jonge mensen?',
    levels: ['B2'],
    category: 'Werk',
  },
  {
    id: 't-b2-werk-14',
    text: 'Welke verantwoordelijkheid heeft een werkgever voor zijn personeel?',
    levels: ['B2'],
    category: 'Werk',
  },
  {
    id: 't-b2-werk-15',
    text: 'Hoe beïnvloedt opleiding de kansen die je krijgt?',
    levels: ['B2'],
    category: 'Werk',
  },
  {
    id: 't-b2-werk-16',
    text: 'Wat vind je van werken op afstand?',
    levels: ['B2'],
    category: 'Werk',
  },
  { id: 't-b2-werk-17', text: 'Hoe ga je om met concurrentie?', levels: ['B2'], category: 'Werk' },
  {
    id: 't-b2-werk-18',
    text: 'Welke vaardigheden zijn in de toekomst het belangrijkst?',
    levels: ['B2'],
    category: 'Werk',
  },
  {
    id: 't-b2-werk-19',
    text: "Hoe denk je over het idee van een 'roeping'?",
    levels: ['B2'],
    category: 'Werk',
  },
  {
    id: 't-b2-werk-20',
    text: 'Wat zou je veranderen aan hoe wij over werk denken?',
    levels: ['B2'],
    category: 'Werk',
  },

  // ══ ETEN ═════════════════════════════════════════════════════════════════
  // A1
  { id: 't-a1-eten-01', text: 'Wat heb je vandaag ontbeten?', levels: ['A1'], category: 'Eten' },
  { id: 't-a1-eten-02', text: 'Wat eet je het liefst?', levels: ['A1'], category: 'Eten' },
  { id: 't-a1-eten-03', text: 'Welk fruit eet je graag?', levels: ['A1'], category: 'Eten' },
  { id: 't-a1-eten-04', text: 'Wat drink je bij het ontbijt?', levels: ['A1'], category: 'Eten' },
  {
    id: 't-a1-eten-05',
    text: 'Welke groente eet je niet graag?',
    levels: ['A1'],
    category: 'Eten',
  },
  { id: 't-a1-eten-06', text: 'Wat eet je graag als snack?', levels: ['A1'], category: 'Eten' },
  { id: 't-a1-eten-07', text: 'Kook je zelf?', levels: ['A1'], category: 'Eten' },
  { id: 't-a1-eten-08', text: 'Wat eet je warm vandaag?', levels: ['A1'], category: 'Eten' },
  { id: 't-a1-eten-09', text: 'Drink je koffie of thee?', levels: ['A1'], category: 'Eten' },
  { id: 't-a1-eten-10', text: 'Welk eten is zoet?', levels: ['A1'], category: 'Eten' },
  { id: 't-a1-eten-11', text: 'Eet je graag brood?', levels: ['A1'], category: 'Eten' },
  { id: 't-a1-eten-12', text: 'Wat eet je op zondag?', levels: ['A1'], category: 'Eten' },
  { id: 't-a1-eten-13', text: 'Hou je van rijst of aardappels?', levels: ['A1'], category: 'Eten' },
  {
    id: 't-a1-eten-14',
    text: 'Welke kleur heeft jouw favoriete eten?',
    levels: ['A1'],
    category: 'Eten',
  },
  { id: 't-a1-eten-15', text: 'Eet je veel of weinig?', levels: ['A1'], category: 'Eten' },
  { id: 't-a1-eten-16', text: 'Wat eet je als je honger hebt?', levels: ['A1'], category: 'Eten' },
  { id: 't-a1-eten-17', text: 'Welk eten is warm en lekker?', levels: ['A1'], category: 'Eten' },
  { id: 't-a1-eten-18', text: 'Eet je graag soep?', levels: ['A1'], category: 'Eten' },
  { id: 't-a1-eten-19', text: 'Wat koop je in de supermarkt?', levels: ['A1'], category: 'Eten' },
  {
    id: 't-a1-eten-20',
    text: 'Welk eten ruikt lekker voor jou?',
    levels: ['A1'],
    category: 'Eten',
  },
  // A2
  {
    id: 't-a2-eten-01',
    text: 'Welk eten uit jouw land vind je het lekkerst?',
    levels: ['A2'],
    category: 'Eten',
  },
  {
    id: 't-a2-eten-02',
    text: 'Wat maak je graag klaar in de keuken?',
    levels: ['A2'],
    category: 'Eten',
  },
  {
    id: 't-a2-eten-03',
    text: 'Wat is jouw favoriete gerecht om te maken?',
    levels: ['A2'],
    category: 'Eten',
  },
  { id: 't-a2-eten-04', text: 'Hoe leer je koken?', levels: ['A2'], category: 'Eten' },
  { id: 't-a2-eten-05', text: 'Wat eet je familie graag samen?', levels: ['A2'], category: 'Eten' },
  {
    id: 't-a2-eten-06',
    text: 'Welk Nederlands eten vind je lekker?',
    levels: ['A2'],
    category: 'Eten',
  },
  {
    id: 't-a2-eten-07',
    text: 'Vertel over een gerecht uit je jeugd.',
    levels: ['A2'],
    category: 'Eten',
  },
  { id: 't-a2-eten-08', text: 'Wat eet je op een feestdag?', levels: ['A2'], category: 'Eten' },
  { id: 't-a2-eten-09', text: 'Hou je van zoet of hartig?', levels: ['A2'], category: 'Eten' },
  {
    id: 't-a2-eten-10',
    text: 'Wie kookt het lekkerst die je kent?',
    levels: ['A2'],
    category: 'Eten',
  },
  { id: 't-a2-eten-11', text: 'Wat koop je op de markt?', levels: ['A2'], category: 'Eten' },
  {
    id: 't-a2-eten-12',
    text: 'Welk eten zou je iemand uit Nederland laten proeven?',
    levels: ['A2'],
    category: 'Eten',
  },
  {
    id: 't-a2-eten-13',
    text: 'Hoe ziet een gezond ontbijt eruit voor jou?',
    levels: ['A2'],
    category: 'Eten',
  },
  {
    id: 't-a2-eten-14',
    text: 'Wat drink je bij een speciale gelegenheid?',
    levels: ['A2'],
    category: 'Eten',
  },
  {
    id: 't-a2-eten-15',
    text: 'Welk eten mis je uit je thuisland?',
    levels: ['A2'],
    category: 'Eten',
  },
  {
    id: 't-a2-eten-16',
    text: 'Hoe vier je een verjaardag met eten?',
    levels: ['A2'],
    category: 'Eten',
  },
  {
    id: 't-a2-eten-17',
    text: 'Wat eet je het liefst in de winter?',
    levels: ['A2'],
    category: 'Eten',
  },
  {
    id: 't-a2-eten-18',
    text: 'Welke kruiden of smaken vind je lekker?',
    levels: ['A2'],
    category: 'Eten',
  },
  { id: 't-a2-eten-19', text: 'Ga je graag uit eten?', levels: ['A2'], category: 'Eten' },
  {
    id: 't-a2-eten-20',
    text: 'Wat is jouw beste kookherinnering?',
    levels: ['A2'],
    category: 'Eten',
  },
  // B1
  {
    id: 't-b1-eten-01',
    text: 'Welk eten verbindt jou met je thuisland?',
    levels: ['B1'],
    category: 'Eten',
  },
  {
    id: 't-b1-eten-02',
    text: 'Hoe belangrijk is samen eten voor jou?',
    levels: ['B1'],
    category: 'Eten',
  },
  {
    id: 't-b1-eten-03',
    text: 'Wat is het verschil tussen eten hier en in je thuisland?',
    levels: ['B1'],
    category: 'Eten',
  },
  {
    id: 't-b1-eten-04',
    text: 'Hoe leerde jij koken, en van wie?',
    levels: ['B1'],
    category: 'Eten',
  },
  {
    id: 't-b1-eten-05',
    text: 'Welke rol speelt eten bij feesten in jouw cultuur?',
    levels: ['B1'],
    category: 'Eten',
  },
  {
    id: 't-b1-eten-06',
    text: 'Wat vind je van de Nederlandse eetcultuur?',
    levels: ['B1'],
    category: 'Eten',
  },
  { id: 't-b1-eten-07', text: 'Hoe gezond eet jij, en waarom?', levels: ['B1'], category: 'Eten' },
  { id: 't-b1-eten-08', text: 'Wat zou je willen leren koken?', levels: ['B1'], category: 'Eten' },
  {
    id: 't-b1-eten-09',
    text: 'Hoe ga je om met eten dat je niet kent?',
    levels: ['B1'],
    category: 'Eten',
  },
  {
    id: 't-b1-eten-10',
    text: 'Welke maaltijd is voor jou het belangrijkst van de dag?',
    levels: ['B1'],
    category: 'Eten',
  },
  {
    id: 't-b1-eten-11',
    text: 'Hoe is jouw relatie met eten veranderd sinds je in Nederland woont?',
    levels: ['B1'],
    category: 'Eten',
  },
  {
    id: 't-b1-eten-12',
    text: 'Wat betekent gastvrijheid met eten voor jou?',
    levels: ['B1'],
    category: 'Eten',
  },
  {
    id: 't-b1-eten-13',
    text: 'Welk gerecht zou je willen doorgeven aan je kinderen?',
    levels: ['B1'],
    category: 'Eten',
  },
  {
    id: 't-b1-eten-14',
    text: 'Hoe belangrijk is het waar je eten vandaan komt?',
    levels: ['B1'],
    category: 'Eten',
  },
  {
    id: 't-b1-eten-15',
    text: 'Wat doe je met eten dat overblijft?',
    levels: ['B1'],
    category: 'Eten',
  },
  {
    id: 't-b1-eten-16',
    text: 'Hoe kies je wat je eet op een dag?',
    levels: ['B1'],
    category: 'Eten',
  },
  {
    id: 't-b1-eten-17',
    text: 'Welke smaak roept een herinnering bij je op?',
    levels: ['B1'],
    category: 'Eten',
  },
  {
    id: 't-b1-eten-18',
    text: 'Hoe ga je om met eten tijdens het vasten of een dieet?',
    levels: ['B1'],
    category: 'Eten',
  },
  { id: 't-b1-eten-19', text: 'Wat vind je van fastfood?', levels: ['B1'], category: 'Eten' },
  {
    id: 't-b1-eten-20',
    text: 'Hoe zou jouw ideale maaltijd eruitzien?',
    levels: ['B1'],
    category: 'Eten',
  },
  // B2
  {
    id: 't-b2-eten-01',
    text: 'Hoe weerspiegelt eten de cultuur van een land?',
    levels: ['B2'],
    category: 'Eten',
  },
  {
    id: 't-b2-eten-02',
    text: 'Wat vind je van voedselverspilling in welvarende landen?',
    levels: ['B2'],
    category: 'Eten',
  },
  {
    id: 't-b2-eten-03',
    text: 'Hoe beïnvloedt globalisering wat wij eten?',
    levels: ['B2'],
    category: 'Eten',
  },
  {
    id: 't-b2-eten-04',
    text: 'Welke rol speelt eten in jouw identiteit?',
    levels: ['B2'],
    category: 'Eten',
  },
  {
    id: 't-b2-eten-05',
    text: 'Hoe denk je over vegetarisch of veganistisch eten?',
    levels: ['B2'],
    category: 'Eten',
  },
  {
    id: 't-b2-eten-06',
    text: 'Wat is de invloed van de voedingsindustrie op onze gezondheid?',
    levels: ['B2'],
    category: 'Eten',
  },
  {
    id: 't-b2-eten-07',
    text: 'Hoe verandert eten de manier waarop mensen samenkomen?',
    levels: ['B2'],
    category: 'Eten',
  },
  {
    id: 't-b2-eten-08',
    text: 'Wat vind je van de trend van gezond eten?',
    levels: ['B2'],
    category: 'Eten',
  },
  {
    id: 't-b2-eten-09',
    text: 'Hoe duurzaam is jouw manier van eten?',
    levels: ['B2'],
    category: 'Eten',
  },
  {
    id: 't-b2-eten-10',
    text: 'Welke verantwoordelijkheid hebben we voor wat we eten?',
    levels: ['B2'],
    category: 'Eten',
  },
  {
    id: 't-b2-eten-11',
    text: 'Hoe beïnvloedt reclame onze eetkeuzes?',
    levels: ['B2'],
    category: 'Eten',
  },
  {
    id: 't-b2-eten-12',
    text: 'Wat zegt eten over sociale klasse?',
    levels: ['B2'],
    category: 'Eten',
  },
  {
    id: 't-b2-eten-13',
    text: 'Hoe ga je om met verschillende eetgewoonten binnen een gezin?',
    levels: ['B2'],
    category: 'Eten',
  },
  {
    id: 't-b2-eten-14',
    text: 'Hoe verandert traditie als eten zich aanpast aan een nieuw land?',
    levels: ['B2'],
    category: 'Eten',
  },
  {
    id: 't-b2-eten-15',
    text: 'Wat vind je van eten als statussymbool?',
    levels: ['B2'],
    category: 'Eten',
  },
  {
    id: 't-b2-eten-16',
    text: 'Hoe zou de wereld de honger het beste kunnen aanpakken?',
    levels: ['B2'],
    category: 'Eten',
  },
  {
    id: 't-b2-eten-17',
    text: 'Welke rol speelt eten in herinnering en heimwee?',
    levels: ['B2'],
    category: 'Eten',
  },
  {
    id: 't-b2-eten-18',
    text: 'Hoe denk je over biologisch versus goedkoop voedsel?',
    levels: ['B2'],
    category: 'Eten',
  },
  {
    id: 't-b2-eten-19',
    text: 'Hoe beïnvloedt klimaatverandering ons eten?',
    levels: ['B2'],
    category: 'Eten',
  },
  {
    id: 't-b2-eten-20',
    text: 'Wat zou je veranderen aan hoe wij met voedsel omgaan?',
    levels: ['B2'],
    category: 'Eten',
  },

  // ══ REIZEN ═══════════════════════════════════════════════════════════════
  // A1
  { id: 't-a1-reizen-01', text: 'Reis je graag?', levels: ['A1'], category: 'Reizen' },
  {
    id: 't-a1-reizen-02',
    text: 'Met welk vervoer reis je het liefst?',
    levels: ['A1'],
    category: 'Reizen',
  },
  {
    id: 't-a1-reizen-03',
    text: 'Ben je weleens met het vliegtuig geweest?',
    levels: ['A1'],
    category: 'Reizen',
  },
  { id: 't-a1-reizen-04', text: 'Waar wil je naartoe?', levels: ['A1'], category: 'Reizen' },
  {
    id: 't-a1-reizen-05',
    text: 'Reis je liever met de trein of de bus?',
    levels: ['A1'],
    category: 'Reizen',
  },
  { id: 't-a1-reizen-06', text: 'Wat neem je mee op reis?', levels: ['A1'], category: 'Reizen' },
  {
    id: 't-a1-reizen-07',
    text: 'Ga je in de zomer op vakantie?',
    levels: ['A1'],
    category: 'Reizen',
  },
  { id: 't-a1-reizen-08', text: 'Welk land wil je zien?', levels: ['A1'], category: 'Reizen' },
  {
    id: 't-a1-reizen-09',
    text: 'Reis je alleen of met anderen?',
    levels: ['A1'],
    category: 'Reizen',
  },
  {
    id: 't-a1-reizen-10',
    text: 'Hou je van de zee of de bergen?',
    levels: ['A1'],
    category: 'Reizen',
  },
  {
    id: 't-a1-reizen-11',
    text: 'Hoe ver is je thuisland van Nederland?',
    levels: ['A1'],
    category: 'Reizen',
  },
  {
    id: 't-a1-reizen-12',
    text: 'Ben je weleens met de boot geweest?',
    levels: ['A1'],
    category: 'Reizen',
  },
  { id: 't-a1-reizen-13', text: 'Wat zie je graag op reis?', levels: ['A1'], category: 'Reizen' },
  { id: 't-a1-reizen-14', text: 'Pak je graag een koffer in?', levels: ['A1'], category: 'Reizen' },
  {
    id: 't-a1-reizen-15',
    text: 'Welk weer wil je op vakantie?',
    levels: ['A1'],
    category: 'Reizen',
  },
  {
    id: 't-a1-reizen-16',
    text: 'Reis je weleens met de fiets?',
    levels: ['A1'],
    category: 'Reizen',
  },
  {
    id: 't-a1-reizen-17',
    text: 'Naar welke stad wil je gaan?',
    levels: ['A1'],
    category: 'Reizen',
  },
  {
    id: 't-a1-reizen-18',
    text: 'Slaap je op reis in een hotel of bij familie?',
    levels: ['A1'],
    category: 'Reizen',
  },
  { id: 't-a1-reizen-19', text: 'Wat eet je graag op reis?', levels: ['A1'], category: 'Reizen' },
  {
    id: 't-a1-reizen-20',
    text: 'Was je laatste reis lang of kort?',
    levels: ['A1'],
    category: 'Reizen',
  },
  // A2
  {
    id: 't-a2-reizen-01',
    text: 'Vertel over je laatste vakantie.',
    levels: ['A2'],
    category: 'Reizen',
  },
  {
    id: 't-a2-reizen-02',
    text: 'Waar zou jij naartoe willen reizen?',
    levels: ['A2'],
    category: 'Reizen',
  },
  {
    id: 't-a2-reizen-03',
    text: 'Wat neem je altijd mee op reis?',
    levels: ['A2'],
    category: 'Reizen',
  },
  {
    id: 't-a2-reizen-04',
    text: 'Hoe was je reis naar Nederland?',
    levels: ['A2'],
    category: 'Reizen',
  },
  {
    id: 't-a2-reizen-05',
    text: 'Welke plek zou je nog eens willen bezoeken?',
    levels: ['A2'],
    category: 'Reizen',
  },
  {
    id: 't-a2-reizen-06',
    text: 'Reis je liever naar de stad of de natuur?',
    levels: ['A2'],
    category: 'Reizen',
  },
  {
    id: 't-a2-reizen-07',
    text: 'Vertel over een mooie plek die je hebt gezien.',
    levels: ['A2'],
    category: 'Reizen',
  },
  {
    id: 't-a2-reizen-08',
    text: 'Wat doe je graag op vakantie?',
    levels: ['A2'],
    category: 'Reizen',
  },
  { id: 't-a2-reizen-09', text: 'Hoe plan je een reis?', levels: ['A2'], category: 'Reizen' },
  {
    id: 't-a2-reizen-10',
    text: 'Welk vervoermiddel vind je het prettigst?',
    levels: ['A2'],
    category: 'Reizen',
  },
  {
    id: 't-a2-reizen-11',
    text: 'Vertel over een reis die niet goed ging.',
    levels: ['A2'],
    category: 'Reizen',
  },
  {
    id: 't-a2-reizen-12',
    text: 'Wat is het verste dat je ooit hebt gereisd?',
    levels: ['A2'],
    category: 'Reizen',
  },
  {
    id: 't-a2-reizen-13',
    text: 'Reis je liever alleen of met anderen?',
    levels: ['A2'],
    category: 'Reizen',
  },
  {
    id: 't-a2-reizen-14',
    text: 'Welk land zou je iemand aanraden?',
    levels: ['A2'],
    category: 'Reizen',
  },
  { id: 't-a2-reizen-15', text: 'Wat leerde je van reizen?', levels: ['A2'], category: 'Reizen' },
  {
    id: 't-a2-reizen-16',
    text: 'Hoe lang duurde je langste reis?',
    levels: ['A2'],
    category: 'Reizen',
  },
  {
    id: 't-a2-reizen-17',
    text: 'Wat is jouw mooiste vakantieherinnering?',
    levels: ['A2'],
    category: 'Reizen',
  },
  {
    id: 't-a2-reizen-18',
    text: 'Welke stad in Nederland wil je bezoeken?',
    levels: ['A2'],
    category: 'Reizen',
  },
  {
    id: 't-a2-reizen-19',
    text: 'Wat eet je graag als je in een ander land bent?',
    levels: ['A2'],
    category: 'Reizen',
  },
  {
    id: 't-a2-reizen-20',
    text: 'Hoe vier je een vakantie met familie?',
    levels: ['A2'],
    category: 'Reizen',
  },
  // B1
  {
    id: 't-b1-reizen-01',
    text: 'Wat neem je altijd mee op vakantie, en waarom?',
    levels: ['B1'],
    category: 'Reizen',
  },
  {
    id: 't-b1-reizen-02',
    text: 'Wat leer je van reizen naar andere landen?',
    levels: ['B1'],
    category: 'Reizen',
  },
  {
    id: 't-b1-reizen-03',
    text: 'Hoe was je reis naar Nederland — vertel erover.',
    levels: ['B1'],
    category: 'Reizen',
  },
  {
    id: 't-b1-reizen-04',
    text: 'Reis je liever om te ontspannen of om te ontdekken?',
    levels: ['B1'],
    category: 'Reizen',
  },
  {
    id: 't-b1-reizen-05',
    text: 'Welke plek heeft de meeste indruk op je gemaakt?',
    levels: ['B1'],
    category: 'Reizen',
  },
  {
    id: 't-b1-reizen-06',
    text: 'Hoe verandert reizen je kijk op de wereld?',
    levels: ['B1'],
    category: 'Reizen',
  },
  {
    id: 't-b1-reizen-07',
    text: 'Wat is het verschil tussen toerist zijn en ergens wonen?',
    levels: ['B1'],
    category: 'Reizen',
  },
  {
    id: 't-b1-reizen-08',
    text: 'Welke reis zou je nog willen maken voordat je oud bent?',
    levels: ['B1'],
    category: 'Reizen',
  },
  {
    id: 't-b1-reizen-09',
    text: 'Hoe ga je om met een andere taal op reis?',
    levels: ['B1'],
    category: 'Reizen',
  },
  {
    id: 't-b1-reizen-10',
    text: 'Wat vind je fijn aan thuiskomen na een reis?',
    levels: ['B1'],
    category: 'Reizen',
  },
  {
    id: 't-b1-reizen-11',
    text: 'Hoe kies je een reisbestemming?',
    levels: ['B1'],
    category: 'Reizen',
  },
  {
    id: 't-b1-reizen-12',
    text: 'Welke rol speelt reizen in jouw leven?',
    levels: ['B1'],
    category: 'Reizen',
  },
  {
    id: 't-b1-reizen-13',
    text: 'Wat zou je een toerist in jouw thuisland aanraden?',
    levels: ['B1'],
    category: 'Reizen',
  },
  {
    id: 't-b1-reizen-14',
    text: 'Hoe ga je om met heimwee als je ver weg bent?',
    levels: ['B1'],
    category: 'Reizen',
  },
  {
    id: 't-b1-reizen-15',
    text: 'Reis je liever met een plan of spontaan?',
    levels: ['B1'],
    category: 'Reizen',
  },
  {
    id: 't-b1-reizen-16',
    text: 'Wat is de mooiste ervaring die je op reis had?',
    levels: ['B1'],
    category: 'Reizen',
  },
  {
    id: 't-b1-reizen-17',
    text: 'Hoe belangrijk is reizen om andere culturen te begrijpen?',
    levels: ['B1'],
    category: 'Reizen',
  },
  {
    id: 't-b1-reizen-18',
    text: 'Welk land zou je willen leren kennen, en waarom?',
    levels: ['B1'],
    category: 'Reizen',
  },
  {
    id: 't-b1-reizen-19',
    text: 'Hoe verschilt reizen nu van vroeger voor jou?',
    levels: ['B1'],
    category: 'Reizen',
  },
  {
    id: 't-b1-reizen-20',
    text: 'Wat zou je meenemen als je voorgoed moest verhuizen?',
    levels: ['B1'],
    category: 'Reizen',
  },
  // B2
  {
    id: 't-b2-reizen-01',
    text: 'Hoe verandert reizen iemands kijk op de wereld?',
    levels: ['B2'],
    category: 'Reizen',
  },
  {
    id: 't-b2-reizen-02',
    text: 'Wat is het verschil tussen reizen en migreren?',
    levels: ['B2'],
    category: 'Reizen',
  },
  {
    id: 't-b2-reizen-03',
    text: 'Hoe denk je over de invloed van massatoerisme?',
    levels: ['B2'],
    category: 'Reizen',
  },
  {
    id: 't-b2-reizen-04',
    text: 'Reizen of ergens echt wonen — wat leert je meer?',
    levels: ['B2'],
    category: 'Reizen',
  },
  {
    id: 't-b2-reizen-05',
    text: 'Hoe beïnvloedt reizen je gevoel van identiteit?',
    levels: ['B2'],
    category: 'Reizen',
  },
  {
    id: 't-b2-reizen-06',
    text: 'Wat vind je van de milieukosten van vliegen?',
    levels: ['B2'],
    category: 'Reizen',
  },
  {
    id: 't-b2-reizen-07',
    text: 'Hoe ga je om met cultuurschok?',
    levels: ['B2'],
    category: 'Reizen',
  },
  {
    id: 't-b2-reizen-08',
    text: 'Welke verantwoordelijkheid heeft een reiziger tegenover de plek die hij bezoekt?',
    levels: ['B2'],
    category: 'Reizen',
  },
  {
    id: 't-b2-reizen-09',
    text: 'Hoe verandert een land door toerisme?',
    levels: ['B2'],
    category: 'Reizen',
  },
  {
    id: 't-b2-reizen-10',
    text: "Wat betekent 'ergens thuis zijn' als je veel reist?",
    levels: ['B2'],
    category: 'Reizen',
  },
  {
    id: 't-b2-reizen-11',
    text: 'Hoe denk je over mensen die hun hele leven op één plek blijven?',
    levels: ['B2'],
    category: 'Reizen',
  },
  {
    id: 't-b2-reizen-12',
    text: 'Wat leert reizen je over jezelf?',
    levels: ['B2'],
    category: 'Reizen',
  },
  {
    id: 't-b2-reizen-13',
    text: 'Hoe romantiseren we reizen volgens jou?',
    levels: ['B2'],
    category: 'Reizen',
  },
  {
    id: 't-b2-reizen-14',
    text: 'Welke plek zou je willen begrijpen in plaats van alleen zien?',
    levels: ['B2'],
    category: 'Reizen',
  },
  {
    id: 't-b2-reizen-15',
    text: 'Hoe beïnvloedt reizen je waardering voor je eigen land?',
    levels: ['B2'],
    category: 'Reizen',
  },
  {
    id: 't-b2-reizen-16',
    text: 'Wat is het verschil tussen een vakantie en een ervaring?',
    levels: ['B2'],
    category: 'Reizen',
  },
  {
    id: 't-b2-reizen-17',
    text: 'Hoe ga je om met de ongelijkheid die je ziet op reis?',
    levels: ['B2'],
    category: 'Reizen',
  },
  {
    id: 't-b2-reizen-18',
    text: 'Zou je permanent in een ander land kunnen wonen?',
    levels: ['B2'],
    category: 'Reizen',
  },
  {
    id: 't-b2-reizen-19',
    text: 'Hoe verandert technologie de manier waarop we reizen?',
    levels: ['B2'],
    category: 'Reizen',
  },
  {
    id: 't-b2-reizen-20',
    text: 'Wat zou je willen dat anderen leren van jouw cultuur?',
    levels: ['B2'],
    category: 'Reizen',
  },

  // ══ VRIJE TIJD ═══════════════════════════════════════════════════════════
  // A1
  {
    id: 't-a1-vrij-01',
    text: 'Wat doe je in het weekend?',
    levels: ['A1'],
    category: 'Vrije tijd',
  },
  { id: 't-a1-vrij-02', text: 'Welke sport vind je leuk?', levels: ['A1'], category: 'Vrije tijd' },
  {
    id: 't-a1-vrij-03',
    text: 'Welke dieren vind je leuk?',
    levels: ['A1'],
    category: 'Vrije tijd',
  },
  {
    id: 't-a1-vrij-04',
    text: 'Wat is jouw favoriete kleur?',
    levels: ['A1'],
    category: 'Vrije tijd',
  },
  { id: 't-a1-vrij-05', text: 'Kijk je graag tv?', levels: ['A1'], category: 'Vrije tijd' },
  {
    id: 't-a1-vrij-06',
    text: 'Welke muziek vind je mooi?',
    levels: ['A1'],
    category: 'Vrije tijd',
  },
  { id: 't-a1-vrij-07', text: 'Wat doe je graag buiten?', levels: ['A1'], category: 'Vrije tijd' },
  { id: 't-a1-vrij-08', text: 'Hou je van wandelen?', levels: ['A1'], category: 'Vrije tijd' },
  { id: 't-a1-vrij-09', text: 'Welk spel speel je graag?', levels: ['A1'], category: 'Vrije tijd' },
  {
    id: 't-a1-vrij-10',
    text: 'Wat is jouw favoriete seizoen?',
    levels: ['A1'],
    category: 'Vrije tijd',
  },
  { id: 't-a1-vrij-11', text: 'Lees je graag?', levels: ['A1'], category: 'Vrije tijd' },
  {
    id: 't-a1-vrij-12',
    text: 'Wat doe je als je vrij bent?',
    levels: ['A1'],
    category: 'Vrije tijd',
  },
  { id: 't-a1-vrij-13', text: 'Speel je een instrument?', levels: ['A1'], category: 'Vrije tijd' },
  { id: 't-a1-vrij-14', text: 'Hou je van dansen?', levels: ['A1'], category: 'Vrije tijd' },
  {
    id: 't-a1-vrij-15',
    text: 'Wat is je favoriete dag van de week?',
    levels: ['A1'],
    category: 'Vrije tijd',
  },
  { id: 't-a1-vrij-16', text: 'Kijk je graag films?', levels: ['A1'], category: 'Vrije tijd' },
  {
    id: 't-a1-vrij-17',
    text: "Wat doe je 's avonds thuis?",
    levels: ['A1'],
    category: 'Vrije tijd',
  },
  { id: 't-a1-vrij-18', text: 'Hou je van zwemmen?', levels: ['A1'], category: 'Vrije tijd' },
  { id: 't-a1-vrij-19', text: 'Welk weer vind je fijn?', levels: ['A1'], category: 'Vrije tijd' },
  { id: 't-a1-vrij-20', text: 'Wat maakt jou blij?', levels: ['A1'], category: 'Vrije tijd' },
  // A2
  {
    id: 't-a2-vrij-01',
    text: 'Wat doe je graag in je vrije tijd?',
    levels: ['A2'],
    category: 'Vrije tijd',
  },
  {
    id: 't-a2-vrij-02',
    text: 'Hoe ziet jouw ideale dag eruit?',
    levels: ['A2'],
    category: 'Vrije tijd',
  },
  {
    id: 't-a2-vrij-03',
    text: 'Welke muziek luister je graag?',
    levels: ['A2'],
    category: 'Vrije tijd',
  },
  {
    id: 't-a2-vrij-04',
    text: 'Wat doe jij als het regent buiten?',
    levels: ['A2'],
    category: 'Vrije tijd',
  },
  {
    id: 't-a2-vrij-05',
    text: 'Wat is jouw favoriete plek om te ontspannen?',
    levels: ['A2'],
    category: 'Vrije tijd',
  },
  {
    id: 't-a2-vrij-06',
    text: 'Welke apps gebruik je het meest?',
    levels: ['A2'],
    category: 'Vrije tijd',
  },
  {
    id: 't-a2-vrij-07',
    text: 'Wat doe je graag op een vrije middag?',
    levels: ['A2'],
    category: 'Vrije tijd',
  },
  {
    id: 't-a2-vrij-08',
    text: 'Vertel over een hobby van je.',
    levels: ['A2'],
    category: 'Vrije tijd',
  },
  {
    id: 't-a2-vrij-09',
    text: 'Welke film of serie vind je leuk?',
    levels: ['A2'],
    category: 'Vrije tijd',
  },
  {
    id: 't-a2-vrij-10',
    text: 'Wat doe je graag met vrienden?',
    levels: ['A2'],
    category: 'Vrije tijd',
  },
  {
    id: 't-a2-vrij-11',
    text: 'Welke sport zou je willen proberen?',
    levels: ['A2'],
    category: 'Vrije tijd',
  },
  {
    id: 't-a2-vrij-12',
    text: 'Hoe ontspan je na een drukke dag?',
    levels: ['A2'],
    category: 'Vrije tijd',
  },
  {
    id: 't-a2-vrij-13',
    text: 'Wat doe je op een zonnige zondag?',
    levels: ['A2'],
    category: 'Vrije tijd',
  },
  {
    id: 't-a2-vrij-14',
    text: 'Welk spel speel je graag met anderen?',
    levels: ['A2'],
    category: 'Vrije tijd',
  },
  {
    id: 't-a2-vrij-15',
    text: 'Vertel over iets wat je onlangs voor het eerst probeerde.',
    levels: ['A2'],
    category: 'Vrije tijd',
  },
  {
    id: 't-a2-vrij-16',
    text: 'Wat zou je willen leren in je vrije tijd?',
    levels: ['A2'],
    category: 'Vrije tijd',
  },
  {
    id: 't-a2-vrij-17',
    text: 'Hoe vier je een vrije dag?',
    levels: ['A2'],
    category: 'Vrije tijd',
  },
  {
    id: 't-a2-vrij-18',
    text: 'Wat is jouw favoriete nummer?',
    levels: ['A2'],
    category: 'Vrije tijd',
  },
  {
    id: 't-a2-vrij-19',
    text: 'Lees je liever een boek of kijk je een film?',
    levels: ['A2'],
    category: 'Vrije tijd',
  },
  {
    id: 't-a2-vrij-20',
    text: 'Wat doe je het liefst alleen?',
    levels: ['A2'],
    category: 'Vrije tijd',
  },
  // B1
  {
    id: 't-b1-vrij-01',
    text: 'Vertel over een mooi moment van vorige week.',
    levels: ['B1'],
    category: 'Vrije tijd',
  },
  {
    id: 't-b1-vrij-02',
    text: 'Wat zou je doen als je een week vrij kreeg?',
    levels: ['B1'],
    category: 'Vrije tijd',
  },
  {
    id: 't-b1-vrij-03',
    text: 'Welk boek of welke film heeft indruk op je gemaakt?',
    levels: ['B1'],
    category: 'Vrije tijd',
  },
  {
    id: 't-b1-vrij-04',
    text: 'Wat is voor jou een goede dag?',
    levels: ['B1'],
    category: 'Vrije tijd',
  },
  {
    id: 't-b1-vrij-05',
    text: 'Hoe belangrijk is vrije tijd voor jou?',
    levels: ['B1'],
    category: 'Vrije tijd',
  },
  {
    id: 't-b1-vrij-06',
    text: 'Welke hobby zou je graag oppakken?',
    levels: ['B1'],
    category: 'Vrije tijd',
  },
  { id: 't-b1-vrij-07', text: 'Hoe ontspan je het beste?', levels: ['B1'], category: 'Vrije tijd' },
  {
    id: 't-b1-vrij-08',
    text: 'Wat doe je om nieuwe energie te krijgen?',
    levels: ['B1'],
    category: 'Vrije tijd',
  },
  {
    id: 't-b1-vrij-09',
    text: 'Vertel over iets wat je graag doet maar te weinig doet.',
    levels: ['B1'],
    category: 'Vrije tijd',
  },
  {
    id: 't-b1-vrij-10',
    text: 'Hoe is jouw vrije tijd veranderd sinds je in Nederland woont?',
    levels: ['B1'],
    category: 'Vrije tijd',
  },
  {
    id: 't-b1-vrij-11',
    text: 'Wat betekent ontspanning voor jou?',
    levels: ['B1'],
    category: 'Vrije tijd',
  },
  {
    id: 't-b1-vrij-12',
    text: 'Welke activiteit geeft je het meeste plezier?',
    levels: ['B1'],
    category: 'Vrije tijd',
  },
  {
    id: 't-b1-vrij-13',
    text: 'Hoe breng je tijd door met de mensen om je heen?',
    levels: ['B1'],
    category: 'Vrije tijd',
  },
  {
    id: 't-b1-vrij-14',
    text: 'Wat zou je doen als geld geen rol speelde?',
    levels: ['B1'],
    category: 'Vrije tijd',
  },
  {
    id: 't-b1-vrij-15',
    text: 'Hoe belangrijk is creativiteit in jouw leven?',
    levels: ['B1'],
    category: 'Vrije tijd',
  },
  {
    id: 't-b1-vrij-16',
    text: 'Welke film of welk verhaal zou je aanraden?',
    levels: ['B1'],
    category: 'Vrije tijd',
  },
  {
    id: 't-b1-vrij-17',
    text: 'Hoe vier je een bijzondere gelegenheid?',
    levels: ['B1'],
    category: 'Vrije tijd',
  },
  {
    id: 't-b1-vrij-18',
    text: 'Wat doe je liever: iets nieuws of iets vertrouwds?',
    levels: ['B1'],
    category: 'Vrije tijd',
  },
  {
    id: 't-b1-vrij-19',
    text: 'Hoe vind je een balans tussen druk en rust?',
    levels: ['B1'],
    category: 'Vrije tijd',
  },
  {
    id: 't-b1-vrij-20',
    text: 'Welke herinnering aan vrije tijd koester je?',
    levels: ['B1'],
    category: 'Vrije tijd',
  },
  // B2
  {
    id: 't-b2-vrij-01',
    text: 'Vertel over een keer dat je iets nieuws durfde te proberen.',
    levels: ['B2'],
    category: 'Vrije tijd',
  },
  {
    id: 't-b2-vrij-02',
    text: 'Welk boek, film of verhaal heeft jou gevormd?',
    levels: ['B2'],
    category: 'Vrije tijd',
  },
  {
    id: 't-b2-vrij-03',
    text: 'Hoe belangrijk is verveling voor de creativiteit?',
    levels: ['B2'],
    category: 'Vrije tijd',
  },
  {
    id: 't-b2-vrij-04',
    text: "Wat zeggen iemands hobby's over wie hij is?",
    levels: ['B2'],
    category: 'Vrije tijd',
  },
  {
    id: 't-b2-vrij-05',
    text: 'Hoe verandert vrije tijd door technologie en sociale media?',
    levels: ['B2'],
    category: 'Vrije tijd',
  },
  {
    id: 't-b2-vrij-06',
    text: 'Wat is het verschil tussen ontspanning en tijdverspilling?',
    levels: ['B2'],
    category: 'Vrije tijd',
  },
  {
    id: 't-b2-vrij-07',
    text: "Hoe zou jij 'een goed besteed leven' omschrijven?",
    levels: ['B2'],
    category: 'Vrije tijd',
  },
  {
    id: 't-b2-vrij-08',
    text: 'Waarom hebben mensen kunst en verhalen nodig?',
    levels: ['B2'],
    category: 'Vrije tijd',
  },
  {
    id: 't-b2-vrij-09',
    text: 'Hoe beïnvloedt drukte de kwaliteit van ons leven?',
    levels: ['B2'],
    category: 'Vrije tijd',
  },
  {
    id: 't-b2-vrij-10',
    text: 'Wat betekent rust in een snelle wereld?',
    levels: ['B2'],
    category: 'Vrije tijd',
  },
  {
    id: 't-b2-vrij-11',
    text: 'Hoe kies je waar je je tijd aan besteedt?',
    levels: ['B2'],
    category: 'Vrije tijd',
  },
  {
    id: 't-b2-vrij-12',
    text: 'Wat vind je van de prestatiedruk in de vrije tijd?',
    levels: ['B2'],
    category: 'Vrije tijd',
  },
  {
    id: 't-b2-vrij-13',
    text: 'Hoe belangrijk is spel en plezier voor volwassenen?',
    levels: ['B2'],
    category: 'Vrije tijd',
  },
  {
    id: 't-b2-vrij-14',
    text: 'Welke rol speelt cultuur in jouw vrije tijd?',
    levels: ['B2'],
    category: 'Vrije tijd',
  },
  {
    id: 't-b2-vrij-15',
    text: 'Hoe verandert wat je leuk vindt naarmate je ouder wordt?',
    levels: ['B2'],
    category: 'Vrije tijd',
  },
  {
    id: 't-b2-vrij-16',
    text: 'Wat zou je doen met een extra dag per week?',
    levels: ['B2'],
    category: 'Vrije tijd',
  },
  {
    id: 't-b2-vrij-17',
    text: 'Hoe beïnvloedt je omgeving wat je in je vrije tijd doet?',
    levels: ['B2'],
    category: 'Vrije tijd',
  },
  {
    id: 't-b2-vrij-18',
    text: 'Is vrije tijd een recht of een luxe?',
    levels: ['B2'],
    category: 'Vrije tijd',
  },
  {
    id: 't-b2-vrij-19',
    text: 'Hoe houd je nieuwsgierigheid levend?',
    levels: ['B2'],
    category: 'Vrije tijd',
  },
  {
    id: 't-b2-vrij-20',
    text: 'Wat zou je willen leren als je nog tien levens had?',
    levels: ['B2'],
    category: 'Vrije tijd',
  },

  // ══ WONEN ════════════════════════════════════════════════════════════════
  // A1
  {
    id: 't-a1-wonen-01',
    text: 'Woon je in een huis of een flat?',
    levels: ['A1'],
    category: 'Wonen',
  },
  { id: 't-a1-wonen-02', text: 'Hoeveel kamers heeft je huis?', levels: ['A1'], category: 'Wonen' },
  { id: 't-a1-wonen-03', text: 'Wat is jouw favoriete kamer?', levels: ['A1'], category: 'Wonen' },
  { id: 't-a1-wonen-04', text: 'Heb je een tuin of balkon?', levels: ['A1'], category: 'Wonen' },
  { id: 't-a1-wonen-05', text: 'Hoe laat sta jij op?', levels: ['A1'], category: 'Wonen' },
  {
    id: 't-a1-wonen-06',
    text: "Wat doe je 's ochtends als eerste?",
    levels: ['A1'],
    category: 'Wonen',
  },
  { id: 't-a1-wonen-07', text: 'Heb je een huisdier?', levels: ['A1'], category: 'Wonen' },
  { id: 't-a1-wonen-08', text: 'Slaap je veel of weinig?', levels: ['A1'], category: 'Wonen' },
  { id: 't-a1-wonen-09', text: 'Wat doe je voor het slapen?', levels: ['A1'], category: 'Wonen' },
  { id: 't-a1-wonen-10', text: 'Is je huis groot of klein?', levels: ['A1'], category: 'Wonen' },
  { id: 't-a1-wonen-11', text: 'Met wie woon je samen?', levels: ['A1'], category: 'Wonen' },
  { id: 't-a1-wonen-12', text: 'Wat zie je vanuit je raam?', levels: ['A1'], category: 'Wonen' },
  { id: 't-a1-wonen-13', text: 'Heb je een lift in je gebouw?', levels: ['A1'], category: 'Wonen' },
  { id: 't-a1-wonen-14', text: 'Welke kleur heeft jouw kamer?', levels: ['A1'], category: 'Wonen' },
  { id: 't-a1-wonen-15', text: 'Wat doe je in de woonkamer?', levels: ['A1'], category: 'Wonen' },
  { id: 't-a1-wonen-16', text: 'Hoe warm is het in je huis?', levels: ['A1'], category: 'Wonen' },
  { id: 't-a1-wonen-17', text: 'Wie maakt het huis schoon?', levels: ['A1'], category: 'Wonen' },
  { id: 't-a1-wonen-18', text: 'Heb je planten in huis?', levels: ['A1'], category: 'Wonen' },
  { id: 't-a1-wonen-19', text: 'Op welke verdieping woon je?', levels: ['A1'], category: 'Wonen' },
  { id: 't-a1-wonen-20', text: 'Wat doe je het liefst thuis?', levels: ['A1'], category: 'Wonen' },
  // A2
  {
    id: 't-a2-wonen-01',
    text: 'Beschrijf je huis: hoe ziet het eruit?',
    levels: ['A2'],
    category: 'Wonen',
  },
  {
    id: 't-a2-wonen-02',
    text: 'Hoe ziet je dagelijkse routine eruit?',
    levels: ['A2'],
    category: 'Wonen',
  },
  { id: 't-a2-wonen-03', text: 'Wat vind je fijn aan je huis?', levels: ['A2'], category: 'Wonen' },
  {
    id: 't-a2-wonen-04',
    text: 'Wat zou je willen veranderen aan je woning?',
    levels: ['A2'],
    category: 'Wonen',
  },
  { id: 't-a2-wonen-05', text: 'Hoe ziet jouw ochtend eruit?', levels: ['A2'], category: 'Wonen' },
  {
    id: 't-a2-wonen-06',
    text: 'Wat doe je om je huis gezellig te maken?',
    levels: ['A2'],
    category: 'Wonen',
  },
  {
    id: 't-a2-wonen-07',
    text: 'Hoe is wonen hier anders dan in je thuisland?',
    levels: ['A2'],
    category: 'Wonen',
  },
  {
    id: 't-a2-wonen-08',
    text: 'Welke kamer gebruik je het meest?',
    levels: ['A2'],
    category: 'Wonen',
  },
  {
    id: 't-a2-wonen-09',
    text: 'Hoe vond je je woning in Nederland?',
    levels: ['A2'],
    category: 'Wonen',
  },
  { id: 't-a2-wonen-10', text: 'Wat doe je in het huishouden?', levels: ['A2'], category: 'Wonen' },
  {
    id: 't-a2-wonen-11',
    text: 'Woon je liever in de stad of op het platteland?',
    levels: ['A2'],
    category: 'Wonen',
  },
  {
    id: 't-a2-wonen-12',
    text: 'Hoe ziet je ideale huis eruit?',
    levels: ['A2'],
    category: 'Wonen',
  },
  { id: 't-a2-wonen-13', text: 'Wat is fijn aan jouw straat?', levels: ['A2'], category: 'Wonen' },
  { id: 't-a2-wonen-14', text: 'Hoe ruim je je huis op?', levels: ['A2'], category: 'Wonen' },
  { id: 't-a2-wonen-15', text: "Wat doe je 's avonds thuis?", levels: ['A2'], category: 'Wonen' },
  { id: 't-a2-wonen-16', text: 'Hoe deel je taken thuis?', levels: ['A2'], category: 'Wonen' },
  { id: 't-a2-wonen-17', text: 'Wat hangt er aan je muur?', levels: ['A2'], category: 'Wonen' },
  {
    id: 't-a2-wonen-18',
    text: 'Heb je genoeg ruimte in je huis?',
    levels: ['A2'],
    category: 'Wonen',
  },
  { id: 't-a2-wonen-19', text: 'Wat zou je in je tuin willen?', levels: ['A2'], category: 'Wonen' },
  {
    id: 't-a2-wonen-20',
    text: 'Hoe maak je je huis warm en gezellig in de winter?',
    levels: ['A2'],
    category: 'Wonen',
  },
  // B1
  {
    id: 't-b1-wonen-01',
    text: 'Wat zou je veranderen aan je dagelijkse routine?',
    levels: ['B1'],
    category: 'Wonen',
  },
  {
    id: 't-b1-wonen-02',
    text: 'Wat zijn de voordelen van in een ander land wonen?',
    levels: ['B1'],
    category: 'Wonen',
  },
  {
    id: 't-b1-wonen-03',
    text: 'Wat maakt een huis tot een thuis?',
    levels: ['B1'],
    category: 'Wonen',
  },
  {
    id: 't-b1-wonen-04',
    text: 'Hoe is jouw woonsituatie veranderd sinds je in Nederland kwam?',
    levels: ['B1'],
    category: 'Wonen',
  },
  {
    id: 't-b1-wonen-05',
    text: 'Woon je liever in de stad of op het platteland, en waarom?',
    levels: ['B1'],
    category: 'Wonen',
  },
  {
    id: 't-b1-wonen-06',
    text: 'Hoe belangrijk is een eigen plek voor jou?',
    levels: ['B1'],
    category: 'Wonen',
  },
  {
    id: 't-b1-wonen-07',
    text: 'Wat mis je aan je vorige woning?',
    levels: ['B1'],
    category: 'Wonen',
  },
  {
    id: 't-b1-wonen-08',
    text: 'Hoe ga je om met huisgenoten of buren?',
    levels: ['B1'],
    category: 'Wonen',
  },
  {
    id: 't-b1-wonen-09',
    text: 'Wat betekent comfort thuis voor jou?',
    levels: ['B1'],
    category: 'Wonen',
  },
  {
    id: 't-b1-wonen-10',
    text: 'Hoe ziet jouw ideale woonomgeving eruit?',
    levels: ['B1'],
    category: 'Wonen',
  },
  {
    id: 't-b1-wonen-11',
    text: 'Hoe belangrijk is het waar je woont voor je geluk?',
    levels: ['B1'],
    category: 'Wonen',
  },
  {
    id: 't-b1-wonen-12',
    text: 'Wat zou je nodig hebben om je echt thuis te voelen?',
    levels: ['B1'],
    category: 'Wonen',
  },
  {
    id: 't-b1-wonen-13',
    text: 'Hoe verdeel je het huishouden eerlijk?',
    levels: ['B1'],
    category: 'Wonen',
  },
  {
    id: 't-b1-wonen-14',
    text: 'Wat vind je van de woningnood in Nederland?',
    levels: ['B1'],
    category: 'Wonen',
  },
  {
    id: 't-b1-wonen-15',
    text: 'Hoe zou je willen wonen als je ouder bent?',
    levels: ['B1'],
    category: 'Wonen',
  },
  {
    id: 't-b1-wonen-16',
    text: 'Welke rol speelt je huis in je dagelijkse leven?',
    levels: ['B1'],
    category: 'Wonen',
  },
  {
    id: 't-b1-wonen-17',
    text: 'Hoe ga je om met weinig ruimte?',
    levels: ['B1'],
    category: 'Wonen',
  },
  {
    id: 't-b1-wonen-18',
    text: 'Wat maakt een buurt fijn om in te wonen?',
    levels: ['B1'],
    category: 'Wonen',
  },
  {
    id: 't-b1-wonen-19',
    text: 'Hoe belangrijk is rust in je woonomgeving?',
    levels: ['B1'],
    category: 'Wonen',
  },
  {
    id: 't-b1-wonen-20',
    text: 'Wat zou je meenemen als je weer moest verhuizen?',
    levels: ['B1'],
    category: 'Wonen',
  },
  // B2
  {
    id: 't-b2-wonen-01',
    text: 'Wat betekent "thuis" voor jou?',
    levels: ['B2'],
    category: 'Wonen',
  },
  {
    id: 't-b2-wonen-02',
    text: 'Beschrijf hoe jouw identiteit veranderd is door in Nederland te wonen.',
    levels: ['B2'],
    category: 'Wonen',
  },
  {
    id: 't-b2-wonen-03',
    text: 'Op welk moment voelde je je voor het eerst echt thuis in Nederland?',
    levels: ['B2'],
    category: 'Wonen',
  },
  {
    id: 't-b2-wonen-04',
    text: 'Kun je je op meer dan één plek tegelijk thuis voelen?',
    levels: ['B2'],
    category: 'Wonen',
  },
  {
    id: 't-b2-wonen-05',
    text: 'Hoe beïnvloedt je woonomgeving wie je bent?',
    levels: ['B2'],
    category: 'Wonen',
  },
  {
    id: 't-b2-wonen-06',
    text: 'Wat vind je van de manier waarop Nederlanders wonen?',
    levels: ['B2'],
    category: 'Wonen',
  },
  {
    id: 't-b2-wonen-07',
    text: 'Hoe denk je over de woningnood als maatschappelijk probleem?',
    levels: ['B2'],
    category: 'Wonen',
  },
  {
    id: 't-b2-wonen-08',
    text: 'Is thuis een plek of een gevoel?',
    levels: ['B2'],
    category: 'Wonen',
  },
  {
    id: 't-b2-wonen-09',
    text: "Hoe verandert het begrip 'thuis' als je migreert?",
    levels: ['B2'],
    category: 'Wonen',
  },
  {
    id: 't-b2-wonen-10',
    text: 'Wat zou een ideale samenleving doen aan wonen?',
    levels: ['B2'],
    category: 'Wonen',
  },
  {
    id: 't-b2-wonen-11',
    text: 'Hoe beïnvloedt het bezit van een huis iemands leven?',
    levels: ['B2'],
    category: 'Wonen',
  },
  {
    id: 't-b2-wonen-12',
    text: 'Hoe belangrijk is privacy in een woning?',
    levels: ['B2'],
    category: 'Wonen',
  },
  {
    id: 't-b2-wonen-13',
    text: 'Hoe verandert de manier van wonen door de generaties?',
    levels: ['B2'],
    category: 'Wonen',
  },
  {
    id: 't-b2-wonen-14',
    text: 'Wat vind je van samen wonen met meerdere generaties?',
    levels: ['B2'],
    category: 'Wonen',
  },
  {
    id: 't-b2-wonen-15',
    text: 'Hoe zou duurzaam wonen eruit moeten zien?',
    levels: ['B2'],
    category: 'Wonen',
  },
  {
    id: 't-b2-wonen-16',
    text: 'Wat verlies en win je als je verhuist naar een nieuw land?',
    levels: ['B2'],
    category: 'Wonen',
  },
  {
    id: 't-b2-wonen-17',
    text: 'Hoe beïnvloedt waar je woont je kansen in het leven?',
    levels: ['B2'],
    category: 'Wonen',
  },
  {
    id: 't-b2-wonen-18',
    text: 'Wat betekent geworteld zijn voor jou?',
    levels: ['B2'],
    category: 'Wonen',
  },
  {
    id: 't-b2-wonen-19',
    text: 'Hoe ga je om met het gevoel tussen twee landen te leven?',
    levels: ['B2'],
    category: 'Wonen',
  },
  {
    id: 't-b2-wonen-20',
    text: "Wat zou je willen dat 'thuis' betekent voor je kinderen?",
    levels: ['B2'],
    category: 'Wonen',
  },

  // ══ GEZONDHEID ═══════════════════════════════════════════════════════════
  // A1
  { id: 't-a1-gezond-01', text: 'Hoe voel je je vandaag?', levels: ['A1'], category: 'Gezondheid' },
  { id: 't-a1-gezond-02', text: 'Slaap je goed?', levels: ['A1'], category: 'Gezondheid' },
  {
    id: 't-a1-gezond-03',
    text: 'Wat doe je om gezond te blijven?',
    levels: ['A1'],
    category: 'Gezondheid',
  },
  { id: 't-a1-gezond-04', text: 'Sport je weleens?', levels: ['A1'], category: 'Gezondheid' },
  { id: 't-a1-gezond-05', text: 'Loop je veel?', levels: ['A1'], category: 'Gezondheid' },
  { id: 't-a1-gezond-06', text: 'Eet je veel groente?', levels: ['A1'], category: 'Gezondheid' },
  { id: 't-a1-gezond-07', text: 'Drink je genoeg water?', levels: ['A1'], category: 'Gezondheid' },
  {
    id: 't-a1-gezond-08',
    text: 'Hoe laat ga je naar bed?',
    levels: ['A1'],
    category: 'Gezondheid',
  },
  { id: 't-a1-gezond-09', text: 'Ben je weleens ziek?', levels: ['A1'], category: 'Gezondheid' },
  {
    id: 't-a1-gezond-10',
    text: 'Wat doe je als je moe bent?',
    levels: ['A1'],
    category: 'Gezondheid',
  },
  { id: 't-a1-gezond-11', text: 'Fiets je vaak?', levels: ['A1'], category: 'Gezondheid' },
  { id: 't-a1-gezond-12', text: 'Wat eet je gezonds?', levels: ['A1'], category: 'Gezondheid' },
  { id: 't-a1-gezond-13', text: 'Voel je je fit?', levels: ['A1'], category: 'Gezondheid' },
  {
    id: 't-a1-gezond-14',
    text: 'Doe je weleens een dutje?',
    levels: ['A1'],
    category: 'Gezondheid',
  },
  { id: 't-a1-gezond-15', text: 'Wandel je graag buiten?', levels: ['A1'], category: 'Gezondheid' },
  { id: 't-a1-gezond-16', text: 'Maakt sporten jou blij?', levels: ['A1'], category: 'Gezondheid' },
  {
    id: 't-a1-gezond-17',
    text: 'Wat doe je als je ziek bent?',
    levels: ['A1'],
    category: 'Gezondheid',
  },
  { id: 't-a1-gezond-18', text: 'Sta je uitgerust op?', levels: ['A1'], category: 'Gezondheid' },
  {
    id: 't-a1-gezond-19',
    text: 'Welke sport is goed voor jou?',
    levels: ['A1'],
    category: 'Gezondheid',
  },
  {
    id: 't-a1-gezond-20',
    text: 'Wat doe je om te ontspannen?',
    levels: ['A1'],
    category: 'Gezondheid',
  },
  // A2
  { id: 't-a2-gezond-01', text: 'Hoe houd jij je gezond?', levels: ['A2'], category: 'Gezondheid' },
  {
    id: 't-a2-gezond-02',
    text: 'Wat doe je om fit te blijven?',
    levels: ['A2'],
    category: 'Gezondheid',
  },
  {
    id: 't-a2-gezond-03',
    text: 'Welke sport doe je graag?',
    levels: ['A2'],
    category: 'Gezondheid',
  },
  {
    id: 't-a2-gezond-04',
    text: 'Hoe ga je om met een drukke dag?',
    levels: ['A2'],
    category: 'Gezondheid',
  },
  {
    id: 't-a2-gezond-05',
    text: 'Wat doe je als je moe bent?',
    levels: ['A2'],
    category: 'Gezondheid',
  },
  { id: 't-a2-gezond-06', text: 'Slaap jij genoeg?', levels: ['A2'], category: 'Gezondheid' },
  {
    id: 't-a2-gezond-07',
    text: 'Hoe ontspan je na een lange dag?',
    levels: ['A2'],
    category: 'Gezondheid',
  },
  {
    id: 't-a2-gezond-08',
    text: 'Wat eet je om gezond te blijven?',
    levels: ['A2'],
    category: 'Gezondheid',
  },
  {
    id: 't-a2-gezond-09',
    text: 'Beweeg je genoeg op een dag?',
    levels: ['A2'],
    category: 'Gezondheid',
  },
  {
    id: 't-a2-gezond-10',
    text: 'Wat doe je als je je niet lekker voelt?',
    levels: ['A2'],
    category: 'Gezondheid',
  },
  {
    id: 't-a2-gezond-11',
    text: 'Hoe belangrijk is sport voor jou?',
    levels: ['A2'],
    category: 'Gezondheid',
  },
  { id: 't-a2-gezond-12', text: 'Wat maakt jou rustig?', levels: ['A2'], category: 'Gezondheid' },
  {
    id: 't-a2-gezond-13',
    text: 'Hoe is de gezondheidszorg in jouw thuisland?',
    levels: ['A2'],
    category: 'Gezondheid',
  },
  {
    id: 't-a2-gezond-14',
    text: 'Wat doe je om je goed te voelen?',
    levels: ['A2'],
    category: 'Gezondheid',
  },
  {
    id: 't-a2-gezond-15',
    text: 'Hoe ga je naar de huisarts in Nederland?',
    levels: ['A2'],
    category: 'Gezondheid',
  },
  {
    id: 't-a2-gezond-16',
    text: 'Wat doe je in de winter om gezond te blijven?',
    levels: ['A2'],
    category: 'Gezondheid',
  },
  {
    id: 't-a2-gezond-17',
    text: 'Hoe belangrijk is buiten zijn voor jou?',
    levels: ['A2'],
    category: 'Gezondheid',
  },
  {
    id: 't-a2-gezond-18',
    text: 'Wat is een gezonde gewoonte van je?',
    levels: ['A2'],
    category: 'Gezondheid',
  },
  {
    id: 't-a2-gezond-19',
    text: 'Welke gewoonte zou je willen veranderen?',
    levels: ['A2'],
    category: 'Gezondheid',
  },
  {
    id: 't-a2-gezond-20',
    text: 'Hoe zorg je goed voor jezelf?',
    levels: ['A2'],
    category: 'Gezondheid',
  },
  // B1
  {
    id: 't-b1-gezond-01',
    text: 'Wat doe je als je je een keer somber voelt?',
    levels: ['B1'],
    category: 'Gezondheid',
  },
  {
    id: 't-b1-gezond-02',
    text: 'Hoe ga jij om met stress?',
    levels: ['B1'],
    category: 'Gezondheid',
  },
  {
    id: 't-b1-gezond-03',
    text: 'Vertel over een moment waarop je iets moeilijks hebt overwonnen.',
    levels: ['B1'],
    category: 'Gezondheid',
  },
  {
    id: 't-b1-gezond-04',
    text: 'Wat doet jou glimlachen als je een slechte dag hebt?',
    levels: ['B1'],
    category: 'Gezondheid',
  },
  {
    id: 't-b1-gezond-05',
    text: 'Hoe belangrijk is gezondheid voor jou?',
    levels: ['B1'],
    category: 'Gezondheid',
  },
  {
    id: 't-b1-gezond-06',
    text: 'Wat doe je om in balans te blijven?',
    levels: ['B1'],
    category: 'Gezondheid',
  },
  {
    id: 't-b1-gezond-07',
    text: 'Hoe zorg je voor je geestelijke gezondheid?',
    levels: ['B1'],
    category: 'Gezondheid',
  },
  {
    id: 't-b1-gezond-08',
    text: 'Welke gewoonte houdt jou gezond?',
    levels: ['B1'],
    category: 'Gezondheid',
  },
  {
    id: 't-b1-gezond-09',
    text: 'Hoe ga je om met tegenslag?',
    levels: ['B1'],
    category: 'Gezondheid',
  },
  { id: 't-b1-gezond-10', text: 'Wat geeft jou energie?', levels: ['B1'], category: 'Gezondheid' },
  {
    id: 't-b1-gezond-11',
    text: 'Hoe belangrijk is slaap voor jou?',
    levels: ['B1'],
    category: 'Gezondheid',
  },
  {
    id: 't-b1-gezond-12',
    text: 'Wat doe je als je je zorgen maakt?',
    levels: ['B1'],
    category: 'Gezondheid',
  },
  {
    id: 't-b1-gezond-13',
    text: 'Hoe ga je om met veranderingen in je leven?',
    levels: ['B1'],
    category: 'Gezondheid',
  },
  {
    id: 't-b1-gezond-14',
    text: 'Wat betekent een gezond leven voor jou?',
    levels: ['B1'],
    category: 'Gezondheid',
  },
  {
    id: 't-b1-gezond-15',
    text: 'Hoe vraag je hulp als je het nodig hebt?',
    levels: ['B1'],
    category: 'Gezondheid',
  },
  {
    id: 't-b1-gezond-16',
    text: 'Hoe houd je je hoofd rustig in drukke tijden?',
    levels: ['B1'],
    category: 'Gezondheid',
  },
  {
    id: 't-b1-gezond-17',
    text: 'Wat heb je geleerd over jezelf in een moeilijke periode?',
    levels: ['B1'],
    category: 'Gezondheid',
  },
  {
    id: 't-b1-gezond-18',
    text: 'Hoe belangrijk is bewegen voor je humeur?',
    levels: ['B1'],
    category: 'Gezondheid',
  },
  {
    id: 't-b1-gezond-19',
    text: 'Wat doe je om goed voor jezelf te zorgen?',
    levels: ['B1'],
    category: 'Gezondheid',
  },
  {
    id: 't-b1-gezond-20',
    text: 'Hoe ga je om met heimwee?',
    levels: ['B1'],
    category: 'Gezondheid',
  },
  // B2
  {
    id: 't-b2-gezond-01',
    text: 'Welke gewoonte zou je graag willen veranderen, en waarom?',
    levels: ['B2'],
    category: 'Gezondheid',
  },
  {
    id: 't-b2-gezond-02',
    text: 'Hoe denk je over de balans tussen lichaam en geest?',
    levels: ['B2'],
    category: 'Gezondheid',
  },
  {
    id: 't-b2-gezond-03',
    text: "Wat betekent 'gezond leven' echt voor jou?",
    levels: ['B2'],
    category: 'Gezondheid',
  },
  {
    id: 't-b2-gezond-04',
    text: 'Hoe gaat de samenleving om met psychische problemen?',
    levels: ['B2'],
    category: 'Gezondheid',
  },
  {
    id: 't-b2-gezond-05',
    text: 'Hoe beïnvloedt stress de moderne mens?',
    levels: ['B2'],
    category: 'Gezondheid',
  },
  {
    id: 't-b2-gezond-06',
    text: 'Welke verantwoordelijkheid heb je voor je eigen gezondheid?',
    levels: ['B2'],
    category: 'Gezondheid',
  },
  {
    id: 't-b2-gezond-07',
    text: 'Hoe denk je over de gezondheidszorg in Nederland?',
    levels: ['B2'],
    category: 'Gezondheid',
  },
  {
    id: 't-b2-gezond-08',
    text: 'Hoe beïnvloedt eenzaamheid de gezondheid?',
    levels: ['B2'],
    category: 'Gezondheid',
  },
  {
    id: 't-b2-gezond-09',
    text: 'Wat vind je van de prestatiedruk in de maatschappij?',
    levels: ['B2'],
    category: 'Gezondheid',
  },
  {
    id: 't-b2-gezond-10',
    text: 'Hoe ga je om met ouder worden?',
    levels: ['B2'],
    category: 'Gezondheid',
  },
  {
    id: 't-b2-gezond-11',
    text: 'Hoe belangrijk is mentale gezondheid vergeleken met fysieke?',
    levels: ['B2'],
    category: 'Gezondheid',
  },
  {
    id: 't-b2-gezond-12',
    text: 'Welke rol speelt geld bij gezondheid?',
    levels: ['B2'],
    category: 'Gezondheid',
  },
  {
    id: 't-b2-gezond-13',
    text: 'Hoe beïnvloedt migratie iemands welzijn?',
    levels: ['B2'],
    category: 'Gezondheid',
  },
  {
    id: 't-b2-gezond-14',
    text: 'Wat zou jij veranderen aan hoe wij over gezondheid praten?',
    levels: ['B2'],
    category: 'Gezondheid',
  },
  {
    id: 't-b2-gezond-15',
    text: 'Hoe ga je om met onzekerheid over de toekomst?',
    levels: ['B2'],
    category: 'Gezondheid',
  },
  {
    id: 't-b2-gezond-16',
    text: "Hoe vind je rust in een wereld die altijd 'aan' staat?",
    levels: ['B2'],
    category: 'Gezondheid',
  },
  {
    id: 't-b2-gezond-17',
    text: 'Welke rol speelt gemeenschap bij gezondheid?',
    levels: ['B2'],
    category: 'Gezondheid',
  },
  {
    id: 't-b2-gezond-18',
    text: 'Hoe denk je over de grens tussen zorg en eigen verantwoordelijkheid?',
    levels: ['B2'],
    category: 'Gezondheid',
  },
  {
    id: 't-b2-gezond-19',
    text: 'Wat heb je geleerd over veerkracht?',
    levels: ['B2'],
    category: 'Gezondheid',
  },
  {
    id: 't-b2-gezond-20',
    text: 'Hoe zou een gezonde samenleving eruitzien?',
    levels: ['B2'],
    category: 'Gezondheid',
  },
];
