import type { Statement } from '../../types/content';

export const STATEMENTS: Statement[] = [
  // ── A1 — eenvoudige keuzes, "liever … of …?" ────────────────────────────
  { id: 's-a1-01', text: 'Liever koffie of thee?', levels: ['A1'], category: 'Eten' },
  { id: 's-a1-02', text: 'Liever een hond of een kat?', levels: ['A1'], category: 'Wonen' },
  { id: 's-a1-03', text: 'Liever zomer of winter?', levels: ['A1'], category: 'Vrije tijd' },
  { id: 's-a1-04', text: 'Liever fietsen of lopen?', levels: ['A1'], category: 'Buurt' },
  { id: 's-a1-05', text: 'Liever brood of rijst?', levels: ['A1'], category: 'Eten' },
  { id: 's-a1-06', text: 'Liever de stad of het dorp?', levels: ['A1'], category: 'Wonen' },
  {
    id: 's-a1-07',
    text: 'Liever vroeg opstaan of laat naar bed?',
    levels: ['A1'],
    category: 'Wonen',
  },
  { id: 's-a1-08', text: 'Liever pizza of pasta?', levels: ['A1'], category: 'Eten' },
  {
    id: 's-a1-09',
    text: 'Liever muziek luisteren of tv kijken?',
    levels: ['A1'],
    category: 'Vrije tijd',
  },
  { id: 's-a1-10', text: 'Liever zwemmen of wandelen?', levels: ['A1'], category: 'Vrije tijd' },
  { id: 's-a1-11', text: 'Liever de ochtend of de avond?', levels: ['A1'], category: 'Vrije tijd' },
  { id: 's-a1-12', text: 'Liever met de bus of met de fiets?', levels: ['A1'], category: 'Buurt' },
  { id: 's-a1-13', text: 'Liever regen of sneeuw?', levels: ['A1'], category: 'Vrije tijd' },
  {
    id: 's-a1-14',
    text: 'Liever veel vrienden of een paar goede vrienden?',
    levels: ['A1'],
    category: 'Familie',
  },
  { id: 's-a1-15', text: 'Liever koud of warm eten?', levels: ['A1'], category: 'Eten' },
  {
    id: 's-a1-16',
    text: 'Liever een groot huis of een klein gezellig huis?',
    levels: ['A1'],
    category: 'Wonen',
  },
  { id: 's-a1-17', text: 'Liever appels of sinaasappels?', levels: ['A1'], category: 'Eten' },
  {
    id: 's-a1-18',
    text: 'Liever binnenshuis of buitenshuis sporten?',
    levels: ['A1'],
    category: 'Vrije tijd',
  },
  {
    id: 's-a1-19',
    text: 'Liever met de hand schrijven of typen?',
    levels: ['A1'],
    category: 'Werk',
  },

  // ── A2 — iets meer uitleg nodig, dagelijkse keuzes ──────────────────────
  { id: 's-a2-01', text: 'Liever koken of uit eten?', levels: ['A2'], category: 'Eten' },
  {
    id: 's-a2-02',
    text: 'Liever een boek lezen of een film kijken?',
    levels: ['A2'],
    category: 'Vrije tijd',
  },
  {
    id: 's-a2-03',
    text: 'Liever in de zon of in de schaduw?',
    levels: ['A2'],
    category: 'Vrije tijd',
  },
  {
    id: 's-a2-04',
    text: 'Liever met de trein of met de auto reizen?',
    levels: ['A2'],
    category: 'Reizen',
  },
  { id: 's-a2-05', text: 'Liever buiten of binnen werken?', levels: ['A2'], category: 'Werk' },
  {
    id: 's-a2-06',
    text: 'Liever een dag alleen of een dag met veel mensen?',
    levels: ['A2'],
    category: 'Vrije tijd',
  },
  {
    id: 's-a2-07',
    text: 'Liever een groot feest of een rustig avondje thuis?',
    levels: ['A2'],
    category: 'Vrije tijd',
  },
  {
    id: 's-a2-08',
    text: 'Liever een lang weekend of een lange zomervakantie?',
    levels: ['A2'],
    category: 'Reizen',
  },
  { id: 's-a2-09', text: 'Liever thuis werken of op kantoor?', levels: ['A2'], category: 'Werk' },
  {
    id: 's-a2-10',
    text: 'Liever nieuws lezen of nieuws kijken?',
    levels: ['A2'],
    category: 'Vrije tijd',
  },
  {
    id: 's-a2-11',
    text: 'Liever een cadeau kopen of zelf maken?',
    levels: ['A2'],
    category: 'Familie',
  },
  {
    id: 's-a2-12',
    text: 'Liever vroeg aankomen of precies op tijd?',
    levels: ['A2'],
    category: 'Werk',
  },
  {
    id: 's-a2-13',
    text: 'Liever reizen met een plan of spontaan?',
    levels: ['A2'],
    category: 'Reizen',
  },
  {
    id: 's-a2-14',
    text: 'Liever een feestje organiseren of naar een feestje gaan?',
    levels: ['A2'],
    category: 'Vrije tijd',
  },
  {
    id: 's-a2-15',
    text: 'Liever in een drukke straat of in een rustige wijk wonen?',
    levels: ['A2'],
    category: 'Wonen',
  },
  {
    id: 's-a2-16',
    text: 'Liever sporten in een sportschool of buiten?',
    levels: ['A2'],
    category: 'Vrije tijd',
  },
  {
    id: 's-a2-17',
    text: 'Liever koffie of warme chocolademelk?',
    levels: ['A2'],
    category: 'Eten',
  },
  {
    id: 's-a2-18',
    text: 'Liever een kleine stad of een grote stad?',
    levels: ['A2'],
    category: 'Wonen',
  },
  {
    id: 's-a2-19',
    text: 'Liever zelf koken of eten bestellen?',
    levels: ['A2'],
    category: 'Eten',
  },
  {
    id: 's-a2-20',
    text: 'Liever vroeg of laat op vakantie gaan?',
    levels: ['A2'],
    category: 'Reizen',
  },

  // ── B1 — stellingen met mening, meer taal nodig ─────────────────────────
  {
    id: 's-b1-01',
    text: 'Geld is belangrijker dan vrije tijd.',
    levels: ['B1'],
    category: 'Werk',
  },
  {
    id: 's-b1-02',
    text: 'Iedereen zou minimaal twee talen moeten spreken.',
    levels: ['B1'],
    category: 'Werk',
  },
  {
    id: 's-b1-03',
    text: 'Een verjaardag vier je het liefst met familie.',
    levels: ['B1'],
    category: 'Familie',
  },
  {
    id: 's-b1-04',
    text: 'Sociale media maken mensen eenzamer.',
    levels: ['B1'],
    category: 'Vrije tijd',
  },
  {
    id: 's-b1-05',
    text: 'Op de fiets gaan is leuker dan met de auto.',
    levels: ['B1'],
    category: 'Buurt',
  },
  {
    id: 's-b1-06',
    text: 'Eerlijk zijn is altijd beter dan aardig zijn.',
    levels: ['B1'],
    category: 'Familie',
  },
  {
    id: 's-b1-07',
    text: 'Op een onbekende plek wonen maakt je sterker.',
    levels: ['B1'],
    category: 'Wonen',
  },
  {
    id: 's-b1-08',
    text: 'Vrienden zijn belangrijker dan familie.',
    levels: ['B1'],
    category: 'Familie',
  },
  {
    id: 's-b1-09',
    text: 'Kinderen leren meer van hun ouders dan van school.',
    levels: ['B1'],
    category: 'Familie',
  },
  {
    id: 's-b1-10',
    text: 'Sport is goed voor je geest, niet alleen je lichaam.',
    levels: ['B1'],
    category: 'Gezondheid',
  },
  {
    id: 's-b1-11',
    text: 'Technologie maakt het leven makkelijker maar ook eenzamer.',
    levels: ['B1'],
    category: 'Vrije tijd',
  },
  {
    id: 's-b1-12',
    text: 'Het is beter om te huren dan een huis te kopen.',
    levels: ['B1'],
    category: 'Wonen',
  },
  {
    id: 's-b1-13',
    text: 'Je hoeft niet te geloven om een goed mens te zijn.',
    levels: ['B1'],
    category: 'Familie',
  },
  {
    id: 's-b1-14',
    text: 'Kinderen zouden meer buiten moeten spelen, minder achter een scherm.',
    levels: ['B1'],
    category: 'Familie',
  },
  {
    id: 's-b1-15',
    text: 'Je leert meer van je fouten dan van je successen.',
    levels: ['B1'],
    category: 'Werk',
  },
  {
    id: 's-b1-16',
    text: 'Het is belangrijk om je eigen cultuur te bewaren als je in een ander land woont.',
    levels: ['B1'],
    category: 'Familie',
  },
  {
    id: 's-b1-17',
    text: 'Rijke landen hebben een plicht om arme landen te helpen.',
    levels: ['B1'],
    category: 'Buurt',
  },
  {
    id: 's-b1-18',
    text: 'Mensen in Nederland zijn eerlijk, maar soms te direct.',
    levels: ['B1'],
    category: 'Buurt',
  },
  {
    id: 's-b1-19',
    text: 'Een goede relatie vraagt om eerlijkheid, ook als dat pijn doet.',
    levels: ['B1'],
    category: 'Familie',
  },
  {
    id: 's-b1-20',
    text: 'Je kunt niet gelukkig zijn zonder werk dat je leuk vindt.',
    levels: ['B1'],
    category: 'Werk',
  },

  // ── B2 — abstracte stellingen, genuanceerde discussie ───────────────────
  {
    id: 's-b2-01',
    text: 'Een wereld zonder geld zou eerlijker zijn.',
    levels: ['B2'],
    category: 'Werk',
  },
  {
    id: 's-b2-02',
    text: 'Kunst is even belangrijk als wetenschap.',
    levels: ['B2'],
    category: 'Vrije tijd',
  },
  {
    id: 's-b2-03',
    text: 'Inburgeren betekent dat je je eigen cultuur deels loslaat.',
    levels: ['B2'],
    category: 'Buurt',
  },
  {
    id: 's-b2-04',
    text: 'Stilte is waardevoller dan muziek.',
    levels: ['B2'],
    category: 'Vrije tijd',
  },
  {
    id: 's-b2-05',
    text: 'Een leven zonder smartphone is rijker.',
    levels: ['B2'],
    category: 'Vrije tijd',
  },
  {
    id: 's-b2-06',
    text: 'Vrijwilligerswerk zou verplicht moeten zijn.',
    levels: ['B2'],
    category: 'Werk',
  },
  {
    id: 's-b2-07',
    text: 'Wie een nieuwe taal leert, leert ook een nieuwe manier van denken.',
    levels: ['B2'],
    category: 'Werk',
  },
  {
    id: 's-b2-08',
    text: 'Nationaliteit zegt niets over wie je bent als mens.',
    levels: ['B2'],
    category: 'Buurt',
  },
  {
    id: 's-b2-09',
    text: 'Democratie is het beste systeem dat we kennen.',
    levels: ['B2'],
    category: 'Buurt',
  },
  {
    id: 's-b2-10',
    text: 'Sociale media hebben meer kwaad dan goed gedaan.',
    levels: ['B2'],
    category: 'Vrije tijd',
  },
  {
    id: 's-b2-11',
    text: 'Onderwijs zou gratis moeten zijn voor iedereen.',
    levels: ['B2'],
    category: 'Werk',
  },
  {
    id: 's-b2-12',
    text: 'Een meertalige opvoeding geeft kinderen een voorsprong.',
    levels: ['B2'],
    category: 'Familie',
  },
  {
    id: 's-b2-13',
    text: 'De Nederlandse directheid is een kwaliteit, geen gebrek aan beleefdheid.',
    levels: ['B2'],
    category: 'Buurt',
  },
  {
    id: 's-b2-14',
    text: 'Armoede is altijd een structureel probleem, nooit een persoonlijk falen.',
    levels: ['B2'],
    category: 'Buurt',
  },
  {
    id: 's-b2-15',
    text: 'Het gaat er niet om waar je vandaan komt, maar waar je naartoe gaat.',
    levels: ['B2'],
    category: 'Buurt',
  },
  {
    id: 's-b2-16',
    text: 'Grenzen tussen landen zouden minder streng moeten zijn.',
    levels: ['B2'],
    category: 'Reizen',
  },
  {
    id: 's-b2-17',
    text: 'Duurzaamheid vraagt offers die de meeste mensen niet willen brengen.',
    levels: ['B2'],
    category: 'Buurt',
  },
  { id: 's-b2-18', text: 'Geluk is een keuze.', levels: ['B2'], category: 'Gezondheid' },
  {
    id: 's-b2-19',
    text: 'Een samenleving heeft regels nodig die niet iedereen leuk vindt.',
    levels: ['B2'],
    category: 'Buurt',
  },
  {
    id: 's-b2-20',
    text: 'De best opgeleide mensen verlaten hun land — is dat een probleem voor jou?',
    levels: ['B2'],
    category: 'Werk',
  },
];
