import type { Statement } from '../../types/content';

export const STATEMENTS: Statement[] = [
  // ══ BUURT ════════════════════════════════════════════════════════════════
  // A1
  {
    id: 's-a1-buurt-01',
    text: 'Liever fietsen of lopen door de buurt?',
    levels: ['A1'],
    category: 'Buurt',
  },
  { id: 's-a1-buurt-02', text: 'Liever de stad of het dorp?', levels: ['A1'], category: 'Buurt' },
  {
    id: 's-a1-buurt-03',
    text: 'Liever een grote winkel of een kleine winkel?',
    levels: ['A1'],
    category: 'Buurt',
  },
  { id: 's-a1-buurt-04', text: 'Liever de bus of de fiets?', levels: ['A1'], category: 'Buurt' },
  {
    id: 's-a1-buurt-05',
    text: 'Liever een huis met tuin of een flat?',
    levels: ['A1'],
    category: 'Buurt',
  },
  {
    id: 's-a1-buurt-06',
    text: 'Liever een rustige straat of een drukke straat?',
    levels: ['A1'],
    category: 'Buurt',
  },
  {
    id: 's-a1-buurt-07',
    text: 'Liever dichtbij het centrum of dichtbij het park?',
    levels: ['A1'],
    category: 'Buurt',
  },
  {
    id: 's-a1-buurt-08',
    text: 'Liever de markt of de supermarkt?',
    levels: ['A1'],
    category: 'Buurt',
  },
  {
    id: 's-a1-buurt-09',
    text: 'Liever een nieuwe buurt of een oude buurt?',
    levels: ['A1'],
    category: 'Buurt',
  },
  {
    id: 's-a1-buurt-10',
    text: 'Liever wonen bij water of bij een park?',
    levels: ['A1'],
    category: 'Buurt',
  },
  // A2
  {
    id: 's-a2-buurt-01',
    text: 'Een park in de buurt is belangrijk.',
    levels: ['A2'],
    category: 'Buurt',
  },
  {
    id: 's-a2-buurt-02',
    text: 'Ik praat graag met mijn buren.',
    levels: ['A2'],
    category: 'Buurt',
  },
  {
    id: 's-a2-buurt-03',
    text: 'De markt is leuker dan de supermarkt.',
    levels: ['A2'],
    category: 'Buurt',
  },
  {
    id: 's-a2-buurt-04',
    text: 'In de stad is altijd iets te doen.',
    levels: ['A2'],
    category: 'Buurt',
  },
  {
    id: 's-a2-buurt-05',
    text: 'Een rustige buurt is fijner dan een drukke buurt.',
    levels: ['A2'],
    category: 'Buurt',
  },
  {
    id: 's-a2-buurt-06',
    text: 'Ik ga liever lopend dan met de bus.',
    levels: ['A2'],
    category: 'Buurt',
  },
  {
    id: 's-a2-buurt-07',
    text: 'Mooie winkels maken een buurt leuk.',
    levels: ['A2'],
    category: 'Buurt',
  },
  {
    id: 's-a2-buurt-08',
    text: 'Het is fijn als de school dichtbij is.',
    levels: ['A2'],
    category: 'Buurt',
  },
  { id: 's-a2-buurt-09', text: 'Buren moeten elkaar groeten.', levels: ['A2'], category: 'Buurt' },
  {
    id: 's-a2-buurt-10',
    text: 'Een schone straat is belangrijk.',
    levels: ['A2'],
    category: 'Buurt',
  },
  // B1
  {
    id: 's-b1-buurt-01',
    text: 'Goede buren zijn belangrijker dan een mooi huis.',
    levels: ['B1'],
    category: 'Buurt',
  },
  {
    id: 's-b1-buurt-02',
    text: 'De gemeente moet meer doen aan groen in de stad.',
    levels: ['B1'],
    category: 'Buurt',
  },
  {
    id: 's-b1-buurt-03',
    text: 'In een dorp ben je gelukkiger dan in de stad.',
    levels: ['B1'],
    category: 'Buurt',
  },
  {
    id: 's-b1-buurt-04',
    text: 'Iedereen zou zijn buren moeten kennen.',
    levels: ['B1'],
    category: 'Buurt',
  },
  {
    id: 's-b1-buurt-05',
    text: 'Het openbaar vervoer in Nederland is goed geregeld.',
    levels: ['B1'],
    category: 'Buurt',
  },
  {
    id: 's-b1-buurt-06',
    text: 'Een buurtfeest brengt mensen samen.',
    levels: ['B1'],
    category: 'Buurt',
  },
  {
    id: 's-b1-buurt-07',
    text: 'Drukte in de stad maakt mensen gestrest.',
    levels: ['B1'],
    category: 'Buurt',
  },
  {
    id: 's-b1-buurt-08',
    text: 'Auto’s horen niet thuis in het stadscentrum.',
    levels: ['B1'],
    category: 'Buurt',
  },
  {
    id: 's-b1-buurt-09',
    text: 'Je bent zelf verantwoordelijk voor een leuke buurt.',
    levels: ['B1'],
    category: 'Buurt',
  },
  {
    id: 's-b1-buurt-10',
    text: 'Nieuwe bewoners maken een buurt beter.',
    levels: ['B1'],
    category: 'Buurt',
  },
  // B2
  {
    id: 's-b2-buurt-01',
    text: 'De overheid is verantwoordelijk voor de leefbaarheid van een wijk.',
    levels: ['B2'],
    category: 'Buurt',
  },
  {
    id: 's-b2-buurt-02',
    text: 'Massatoerisme verpest het karakter van een stad.',
    levels: ['B2'],
    category: 'Buurt',
  },
  {
    id: 's-b2-buurt-03',
    text: 'Stadscentra zouden autovrij moeten zijn.',
    levels: ['B2'],
    category: 'Buurt',
  },
  {
    id: 's-b2-buurt-04',
    text: 'Gemengde wijken zijn beter dan wijken met alleen rijk of alleen arm.',
    levels: ['B2'],
    category: 'Buurt',
  },
  {
    id: 's-b2-buurt-05',
    text: 'Anonimiteit in de stad is een probleem.',
    levels: ['B2'],
    category: 'Buurt',
  },
  {
    id: 's-b2-buurt-06',
    text: 'Cultureel erfgoed moet altijd beschermd worden.',
    levels: ['B2'],
    category: 'Buurt',
  },
  {
    id: 's-b2-buurt-07',
    text: 'Bewoners zouden meer inspraak moeten hebben in hun buurt.',
    levels: ['B2'],
    category: 'Buurt',
  },
  {
    id: 's-b2-buurt-08',
    text: 'Een stad kan niet tegelijk modern en gezellig zijn.',
    levels: ['B2'],
    category: 'Buurt',
  },
  {
    id: 's-b2-buurt-09',
    text: 'Woningnood is het grootste probleem van Nederland.',
    levels: ['B2'],
    category: 'Buurt',
  },
  {
    id: 's-b2-buurt-10',
    text: 'Het opknappen van oude wijken jaagt de oorspronkelijke bewoners weg.',
    levels: ['B2'],
    category: 'Buurt',
  },

  // ══ FAMILIE ══════════════════════════════════════════════════════════════
  // A1
  {
    id: 's-a1-familie-01',
    text: 'Liever een grote familie of een kleine familie?',
    levels: ['A1'],
    category: 'Familie',
  },
  {
    id: 's-a1-familie-02',
    text: 'Liever tijd met vrienden of tijd met familie?',
    levels: ['A1'],
    category: 'Familie',
  },
  {
    id: 's-a1-familie-03',
    text: 'Liever bellen of een bericht sturen?',
    levels: ['A1'],
    category: 'Familie',
  },
  {
    id: 's-a1-familie-04',
    text: 'Liever samen eten of alleen eten?',
    levels: ['A1'],
    category: 'Familie',
  },
  {
    id: 's-a1-familie-05',
    text: 'Liever een feest met veel mensen of met weinig mensen?',
    levels: ['A1'],
    category: 'Familie',
  },
  {
    id: 's-a1-familie-06',
    text: 'Liever een broer of een zus?',
    levels: ['A1'],
    category: 'Familie',
  },
  {
    id: 's-a1-familie-07',
    text: 'Liever spelen met kinderen of praten met volwassenen?',
    levels: ['A1'],
    category: 'Familie',
  },
  {
    id: 's-a1-familie-08',
    text: 'Liever een cadeau geven of een cadeau krijgen?',
    levels: ['A1'],
    category: 'Familie',
  },
  {
    id: 's-a1-familie-09',
    text: 'Liever bij familie wonen of alleen wonen?',
    levels: ['A1'],
    category: 'Familie',
  },
  {
    id: 's-a1-familie-10',
    text: 'Liever een verjaardag thuis of in een restaurant?',
    levels: ['A1'],
    category: 'Familie',
  },
  // A2
  {
    id: 's-a2-familie-01',
    text: 'Familie is het belangrijkst in het leven.',
    levels: ['A2'],
    category: 'Familie',
  },
  {
    id: 's-a2-familie-02',
    text: 'Vrienden zijn net zo belangrijk als familie.',
    levels: ['A2'],
    category: 'Familie',
  },
  {
    id: 's-a2-familie-03',
    text: 'Het is fijn om dichtbij je familie te wonen.',
    levels: ['A2'],
    category: 'Familie',
  },
  {
    id: 's-a2-familie-04',
    text: 'Een verjaardag moet je altijd vieren.',
    levels: ['A2'],
    category: 'Familie',
  },
  {
    id: 's-a2-familie-05',
    text: 'Kinderen moeten naar hun ouders luisteren.',
    levels: ['A2'],
    category: 'Familie',
  },
  { id: 's-a2-familie-06', text: 'Samen eten is gezellig.', levels: ['A2'], category: 'Familie' },
  { id: 's-a2-familie-07', text: 'Oude mensen weten veel.', levels: ['A2'], category: 'Familie' },
  {
    id: 's-a2-familie-08',
    text: 'Het is moeilijk om nieuwe vrienden te maken.',
    levels: ['A2'],
    category: 'Familie',
  },
  {
    id: 's-a2-familie-09',
    text: 'Je moet je familie elke week zien.',
    levels: ['A2'],
    category: 'Familie',
  },
  {
    id: 's-a2-familie-10',
    text: 'Een goede vriend helpt je altijd.',
    levels: ['A2'],
    category: 'Familie',
  },
  // B1
  {
    id: 's-b1-familie-01',
    text: 'Familie is belangrijker dan vrienden.',
    levels: ['B1'],
    category: 'Familie',
  },
  {
    id: 's-b1-familie-02',
    text: 'Ouders moeten streng zijn voor hun kinderen.',
    levels: ['B1'],
    category: 'Familie',
  },
  { id: 's-b1-familie-03', text: 'Vriendschap kost moeite.', levels: ['B1'], category: 'Familie' },
  {
    id: 's-b1-familie-04',
    text: 'Goede vrienden voelen als familie.',
    levels: ['B1'],
    category: 'Familie',
  },
  {
    id: 's-b1-familie-05',
    text: 'Kinderen moeten voor hun oude ouders zorgen.',
    levels: ['B1'],
    category: 'Familie',
  },
  {
    id: 's-b1-familie-06',
    text: 'Tradities binnen een familie moet je doorgeven.',
    levels: ['B1'],
    category: 'Familie',
  },
  {
    id: 's-b1-familie-07',
    text: 'Eerlijkheid is belangrijker dan beleefdheid in een familie.',
    levels: ['B1'],
    category: 'Familie',
  },
  {
    id: 's-b1-familie-08',
    text: 'Afstand kan een familieband juist sterker maken.',
    levels: ['B1'],
    category: 'Familie',
  },
  {
    id: 's-b1-familie-09',
    text: 'Soms ruzie maken is gezond.',
    levels: ['B1'],
    category: 'Familie',
  },
  {
    id: 's-b1-familie-10',
    text: 'Iedereen heeft een voorbeeld of mentor nodig.',
    levels: ['B1'],
    category: 'Familie',
  },
  // B2
  {
    id: 's-b2-familie-01',
    text: 'Je familie bepaalt voor een groot deel wie je wordt.',
    levels: ['B2'],
    category: 'Familie',
  },
  {
    id: 's-b2-familie-02',
    text: 'Ouders mogen verwachtingen hebben van hun kinderen.',
    levels: ['B2'],
    category: 'Familie',
  },
  {
    id: 's-b2-familie-03',
    text: 'Loyaliteit aan familie gaat soms te ver.',
    levels: ['B2'],
    category: 'Familie',
  },
  {
    id: 's-b2-familie-04',
    text: 'Vriendschap is een keuze en daarom waardevoller dan familie.',
    levels: ['B2'],
    category: 'Familie',
  },
  {
    id: 's-b2-familie-05',
    text: 'Migratie verzwakt altijd de familieband.',
    levels: ['B2'],
    category: 'Familie',
  },
  {
    id: 's-b2-familie-06',
    text: 'De vaste rolverdeling tussen man en vrouw is achterhaald.',
    levels: ['B2'],
    category: 'Familie',
  },
  {
    id: 's-b2-familie-07',
    text: 'Je hebt het recht om het contact met familie te verbreken.',
    levels: ['B2'],
    category: 'Familie',
  },
  {
    id: 's-b2-familie-08',
    text: 'Of je kinderen krijgt, is een puur persoonlijke keuze.',
    levels: ['B2'],
    category: 'Familie',
  },
  {
    id: 's-b2-familie-09',
    text: 'Vergeven is belangrijker dan gelijk hebben.',
    levels: ['B2'],
    category: 'Familie',
  },
  {
    id: 's-b2-familie-10',
    text: 'Verschillende generaties zullen elkaar nooit echt begrijpen.',
    levels: ['B2'],
    category: 'Familie',
  },

  // ══ WERK ═════════════════════════════════════════════════════════════════
  // A1
  { id: 's-a1-werk-01', text: 'Liever binnen of buiten werken?', levels: ['A1'], category: 'Werk' },
  {
    id: 's-a1-werk-02',
    text: 'Liever alleen of met anderen werken?',
    levels: ['A1'],
    category: 'Werk',
  },
  {
    id: 's-a1-werk-03',
    text: 'Liever vroeg beginnen of laat beginnen?',
    levels: ['A1'],
    category: 'Werk',
  },
  {
    id: 's-a1-werk-04',
    text: 'Liever met je handen of met de computer werken?',
    levels: ['A1'],
    category: 'Werk',
  },
  {
    id: 's-a1-werk-05',
    text: 'Liever een rustige baan of een drukke baan?',
    levels: ['A1'],
    category: 'Werk',
  },
  { id: 's-a1-werk-06', text: 'Liever leren of werken?', levels: ['A1'], category: 'Werk' },
  {
    id: 's-a1-werk-07',
    text: 'Liever een korte pauze of een lange pauze?',
    levels: ['A1'],
    category: 'Werk',
  },
  {
    id: 's-a1-werk-08',
    text: 'Liever een grote klas of een kleine klas?',
    levels: ['A1'],
    category: 'Werk',
  },
  { id: 's-a1-werk-09', text: 'Liever schrijven of typen?', levels: ['A1'], category: 'Werk' },
  {
    id: 's-a1-werk-10',
    text: 'Liever veel geld of veel vrije tijd?',
    levels: ['A1'],
    category: 'Werk',
  },
  // A2
  {
    id: 's-a2-werk-01',
    text: 'Werk is belangrijk voor een mens.',
    levels: ['A2'],
    category: 'Werk',
  },
  {
    id: 's-a2-werk-02',
    text: 'Een goede collega maakt het werk leuker.',
    levels: ['A2'],
    category: 'Werk',
  },
  { id: 's-a2-werk-03', text: 'Leren kan op elke leeftijd.', levels: ['A2'], category: 'Werk' },
  { id: 's-a2-werk-04', text: 'Een diploma helpt je aan werk.', levels: ['A2'], category: 'Werk' },
  {
    id: 's-a2-werk-05',
    text: 'Iedereen zou betaald werk moeten hebben.',
    levels: ['A2'],
    category: 'Werk',
  },
  { id: 's-a2-werk-06', text: 'Een baas moet vriendelijk zijn.', levels: ['A2'], category: 'Werk' },
  {
    id: 's-a2-werk-07',
    text: 'Talen leren is moeilijk maar nuttig.',
    levels: ['A2'],
    category: 'Werk',
  },
  {
    id: 's-a2-werk-08',
    text: 'Werken in een team is fijner dan alleen werken.',
    levels: ['A2'],
    category: 'Werk',
  },
  {
    id: 's-a2-werk-09',
    text: 'Een goede baan past bij wie je bent.',
    levels: ['A2'],
    category: 'Werk',
  },
  {
    id: 's-a2-werk-10',
    text: 'Op tijd komen op je werk is belangrijk.',
    levels: ['A2'],
    category: 'Werk',
  },
  // B1
  { id: 's-b1-werk-01', text: 'Werk geeft je leven zin.', levels: ['B1'], category: 'Werk' },
  {
    id: 's-b1-werk-02',
    text: 'Geld is de belangrijkste reden om te werken.',
    levels: ['B1'],
    category: 'Werk',
  },
  {
    id: 's-b1-werk-03',
    text: 'Een diploma zegt niets over hoe goed iemand is.',
    levels: ['B1'],
    category: 'Werk',
  },
  {
    id: 's-b1-werk-04',
    text: 'Vrijwilligerswerk is net zo waardevol als betaald werk.',
    levels: ['B1'],
    category: 'Werk',
  },
  {
    id: 's-b1-werk-05',
    text: 'Je moet werk doen waar je gelukkig van wordt.',
    levels: ['B1'],
    category: 'Werk',
  },
  {
    id: 's-b1-werk-06',
    text: 'Een goede leidinggevende luistert naar het team.',
    levels: ['B1'],
    category: 'Werk',
  },
  { id: 's-b1-werk-07', text: 'Fouten maken hoort bij leren.', levels: ['B1'], category: 'Werk' },
  {
    id: 's-b1-werk-08',
    text: 'De werkdruk in Nederland is te hoog.',
    levels: ['B1'],
    category: 'Werk',
  },
  {
    id: 's-b1-werk-09',
    text: 'Iedereen verdient een tweede kans op de arbeidsmarkt.',
    levels: ['B1'],
    category: 'Werk',
  },
  {
    id: 's-b1-werk-10',
    text: 'Je moet je hele leven blijven leren.',
    levels: ['B1'],
    category: 'Werk',
  },
  // B2
  {
    id: 's-b2-werk-01',
    text: 'Werk zou niet het belangrijkste in een leven moeten zijn.',
    levels: ['B2'],
    category: 'Werk',
  },
  {
    id: 's-b2-werk-02',
    text: 'Automatisering kost meer banen dan het oplevert.',
    levels: ['B2'],
    category: 'Werk',
  },
  {
    id: 's-b2-werk-03',
    text: 'Passie is belangrijker dan een hoog salaris.',
    levels: ['B2'],
    category: 'Werk',
  },
  {
    id: 's-b2-werk-04',
    text: 'De vierdaagse werkweek zou de norm moeten worden.',
    levels: ['B2'],
    category: 'Werk',
  },
  {
    id: 's-b2-werk-05',
    text: 'Succes wordt te veel afgemeten aan werk en geld.',
    levels: ['B2'],
    category: 'Werk',
  },
  {
    id: 's-b2-werk-06',
    text: 'Werkgevers zijn verantwoordelijk voor het welzijn van hun personeel.',
    levels: ['B2'],
    category: 'Werk',
  },
  {
    id: 's-b2-werk-07',
    text: 'Thuiswerken maakt mensen eenzamer.',
    levels: ['B2'],
    category: 'Werk',
  },
  {
    id: 's-b2-werk-08',
    text: 'Iedereen zou een basisinkomen moeten krijgen.',
    levels: ['B2'],
    category: 'Werk',
  },
  {
    id: 's-b2-werk-09',
    text: 'Concurrentie maakt mensen beter in hun werk.',
    levels: ['B2'],
    category: 'Werk',
  },
  {
    id: 's-b2-werk-10',
    text: "Een 'roeping' bestaat niet — werk is gewoon werk.",
    levels: ['B2'],
    category: 'Werk',
  },

  // ══ ETEN ═════════════════════════════════════════════════════════════════
  // A1
  { id: 's-a1-eten-01', text: 'Liever koffie of thee?', levels: ['A1'], category: 'Eten' },
  { id: 's-a1-eten-02', text: 'Liever brood of rijst?', levels: ['A1'], category: 'Eten' },
  { id: 's-a1-eten-03', text: 'Liever zoet of zout?', levels: ['A1'], category: 'Eten' },
  { id: 's-a1-eten-04', text: 'Liever soep of salade?', levels: ['A1'], category: 'Eten' },
  { id: 's-a1-eten-05', text: 'Liever kaas of worst?', levels: ['A1'], category: 'Eten' },
  { id: 's-a1-eten-06', text: 'Liever water of sap?', levels: ['A1'], category: 'Eten' },
  { id: 's-a1-eten-07', text: 'Liever zelf koken of uit eten?', levels: ['A1'], category: 'Eten' },
  { id: 's-a1-eten-08', text: 'Liever fruit of koek?', levels: ['A1'], category: 'Eten' },
  { id: 's-a1-eten-09', text: 'Liever warm eten of koud eten?', levels: ['A1'], category: 'Eten' },
  { id: 's-a1-eten-10', text: 'Liever ontbijt of avondeten?', levels: ['A1'], category: 'Eten' },
  // A2
  {
    id: 's-a2-eten-01',
    text: 'Samen eten is gezelliger dan alleen eten.',
    levels: ['A2'],
    category: 'Eten',
  },
  {
    id: 's-a2-eten-02',
    text: 'Zelf koken is gezonder dan kant-en-klaar eten.',
    levels: ['A2'],
    category: 'Eten',
  },
  {
    id: 's-a2-eten-03',
    text: 'Het ontbijt is de belangrijkste maaltijd.',
    levels: ['A2'],
    category: 'Eten',
  },
  {
    id: 's-a2-eten-04',
    text: 'Eten uit andere landen is lekker.',
    levels: ['A2'],
    category: 'Eten',
  },
  { id: 's-a2-eten-05', text: 'Op de markt is het eten verser.', levels: ['A2'], category: 'Eten' },
  { id: 's-a2-eten-06', text: 'Groente eten is belangrijk.', levels: ['A2'], category: 'Eten' },
  {
    id: 's-a2-eten-07',
    text: 'Een feest zonder eten is geen feest.',
    levels: ['A2'],
    category: 'Eten',
  },
  { id: 's-a2-eten-08', text: 'Koken kun je leren.', levels: ['A2'], category: 'Eten' },
  { id: 's-a2-eten-09', text: 'Te veel snoep is niet goed.', levels: ['A2'], category: 'Eten' },
  { id: 's-a2-eten-10', text: 'Eten verbindt mensen.', levels: ['A2'], category: 'Eten' },
  // B1
  {
    id: 's-b1-eten-01',
    text: 'Gezond eten is duurder dan ongezond eten.',
    levels: ['B1'],
    category: 'Eten',
  },
  {
    id: 's-b1-eten-02',
    text: 'Iedereen zou minder vlees moeten eten.',
    levels: ['B1'],
    category: 'Eten',
  },
  {
    id: 's-b1-eten-03',
    text: 'Fastfood hoort niet in een gezond leven.',
    levels: ['B1'],
    category: 'Eten',
  },
  {
    id: 's-b1-eten-04',
    text: 'Eten uit je thuisland mis je het meest.',
    levels: ['B1'],
    category: 'Eten',
  },
  {
    id: 's-b1-eten-05',
    text: 'Gastvrijheid laat je zien met eten.',
    levels: ['B1'],
    category: 'Eten',
  },
  {
    id: 's-b1-eten-06',
    text: 'Voedsel verspillen is een grote fout.',
    levels: ['B1'],
    category: 'Eten',
  },
  {
    id: 's-b1-eten-07',
    text: 'Je leert een cultuur kennen via het eten.',
    levels: ['B1'],
    category: 'Eten',
  },
  {
    id: 's-b1-eten-08',
    text: 'Een gezin zou elke dag samen moeten eten.',
    levels: ['B1'],
    category: 'Eten',
  },
  { id: 's-b1-eten-09', text: 'De Nederlandse keuken is saai.', levels: ['B1'], category: 'Eten' },
  {
    id: 's-b1-eten-10',
    text: 'Wat je eet, bepaalt hoe je je voelt.',
    levels: ['B1'],
    category: 'Eten',
  },
  // B2
  {
    id: 's-b2-eten-01',
    text: 'De voedingsindustrie maakt mensen ongezond.',
    levels: ['B2'],
    category: 'Eten',
  },
  {
    id: 's-b2-eten-02',
    text: 'Vlees zou duurder gemaakt moeten worden.',
    levels: ['B2'],
    category: 'Eten',
  },
  {
    id: 's-b2-eten-03',
    text: 'Voedsel verspillen is moreel onaanvaardbaar.',
    levels: ['B2'],
    category: 'Eten',
  },
  {
    id: 's-b2-eten-04',
    text: 'Biologisch eten is een luxe voor rijke mensen.',
    levels: ['B2'],
    category: 'Eten',
  },
  {
    id: 's-b2-eten-05',
    text: 'Globalisering heeft de lokale eetcultuur verzwakt.',
    levels: ['B2'],
    category: 'Eten',
  },
  {
    id: 's-b2-eten-06',
    text: 'Iedereen heeft recht op gezond voedsel.',
    levels: ['B2'],
    category: 'Eten',
  },
  {
    id: 's-b2-eten-07',
    text: 'Wat we eten zegt iets over onze sociale klasse.',
    levels: ['B2'],
    category: 'Eten',
  },
  {
    id: 's-b2-eten-08',
    text: 'De overheid moet ongezond eten zwaarder belasten.',
    levels: ['B2'],
    category: 'Eten',
  },
  {
    id: 's-b2-eten-09',
    text: 'Klimaatverandering dwingt ons anders te eten.',
    levels: ['B2'],
    category: 'Eten',
  },
  {
    id: 's-b2-eten-10',
    text: 'Eten is meer dan voeding — het is identiteit.',
    levels: ['B2'],
    category: 'Eten',
  },

  // ══ REIZEN ═══════════════════════════════════════════════════════════════
  // A1
  { id: 's-a1-reizen-01', text: 'Liever de trein of de bus?', levels: ['A1'], category: 'Reizen' },
  { id: 's-a1-reizen-02', text: 'Liever de zee of de bergen?', levels: ['A1'], category: 'Reizen' },
  {
    id: 's-a1-reizen-03',
    text: 'Liever een warm land of een koud land?',
    levels: ['A1'],
    category: 'Reizen',
  },
  {
    id: 's-a1-reizen-04',
    text: 'Liever ver weg of dichtbij op vakantie?',
    levels: ['A1'],
    category: 'Reizen',
  },
  {
    id: 's-a1-reizen-05',
    text: 'Liever alleen reizen of samen reizen?',
    levels: ['A1'],
    category: 'Reizen',
  },
  {
    id: 's-a1-reizen-06',
    text: 'Liever een hotel of bij familie slapen?',
    levels: ['A1'],
    category: 'Reizen',
  },
  {
    id: 's-a1-reizen-07',
    text: 'Liever een korte reis of een lange reis?',
    levels: ['A1'],
    category: 'Reizen',
  },
  {
    id: 's-a1-reizen-08',
    text: 'Liever het vliegtuig of de auto?',
    levels: ['A1'],
    category: 'Reizen',
  },
  {
    id: 's-a1-reizen-09',
    text: 'Liever de stad of de natuur bezoeken?',
    levels: ['A1'],
    category: 'Reizen',
  },
  {
    id: 's-a1-reizen-10',
    text: 'Liever zomervakantie of wintervakantie?',
    levels: ['A1'],
    category: 'Reizen',
  },
  // A2
  { id: 's-a2-reizen-01', text: 'Reizen is leuk maar duur.', levels: ['A2'], category: 'Reizen' },
  { id: 's-a2-reizen-02', text: 'Op vakantie leer je veel.', levels: ['A2'], category: 'Reizen' },
  {
    id: 's-a2-reizen-03',
    text: 'De trein is fijner dan de auto.',
    levels: ['A2'],
    category: 'Reizen',
  },
  {
    id: 's-a2-reizen-04',
    text: 'Reizen met familie is gezellig.',
    levels: ['A2'],
    category: 'Reizen',
  },
  {
    id: 's-a2-reizen-05',
    text: 'Op reis hoor je een nieuwe taal te proberen.',
    levels: ['A2'],
    category: 'Reizen',
  },
  {
    id: 's-a2-reizen-06',
    text: 'Het strand is de fijnste vakantieplek.',
    levels: ['A2'],
    category: 'Reizen',
  },
  {
    id: 's-a2-reizen-07',
    text: 'Een reis moet je goed plannen.',
    levels: ['A2'],
    category: 'Reizen',
  },
  {
    id: 's-a2-reizen-08',
    text: 'Thuiskomen na een reis is fijn.',
    levels: ['A2'],
    category: 'Reizen',
  },
  {
    id: 's-a2-reizen-09',
    text: 'Iedereen zou een keer moeten vliegen.',
    levels: ['A2'],
    category: 'Reizen',
  },
  {
    id: 's-a2-reizen-10',
    text: 'Een reis is een mooier cadeau dan een ding.',
    levels: ['A2'],
    category: 'Reizen',
  },
  // B1
  {
    id: 's-b1-reizen-01',
    text: 'Reizen verandert je kijk op de wereld.',
    levels: ['B1'],
    category: 'Reizen',
  },
  {
    id: 's-b1-reizen-02',
    text: 'Je leert een land pas kennen als je er woont.',
    levels: ['B1'],
    category: 'Reizen',
  },
  {
    id: 's-b1-reizen-03',
    text: 'Spontaan reizen is leuker dan alles plannen.',
    levels: ['B1'],
    category: 'Reizen',
  },
  {
    id: 's-b1-reizen-04',
    text: 'Reizen is de beste manier om een taal te leren.',
    levels: ['B1'],
    category: 'Reizen',
  },
  {
    id: 's-b1-reizen-05',
    text: 'Een verre reis is elke euro waard.',
    levels: ['B1'],
    category: 'Reizen',
  },
  {
    id: 's-b1-reizen-06',
    text: 'Toeristen begrijpen een land nooit echt.',
    levels: ['B1'],
    category: 'Reizen',
  },
  { id: 's-b1-reizen-07', text: 'Heimwee hoort bij reizen.', levels: ['B1'], category: 'Reizen' },
  {
    id: 's-b1-reizen-08',
    text: 'Je hoeft niet ver te reizen om iets moois te zien.',
    levels: ['B1'],
    category: 'Reizen',
  },
  {
    id: 's-b1-reizen-09',
    text: 'Reizen maakt mensen toleranter.',
    levels: ['B1'],
    category: 'Reizen',
  },
  {
    id: 's-b1-reizen-10',
    text: 'Een mens zou minstens één keer in een ander land moeten wonen.',
    levels: ['B1'],
    category: 'Reizen',
  },
  // B2
  {
    id: 's-b2-reizen-01',
    text: 'Vliegen zou duurder moeten zijn vanwege het milieu.',
    levels: ['B2'],
    category: 'Reizen',
  },
  {
    id: 's-b2-reizen-02',
    text: 'Massatoerisme vernietigt de plekken die mensen mooi vinden.',
    levels: ['B2'],
    category: 'Reizen',
  },
  {
    id: 's-b2-reizen-03',
    text: 'Reizen is een luxe die we te gewoon zijn gaan vinden.',
    levels: ['B2'],
    category: 'Reizen',
  },
  {
    id: 's-b2-reizen-04',
    text: 'Migreren leert je meer over jezelf dan reizen.',
    levels: ['B2'],
    category: 'Reizen',
  },
  {
    id: 's-b2-reizen-05',
    text: 'De reisindustrie romantiseert armoede in arme landen.',
    levels: ['B2'],
    category: 'Reizen',
  },
  {
    id: 's-b2-reizen-06',
    text: 'Je kunt je op meerdere plekken tegelijk thuis voelen.',
    levels: ['B2'],
    category: 'Reizen',
  },
  {
    id: 's-b2-reizen-07',
    text: 'Reizen maakt mensen niet automatisch wijzer.',
    levels: ['B2'],
    category: 'Reizen',
  },
  {
    id: 's-b2-reizen-08',
    text: 'Een toerist heeft verantwoordelijkheid tegenover de plek die hij bezoekt.',
    levels: ['B2'],
    category: 'Reizen',
  },
  {
    id: 's-b2-reizen-09',
    text: 'Technologie heeft het echte avontuur uit reizen gehaald.',
    levels: ['B2'],
    category: 'Reizen',
  },
  {
    id: 's-b2-reizen-10',
    text: 'Grenzen tussen landen zouden niet moeten bestaan.',
    levels: ['B2'],
    category: 'Reizen',
  },

  // ══ VRIJE TIJD ═══════════════════════════════════════════════════════════
  // A1
  {
    id: 's-a1-vrij-01',
    text: 'Liever muziek luisteren of tv kijken?',
    levels: ['A1'],
    category: 'Vrije tijd',
  },
  {
    id: 's-a1-vrij-02',
    text: 'Liever zwemmen of wandelen?',
    levels: ['A1'],
    category: 'Vrije tijd',
  },
  { id: 's-a1-vrij-03', text: 'Liever lezen of tekenen?', levels: ['A1'], category: 'Vrije tijd' },
  { id: 's-a1-vrij-04', text: 'Liever dansen of zingen?', levels: ['A1'], category: 'Vrije tijd' },
  {
    id: 's-a1-vrij-05',
    text: 'Liever een spel of een film?',
    levels: ['A1'],
    category: 'Vrije tijd',
  },
  {
    id: 's-a1-vrij-06',
    text: 'Liever binnen of buiten spelen?',
    levels: ['A1'],
    category: 'Vrije tijd',
  },
  {
    id: 's-a1-vrij-07',
    text: 'Liever sport kijken of sport doen?',
    levels: ['A1'],
    category: 'Vrije tijd',
  },
  {
    id: 's-a1-vrij-08',
    text: 'Liever de zon of de regen?',
    levels: ['A1'],
    category: 'Vrije tijd',
  },
  {
    id: 's-a1-vrij-09',
    text: 'Liever alleen of samen iets doen?',
    levels: ['A1'],
    category: 'Vrije tijd',
  },
  {
    id: 's-a1-vrij-10',
    text: "Liever 's ochtends of 's avonds vrij?",
    levels: ['A1'],
    category: 'Vrije tijd',
  },
  // A2
  {
    id: 's-a2-vrij-01',
    text: 'Vrije tijd is net zo belangrijk als werk.',
    levels: ['A2'],
    category: 'Vrije tijd',
  },
  {
    id: 's-a2-vrij-02',
    text: 'Sport is goed voor iedereen.',
    levels: ['A2'],
    category: 'Vrije tijd',
  },
  {
    id: 's-a2-vrij-03',
    text: 'Een hobby maakt je leven leuker.',
    levels: ['A2'],
    category: 'Vrije tijd',
  },
  {
    id: 's-a2-vrij-04',
    text: 'Op het weekend verheug je je het meest.',
    levels: ['A2'],
    category: 'Vrije tijd',
  },
  {
    id: 's-a2-vrij-05',
    text: 'Buiten zijn is gezonder dan binnen zijn.',
    levels: ['A2'],
    category: 'Vrije tijd',
  },
  {
    id: 's-a2-vrij-06',
    text: 'Een boek lezen is ontspannend.',
    levels: ['A2'],
    category: 'Vrije tijd',
  },
  { id: 's-a2-vrij-07', text: 'Muziek maakt blij.', levels: ['A2'], category: 'Vrije tijd' },
  {
    id: 's-a2-vrij-08',
    text: 'Samen iets doen is leuker dan alleen.',
    levels: ['A2'],
    category: 'Vrije tijd',
  },
  {
    id: 's-a2-vrij-09',
    text: 'Een feest is een mooie afsluiting van de week.',
    levels: ['A2'],
    category: 'Vrije tijd',
  },
  {
    id: 's-a2-vrij-10',
    text: 'Iedereen heeft een hobby nodig.',
    levels: ['A2'],
    category: 'Vrije tijd',
  },
  // B1
  {
    id: 's-b1-vrij-01',
    text: 'Mensen hebben te weinig vrije tijd.',
    levels: ['B1'],
    category: 'Vrije tijd',
  },
  {
    id: 's-b1-vrij-02',
    text: 'Een hobby zegt veel over wie je bent.',
    levels: ['B1'],
    category: 'Vrije tijd',
  },
  {
    id: 's-b1-vrij-03',
    text: 'Je moet je vrije tijd nuttig besteden.',
    levels: ['B1'],
    category: 'Vrije tijd',
  },
  {
    id: 's-b1-vrij-04',
    text: 'Niets doen is ook waardevol.',
    levels: ['B1'],
    category: 'Vrije tijd',
  },
  {
    id: 's-b1-vrij-05',
    text: 'Creativiteit kun je leren.',
    levels: ['B1'],
    category: 'Vrije tijd',
  },
  {
    id: 's-b1-vrij-06',
    text: 'Vrijwilligerswerk hoort bij een goed leven.',
    levels: ['B1'],
    category: 'Vrije tijd',
  },
  {
    id: 's-b1-vrij-07',
    text: 'Te veel tv kijken is tijdverspilling.',
    levels: ['B1'],
    category: 'Vrije tijd',
  },
  {
    id: 's-b1-vrij-08',
    text: 'Echte ontspanning lukt alleen zonder telefoon.',
    levels: ['B1'],
    category: 'Vrije tijd',
  },
  {
    id: 's-b1-vrij-09',
    text: "Een leven zonder hobby's is leeg.",
    levels: ['B1'],
    category: 'Vrije tijd',
  },
  {
    id: 's-b1-vrij-10',
    text: 'Vrije tijd zou je vooral met anderen moeten doorbrengen.',
    levels: ['B1'],
    category: 'Vrije tijd',
  },
  // B2
  {
    id: 's-b2-vrij-01',
    text: 'Verveling is nodig om creatief te zijn.',
    levels: ['B2'],
    category: 'Vrije tijd',
  },
  {
    id: 's-b2-vrij-02',
    text: 'Sociale media hebben onze vrije tijd verpest.',
    levels: ['B2'],
    category: 'Vrije tijd',
  },
  {
    id: 's-b2-vrij-03',
    text: 'Vrije tijd is een recht, geen luxe.',
    levels: ['B2'],
    category: 'Vrije tijd',
  },
  {
    id: 's-b2-vrij-04',
    text: "We voelen te veel druk om onze vrije tijd 'nuttig' te besteden.",
    levels: ['B2'],
    category: 'Vrije tijd',
  },
  {
    id: 's-b2-vrij-05',
    text: 'Volwassenen spelen te weinig.',
    levels: ['B2'],
    category: 'Vrije tijd',
  },
  {
    id: 's-b2-vrij-06',
    text: 'Kunst en cultuur zijn een noodzaak, geen luxe.',
    levels: ['B2'],
    category: 'Vrije tijd',
  },
  {
    id: 's-b2-vrij-07',
    text: 'Een druk leven is geen rijk leven.',
    levels: ['B2'],
    category: 'Vrije tijd',
  },
  {
    id: 's-b2-vrij-08',
    text: 'Rust vinden is de grootste uitdaging van deze tijd.',
    levels: ['B2'],
    category: 'Vrije tijd',
  },
  {
    id: 's-b2-vrij-09',
    text: "Hobby's zouden niet om prestatie moeten draaien.",
    levels: ['B2'],
    category: 'Vrije tijd',
  },
  {
    id: 's-b2-vrij-10',
    text: 'Nieuwsgierigheid is de sleutel tot een gelukkig leven.',
    levels: ['B2'],
    category: 'Vrije tijd',
  },

  // ══ WONEN ════════════════════════════════════════════════════════════════
  // A1
  { id: 's-a1-wonen-01', text: 'Liever een huis of een flat?', levels: ['A1'], category: 'Wonen' },
  {
    id: 's-a1-wonen-02',
    text: 'Liever een grote kamer of een kleine kamer?',
    levels: ['A1'],
    category: 'Wonen',
  },
  {
    id: 's-a1-wonen-03',
    text: 'Liever een tuin of een balkon?',
    levels: ['A1'],
    category: 'Wonen',
  },
  {
    id: 's-a1-wonen-04',
    text: 'Liever vroeg opstaan of laat naar bed?',
    levels: ['A1'],
    category: 'Wonen',
  },
  {
    id: 's-a1-wonen-05',
    text: 'Liever boven of beneden wonen?',
    levels: ['A1'],
    category: 'Wonen',
  },
  {
    id: 's-a1-wonen-06',
    text: 'Liever een nieuw huis of een oud huis?',
    levels: ['A1'],
    category: 'Wonen',
  },
  {
    id: 's-a1-wonen-07',
    text: 'Liever planten of geen planten in huis?',
    levels: ['A1'],
    category: 'Wonen',
  },
  {
    id: 's-a1-wonen-08',
    text: 'Liever alleen wonen of samen wonen?',
    levels: ['A1'],
    category: 'Wonen',
  },
  {
    id: 's-a1-wonen-09',
    text: 'Liever opruimen of laten liggen?',
    levels: ['A1'],
    category: 'Wonen',
  },
  {
    id: 's-a1-wonen-10',
    text: 'Liever licht of donker in huis?',
    levels: ['A1'],
    category: 'Wonen',
  },
  // A2
  {
    id: 's-a2-wonen-01',
    text: 'Een eigen kamer is belangrijk.',
    levels: ['A2'],
    category: 'Wonen',
  },
  {
    id: 's-a2-wonen-02',
    text: 'Een gezellig huis maakt je blij.',
    levels: ['A2'],
    category: 'Wonen',
  },
  { id: 's-a2-wonen-03', text: 'Opruimen geeft rust.', levels: ['A2'], category: 'Wonen' },
  {
    id: 's-a2-wonen-04',
    text: 'Wonen in Nederland is anders dan in mijn thuisland.',
    levels: ['A2'],
    category: 'Wonen',
  },
  {
    id: 's-a2-wonen-05',
    text: 'Een tuin is fijner dan een balkon.',
    levels: ['A2'],
    category: 'Wonen',
  },
  {
    id: 's-a2-wonen-06',
    text: 'Iedereen moet meehelpen in het huishouden.',
    levels: ['A2'],
    category: 'Wonen',
  },
  {
    id: 's-a2-wonen-07',
    text: 'Een huis hoeft niet groot te zijn.',
    levels: ['A2'],
    category: 'Wonen',
  },
  {
    id: 's-a2-wonen-08',
    text: 'Planten maken een huis gezelliger.',
    levels: ['A2'],
    category: 'Wonen',
  },
  {
    id: 's-a2-wonen-09',
    text: 'Een rustige buurt is fijn om in te wonen.',
    levels: ['A2'],
    category: 'Wonen',
  },
  { id: 's-a2-wonen-10', text: 'Verhuizen is stressvol.', levels: ['A2'], category: 'Wonen' },
  // B1
  {
    id: 's-b1-wonen-01',
    text: 'Een huis is pas een thuis met de juiste mensen.',
    levels: ['B1'],
    category: 'Wonen',
  },
  {
    id: 's-b1-wonen-02',
    text: 'De grootte van je huis bepaalt niet je geluk.',
    levels: ['B1'],
    category: 'Wonen',
  },
  {
    id: 's-b1-wonen-03',
    text: 'Het huishouden moet eerlijk verdeeld worden.',
    levels: ['B1'],
    category: 'Wonen',
  },
  {
    id: 's-b1-wonen-04',
    text: 'Wonen in de stad is beter dan op het platteland.',
    levels: ['B1'],
    category: 'Wonen',
  },
  {
    id: 's-b1-wonen-05',
    text: 'Privacy thuis is heel belangrijk.',
    levels: ['B1'],
    category: 'Wonen',
  },
  {
    id: 's-b1-wonen-06',
    text: 'Je moet je snel thuis kunnen voelen op een nieuwe plek.',
    levels: ['B1'],
    category: 'Wonen',
  },
  {
    id: 's-b1-wonen-07',
    text: 'Een eigen plek hebben is een basisbehoefte.',
    levels: ['B1'],
    category: 'Wonen',
  },
  {
    id: 's-b1-wonen-08',
    text: 'Klein wonen kan ook prettig zijn.',
    levels: ['B1'],
    category: 'Wonen',
  },
  {
    id: 's-b1-wonen-09',
    text: 'Je woonomgeving beïnvloedt je humeur.',
    levels: ['B1'],
    category: 'Wonen',
  },
  {
    id: 's-b1-wonen-10',
    text: 'Comfort thuis is belangrijker dan een mooi uiterlijk.',
    levels: ['B1'],
    category: 'Wonen',
  },
  // B2
  {
    id: 's-b2-wonen-01',
    text: "'Thuis' is een gevoel, geen plek.",
    levels: ['B2'],
    category: 'Wonen',
  },
  {
    id: 's-b2-wonen-02',
    text: 'Een eigen huis bezitten zou voor iedereen mogelijk moeten zijn.',
    levels: ['B2'],
    category: 'Wonen',
  },
  {
    id: 's-b2-wonen-03',
    text: 'De woningmarkt is oneerlijk geworden.',
    levels: ['B2'],
    category: 'Wonen',
  },
  {
    id: 's-b2-wonen-04',
    text: 'Je kunt je geboorteland en je nieuwe land allebei thuis noemen.',
    levels: ['B2'],
    category: 'Wonen',
  },
  {
    id: 's-b2-wonen-05',
    text: 'Wonen met meerdere generaties is beter dan apart wonen.',
    levels: ['B2'],
    category: 'Wonen',
  },
  {
    id: 's-b2-wonen-06',
    text: 'Waar je woont, bepaalt je kansen in het leven.',
    levels: ['B2'],
    category: 'Wonen',
  },
  {
    id: 's-b2-wonen-07',
    text: 'Duurzaam wonen zou verplicht moeten zijn.',
    levels: ['B2'],
    category: 'Wonen',
  },
  {
    id: 's-b2-wonen-08',
    text: 'Het bezit van een huis maakt mensen niet gelukkiger.',
    levels: ['B2'],
    category: 'Wonen',
  },
  {
    id: 's-b2-wonen-09',
    text: 'Migreren betekent altijd een stukje thuis verliezen.',
    levels: ['B2'],
    category: 'Wonen',
  },
  {
    id: 's-b2-wonen-10',
    text: 'De overheid moet de woningnood oplossen, niet de markt.',
    levels: ['B2'],
    category: 'Wonen',
  },

  // ══ GEZONDHEID ═══════════════════════════════════════════════════════════
  // A1
  {
    id: 's-a1-gezond-01',
    text: 'Liever lopen of fietsen?',
    levels: ['A1'],
    category: 'Gezondheid',
  },
  {
    id: 's-a1-gezond-02',
    text: 'Liever vroeg of laat slapen?',
    levels: ['A1'],
    category: 'Gezondheid',
  },
  {
    id: 's-a1-gezond-03',
    text: 'Liever water of frisdrank?',
    levels: ['A1'],
    category: 'Gezondheid',
  },
  {
    id: 's-a1-gezond-04',
    text: 'Liever sporten of rusten?',
    levels: ['A1'],
    category: 'Gezondheid',
  },
  {
    id: 's-a1-gezond-05',
    text: 'Liever binnen of buiten bewegen?',
    levels: ['A1'],
    category: 'Gezondheid',
  },
  {
    id: 's-a1-gezond-06',
    text: 'Liever een dutje of doorgaan?',
    levels: ['A1'],
    category: 'Gezondheid',
  },
  { id: 's-a1-gezond-07', text: 'Liever fruit of chips?', levels: ['A1'], category: 'Gezondheid' },
  {
    id: 's-a1-gezond-08',
    text: 'Liever wandelen of zwemmen?',
    levels: ['A1'],
    category: 'Gezondheid',
  },
  {
    id: 's-a1-gezond-09',
    text: 'Liever koud of warm weer?',
    levels: ['A1'],
    category: 'Gezondheid',
  },
  {
    id: 's-a1-gezond-10',
    text: "Liever 's ochtends of 's avonds sporten?",
    levels: ['A1'],
    category: 'Gezondheid',
  },
  // A2
  {
    id: 's-a2-gezond-01',
    text: 'Genoeg slapen is belangrijk.',
    levels: ['A2'],
    category: 'Gezondheid',
  },
  { id: 's-a2-gezond-02', text: 'Sport maakt je blij.', levels: ['A2'], category: 'Gezondheid' },
  {
    id: 's-a2-gezond-03',
    text: 'Water drinken is gezond.',
    levels: ['A2'],
    category: 'Gezondheid',
  },
  {
    id: 's-a2-gezond-04',
    text: 'Buiten zijn is goed voor je.',
    levels: ['A2'],
    category: 'Gezondheid',
  },
  {
    id: 's-a2-gezond-05',
    text: 'Iedereen moet elke dag bewegen.',
    levels: ['A2'],
    category: 'Gezondheid',
  },
  {
    id: 's-a2-gezond-06',
    text: 'Gezond eten helpt tegen ziek worden.',
    levels: ['A2'],
    category: 'Gezondheid',
  },
  {
    id: 's-a2-gezond-07',
    text: 'Rust nemen is geen luxe.',
    levels: ['A2'],
    category: 'Gezondheid',
  },
  {
    id: 's-a2-gezond-08',
    text: 'Wandelen is een fijne sport.',
    levels: ['A2'],
    category: 'Gezondheid',
  },
  {
    id: 's-a2-gezond-09',
    text: 'Een gezonde gewoonte begin je vandaag.',
    levels: ['A2'],
    category: 'Gezondheid',
  },
  {
    id: 's-a2-gezond-10',
    text: 'Naar de dokter gaan hoeft niet eng te zijn.',
    levels: ['A2'],
    category: 'Gezondheid',
  },
  // B1
  {
    id: 's-b1-gezond-01',
    text: 'Gezondheid is het belangrijkste dat er is.',
    levels: ['B1'],
    category: 'Gezondheid',
  },
  {
    id: 's-b1-gezond-02',
    text: 'Een gezonde geest is belangrijker dan een gezond lichaam.',
    levels: ['B1'],
    category: 'Gezondheid',
  },
  {
    id: 's-b1-gezond-03',
    text: 'Stress hoort bij het moderne leven.',
    levels: ['B1'],
    category: 'Gezondheid',
  },
  {
    id: 's-b1-gezond-04',
    text: 'Je bent zelf verantwoordelijk voor je gezondheid.',
    levels: ['B1'],
    category: 'Gezondheid',
  },
  {
    id: 's-b1-gezond-05',
    text: 'Bewegen helpt tegen een slechte stemming.',
    levels: ['B1'],
    category: 'Gezondheid',
  },
  {
    id: 's-b1-gezond-06',
    text: 'Hulp vragen is een teken van kracht.',
    levels: ['B1'],
    category: 'Gezondheid',
  },
  {
    id: 's-b1-gezond-07',
    text: 'Genoeg slaap is belangrijker dan veel werken.',
    levels: ['B1'],
    category: 'Gezondheid',
  },
  {
    id: 's-b1-gezond-08',
    text: 'Een moeilijke periode kan je laten groeien.',
    levels: ['B1'],
    category: 'Gezondheid',
  },
  {
    id: 's-b1-gezond-09',
    text: 'Tegenslag maakt je sterker.',
    levels: ['B1'],
    category: 'Gezondheid',
  },
  {
    id: 's-b1-gezond-10',
    text: 'Een gezond leven kost discipline.',
    levels: ['B1'],
    category: 'Gezondheid',
  },
  // B2
  {
    id: 's-b2-gezond-01',
    text: 'Mentale gezondheid is even belangrijk als fysieke gezondheid.',
    levels: ['B2'],
    category: 'Gezondheid',
  },
  {
    id: 's-b2-gezond-02',
    text: 'De maatschappij legt te veel prestatiedruk op mensen.',
    levels: ['B2'],
    category: 'Gezondheid',
  },
  {
    id: 's-b2-gezond-03',
    text: 'Eenzaamheid is een groot gezondheidsprobleem geworden.',
    levels: ['B2'],
    category: 'Gezondheid',
  },
  {
    id: 's-b2-gezond-04',
    text: 'Goede gezondheidszorg zou voor iedereen gratis moeten zijn.',
    levels: ['B2'],
    category: 'Gezondheid',
  },
  {
    id: 's-b2-gezond-05',
    text: 'Gezondheid is deels een kwestie van geld.',
    levels: ['B2'],
    category: 'Gezondheid',
  },
  {
    id: 's-b2-gezond-06',
    text: 'We praten nog te weinig open over psychische problemen.',
    levels: ['B2'],
    category: 'Gezondheid',
  },
  {
    id: 's-b2-gezond-07',
    text: 'De zorg voor ouderen schiet tekort.',
    levels: ['B2'],
    category: 'Gezondheid',
  },
  {
    id: 's-b2-gezond-08',
    text: 'Je gezondheid is niet alleen je eigen verantwoordelijkheid.',
    levels: ['B2'],
    category: 'Gezondheid',
  },
  {
    id: 's-b2-gezond-09',
    text: "Een wereld die altijd 'aan' staat, maakt mensen ziek.",
    levels: ['B2'],
    category: 'Gezondheid',
  },
  {
    id: 's-b2-gezond-10',
    text: 'Veerkracht kun je leren.',
    levels: ['B2'],
    category: 'Gezondheid',
  },
];
