import type { Level } from '../../types/content';

export type PromptCardStatus = 'saved' | 'wants_to_practice' | 'difficult' | 'practiced';

export interface PromptCard {
  id: string;
  title: string;
  theme: string;
  level: Extract<Level, 'A1' | 'A2' | 'B1'>;
  description: string;
  speakingGoal: string;
  questions: string[];
  usefulPhrases: string[];
  targetWords?: string[];
  tip?: string;
}

export interface ShadowingSentence {
  id: string;
  level: Extract<Level, 'A1' | 'A2' | 'B1'>;
  sentence: string;
  theme: string;
  tip: string;
  difficultWords?: string[];
  chunks?: string[];
}

export const PROMPT_CARD_STATUS_LABELS: Record<PromptCardStatus, string> = {
  saved: 'Opgeslagen',
  wants_to_practice: 'Dit wil ik oefenen',
  difficult: 'Dit vind ik moeilijk',
  practiced: 'Dit heb ik geoefend',
};

export const PROMPT_CARDS: PromptCard[] = [
  {
    id: 'introduce-yourself-a1',
    title: 'Jezelf voorstellen',
    theme: 'Kennismaken',
    level: 'A1',
    description: 'Vertel kort wie je bent en waar je vandaan komt.',
    speakingGoal: 'Oefen een simpele introductie in het Nederlands.',
    questions: [
      'Hoe heet je?',
      'Waar woon je?',
      'Uit welk land kom je?',
      'Wat vind je leuk om te doen?',
    ],
    usefulPhrases: ['Ik heet…', 'Ik woon in…', 'Ik kom uit…'],
    targetWords: ['naam', 'woonplaats', 'land'],
    tip: 'Laat het taalmaatje dezelfde zinnen meerdere keren rustig herhalen.',
  },
  {
    id: 'family-a1',
    title: 'Familie',
    theme: 'Familie',
    level: 'A1',
    description: 'Praat over mensen in je familie.',
    speakingGoal: 'Oefen korte zinnen over familieleden.',
    questions: [
      'Heb je familie in Nederland?',
      'Wie woont er bij jou thuis?',
      'Heb je broers of zussen?',
      'Wie zie je vaak?',
    ],
    usefulPhrases: ['Mijn familie is…', 'Ik heb…', 'Bij mij thuis wonen…'],
    targetWords: ['moeder', 'vader', 'kinderen'],
  },
  {
    id: 'living-a1',
    title: 'Wonen',
    theme: 'Wonen',
    level: 'A1',
    description: 'Vertel over je huis en buurt.',
    speakingGoal: 'Oefen woorden voor wonen en de buurt.',
    questions: [
      'Waar woon je?',
      'Woon je in een huis of appartement?',
      'Is je buurt rustig?',
      'Wat is dichtbij jouw huis?',
    ],
    usefulPhrases: ['Ik woon in…', 'Mijn huis is…', 'In mijn buurt is…'],
    targetWords: ['huis', 'appartement', 'buurt'],
  },
  {
    id: 'food-drinks-a1',
    title: 'Eten en drinken',
    theme: 'Eten',
    level: 'A1',
    description: 'Praat over eten, drinken en wat je lekker vindt.',
    speakingGoal: 'Oefen voorkeuren en eenvoudige bestellingen.',
    questions: [
      'Wat eet je graag?',
      'Wat drink je graag?',
      'Wat eet je in de ochtend?',
      'Vind je Nederlands eten lekker?',
    ],
    usefulPhrases: ['Ik eet graag…', 'Ik drink…', 'Ik vind … lekker'],
    targetWords: ['brood', 'water', 'lekker'],
  },
  {
    id: 'groceries-a1',
    title: 'Boodschappen doen',
    theme: 'Boodschappen',
    level: 'A1',
    description: 'Oefen een gesprek in de supermarkt.',
    speakingGoal: 'Vraag waar iets ligt en zeg wat je wilt kopen.',
    questions: [
      'Wat koop je vandaag?',
      'Waar is de melk?',
      'Hoeveel kost dit?',
      'Heb je een tas nodig?',
    ],
    usefulPhrases: ['Ik zoek…', 'Waar ligt…?', 'Ik wil graag…'],
    targetWords: ['supermarkt', 'kopen', 'tas'],
  },
  {
    id: 'daily-routine-a1',
    title: 'Dagelijkse routine',
    theme: 'Dagelijks leven',
    level: 'A1',
    description: 'Vertel wat je op een normale dag doet.',
    speakingGoal: 'Oefen tijden en dagelijkse activiteiten.',
    questions: [
      'Hoe laat sta je op?',
      'Wat doe je in de ochtend?',
      'Wanneer eet je avondeten?',
      'Wat doe je in de avond?',
    ],
    usefulPhrases: ['Ik sta op om…', 'Daarna ga ik…', 'In de avond…'],
    targetWords: ['ochtend', 'middag', 'avond'],
  },
  {
    id: 'hobbies-a1',
    title: 'Hobby’s',
    theme: 'Vrije tijd',
    level: 'A1',
    description: 'Praat over wat je graag doet.',
    speakingGoal: 'Oefen zinnen met “ik hou van” en “ik vind leuk”.',
    questions: ['Wat doe je graag?', 'Sport je?', 'Kijk je graag tv?', 'Doe je iets met vrienden?'],
    usefulPhrases: ['Ik hou van…', 'Ik vind … leuk', 'In mijn vrije tijd…'],
    targetWords: ['hobby', 'sport', 'vrienden'],
  },
  {
    id: 'weather-a1',
    title: 'Weer',
    theme: 'Weer',
    level: 'A1',
    description: 'Praat over het weer vandaag.',
    speakingGoal: 'Oefen eenvoudige zinnen over temperatuur en regen.',
    questions: [
      'Hoe is het weer vandaag?',
      'Is het koud of warm?',
      'Regent het?',
      'Wat doe je bij mooi weer?',
    ],
    usefulPhrases: ['Het is koud', 'Het regent', 'Vandaag is het mooi weer'],
    targetWords: ['regen', 'zon', 'koud'],
  },
  {
    id: 'make-appointment-a2',
    title: 'Afspraak maken',
    theme: 'Afspraken',
    level: 'A2',
    description: 'Maak of verplaats een afspraak.',
    speakingGoal: 'Oefen beleefd vragen om een datum en tijd.',
    questions: [
      'Wanneer kunt u?',
      'Kan ik een afspraak maken?',
      'Kan de afspraak later?',
      'Hoe laat is de afspraak?',
    ],
    usefulPhrases: ['Ik wil graag een afspraak maken', 'Kan het op…?', 'Dat komt goed uit'],
    targetWords: ['afspraak', 'datum', 'tijd'],
    tip: 'Speel een kort telefoongesprek na.',
  },
  {
    id: 'public-transport-a2',
    title: 'Onderweg / OV',
    theme: 'Reizen',
    level: 'A2',
    description: 'Vraag de weg of praat over bus en trein.',
    speakingGoal: 'Oefen reizen met openbaar vervoer.',
    questions: [
      'Waar is het station?',
      'Welke bus moet ik nemen?',
      'Hoe laat vertrekt de trein?',
      'Waar moet ik uitstappen?',
    ],
    usefulPhrases: ['Ik zoek…', 'Welke bus gaat naar…?', 'Moet ik hier uitstappen?'],
    targetWords: ['station', 'halte', 'vertrekken'],
  },
  {
    id: 'shopping-a2',
    title: 'Winkelen',
    theme: 'Winkelen',
    level: 'A2',
    description: 'Oefen vragen stellen in een winkel.',
    speakingGoal: 'Vraag om maat, prijs en hulp.',
    questions: [
      'Heeft u deze in een andere maat?',
      'Hoeveel kost dit?',
      'Kan ik dit passen?',
      'Waar kan ik betalen?',
    ],
    usefulPhrases: ['Ik zoek…', 'Heeft u…?', 'Kan ik pinnen?'],
    targetWords: ['maat', 'prijs', 'passen'],
  },
  {
    id: 'restaurant-a2',
    title: 'Bestellen in een restaurant',
    theme: 'Restaurant',
    level: 'A2',
    description: 'Oefen eten of drinken bestellen.',
    speakingGoal: 'Oefen hoe je eten of drinken bestelt.',
    questions: [
      'Wat wil je bestellen?',
      'Wil je iets drinken?',
      'Hoe vraag je om de rekening?',
      'Is alles naar wens?',
    ],
    usefulPhrases: ['Ik wil graag…', 'Mag ik de menukaart?', 'Mag ik betalen?'],
    targetWords: ['menukaart', 'rekening', 'bestellen'],
    tip: 'Gebruik echte menuwoorden als extra woordenschat.',
  },
  {
    id: 'doctor-a2',
    title: 'Naar de huisarts',
    theme: 'Gezondheid',
    level: 'A2',
    description: 'Vertel eenvoudig wat er aan de hand is.',
    speakingGoal: 'Oefen klachten uitleggen en hulp vragen.',
    questions: [
      'Waar heeft u pijn?',
      'Sinds wanneer heeft u klachten?',
      'Heeft u koorts?',
      'Wilt u een afspraak maken?',
    ],
    usefulPhrases: ['Ik heb pijn aan…', 'Ik voel me…', 'Sinds gisteren…'],
    targetWords: ['huisarts', 'pijn', 'klacht'],
    tip: 'Houd het veilig en praktisch; vraag niet naar gevoelige details.',
  },
  {
    id: 'school-children-a2',
    title: 'School of kinderen',
    theme: 'School',
    level: 'A2',
    description: 'Praat over school, kinderen of een oudergesprek.',
    speakingGoal: 'Oefen vragen aan school of opvang.',
    questions: [
      'Hoe gaat het op school?',
      'Wanneer is de afspraak?',
      'Wat moet mijn kind meenemen?',
      'Kan ik de juf spreken?',
    ],
    usefulPhrases: ['Ik heb een vraag over…', 'Kunt u uitleggen…?', 'Mijn kind heeft…'],
    targetWords: ['school', 'juf', 'meenemen'],
  },
  {
    id: 'job-interview-b1',
    title: 'Werk zoeken / werkgesprek',
    theme: 'Werk',
    level: 'B1',
    description: 'Oefen praten over ervaring en werk zoeken.',
    speakingGoal: 'Vertel waarom je een baan wilt en wat je kunt.',
    questions: [
      'Wat voor werk zoekt u?',
      'Welke ervaring heeft u?',
      'Waarom past deze baan bij u?',
      'Wanneer kunt u beginnen?',
    ],
    usefulPhrases: ['Ik heb ervaring met…', 'Ik ben goed in…', 'Ik wil graag werken als…'],
    targetWords: ['ervaring', 'solliciteren', 'beschikbaar'],
  },
  {
    id: 'municipality-b1',
    title: 'Gemeente',
    theme: 'Gemeente',
    level: 'B1',
    description: 'Oefen vragen stellen aan de gemeente.',
    speakingGoal: 'Leg uit waarvoor je komt en welke hulp je nodig hebt.',
    questions: [
      'Waarvoor komt u vandaag?',
      'Heeft u een afspraak?',
      'Welk formulier heeft u nodig?',
      'Kunt u dit uitleggen?',
    ],
    usefulPhrases: ['Ik kom voor…', 'Ik heb hulp nodig bij…', 'Kunt u mij helpen met…'],
    targetWords: ['formulier', 'loket', 'afspraak'],
  },
  {
    id: 'neighbours-b1',
    title: 'Buren',
    theme: 'Buurt',
    level: 'B1',
    description: 'Oefen vriendelijk praten met buren.',
    speakingGoal: 'Vertel iets, vraag iets of bespreek een probleem rustig.',
    questions: [
      'Hoe groet je je buren?',
      'Hoe vraag je om hulp?',
      'Hoe leg je uit dat er geluidsoverlast is?',
      'Hoe maak je een afspraak met buren?',
    ],
    usefulPhrases: [
      'Mag ik u iets vragen?',
      'Zou het misschien kunnen dat…?',
      'Dank u voor uw begrip',
    ],
    targetWords: ['buren', 'overlast', 'begrip'],
  },
  {
    id: 'phone-call-b1',
    title: 'Telefoneren',
    theme: 'Telefoneren',
    level: 'B1',
    description: 'Oefen een kort telefoongesprek.',
    speakingGoal: 'Begin, vraag door en sluit een gesprek netjes af.',
    questions: [
      'Met wie spreek ik?',
      'Kunt u dat herhalen?',
      'Waar gaat het over?',
      'Kan ik later terugbellen?',
    ],
    usefulPhrases: ['U spreekt met…', 'Kunt u wat langzamer praten?', 'Bedankt voor uw hulp'],
    targetWords: ['herhalen', 'terugbellen', 'gesprek'],
  },
  {
    id: 'explain-complaint-b1',
    title: 'Klacht uitleggen',
    theme: 'Probleem uitleggen',
    level: 'B1',
    description: 'Leg rustig uit wat er niet goed gaat.',
    speakingGoal: 'Oefen een probleem helder en beleefd uitleggen.',
    questions: [
      'Wat is het probleem?',
      'Wanneer is het begonnen?',
      'Wat wilt u dat er gebeurt?',
      'Met wie heeft u al gesproken?',
    ],
    usefulPhrases: [
      'Ik wil graag uitleggen wat er is gebeurd',
      'Het probleem is…',
      'Ik hoop dat u kunt helpen',
    ],
    targetWords: ['klacht', 'oplossing', 'gebeurd'],
  },
  {
    id: 'give-opinion-b1',
    title: 'Mening geven',
    theme: 'Mening',
    level: 'B1',
    description: 'Vertel wat je vindt en waarom.',
    speakingGoal: 'Oefen je mening geven met een reden.',
    questions: [
      'Wat vind je hiervan?',
      'Waarom vind je dat?',
      'Ben je het ermee eens?',
      'Wat is volgens jou een goede oplossing?',
    ],
    usefulPhrases: ['Ik vind dat…', 'Volgens mij…', 'Omdat…'],
    targetWords: ['mening', 'reden', 'oplossing'],
  },
];

export const SHADOWING_SENTENCES: ShadowingSentence[] = [
  {
    id: 'a1-name',
    level: 'A1',
    sentence: 'Ik heet Maria.',
    theme: 'Kennismaken',
    tip: 'Spreek langzaam: Ik — heet — Maria.',
    difficultWords: ['heet'],
    chunks: ['Ik heet', 'Maria'],
  },
  {
    id: 'a1-live',
    level: 'A1',
    sentence: 'Ik woon in Leiden.',
    theme: 'Wonen',
    tip: 'Let op de korte klank in “woon”.',
    difficultWords: ['woon'],
    chunks: ['Ik woon', 'in Leiden'],
  },
  {
    id: 'a1-shop',
    level: 'A1',
    sentence: 'Ik ga naar de winkel.',
    theme: 'Boodschappen',
    tip: 'Zeg “naar de” als één rustig stukje.',
    difficultWords: ['winkel'],
    chunks: ['Ik ga', 'naar de winkel'],
  },
  {
    id: 'a1-water',
    level: 'A1',
    sentence: 'Mag ik water?',
    theme: 'Restaurant',
    tip: 'Maak van je stem een vraag aan het einde.',
    difficultWords: ['water'],
    chunks: ['Mag ik', 'water?'],
  },
  {
    id: 'a1-weather',
    level: 'A1',
    sentence: 'Vandaag is het mooi weer.',
    theme: 'Weer',
    tip: 'Begin rustig met “Vandaag”.',
    difficultWords: ['vandaag'],
    chunks: ['Vandaag', 'is het mooi weer'],
  },
  {
    id: 'a2-appointment',
    level: 'A2',
    sentence: 'Ik wil graag een afspraak maken.',
    theme: 'Afspraken',
    tip: 'Oefen eerst “Ik wil graag”, daarna de hele zin.',
    difficultWords: ['afspraak'],
    chunks: ['Ik wil graag', 'een afspraak maken'],
  },
  {
    id: 'a2-repeat',
    level: 'A2',
    sentence: 'Kunt u dat nog een keer zeggen?',
    theme: 'Telefoneren',
    tip: 'Spreek beleefd en rustig.',
    difficultWords: ['nog een keer'],
    chunks: ['Kunt u dat', 'nog een keer zeggen?'],
  },
  {
    id: 'a2-supermarket',
    level: 'A2',
    sentence: 'Ik zoek de supermarkt.',
    theme: 'Onderweg',
    tip: 'Laat “zoek” duidelijk klinken.',
    difficultWords: ['zoek'],
    chunks: ['Ik zoek', 'de supermarkt'],
  },
  {
    id: 'a2-worked',
    level: 'A2',
    sentence: 'Ik heb gisteren gewerkt.',
    theme: 'Werk',
    tip: 'Let op het einde van “gewerkt”.',
    difficultWords: ['gisteren', 'gewerkt'],
    chunks: ['Ik heb gisteren', 'gewerkt'],
  },
  {
    id: 'a2-bill',
    level: 'A2',
    sentence: 'Mag ik de rekening alstublieft?',
    theme: 'Restaurant',
    tip: 'Zeg “alstublieft” rustig in stukjes.',
    difficultWords: ['rekening', 'alstublieft'],
    chunks: ['Mag ik de rekening', 'alstublieft?'],
  },
  {
    id: 'b1-practice',
    level: 'B1',
    sentence: 'Ik vind het belangrijk om Nederlands te oefenen.',
    theme: 'Leren',
    tip: 'Leg nadruk op “belangrijk”.',
    difficultWords: ['belangrijk'],
    chunks: ['Ik vind het belangrijk', 'om Nederlands te oefenen'],
  },
  {
    id: 'b1-child-sick',
    level: 'B1',
    sentence: 'Ik kon niet komen, omdat mijn kind ziek was.',
    theme: 'Afspraak',
    tip: 'Pauzeer kort na de komma.',
    difficultWords: ['omdat'],
    chunks: ['Ik kon niet komen', 'omdat mijn kind ziek was'],
  },
  {
    id: 'b1-explain',
    level: 'B1',
    sentence: 'Ik wil graag uitleggen wat er is gebeurd.',
    theme: 'Probleem uitleggen',
    tip: 'Spreek “uitleggen” langzaam uit.',
    difficultWords: ['uitleggen', 'gebeurd'],
    chunks: ['Ik wil graag uitleggen', 'wat er is gebeurd'],
  },
  {
    id: 'b1-solution',
    level: 'B1',
    sentence: 'Volgens mij is dit een goede oplossing.',
    theme: 'Mening',
    tip: 'Begin rustig met “Volgens mij”.',
    difficultWords: ['volgens mij', 'oplossing'],
    chunks: ['Volgens mij', 'is dit een goede oplossing'],
  },
  {
    id: 'b1-form',
    level: 'B1',
    sentence: 'Ik heb hulp nodig bij het invullen van dit formulier.',
    theme: 'Gemeente',
    tip: 'Oefen “invullen van dit formulier” apart.',
    difficultWords: ['invullen', 'formulier'],
    chunks: ['Ik heb hulp nodig', 'bij het invullen van dit formulier'],
  },
];
