import type { WieWatCard } from '../../types/content';

export const WIEWAT_CARDS: WieWatCard[] = [
  // ── Beroep ──────────────────────────────────────────────────────────────
  { id: 'ww-b-dokter', word: 'Dokter', category: 'Beroep', emoji: '🩺' },
  { id: 'ww-b-leraar', word: 'Leraar', category: 'Beroep', emoji: '📚' },
  { id: 'ww-b-bakker', word: 'Bakker', category: 'Beroep', emoji: '🍞' },
  { id: 'ww-b-agent', word: 'Politieagent', category: 'Beroep', emoji: '👮' },
  { id: 'ww-b-tandarts', word: 'Tandarts', category: 'Beroep', emoji: '🦷' },
  { id: 'ww-b-brandweer', word: 'Brandweerman', category: 'Beroep', emoji: '🚒' },
  { id: 'ww-b-verpleeg', word: 'Verpleegkundige', category: 'Beroep', emoji: '💉' },
  { id: 'ww-b-kok', word: 'Kok', category: 'Beroep', emoji: '👨‍🍳' },
  { id: 'ww-b-piloot', word: 'Piloot', category: 'Beroep', emoji: '✈️' },
  { id: 'ww-b-schrijver', word: 'Schrijver', category: 'Beroep', emoji: '✍️' },
  { id: 'ww-b-timmerman', word: 'Timmerman', category: 'Beroep', emoji: '🔨' },
  { id: 'ww-b-fotograaf', word: 'Fotograaf', category: 'Beroep', emoji: '📷' },
  { id: 'ww-b-chauffeur', word: 'Chauffeur', category: 'Beroep', emoji: '🚌' },
  { id: 'ww-b-dierenarts', word: 'Dierenarts', category: 'Beroep', emoji: '🐾' },
  { id: 'ww-b-journalist', word: 'Journalist', category: 'Beroep', emoji: '📰' },
  { id: 'ww-b-schilder', word: 'Schilder', category: 'Beroep', emoji: '🎨' },
  { id: 'ww-b-kapper', word: 'Kapper', category: 'Beroep', emoji: '✂️' },
  { id: 'ww-b-boer', word: 'Boer', category: 'Beroep', emoji: '🚜' },
  { id: 'ww-b-rechter', word: 'Rechter', category: 'Beroep', emoji: '⚖️' },
  { id: 'ww-b-bibliotheek', word: 'Bibliotheekmedewerker', category: 'Beroep', emoji: '📖' },

  // ── Dier ────────────────────────────────────────────────────────────────
  { id: 'ww-d-hond', word: 'Hond', category: 'Dier', emoji: '🐕' },
  { id: 'ww-d-kat', word: 'Kat', category: 'Dier', emoji: '🐈' },
  { id: 'ww-d-olifant', word: 'Olifant', category: 'Dier', emoji: '🐘' },
  { id: 'ww-d-leeuw', word: 'Leeuw', category: 'Dier', emoji: '🦁' },
  { id: 'ww-d-tijger', word: 'Tijger', category: 'Dier', emoji: '🐯' },
  { id: 'ww-d-giraffe', word: 'Giraffe', category: 'Dier', emoji: '🦒' },
  { id: 'ww-d-aap', word: 'Aap', category: 'Dier', emoji: '🐒' },
  { id: 'ww-d-paard', word: 'Paard', category: 'Dier', emoji: '🐴' },
  { id: 'ww-d-koe', word: 'Koe', category: 'Dier', emoji: '🐄' },
  { id: 'ww-d-kip', word: 'Kip', category: 'Dier', emoji: '🐔' },
  { id: 'ww-d-haai', word: 'Haai', category: 'Dier', emoji: '🦈' },
  { id: 'ww-d-dolfijn', word: 'Dolfijn', category: 'Dier', emoji: '🐬' },
  { id: 'ww-d-konijn', word: 'Konijn', category: 'Dier', emoji: '🐇' },
  { id: 'ww-d-slang', word: 'Slang', category: 'Dier', emoji: '🐍' },
  { id: 'ww-d-arend', word: 'Arend', category: 'Dier', emoji: '🦅' },
  { id: 'ww-d-nijlpaard', word: 'Nijlpaard', category: 'Dier', emoji: '🦛' },
  { id: 'ww-d-beer', word: 'Beer', category: 'Dier', emoji: '🐻' },
  { id: 'ww-d-vos', word: 'Vos', category: 'Dier', emoji: '🦊' },
  { id: 'ww-d-uil', word: 'Uil', category: 'Dier', emoji: '🦉' },
  { id: 'ww-d-pinguin', word: 'Pinguïn', category: 'Dier', emoji: '🐧' },

  // ── Voorwerp ────────────────────────────────────────────────────────────
  { id: 'ww-v-stoel', word: 'Stoel', category: 'Voorwerp', emoji: '🪑' },
  { id: 'ww-v-fiets', word: 'Fiets', category: 'Voorwerp', emoji: '🚲' },
  { id: 'ww-v-telefoon', word: 'Telefoon', category: 'Voorwerp', emoji: '📱' },
  { id: 'ww-v-boek', word: 'Boek', category: 'Voorwerp', emoji: '📕' },
  { id: 'ww-v-bril', word: 'Bril', category: 'Voorwerp', emoji: '👓' },
  { id: 'ww-v-sleutel', word: 'Sleutel', category: 'Voorwerp', emoji: '🔑' },
  { id: 'ww-v-paraplu', word: 'Paraplu', category: 'Voorwerp', emoji: '☂️' },
  { id: 'ww-v-spiegel', word: 'Spiegel', category: 'Voorwerp', emoji: '🪞' },
  { id: 'ww-v-koffer', word: 'Koffer', category: 'Voorwerp', emoji: '🧳' },
  { id: 'ww-v-gitaar', word: 'Gitaar', category: 'Voorwerp', emoji: '🎸' },
  { id: 'ww-v-camera', word: 'Camera', category: 'Voorwerp', emoji: '📷' },
  { id: 'ww-v-schaar', word: 'Schaar', category: 'Voorwerp', emoji: '✂️' },
  { id: 'ww-v-zaklamp', word: 'Zaklamp', category: 'Voorwerp', emoji: '🔦' },
  { id: 'ww-v-emmer', word: 'Emmer', category: 'Voorwerp', emoji: '🪣' },
  { id: 'ww-v-horloge', word: 'Horloge', category: 'Voorwerp', emoji: '⌚' },
  { id: 'ww-v-ballon', word: 'Ballon', category: 'Voorwerp', emoji: '🎈' },
  { id: 'ww-v-kompas', word: 'Kompas', category: 'Voorwerp', emoji: '🧭' },
  { id: 'ww-v-thermometer', word: 'Thermometer', category: 'Voorwerp', emoji: '🌡️' },
  { id: 'ww-v-ladder', word: 'Ladder', category: 'Voorwerp', emoji: '🪜' },
  { id: 'ww-v-tandenborstel', word: 'Tandenborstel', category: 'Voorwerp', emoji: '🪥' },

  // ── Persoon ─────────────────────────────────────────────────────────────
  { id: 'ww-p-einstein', word: 'Albert Einstein', category: 'Persoon', emoji: '🧠' },
  { id: 'ww-p-mandela', word: 'Nelson Mandela', category: 'Persoon', emoji: '✊' },
  { id: 'ww-p-vangogh', word: 'Vincent van Gogh', category: 'Persoon', emoji: '🎨' },
  { id: 'ww-p-annefrank', word: 'Anne Frank', category: 'Persoon', emoji: '📔' },
  { id: 'ww-p-sinterklaas', word: 'Sinterklaas', category: 'Persoon', emoji: '🎅' },
  { id: 'ww-p-maxima', word: 'Koningin Máxima', category: 'Persoon', emoji: '👑' },
  { id: 'ww-p-rembrandt', word: 'Rembrandt', category: 'Persoon', emoji: '🖼️' },
  { id: 'ww-p-obama', word: 'Barack Obama', category: 'Persoon', emoji: '🇺🇸' },
  { id: 'ww-p-cleopatra', word: 'Cleopatra', category: 'Persoon', emoji: '🏺' },
  { id: 'ww-p-shakespeare', word: 'Shakespeare', category: 'Persoon', emoji: '🎭' },
  { id: 'ww-p-napoleon', word: 'Napoleon', category: 'Persoon', emoji: '⚔️' },
  { id: 'ww-p-mozart', word: 'Mozart', category: 'Persoon', emoji: '🎵' },
  { id: 'ww-p-darwin', word: 'Charles Darwin', category: 'Persoon', emoji: '🐒' },
  { id: 'ww-p-mariecurie', word: 'Marie Curie', category: 'Persoon', emoji: '⚗️' },
  { id: 'ww-p-cruyff', word: 'Johan Cruyff', category: 'Persoon', emoji: '⚽' },

  // ── Eten ────────────────────────────────────────────────────────────────
  { id: 'ww-e-stroopwafel', word: 'Stroopwafel', category: 'Eten', emoji: '🍪' },
  { id: 'ww-e-pizza', word: 'Pizza', category: 'Eten', emoji: '🍕' },
  { id: 'ww-e-sushi', word: 'Sushi', category: 'Eten', emoji: '🍣' },
  { id: 'ww-e-patat', word: 'Patat', category: 'Eten', emoji: '🍟' },
  { id: 'ww-e-kaas', word: 'Kaas', category: 'Eten', emoji: '🧀' },
  { id: 'ww-e-chocolade', word: 'Chocolade', category: 'Eten', emoji: '🍫' },
  { id: 'ww-e-appel', word: 'Appel', category: 'Eten', emoji: '🍎' },
  { id: 'ww-e-brood', word: 'Brood', category: 'Eten', emoji: '🍞' },
  { id: 'ww-e-soep', word: 'Soep', category: 'Eten', emoji: '🍲' },
  { id: 'ww-e-koffie', word: 'Koffie', category: 'Eten', emoji: '☕' },
  { id: 'ww-e-aardappel', word: 'Aardappel', category: 'Eten', emoji: '🥔' },
  { id: 'ww-e-haring', word: 'Haring', category: 'Eten', emoji: '🐟' },
  { id: 'ww-e-pannenkoek', word: 'Pannenkoek', category: 'Eten', emoji: '🥞' },
  { id: 'ww-e-tomaat', word: 'Tomaat', category: 'Eten', emoji: '🍅' },
  { id: 'ww-e-ijs', word: 'Ijs', category: 'Eten', emoji: '🍦' },
  { id: 'ww-e-banaan', word: 'Banaan', category: 'Eten', emoji: '🍌' },
  { id: 'ww-e-ei', word: 'Ei', category: 'Eten', emoji: '🥚' },
  { id: 'ww-e-worst', word: 'Worst', category: 'Eten', emoji: '🌭' },
  { id: 'ww-e-rijst', word: 'Rijst', category: 'Eten', emoji: '🍚' },
  { id: 'ww-e-yoghurt', word: 'Yoghurt', category: 'Eten', emoji: '🥛' },

  // ── Plek ────────────────────────────────────────────────────────────────
  { id: 'ww-pl-strand', word: 'Strand', category: 'Plek', emoji: '🏖️' },
  { id: 'ww-pl-station', word: 'Station', category: 'Plek', emoji: '🚉' },
  { id: 'ww-pl-ziekenhuis', word: 'Ziekenhuis', category: 'Plek', emoji: '🏥' },
  { id: 'ww-pl-park', word: 'Park', category: 'Plek', emoji: '🌳' },
  { id: 'ww-pl-restaurant', word: 'Restaurant', category: 'Plek', emoji: '🍽️' },
  { id: 'ww-pl-bibliotheek', word: 'Bibliotheek', category: 'Plek', emoji: '📚' },
  { id: 'ww-pl-vliegveld', word: 'Vliegveld', category: 'Plek', emoji: '✈️' },
  { id: 'ww-pl-museum', word: 'Museum', category: 'Plek', emoji: '🖼️' },
  { id: 'ww-pl-dierentuin', word: 'Dierentuin', category: 'Plek', emoji: '🦓' },
  { id: 'ww-pl-bioscoop', word: 'Bioscoop', category: 'Plek', emoji: '🎬' },
  { id: 'ww-pl-supermarkt', word: 'Supermarkt', category: 'Plek', emoji: '🛒' },
  { id: 'ww-pl-kerk', word: 'Kerk', category: 'Plek', emoji: '⛪' },
  { id: 'ww-pl-markt', word: 'Markt', category: 'Plek', emoji: '🏪' },
  { id: 'ww-pl-school', word: 'School', category: 'Plek', emoji: '🏫' },
  { id: 'ww-pl-apotheek', word: 'Apotheek', category: 'Plek', emoji: '💊' },
];
