import type { WordPrompt } from '../../types/content';

export const WORD_PROMPTS: WordPrompt[] = [
  // ══ BUURT ════════════════════════════════════════════════════════════════
  // A1
  { id: 'wp-a1-buurt-01', word: 'straat', emoji: '🛣️', levels: ['A1'], category: 'Buurt' },
  { id: 'wp-a1-buurt-02', word: 'winkel', emoji: '🏪', levels: ['A1'], category: 'Buurt' },
  { id: 'wp-a1-buurt-03', word: 'park', emoji: '🌳', levels: ['A1'], category: 'Buurt' },
  { id: 'wp-a1-buurt-04', word: 'school', emoji: '🏫', levels: ['A1'], category: 'Buurt' },
  { id: 'wp-a1-buurt-05', word: 'fiets', emoji: '🚲', levels: ['A1'], category: 'Buurt' },
  { id: 'wp-a1-buurt-06', word: 'bus', emoji: '🚌', levels: ['A1'], category: 'Buurt' },
  { id: 'wp-a1-buurt-07', word: 'markt', emoji: '🛒', levels: ['A1'], category: 'Buurt' },
  { id: 'wp-a1-buurt-08', word: 'buur', emoji: '🧑', levels: ['A1'], category: 'Buurt' },
  { id: 'wp-a1-buurt-09', word: 'plein', emoji: '⛲', levels: ['A1'], category: 'Buurt' },
  { id: 'wp-a1-buurt-10', word: 'stad', emoji: '🏙️', levels: ['A1'], category: 'Buurt' },
  // A2
  { id: 'wp-a2-buurt-01', word: 'supermarkt', emoji: '🛒', levels: ['A2'], category: 'Buurt' },
  { id: 'wp-a2-buurt-02', word: 'bibliotheek', emoji: '📚', levels: ['A2'], category: 'Buurt' },
  { id: 'wp-a2-buurt-03', word: 'speeltuin', emoji: '🛝', levels: ['A2'], category: 'Buurt' },
  { id: 'wp-a2-buurt-04', word: 'kerk', emoji: '⛪', levels: ['A2'], category: 'Buurt' },
  { id: 'wp-a2-buurt-05', word: 'station', emoji: '🚉', levels: ['A2'], category: 'Buurt' },
  { id: 'wp-a2-buurt-06', word: 'brug', emoji: '🌉', levels: ['A2'], category: 'Buurt' },
  { id: 'wp-a2-buurt-07', word: 'gracht', emoji: '🛶', levels: ['A2'], category: 'Buurt' },
  { id: 'wp-a2-buurt-08', word: 'wijk', emoji: '🏘️', levels: ['A2'], category: 'Buurt' },
  { id: 'wp-a2-buurt-09', word: 'apotheek', emoji: '💊', levels: ['A2'], category: 'Buurt' },
  { id: 'wp-a2-buurt-10', word: 'museum', emoji: '🏛️', levels: ['A2'], category: 'Buurt' },
  // B1
  { id: 'wp-b1-buurt-01', word: 'gemeente', levels: ['B1'], category: 'Buurt' },
  { id: 'wp-b1-buurt-02', word: 'voorzieningen', levels: ['B1'], category: 'Buurt' },
  { id: 'wp-b1-buurt-03', word: 'verkeer', emoji: '🚦', levels: ['B1'], category: 'Buurt' },
  { id: 'wp-b1-buurt-04', word: 'omgeving', levels: ['B1'], category: 'Buurt' },
  { id: 'wp-b1-buurt-05', word: 'geluidsoverlast', emoji: '🔊', levels: ['B1'], category: 'Buurt' },
  { id: 'wp-b1-buurt-06', word: 'buurtfeest', emoji: '🎉', levels: ['B1'], category: 'Buurt' },
  { id: 'wp-b1-buurt-07', word: 'openbaar vervoer', emoji: '🚌', levels: ['B1'], category: 'Buurt' },
  { id: 'wp-b1-buurt-08', word: 'veiligheid', emoji: '🛡️', levels: ['B1'], category: 'Buurt' },
  { id: 'wp-b1-buurt-09', word: 'nieuwbouw', emoji: '🏗️', levels: ['B1'], category: 'Buurt' },
  { id: 'wp-b1-buurt-10', word: 'groenvoorziening', emoji: '🌳', levels: ['B1'], category: 'Buurt' },
  // B2
  { id: 'wp-b2-buurt-01', word: 'leefbaarheid', levels: ['B2'], category: 'Buurt' },
  { id: 'wp-b2-buurt-02', word: 'gemeenschap', levels: ['B2'], category: 'Buurt' },
  { id: 'wp-b2-buurt-03', word: 'infrastructuur', levels: ['B2'], category: 'Buurt' },
  { id: 'wp-b2-buurt-04', word: 'sociale cohesie', levels: ['B2'], category: 'Buurt' },
  { id: 'wp-b2-buurt-05', word: 'stadsontwikkeling', levels: ['B2'], category: 'Buurt' },
  { id: 'wp-b2-buurt-06', word: 'anonimiteit', levels: ['B2'], category: 'Buurt' },
  { id: 'wp-b2-buurt-07', word: 'segregatie', levels: ['B2'], category: 'Buurt' },
  { id: 'wp-b2-buurt-08', word: 'burgerinitiatief', levels: ['B2'], category: 'Buurt' },
  { id: 'wp-b2-buurt-09', word: 'duurzaamheid', levels: ['B2'], category: 'Buurt' },
  { id: 'wp-b2-buurt-10', word: 'verloedering', levels: ['B2'], category: 'Buurt' },

  // ══ FAMILIE ══════════════════════════════════════════════════════════════
  // A1
  { id: 'wp-a1-familie-01', word: 'moeder', emoji: '👩', levels: ['A1'], category: 'Familie' },
  { id: 'wp-a1-familie-02', word: 'vader', emoji: '👨', levels: ['A1'], category: 'Familie' },
  { id: 'wp-a1-familie-03', word: 'kind', emoji: '🧒', levels: ['A1'], category: 'Familie' },
  { id: 'wp-a1-familie-04', word: 'broer', emoji: '👦', levels: ['A1'], category: 'Familie' },
  { id: 'wp-a1-familie-05', word: 'zus', emoji: '👧', levels: ['A1'], category: 'Familie' },
  { id: 'wp-a1-familie-06', word: 'oma', emoji: '👵', levels: ['A1'], category: 'Familie' },
  { id: 'wp-a1-familie-07', word: 'opa', emoji: '👴', levels: ['A1'], category: 'Familie' },
  { id: 'wp-a1-familie-08', word: 'baby', emoji: '👶', levels: ['A1'], category: 'Familie' },
  { id: 'wp-a1-familie-09', word: 'foto', emoji: '📷', levels: ['A1'], category: 'Familie' },
  { id: 'wp-a1-familie-10', word: 'familie', emoji: '👨‍👩‍👧', levels: ['A1'], category: 'Familie' },
  // A2
  { id: 'wp-a2-familie-01', word: 'verjaardag', emoji: '🎂', levels: ['A2'], category: 'Familie' },
  { id: 'wp-a2-familie-02', word: 'vriend', emoji: '🤝', levels: ['A2'], category: 'Familie' },
  { id: 'wp-a2-familie-03', word: 'neef', emoji: '👦', levels: ['A2'], category: 'Familie' },
  { id: 'wp-a2-familie-04', word: 'nicht', emoji: '👧', levels: ['A2'], category: 'Familie' },
  { id: 'wp-a2-familie-05', word: 'oom', emoji: '🧔', levels: ['A2'], category: 'Familie' },
  { id: 'wp-a2-familie-06', word: 'tante', emoji: '👩', levels: ['A2'], category: 'Familie' },
  { id: 'wp-a2-familie-07', word: 'bruiloft', emoji: '💒', levels: ['A2'], category: 'Familie' },
  { id: 'wp-a2-familie-08', word: 'cadeau', emoji: '🎁', levels: ['A2'], category: 'Familie' },
  { id: 'wp-a2-familie-09', word: 'gezin', emoji: '👪', levels: ['A2'], category: 'Familie' },
  { id: 'wp-a2-familie-10', word: 'buurvrouw', emoji: '👩', levels: ['A2'], category: 'Familie' },
  // B1
  { id: 'wp-b1-familie-01', word: 'opvoeding', levels: ['B1'], category: 'Familie' },
  { id: 'wp-b1-familie-02', word: 'traditie', levels: ['B1'], category: 'Familie' },
  { id: 'wp-b1-familie-03', word: 'generatie', levels: ['B1'], category: 'Familie' },
  { id: 'wp-b1-familie-04', word: 'vriendschap', levels: ['B1'], category: 'Familie' },
  { id: 'wp-b1-familie-05', word: 'vertrouwen', levels: ['B1'], category: 'Familie' },
  { id: 'wp-b1-familie-06', word: 'herinnering', levels: ['B1'], category: 'Familie' },
  { id: 'wp-b1-familie-07', word: 'afscheid', levels: ['B1'], category: 'Familie' },
  { id: 'wp-b1-familie-08', word: 'steun', levels: ['B1'], category: 'Familie' },
  { id: 'wp-b1-familie-09', word: 'respect', levels: ['B1'], category: 'Familie' },
  { id: 'wp-b1-familie-10', word: 'relatie', levels: ['B1'], category: 'Familie' },
  // B2
  { id: 'wp-b2-familie-01', word: 'identiteit', levels: ['B2'], category: 'Familie' },
  { id: 'wp-b2-familie-02', word: 'loyaliteit', levels: ['B2'], category: 'Familie' },
  { id: 'wp-b2-familie-03', word: 'verwachtingen', levels: ['B2'], category: 'Familie' },
  { id: 'wp-b2-familie-04', word: 'verbondenheid', levels: ['B2'], category: 'Familie' },
  { id: 'wp-b2-familie-05', word: 'conflict', levels: ['B2'], category: 'Familie' },
  { id: 'wp-b2-familie-06', word: 'intimiteit', levels: ['B2'], category: 'Familie' },
  { id: 'wp-b2-familie-07', word: 'vervreemding', levels: ['B2'], category: 'Familie' },
  { id: 'wp-b2-familie-08', word: 'rolverdeling', levels: ['B2'], category: 'Familie' },
  { id: 'wp-b2-familie-09', word: 'vergeving', levels: ['B2'], category: 'Familie' },
  { id: 'wp-b2-familie-10', word: 'opoffering', levels: ['B2'], category: 'Familie' },

  // ══ WERK ═════════════════════════════════════════════════════════════════
  // A1
  { id: 'wp-a1-werk-01', word: 'school', emoji: '🏫', levels: ['A1'], category: 'Werk' },
  { id: 'wp-a1-werk-02', word: 'werk', emoji: '💼', levels: ['A1'], category: 'Werk' },
  { id: 'wp-a1-werk-03', word: 'baas', emoji: '🧑‍💼', levels: ['A1'], category: 'Werk' },
  { id: 'wp-a1-werk-04', word: 'geld', emoji: '💶', levels: ['A1'], category: 'Werk' },
  { id: 'wp-a1-werk-05', word: 'pen', emoji: '🖊️', levels: ['A1'], category: 'Werk' },
  { id: 'wp-a1-werk-06', word: 'boek', emoji: '📖', levels: ['A1'], category: 'Werk' },
  { id: 'wp-a1-werk-07', word: 'klas', emoji: '🧑‍🏫', levels: ['A1'], category: 'Werk' },
  { id: 'wp-a1-werk-08', word: 'les', emoji: '📝', levels: ['A1'], category: 'Werk' },
  { id: 'wp-a1-werk-09', word: 'computer', emoji: '💻', levels: ['A1'], category: 'Werk' },
  { id: 'wp-a1-werk-10', word: 'taak', emoji: '✅', levels: ['A1'], category: 'Werk' },
  // A2
  { id: 'wp-a2-werk-01', word: 'collega', emoji: '🧑‍🤝‍🧑', levels: ['A2'], category: 'Werk' },
  { id: 'wp-a2-werk-02', word: 'sollicitatie', emoji: '📋', levels: ['A2'], category: 'Werk' },
  { id: 'wp-a2-werk-03', word: 'salaris', emoji: '💰', levels: ['A2'], category: 'Werk' },
  { id: 'wp-a2-werk-04', word: 'pauze', emoji: '☕', levels: ['A2'], category: 'Werk' },
  { id: 'wp-a2-werk-05', word: 'kantoor', emoji: '🏢', levels: ['A2'], category: 'Werk' },
  { id: 'wp-a2-werk-06', word: 'diploma', emoji: '🎓', levels: ['A2'], category: 'Werk' },
  { id: 'wp-a2-werk-07', word: 'beroep', emoji: '🧰', levels: ['A2'], category: 'Werk' },
  { id: 'wp-a2-werk-08', word: 'contract', emoji: '📄', levels: ['A2'], category: 'Werk' },
  { id: 'wp-a2-werk-09', word: 'cursus', emoji: '📚', levels: ['A2'], category: 'Werk' },
  { id: 'wp-a2-werk-10', word: 'afspraak', emoji: '📅', levels: ['A2'], category: 'Werk' },
  // B1
  { id: 'wp-b1-werk-01', word: 'carrière', levels: ['B1'], category: 'Werk' },
  { id: 'wp-b1-werk-02', word: 'motivatie', levels: ['B1'], category: 'Werk' },
  { id: 'wp-b1-werk-03', word: 'samenwerking', levels: ['B1'], category: 'Werk' },
  { id: 'wp-b1-werk-04', word: 'deadline', levels: ['B1'], category: 'Werk' },
  { id: 'wp-b1-werk-05', word: 'vaardigheid', levels: ['B1'], category: 'Werk' },
  { id: 'wp-b1-werk-06', word: 'ervaring', levels: ['B1'], category: 'Werk' },
  { id: 'wp-b1-werk-07', word: 'ambitie', levels: ['B1'], category: 'Werk' },
  { id: 'wp-b1-werk-08', word: 'werkdruk', levels: ['B1'], category: 'Werk' },
  { id: 'wp-b1-werk-09', word: 'opleiding', levels: ['B1'], category: 'Werk' },
  { id: 'wp-b1-werk-10', word: 'feedback', levels: ['B1'], category: 'Werk' },
  // B2
  { id: 'wp-b2-werk-01', word: 'arbeidsmarkt', levels: ['B2'], category: 'Werk' },
  { id: 'wp-b2-werk-02', word: 'automatisering', levels: ['B2'], category: 'Werk' },
  { id: 'wp-b2-werk-03', word: 'professionaliteit', levels: ['B2'], category: 'Werk' },
  { id: 'wp-b2-werk-04', word: 'werkethiek', levels: ['B2'], category: 'Werk' },
  { id: 'wp-b2-werk-05', word: 'ondernemerschap', levels: ['B2'], category: 'Werk' },
  { id: 'wp-b2-werk-06', word: 'hiërarchie', levels: ['B2'], category: 'Werk' },
  { id: 'wp-b2-werk-07', word: 'productiviteit', levels: ['B2'], category: 'Werk' },
  { id: 'wp-b2-werk-08', word: 'burn-out', levels: ['B2'], category: 'Werk' },
  { id: 'wp-b2-werk-09', word: 'roeping', levels: ['B2'], category: 'Werk' },
  { id: 'wp-b2-werk-10', word: 'flexibiliteit', levels: ['B2'], category: 'Werk' },

  // ══ ETEN ═════════════════════════════════════════════════════════════════
  // A1
  { id: 'wp-a1-eten-01', word: 'brood', emoji: '🍞', levels: ['A1'], category: 'Eten' },
  { id: 'wp-a1-eten-02', word: 'appel', emoji: '🍎', levels: ['A1'], category: 'Eten' },
  { id: 'wp-a1-eten-03', word: 'water', emoji: '💧', levels: ['A1'], category: 'Eten' },
  { id: 'wp-a1-eten-04', word: 'melk', emoji: '🥛', levels: ['A1'], category: 'Eten' },
  { id: 'wp-a1-eten-05', word: 'kaas', emoji: '🧀', levels: ['A1'], category: 'Eten' },
  { id: 'wp-a1-eten-06', word: 'ei', emoji: '🥚', levels: ['A1'], category: 'Eten' },
  { id: 'wp-a1-eten-07', word: 'soep', emoji: '🍲', levels: ['A1'], category: 'Eten' },
  { id: 'wp-a1-eten-08', word: 'rijst', emoji: '🍚', levels: ['A1'], category: 'Eten' },
  { id: 'wp-a1-eten-09', word: 'thee', emoji: '🍵', levels: ['A1'], category: 'Eten' },
  { id: 'wp-a1-eten-10', word: 'koffie', emoji: '☕', levels: ['A1'], category: 'Eten' },
  // A2
  { id: 'wp-a2-eten-01', word: 'ontbijt', emoji: '🍳', levels: ['A2'], category: 'Eten' },
  { id: 'wp-a2-eten-02', word: 'recept', emoji: '📋', levels: ['A2'], category: 'Eten' },
  { id: 'wp-a2-eten-03', word: 'groente', emoji: '🥦', levels: ['A2'], category: 'Eten' },
  { id: 'wp-a2-eten-04', word: 'dessert', emoji: '🍰', levels: ['A2'], category: 'Eten' },
  { id: 'wp-a2-eten-05', word: 'restaurant', emoji: '🍽️', levels: ['A2'], category: 'Eten' },
  { id: 'wp-a2-eten-06', word: 'boodschappen', emoji: '🛒', levels: ['A2'], category: 'Eten' },
  { id: 'wp-a2-eten-07', word: 'keuken', emoji: '🍴', levels: ['A2'], category: 'Eten' },
  { id: 'wp-a2-eten-08', word: 'maaltijd', emoji: '🍲', levels: ['A2'], category: 'Eten' },
  { id: 'wp-a2-eten-09', word: 'snack', emoji: '🍪', levels: ['A2'], category: 'Eten' },
  { id: 'wp-a2-eten-10', word: 'fruit', emoji: '🍓', levels: ['A2'], category: 'Eten' },
  // B1
  { id: 'wp-b1-eten-01', word: 'voeding', levels: ['B1'], category: 'Eten' },
  { id: 'wp-b1-eten-02', word: 'smaak', levels: ['B1'], category: 'Eten' },
  { id: 'wp-b1-eten-03', word: 'gerecht', levels: ['B1'], category: 'Eten' },
  { id: 'wp-b1-eten-04', word: 'gastvrijheid', levels: ['B1'], category: 'Eten' },
  { id: 'wp-b1-eten-05', word: 'eetcultuur', levels: ['B1'], category: 'Eten' },
  { id: 'wp-b1-eten-06', word: 'dieet', levels: ['B1'], category: 'Eten' },
  { id: 'wp-b1-eten-07', word: 'ingrediënt', levels: ['B1'], category: 'Eten' },
  { id: 'wp-b1-eten-08', word: 'bereiding', levels: ['B1'], category: 'Eten' },
  { id: 'wp-b1-eten-09', word: 'portie', levels: ['B1'], category: 'Eten' },
  { id: 'wp-b1-eten-10', word: 'specerij', levels: ['B1'], category: 'Eten' },
  // B2
  { id: 'wp-b2-eten-01', word: 'voedselverspilling', levels: ['B2'], category: 'Eten' },
  { id: 'wp-b2-eten-02', word: 'duurzaamheid', levels: ['B2'], category: 'Eten' },
  { id: 'wp-b2-eten-03', word: 'voedingsindustrie', levels: ['B2'], category: 'Eten' },
  { id: 'wp-b2-eten-04', word: 'consumptie', levels: ['B2'], category: 'Eten' },
  { id: 'wp-b2-eten-05', word: 'globalisering', levels: ['B2'], category: 'Eten' },
  { id: 'wp-b2-eten-06', word: 'biologisch', levels: ['B2'], category: 'Eten' },
  { id: 'wp-b2-eten-07', word: 'schaarste', levels: ['B2'], category: 'Eten' },
  { id: 'wp-b2-eten-08', word: 'eetgewoonte', levels: ['B2'], category: 'Eten' },
  { id: 'wp-b2-eten-09', word: 'herkomst', levels: ['B2'], category: 'Eten' },
  { id: 'wp-b2-eten-10', word: 'overvloed', levels: ['B2'], category: 'Eten' },

  // ══ REIZEN ═══════════════════════════════════════════════════════════════
  // A1
  { id: 'wp-a1-reizen-01', word: 'trein', emoji: '🚆', levels: ['A1'], category: 'Reizen' },
  { id: 'wp-a1-reizen-02', word: 'bus', emoji: '🚌', levels: ['A1'], category: 'Reizen' },
  { id: 'wp-a1-reizen-03', word: 'auto', emoji: '🚗', levels: ['A1'], category: 'Reizen' },
  { id: 'wp-a1-reizen-04', word: 'koffer', emoji: '🧳', levels: ['A1'], category: 'Reizen' },
  { id: 'wp-a1-reizen-05', word: 'zee', emoji: '🌊', levels: ['A1'], category: 'Reizen' },
  { id: 'wp-a1-reizen-06', word: 'kaart', emoji: '🗺️', levels: ['A1'], category: 'Reizen' },
  { id: 'wp-a1-reizen-07', word: 'weg', emoji: '🛣️', levels: ['A1'], category: 'Reizen' },
  { id: 'wp-a1-reizen-08', word: 'vakantie', emoji: '🏖️', levels: ['A1'], category: 'Reizen' },
  { id: 'wp-a1-reizen-09', word: 'boot', emoji: '⛵', levels: ['A1'], category: 'Reizen' },
  { id: 'wp-a1-reizen-10', word: 'hotel', emoji: '🏨', levels: ['A1'], category: 'Reizen' },
  // A2
  { id: 'wp-a2-reizen-01', word: 'vliegtuig', emoji: '✈️', levels: ['A2'], category: 'Reizen' },
  { id: 'wp-a2-reizen-02', word: 'station', emoji: '🚉', levels: ['A2'], category: 'Reizen' },
  { id: 'wp-a2-reizen-03', word: 'paspoort', emoji: '🛂', levels: ['A2'], category: 'Reizen' },
  { id: 'wp-a2-reizen-04', word: 'bestemming', emoji: '📍', levels: ['A2'], category: 'Reizen' },
  { id: 'wp-a2-reizen-05', word: 'strand', emoji: '🏝️', levels: ['A2'], category: 'Reizen' },
  { id: 'wp-a2-reizen-06', word: 'berg', emoji: '⛰️', levels: ['A2'], category: 'Reizen' },
  { id: 'wp-a2-reizen-07', word: 'route', emoji: '🧭', levels: ['A2'], category: 'Reizen' },
  { id: 'wp-a2-reizen-08', word: 'reisgids', emoji: '📔', levels: ['A2'], category: 'Reizen' },
  { id: 'wp-a2-reizen-09', word: 'grens', emoji: '🚧', levels: ['A2'], category: 'Reizen' },
  { id: 'wp-a2-reizen-10', word: 'rugzak', emoji: '🎒', levels: ['A2'], category: 'Reizen' },
  // B1
  { id: 'wp-b1-reizen-01', word: 'avontuur', levels: ['B1'], category: 'Reizen' },
  { id: 'wp-b1-reizen-02', word: 'ervaring', levels: ['B1'], category: 'Reizen' },
  { id: 'wp-b1-reizen-03', word: 'cultuurverschil', levels: ['B1'], category: 'Reizen' },
  { id: 'wp-b1-reizen-04', word: 'heimwee', levels: ['B1'], category: 'Reizen' },
  { id: 'wp-b1-reizen-05', word: 'ontdekking', levels: ['B1'], category: 'Reizen' },
  { id: 'wp-b1-reizen-06', word: 'planning', levels: ['B1'], category: 'Reizen' },
  { id: 'wp-b1-reizen-07', word: 'bagage', levels: ['B1'], category: 'Reizen' },
  { id: 'wp-b1-reizen-08', word: 'verblijf', levels: ['B1'], category: 'Reizen' },
  { id: 'wp-b1-reizen-09', word: 'reisgenoot', levels: ['B1'], category: 'Reizen' },
  { id: 'wp-b1-reizen-10', word: 'verre reis', levels: ['B1'], category: 'Reizen' },
  // B2
  { id: 'wp-b2-reizen-01', word: 'massatoerisme', levels: ['B2'], category: 'Reizen' },
  { id: 'wp-b2-reizen-02', word: 'cultuurschok', levels: ['B2'], category: 'Reizen' },
  { id: 'wp-b2-reizen-03', word: 'migratie', levels: ['B2'], category: 'Reizen' },
  { id: 'wp-b2-reizen-04', word: 'ecologische voetafdruk', levels: ['B2'], category: 'Reizen' },
  { id: 'wp-b2-reizen-05', word: 'vrijheid', levels: ['B2'], category: 'Reizen' },
  { id: 'wp-b2-reizen-06', word: 'ontheemding', levels: ['B2'], category: 'Reizen' },
  { id: 'wp-b2-reizen-07', word: 'authenticiteit', levels: ['B2'], category: 'Reizen' },
  { id: 'wp-b2-reizen-08', word: 'mobiliteit', levels: ['B2'], category: 'Reizen' },
  { id: 'wp-b2-reizen-09', word: 'horizon', levels: ['B2'], category: 'Reizen' },
  { id: 'wp-b2-reizen-10', word: 'verlangen', levels: ['B2'], category: 'Reizen' },

  // ══ VRIJE TIJD ═══════════════════════════════════════════════════════════
  // A1
  { id: 'wp-a1-vrij-01', word: 'spel', emoji: '🎲', levels: ['A1'], category: 'Vrije tijd' },
  { id: 'wp-a1-vrij-02', word: 'bal', emoji: '⚽', levels: ['A1'], category: 'Vrije tijd' },
  { id: 'wp-a1-vrij-03', word: 'muziek', emoji: '🎵', levels: ['A1'], category: 'Vrije tijd' },
  { id: 'wp-a1-vrij-04', word: 'film', emoji: '🎬', levels: ['A1'], category: 'Vrije tijd' },
  { id: 'wp-a1-vrij-05', word: 'boek', emoji: '📚', levels: ['A1'], category: 'Vrije tijd' },
  { id: 'wp-a1-vrij-06', word: 'kleur', emoji: '🎨', levels: ['A1'], category: 'Vrije tijd' },
  { id: 'wp-a1-vrij-07', word: 'dans', emoji: '💃', levels: ['A1'], category: 'Vrije tijd' },
  { id: 'wp-a1-vrij-08', word: 'tv', emoji: '📺', levels: ['A1'], category: 'Vrije tijd' },
  { id: 'wp-a1-vrij-09', word: 'zon', emoji: '☀️', levels: ['A1'], category: 'Vrije tijd' },
  { id: 'wp-a1-vrij-10', word: 'tekenen', emoji: '✏️', levels: ['A1'], category: 'Vrije tijd' },
  // A2
  { id: 'wp-a2-vrij-01', word: 'sport', emoji: '⚽', levels: ['A2'], category: 'Vrije tijd' },
  { id: 'wp-a2-vrij-02', word: 'hobby', emoji: '🎯', levels: ['A2'], category: 'Vrije tijd' },
  { id: 'wp-a2-vrij-03', word: 'weekend', emoji: '🎉', levels: ['A2'], category: 'Vrije tijd' },
  { id: 'wp-a2-vrij-04', word: 'feest', emoji: '🥳', levels: ['A2'], category: 'Vrije tijd' },
  { id: 'wp-a2-vrij-05', word: 'concert', emoji: '🎤', levels: ['A2'], category: 'Vrije tijd' },
  { id: 'wp-a2-vrij-06', word: 'wandeling', emoji: '🚶', levels: ['A2'], category: 'Vrije tijd' },
  { id: 'wp-a2-vrij-07', word: 'fotografie', emoji: '📷', levels: ['A2'], category: 'Vrije tijd' },
  { id: 'wp-a2-vrij-08', word: 'puzzel', emoji: '🧩', levels: ['A2'], category: 'Vrije tijd' },
  { id: 'wp-a2-vrij-09', word: 'tuinieren', emoji: '🌱', levels: ['A2'], category: 'Vrije tijd' },
  { id: 'wp-a2-vrij-10', word: 'zwemmen', emoji: '🏊', levels: ['A2'], category: 'Vrije tijd' },
  // B1
  { id: 'wp-b1-vrij-01', word: 'ontspanning', levels: ['B1'], category: 'Vrije tijd' },
  { id: 'wp-b1-vrij-02', word: 'creativiteit', levels: ['B1'], category: 'Vrije tijd' },
  { id: 'wp-b1-vrij-03', word: 'nieuwsgierigheid', levels: ['B1'], category: 'Vrije tijd' },
  { id: 'wp-b1-vrij-04', word: 'plezier', levels: ['B1'], category: 'Vrije tijd' },
  { id: 'wp-b1-vrij-05', word: 'talent', levels: ['B1'], category: 'Vrije tijd' },
  { id: 'wp-b1-vrij-06', word: 'uitdaging', levels: ['B1'], category: 'Vrije tijd' },
  { id: 'wp-b1-vrij-07', word: 'gewoonte', levels: ['B1'], category: 'Vrije tijd' },
  { id: 'wp-b1-vrij-08', word: 'inspiratie', levels: ['B1'], category: 'Vrije tijd' },
  { id: 'wp-b1-vrij-09', word: 'vrijwilligerswerk', levels: ['B1'], category: 'Vrije tijd' },
  { id: 'wp-b1-vrij-10', word: 'balans', levels: ['B1'], category: 'Vrije tijd' },
  // B2
  { id: 'wp-b2-vrij-01', word: 'zingeving', levels: ['B2'], category: 'Vrije tijd' },
  { id: 'wp-b2-vrij-02', word: 'prestatiedruk', levels: ['B2'], category: 'Vrije tijd' },
  { id: 'wp-b2-vrij-03', word: 'verveling', levels: ['B2'], category: 'Vrije tijd' },
  { id: 'wp-b2-vrij-04', word: 'mindfulness', levels: ['B2'], category: 'Vrije tijd' },
  { id: 'wp-b2-vrij-05', word: 'zelfontplooiing', levels: ['B2'], category: 'Vrije tijd' },
  { id: 'wp-b2-vrij-06', word: 'escapisme', levels: ['B2'], category: 'Vrije tijd' },
  { id: 'wp-b2-vrij-07', word: 'ambacht', levels: ['B2'], category: 'Vrije tijd' },
  { id: 'wp-b2-vrij-08', word: 'beleving', levels: ['B2'], category: 'Vrije tijd' },
  { id: 'wp-b2-vrij-09', word: 'routine', levels: ['B2'], category: 'Vrije tijd' },
  { id: 'wp-b2-vrij-10', word: 'verwondering', levels: ['B2'], category: 'Vrije tijd' },

  // ══ WONEN ════════════════════════════════════════════════════════════════
  // A1
  { id: 'wp-a1-wonen-01', word: 'huis', emoji: '🏠', levels: ['A1'], category: 'Wonen' },
  { id: 'wp-a1-wonen-02', word: 'kamer', emoji: '🚪', levels: ['A1'], category: 'Wonen' },
  { id: 'wp-a1-wonen-03', word: 'deur', emoji: '🚪', levels: ['A1'], category: 'Wonen' },
  { id: 'wp-a1-wonen-04', word: 'raam', emoji: '🪟', levels: ['A1'], category: 'Wonen' },
  { id: 'wp-a1-wonen-05', word: 'bed', emoji: '🛏️', levels: ['A1'], category: 'Wonen' },
  { id: 'wp-a1-wonen-06', word: 'stoel', emoji: '🪑', levels: ['A1'], category: 'Wonen' },
  { id: 'wp-a1-wonen-07', word: 'tafel', emoji: '🍽️', levels: ['A1'], category: 'Wonen' },
  { id: 'wp-a1-wonen-08', word: 'tuin', emoji: '🌷', levels: ['A1'], category: 'Wonen' },
  { id: 'wp-a1-wonen-09', word: 'sleutel', emoji: '🔑', levels: ['A1'], category: 'Wonen' },
  { id: 'wp-a1-wonen-10', word: 'lamp', emoji: '💡', levels: ['A1'], category: 'Wonen' },
  // A2
  { id: 'wp-a2-wonen-01', word: 'woonkamer', emoji: '🛋️', levels: ['A2'], category: 'Wonen' },
  { id: 'wp-a2-wonen-02', word: 'keuken', emoji: '🍴', levels: ['A2'], category: 'Wonen' },
  { id: 'wp-a2-wonen-03', word: 'badkamer', emoji: '🛁', levels: ['A2'], category: 'Wonen' },
  { id: 'wp-a2-wonen-04', word: 'balkon', emoji: '🪴', levels: ['A2'], category: 'Wonen' },
  { id: 'wp-a2-wonen-05', word: 'meubel', emoji: '🪑', levels: ['A2'], category: 'Wonen' },
  { id: 'wp-a2-wonen-06', word: 'verhuizen', emoji: '📦', levels: ['A2'], category: 'Wonen' },
  { id: 'wp-a2-wonen-07', word: 'huur', emoji: '💶', levels: ['A2'], category: 'Wonen' },
  { id: 'wp-a2-wonen-08', word: 'zolder', emoji: '🏚️', levels: ['A2'], category: 'Wonen' },
  { id: 'wp-a2-wonen-09', word: 'trap', emoji: '🪜', levels: ['A2'], category: 'Wonen' },
  { id: 'wp-a2-wonen-10', word: 'schoonmaken', emoji: '🧹', levels: ['A2'], category: 'Wonen' },
  // B1
  { id: 'wp-b1-wonen-01', word: 'woonomgeving', levels: ['B1'], category: 'Wonen' },
  { id: 'wp-b1-wonen-02', word: 'comfort', levels: ['B1'], category: 'Wonen' },
  { id: 'wp-b1-wonen-03', word: 'privacy', levels: ['B1'], category: 'Wonen' },
  { id: 'wp-b1-wonen-04', word: 'gezelligheid', levels: ['B1'], category: 'Wonen' },
  { id: 'wp-b1-wonen-05', word: 'onderhoud', levels: ['B1'], category: 'Wonen' },
  { id: 'wp-b1-wonen-06', word: 'huishouden', levels: ['B1'], category: 'Wonen' },
  { id: 'wp-b1-wonen-07', word: 'ruimte', levels: ['B1'], category: 'Wonen' },
  { id: 'wp-b1-wonen-08', word: 'woonsituatie', levels: ['B1'], category: 'Wonen' },
  { id: 'wp-b1-wonen-09', word: 'indeling', levels: ['B1'], category: 'Wonen' },
  { id: 'wp-b1-wonen-10', word: 'buurman', levels: ['B1'], category: 'Wonen' },
  // B2
  { id: 'wp-b2-wonen-01', word: 'woningnood', levels: ['B2'], category: 'Wonen' },
  { id: 'wp-b2-wonen-02', word: 'geborgenheid', levels: ['B2'], category: 'Wonen' },
  { id: 'wp-b2-wonen-03', word: 'eigendom', levels: ['B2'], category: 'Wonen' },
  { id: 'wp-b2-wonen-04', word: 'leefruimte', levels: ['B2'], category: 'Wonen' },
  { id: 'wp-b2-wonen-05', word: 'duurzaam wonen', levels: ['B2'], category: 'Wonen' },
  { id: 'wp-b2-wonen-06', word: 'thuisgevoel', levels: ['B2'], category: 'Wonen' },
  { id: 'wp-b2-wonen-07', word: 'woningmarkt', levels: ['B2'], category: 'Wonen' },
  { id: 'wp-b2-wonen-08', word: 'isolement', levels: ['B2'], category: 'Wonen' },
  { id: 'wp-b2-wonen-09', word: 'verbondenheid', levels: ['B2'], category: 'Wonen' },
  { id: 'wp-b2-wonen-10', word: 'wooncultuur', levels: ['B2'], category: 'Wonen' },

  // ══ GEZONDHEID ═══════════════════════════════════════════════════════════
  // A1
  { id: 'wp-a1-gezond-01', word: 'water', emoji: '💧', levels: ['A1'], category: 'Gezondheid' },
  { id: 'wp-a1-gezond-02', word: 'slaap', emoji: '😴', levels: ['A1'], category: 'Gezondheid' },
  { id: 'wp-a1-gezond-03', word: 'sport', emoji: '🏃', levels: ['A1'], category: 'Gezondheid' },
  { id: 'wp-a1-gezond-04', word: 'dokter', emoji: '🩺', levels: ['A1'], category: 'Gezondheid' },
  { id: 'wp-a1-gezond-05', word: 'ziek', emoji: '🤒', levels: ['A1'], category: 'Gezondheid' },
  { id: 'wp-a1-gezond-06', word: 'moe', emoji: '🥱', levels: ['A1'], category: 'Gezondheid' },
  { id: 'wp-a1-gezond-07', word: 'lopen', emoji: '🚶', levels: ['A1'], category: 'Gezondheid' },
  { id: 'wp-a1-gezond-08', word: 'hand', emoji: '✋', levels: ['A1'], category: 'Gezondheid' },
  { id: 'wp-a1-gezond-09', word: 'rust', emoji: '🛌', levels: ['A1'], category: 'Gezondheid' },
  { id: 'wp-a1-gezond-10', word: 'fit', emoji: '💪', levels: ['A1'], category: 'Gezondheid' },
  // A2
  { id: 'wp-a2-gezond-01', word: 'huisarts', emoji: '🩺', levels: ['A2'], category: 'Gezondheid' },
  { id: 'wp-a2-gezond-02', word: 'medicijn', emoji: '💊', levels: ['A2'], category: 'Gezondheid' },
  { id: 'wp-a2-gezond-03', word: 'beweging', emoji: '🤸', levels: ['A2'], category: 'Gezondheid' },
  { id: 'wp-a2-gezond-04', word: 'gezond', emoji: '🥗', levels: ['A2'], category: 'Gezondheid' },
  { id: 'wp-a2-gezond-05', word: 'ontspannen', emoji: '🧘', levels: ['A2'], category: 'Gezondheid' },
  { id: 'wp-a2-gezond-06', word: 'vitamine', emoji: '🍊', levels: ['A2'], category: 'Gezondheid' },
  { id: 'wp-a2-gezond-07', word: 'verkouden', emoji: '🤧', levels: ['A2'], category: 'Gezondheid' },
  { id: 'wp-a2-gezond-08', word: 'energie', emoji: '⚡', levels: ['A2'], category: 'Gezondheid' },
  { id: 'wp-a2-gezond-09', word: 'wandelen', emoji: '🥾', levels: ['A2'], category: 'Gezondheid' },
  { id: 'wp-a2-gezond-10', word: 'tandarts', emoji: '🦷', levels: ['A2'], category: 'Gezondheid' },
  // B1
  { id: 'wp-b1-gezond-01', word: 'welzijn', levels: ['B1'], category: 'Gezondheid' },
  { id: 'wp-b1-gezond-02', word: 'stress', levels: ['B1'], category: 'Gezondheid' },
  { id: 'wp-b1-gezond-03', word: 'balans', levels: ['B1'], category: 'Gezondheid' },
  { id: 'wp-b1-gezond-04', word: 'veerkracht', levels: ['B1'], category: 'Gezondheid' },
  { id: 'wp-b1-gezond-05', word: 'gewoonte', levels: ['B1'], category: 'Gezondheid' },
  { id: 'wp-b1-gezond-06', word: 'herstel', levels: ['B1'], category: 'Gezondheid' },
  { id: 'wp-b1-gezond-07', word: 'conditie', levels: ['B1'], category: 'Gezondheid' },
  { id: 'wp-b1-gezond-08', word: 'vermoeidheid', levels: ['B1'], category: 'Gezondheid' },
  { id: 'wp-b1-gezond-09', word: 'zorg', levels: ['B1'], category: 'Gezondheid' },
  { id: 'wp-b1-gezond-10', word: 'levensstijl', levels: ['B1'], category: 'Gezondheid' },
  // B2
  { id: 'wp-b2-gezond-01', word: 'mentale gezondheid', levels: ['B2'], category: 'Gezondheid' },
  { id: 'wp-b2-gezond-02', word: 'eenzaamheid', levels: ['B2'], category: 'Gezondheid' },
  { id: 'wp-b2-gezond-03', word: 'preventie', levels: ['B2'], category: 'Gezondheid' },
  { id: 'wp-b2-gezond-04', word: 'veroudering', levels: ['B2'], category: 'Gezondheid' },
  { id: 'wp-b2-gezond-05', word: 'burn-out', levels: ['B2'], category: 'Gezondheid' },
  { id: 'wp-b2-gezond-06', word: 'zelfzorg', levels: ['B2'], category: 'Gezondheid' },
  { id: 'wp-b2-gezond-07', word: 'draagkracht', levels: ['B2'], category: 'Gezondheid' },
  { id: 'wp-b2-gezond-08', word: 'kwetsbaarheid', levels: ['B2'], category: 'Gezondheid' },
  { id: 'wp-b2-gezond-09', word: 'gezondheidszorg', levels: ['B2'], category: 'Gezondheid' },
  { id: 'wp-b2-gezond-10', word: 'vitaliteit', levels: ['B2'], category: 'Gezondheid' },
];
