import type { PronunciationWord } from './types';

export const WORDS_B1: PronunciationWord[] = [
  // maatschappij
  {
    id: 'maatschappij',
    word: 'maatschappij',
    level: 'B1',
    theme: 'maatschappij',
    exampleSentence: 'De maatschappij verandert snel.',
  },
  {
    id: 'samenleving',
    word: 'samenleving',
    level: 'B1',
    theme: 'maatschappij',
    exampleSentence: 'We leven in een diverse samenleving.',
  },
  {
    id: 'democratie',
    word: 'democratie',
    level: 'B1',
    theme: 'maatschappij',
    exampleSentence: 'Nederland is een democratie.',
  },
  {
    id: 'regering',
    word: 'regering',
    level: 'B1',
    theme: 'maatschappij',
    exampleSentence: 'De regering neemt een besluit.',
  },
  {
    id: 'politie',
    word: 'politie',
    level: 'B1',
    theme: 'maatschappij',
    exampleSentence: 'De politie helpt bij een ongeluk.',
  },
  {
    id: 'gemeente',
    word: 'gemeente',
    level: 'B1',
    theme: 'maatschappij',
    exampleSentence: 'De gemeente regelt de afvalophaling.',
  },
  {
    id: 'wet',
    word: 'wet',
    level: 'B1',
    theme: 'maatschappij',
    exampleSentence: 'Je moet de wet volgen.',
  },
  {
    id: 'recht',
    word: 'recht',
    level: 'B1',
    theme: 'maatschappij',
    grammar: '(het)',
    exampleSentence: 'Iedereen heeft recht op onderwijs.',
  },
  {
    id: 'rechter',
    word: 'rechter',
    level: 'B1',
    theme: 'maatschappij',
    exampleSentence: 'De rechter doet uitspraak.',
  },
  {
    id: 'misdaad',
    word: 'misdaad',
    level: 'B1',
    theme: 'maatschappij',
    exampleSentence: 'Misdaad is een groot probleem.',
  },
  {
    id: 'verkiezing',
    word: 'verkiezing',
    level: 'B1',
    theme: 'maatschappij',
    exampleSentence: 'De verkiezing is volgende maand.',
  },
  {
    id: 'partij',
    word: 'partij',
    level: 'B1',
    theme: 'maatschappij',
    exampleSentence: 'Voor welke partij stem je?',
  },
  {
    id: 'minister',
    word: 'minister',
    level: 'B1',
    theme: 'maatschappij',
    exampleSentence: 'De minister spreekt in de Kamer.',
  },
  {
    id: 'burgemeester',
    word: 'burgemeester',
    level: 'B1',
    theme: 'maatschappij',
    exampleSentence: 'De burgemeester opent het festival.',
  },
  {
    id: 'vrijheid',
    word: 'vrijheid',
    level: 'B1',
    theme: 'maatschappij',
    exampleSentence: 'Vrijheid is heel belangrijk.',
  },
  {
    id: 'bevolking',
    word: 'bevolking',
    level: 'B1',
    theme: 'maatschappij',
    exampleSentence: 'De bevolking groeit.',
  },
  {
    id: 'nationaliteit',
    word: 'nationaliteit',
    level: 'B1',
    theme: 'maatschappij',
    exampleSentence: 'Wat is je nationaliteit?',
  },
  {
    id: 'cultuur',
    word: 'cultuur',
    level: 'B1',
    theme: 'maatschappij',
    exampleSentence: 'De Nederlandse cultuur is divers.',
  },
  {
    id: 'geschiedenis',
    word: 'geschiedenis',
    level: 'B1',
    theme: 'maatschappij',
    exampleSentence: 'Ik leer over de geschiedenis van Nederland.',
  },
  {
    id: 'oorlog',
    word: 'oorlog',
    level: 'B1',
    theme: 'maatschappij',
    exampleSentence: 'Oorlog is verschrikkelijk.',
  },
  {
    id: 'vrede',
    word: 'vrede',
    level: 'B1',
    theme: 'maatschappij',
    exampleSentence: 'We hopen op vrede.',
  },
  {
    id: 'organisatie',
    word: 'organisatie',
    level: 'B1',
    theme: 'maatschappij',
    exampleSentence: 'De organisatie helpt vluchtelingen.',
  },
  {
    id: 'vereniging',
    word: 'vereniging',
    level: 'B1',
    theme: 'maatschappij',
    exampleSentence: 'Ik ben lid van een sportvereniging.',
  },
  {
    id: 'stichting',
    word: 'stichting',
    level: 'B1',
    theme: 'maatschappij',
    exampleSentence: 'De stichting zamelt geld in.',
  },
  {
    id: 'sociaal',
    word: 'sociaal',
    level: 'B1',
    theme: 'maatschappij',
    exampleSentence: 'Het is een sociaal probleem.',
  },
  {
    id: 'gemeenschap',
    word: 'gemeenschap',
    level: 'B1',
    theme: 'maatschappij',
    exampleSentence: 'De gemeenschap werkt samen.',
  },
  {
    id: 'norm',
    word: 'norm',
    level: 'B1',
    theme: 'maatschappij',
    exampleSentence: 'Iedere cultuur heeft normen en waarden.',
  },
  {
    id: 'waarde',
    word: 'waarde',
    level: 'B1',
    theme: 'maatschappij',
    exampleSentence: 'Eerlijkheid is een belangrijke waarde.',
  },
  // formeel
  {
    id: 'overheid',
    word: 'overheid',
    level: 'B1',
    theme: 'formeel',
    exampleSentence: 'De overheid maakt de regels.',
  },
  {
    id: 'formulier',
    word: 'formulier',
    level: 'B1',
    theme: 'formeel',
    grammar: '(het)',
    exampleSentence: 'Vul het formulier in.',
  },
  {
    id: 'document',
    word: 'document',
    level: 'B1',
    theme: 'formeel',
    grammar: '(het)',
    exampleSentence: 'Neem je documenten mee.',
  },
  {
    id: 'vergunning',
    word: 'vergunning',
    level: 'B1',
    theme: 'formeel',
    exampleSentence: 'Je hebt een vergunning nodig.',
  },
  {
    id: 'aanvragen',
    word: 'aanvragen',
    level: 'B1',
    theme: 'formeel',
    exampleSentence: 'Ik wil een paspoort aanvragen.',
  },
  {
    id: 'officieel',
    word: 'officieel',
    level: 'B1',
    theme: 'formeel',
    exampleSentence: 'Dit is een officieel document.',
  },
  {
    id: 'toestemming',
    word: 'toestemming',
    level: 'B1',
    theme: 'formeel',
    exampleSentence: 'Ik heb toestemming nodig.',
  },
  {
    id: 'verplichten',
    word: 'verplichten',
    level: 'B1',
    theme: 'formeel',
    exampleSentence: 'De school verplicht een uniform.',
  },
  {
    id: 'verboden',
    word: 'verboden',
    level: 'B1',
    theme: 'formeel',
    exampleSentence: 'Roken is hier verboden.',
  },
  {
    id: 'openbaar',
    word: 'openbaar',
    level: 'B1',
    theme: 'formeel',
    exampleSentence: 'Het openbaar vervoer is goed.',
  },
  {
    id: 'verklaring',
    word: 'verklaring',
    level: 'B1',
    theme: 'formeel',
    exampleSentence: 'Ik heb een verklaring nodig.',
  },
  {
    id: 'opdracht',
    word: 'opdracht',
    level: 'B1',
    theme: 'formeel',
    exampleSentence: 'De leraar geeft een opdracht.',
  },
  {
    id: 'bestuur',
    word: 'bestuur',
    level: 'B1',
    theme: 'formeel',
    grammar: '(het)',
    exampleSentence: 'Het bestuur neemt beslissingen.',
  },
  {
    id: 'beleid',
    word: 'beleid',
    level: 'B1',
    theme: 'formeel',
    grammar: '(het)',
    exampleSentence: 'Het beleid is veranderd.',
  },
  {
    id: 'commissie',
    word: 'commissie',
    level: 'B1',
    theme: 'formeel',
    exampleSentence: 'De commissie vergadert morgen.',
  },
  {
    id: 'instantie',
    word: 'instantie',
    level: 'B1',
    theme: 'formeel',
    exampleSentence: 'Neem contact op met de juiste instantie.',
  },
  // werk & carrière (B1 level)
  {
    id: 'carriere',
    word: 'carrière',
    level: 'B1',
    theme: 'werk',
    exampleSentence: 'Zij maakt carrière bij een groot bedrijf.',
  },
  {
    id: 'solliciteren',
    word: 'solliciteren',
    level: 'B1',
    theme: 'werk',
    exampleSentence: 'Ik ga solliciteren bij die firma.',
  },
  {
    id: 'ontslag',
    word: 'ontslag',
    level: 'B1',
    theme: 'werk',
    grammar: '(het)',
    exampleSentence: 'Hij heeft ontslag genomen.',
  },
  {
    id: 'samenwerking',
    word: 'samenwerking',
    level: 'B1',
    theme: 'werk',
    exampleSentence: 'De samenwerking verloopt goed.',
  },
  {
    id: 'vergadering',
    word: 'vergadering',
    level: 'B1',
    theme: 'werk',
    exampleSentence: 'De vergadering begint om twee uur.',
  },
  {
    id: 'overleg',
    word: 'overleg',
    level: 'B1',
    theme: 'werk',
    grammar: '(het)',
    exampleSentence: 'We hebben overleg met het team.',
  },
  {
    id: 'prestatie',
    word: 'prestatie',
    level: 'B1',
    theme: 'werk',
    exampleSentence: 'Dat is een goede prestatie.',
  },
  {
    id: 'resultaat',
    word: 'resultaat',
    level: 'B1',
    theme: 'werk',
    grammar: '(het)',
    exampleSentence: 'Het resultaat is positief.',
  },
  {
    id: 'verantwoordelijk',
    word: 'verantwoordelijk',
    level: 'B1',
    theme: 'werk',
    exampleSentence: 'Ik ben verantwoordelijk voor dit project.',
  },
  {
    id: 'functie',
    word: 'functie',
    level: 'B1',
    theme: 'werk',
    exampleSentence: 'Wat is je functie?',
  },
  {
    id: 'personeel',
    word: 'personeel',
    level: 'B1',
    theme: 'werk',
    grammar: '(het)',
    exampleSentence: 'Het personeel is vriendelijk.',
  },
  {
    id: 'industrie',
    word: 'industrie',
    level: 'B1',
    theme: 'werk',
    exampleSentence: 'De industrie groeit in deze regio.',
  },
  {
    id: 'economie',
    word: 'economie',
    level: 'B1',
    theme: 'werk',
    exampleSentence: 'De economie gaat goed.',
  },
  {
    id: 'handel',
    word: 'handel',
    level: 'B1',
    theme: 'werk',
    exampleSentence: 'Nederland leeft van de handel.',
  },
  {
    id: 'productie',
    word: 'productie',
    level: 'B1',
    theme: 'werk',
    exampleSentence: 'De productie is gestegen.',
  },
  // mening & discussie
  {
    id: 'beweren',
    word: 'beweren',
    level: 'B1',
    theme: 'mening',
    exampleSentence: 'Hij beweert dat het waar is.',
  },
  {
    id: 'discussie',
    word: 'discussie',
    level: 'B1',
    theme: 'mening',
    exampleSentence: 'Er is een discussie over het plan.',
  },
  {
    id: 'standpunt',
    word: 'standpunt',
    level: 'B1',
    theme: 'mening',
    grammar: '(het)',
    exampleSentence: 'Wat is jouw standpunt?',
  },
  {
    id: 'overtuigen',
    word: 'overtuigen',
    level: 'B1',
    theme: 'mening',
    exampleSentence: 'Ik probeer haar te overtuigen.',
  },
  {
    id: 'kritiek',
    word: 'kritiek',
    level: 'B1',
    theme: 'mening',
    exampleSentence: 'Er is veel kritiek op het plan.',
  },
  {
    id: 'kritisch',
    word: 'kritisch',
    level: 'B1',
    theme: 'mening',
    exampleSentence: 'Wees kritisch over wat je leest.',
  },
  {
    id: 'erkennen',
    word: 'erkennen',
    level: 'B1',
    theme: 'mening',
    exampleSentence: 'Ik erken dat het moeilijk is.',
  },
  {
    id: 'verklaren',
    word: 'verklaren',
    level: 'B1',
    theme: 'mening',
    exampleSentence: 'Kun je dat verklaren?',
  },
  {
    id: 'bewijzen',
    word: 'bewijzen',
    level: 'B1',
    theme: 'mening',
    exampleSentence: 'Kun je dat bewijzen?',
  },
  {
    id: 'conclusie',
    word: 'conclusie',
    level: 'B1',
    theme: 'mening',
    exampleSentence: 'Mijn conclusie is dat het werkt.',
  },
  {
    id: 'argument',
    word: 'argument',
    level: 'B1',
    theme: 'mening',
    grammar: '(het)',
    exampleSentence: 'Dat is een sterk argument.',
  },
  {
    id: 'aandacht',
    word: 'aandacht',
    level: 'B1',
    theme: 'mening',
    exampleSentence: 'Geef aandacht aan dit probleem.',
  },
  {
    id: 'invloed',
    word: 'invloed',
    level: 'B1',
    theme: 'mening',
    exampleSentence: 'Het weer heeft invloed op mijn humeur.',
  },
  {
    id: 'gevolg',
    word: 'gevolg',
    level: 'B1',
    theme: 'mening',
    grammar: '(het)',
    exampleSentence: 'Wat zijn de gevolgen?',
  },
  {
    id: 'oorzaak',
    word: 'oorzaak',
    level: 'B1',
    theme: 'mening',
    exampleSentence: 'Wat is de oorzaak van het probleem?',
  },
  {
    id: 'oplossen',
    word: 'oplossen',
    level: 'B1',
    theme: 'mening',
    exampleSentence: 'We moeten dit probleem oplossen.',
  },
  {
    id: 'voorstel',
    word: 'voorstel',
    level: 'B1',
    theme: 'mening',
    grammar: '(het)',
    exampleSentence: 'Ik heb een voorstel.',
  },
  {
    id: 'voorstellen',
    word: 'voorstellen',
    level: 'B1',
    theme: 'mening',
    exampleSentence: 'Ik stel voor dat we morgen beginnen.',
  },
  {
    id: 'instemmen',
    word: 'instemmen',
    level: 'B1',
    theme: 'mening',
    exampleSentence: 'Ik stem in met het voorstel.',
  },
  {
    id: 'tegenstelling',
    word: 'tegenstelling',
    level: 'B1',
    theme: 'mening',
    exampleSentence: 'Er is een tegenstelling in zijn verhaal.',
  },
  // overig — abstract/formal B1 words
  {
    id: 'ontwikkeling',
    word: 'ontwikkeling',
    level: 'B1',
    theme: 'overig',
    exampleSentence: 'De ontwikkeling gaat snel.',
  },
  {
    id: 'ontwikkelen',
    word: 'ontwikkelen',
    level: 'B1',
    theme: 'overig',
    exampleSentence: 'We ontwikkelen een nieuw product.',
  },
  {
    id: 'onderzoek',
    word: 'onderzoek',
    level: 'B1',
    theme: 'overig',
    grammar: '(het)',
    exampleSentence: 'Het onderzoek toont aan dat het werkt.',
  },
  {
    id: 'onderzoeken',
    word: 'onderzoeken',
    level: 'B1',
    theme: 'overig',
    exampleSentence: 'We onderzoeken het probleem.',
  },
  {
    id: 'methode',
    word: 'methode',
    level: 'B1',
    theme: 'overig',
    exampleSentence: 'Deze methode werkt goed.',
  },
  {
    id: 'proces',
    word: 'proces',
    level: 'B1',
    theme: 'overig',
    grammar: '(het)',
    exampleSentence: 'Het is een lang proces.',
  },
  {
    id: 'systeem',
    word: 'systeem',
    level: 'B1',
    theme: 'overig',
    grammar: '(het)',
    exampleSentence: 'Het systeem werkt niet.',
  },
  {
    id: 'structuur',
    word: 'structuur',
    level: 'B1',
    theme: 'overig',
    exampleSentence: 'De structuur is duidelijk.',
  },
  {
    id: 'niveau',
    word: 'niveau',
    level: 'B1',
    theme: 'overig',
    grammar: '(het)',
    exampleSentence: 'Het niveau is hoog.',
  },
  {
    id: 'factor',
    word: 'factor',
    level: 'B1',
    theme: 'overig',
    exampleSentence: 'Dat is een belangrijke factor.',
  },
  {
    id: 'aspect',
    word: 'aspect',
    level: 'B1',
    theme: 'overig',
    grammar: '(het)',
    exampleSentence: 'Dat is een belangrijk aspect.',
  },
  {
    id: 'principe',
    word: 'principe',
    level: 'B1',
    theme: 'overig',
    grammar: '(het)',
    exampleSentence: 'In principe ben ik het ermee eens.',
  },
  {
    id: 'bewust',
    word: 'bewust',
    level: 'B1',
    theme: 'overig',
    exampleSentence: 'Ik ben me bewust van het risico.',
  },
  {
    id: 'indruk',
    word: 'indruk',
    level: 'B1',
    theme: 'overig',
    exampleSentence: 'Het maakte grote indruk op me.',
  },
  {
    id: 'ervaren-adj',
    word: 'ervaren',
    level: 'B1',
    theme: 'overig',
    exampleSentence: 'Zij is een ervaren leraar.',
  },
  {
    id: 'beschikbaar',
    word: 'beschikbaar',
    level: 'B1',
    theme: 'overig',
    exampleSentence: 'De informatie is beschikbaar.',
  },
  {
    id: 'beperken',
    word: 'beperken',
    level: 'B1',
    theme: 'overig',
    exampleSentence: 'We moeten de kosten beperken.',
  },
  {
    id: 'bereiken',
    word: 'bereiken',
    level: 'B1',
    theme: 'overig',
    exampleSentence: 'We hebben ons doel bereikt.',
  },
  {
    id: 'verbeteren',
    word: 'verbeteren',
    level: 'B1',
    theme: 'overig',
    exampleSentence: 'Ik wil mijn Nederlands verbeteren.',
  },
  {
    id: 'beschermen',
    word: 'beschermen',
    level: 'B1',
    theme: 'overig',
    exampleSentence: 'We moeten het milieu beschermen.',
  },
  {
    id: 'bijdragen',
    word: 'bijdragen',
    level: 'B1',
    theme: 'overig',
    exampleSentence: 'Iedereen kan bijdragen.',
  },
  {
    id: 'aanbieden',
    word: 'aanbieden',
    level: 'B1',
    theme: 'overig',
    exampleSentence: 'Ik bied mijn hulp aan.',
  },
  {
    id: 'aanpassen',
    word: 'aanpassen',
    level: 'B1',
    theme: 'overig',
    exampleSentence: 'We passen het plan aan.',
  },
  {
    id: 'aansluiten',
    word: 'aansluiten',
    level: 'B1',
    theme: 'overig',
    exampleSentence: 'Ik sluit me aan bij de groep.',
  },
  {
    id: 'afhangen',
    word: 'afhangen',
    level: 'B1',
    theme: 'overig',
    exampleSentence: 'Het hangt af van het weer.',
  },
  {
    id: 'bepalen',
    word: 'bepalen',
    level: 'B1',
    theme: 'overig',
    exampleSentence: 'Jij bepaalt zelf wat je doet.',
  },
  {
    id: 'betrekken',
    word: 'betrekken',
    level: 'B1',
    theme: 'overig',
    exampleSentence: 'We betrekken iedereen bij het plan.',
  },
  {
    id: 'bevinden',
    word: 'bevinden',
    level: 'B1',
    theme: 'overig',
    exampleSentence: 'Het kantoor bevindt zich in het centrum.',
  },
  {
    id: 'dwingen',
    word: 'dwingen',
    level: 'B1',
    theme: 'overig',
    exampleSentence: 'Je kunt niemand dwingen.',
  },
  {
    id: 'leiden',
    word: 'leiden',
    level: 'B1',
    theme: 'overig',
    exampleSentence: 'Zij leidt het project.',
  },
  {
    id: 'leveren',
    word: 'leveren',
    level: 'B1',
    theme: 'overig',
    exampleSentence: 'Het bedrijf levert producten aan winkels.',
  },
  {
    id: 'lijden',
    word: 'lijden',
    level: 'B1',
    theme: 'overig',
    exampleSentence: 'Hij lijdt aan een ziekte.',
  },
  {
    id: 'lijken',
    word: 'lijken',
    level: 'B1',
    theme: 'overig',
    exampleSentence: 'Het lijkt een goed plan.',
  },
  {
    id: 'menen',
    word: 'menen',
    level: 'B1',
    theme: 'overig',
    exampleSentence: 'Ik meen het serieus.',
  },
  {
    id: 'merken',
    word: 'merken',
    level: 'B1',
    theme: 'overig',
    exampleSentence: 'Ik merk dat je moe bent.',
  },
  {
    id: 'opmerken',
    word: 'opmerken',
    level: 'B1',
    theme: 'overig',
    exampleSentence: 'Ik wil iets opmerken.',
  },
  {
    id: 'oprichten',
    word: 'oprichten',
    level: 'B1',
    theme: 'overig',
    exampleSentence: 'Zij wil een bedrijf oprichten.',
  },
  {
    id: 'stellen',
    word: 'stellen',
    level: 'B1',
    theme: 'overig',
    exampleSentence: 'Ik wil een vraag stellen.',
  },
  {
    id: 'streven',
    word: 'streven',
    level: 'B1',
    theme: 'overig',
    exampleSentence: 'We streven naar verbetering.',
  },
  {
    id: 'uitvoeren',
    word: 'uitvoeren',
    level: 'B1',
    theme: 'overig',
    exampleSentence: 'We voeren het plan uit.',
  },
  {
    id: 'verwachten',
    word: 'verwachten',
    level: 'B1',
    theme: 'overig',
    exampleSentence: 'Ik verwacht dat het morgen regent.',
  },
  {
    id: 'voorbereiden',
    word: 'voorbereiden',
    level: 'B1',
    theme: 'overig',
    exampleSentence: 'Ik bereid me voor op het examen.',
  },
  {
    id: 'voorkomen',
    word: 'voorkomen',
    level: 'B1',
    theme: 'overig',
    exampleSentence: 'We willen problemen voorkomen.',
  },
  {
    id: 'vaststellen',
    word: 'vaststellen',
    level: 'B1',
    theme: 'overig',
    exampleSentence: 'De politie stelt de feiten vast.',
  },
  {
    id: 'relatie',
    word: 'relatie',
    level: 'B1',
    theme: 'overig',
    exampleSentence: 'Wij hebben een goede relatie.',
  },
  {
    id: 'verband',
    word: 'verband',
    level: 'B1',
    theme: 'overig',
    grammar: '(het)',
    exampleSentence: 'Er is een verband tussen de twee.',
  },
  {
    id: 'verhouding',
    word: 'verhouding',
    level: 'B1',
    theme: 'overig',
    exampleSentence: 'De verhouding is niet gelijk.',
  },
  {
    id: 'omgeving',
    word: 'omgeving',
    level: 'B1',
    theme: 'overig',
    exampleSentence: 'De omgeving is heel mooi.',
  },
  {
    id: 'omstandigheid',
    word: 'omstandigheid',
    level: 'B1',
    theme: 'overig',
    exampleSentence: 'Onder deze omstandigheden is het lastig.',
  },
  {
    id: 'toekomst',
    word: 'toekomst',
    level: 'B1',
    theme: 'overig',
    exampleSentence: 'De toekomst ziet er goed uit.',
  },
  {
    id: 'verleden',
    word: 'verleden',
    level: 'B1',
    theme: 'overig',
    grammar: '(het)',
    exampleSentence: 'In het verleden was het anders.',
  },
  {
    id: 'periode',
    word: 'periode',
    level: 'B1',
    theme: 'overig',
    exampleSentence: 'Het was een moeilijke periode.',
  },
  {
    id: 'generatie',
    word: 'generatie',
    level: 'B1',
    theme: 'overig',
    exampleSentence: 'De nieuwe generatie denkt anders.',
  },
  {
    id: 'traditie',
    word: 'traditie',
    level: 'B1',
    theme: 'overig',
    exampleSentence: 'Het is een oude traditie.',
  },
  {
    id: 'toestand',
    word: 'toestand',
    level: 'B1',
    theme: 'overig',
    exampleSentence: 'De toestand is ernstig.',
  },
  {
    id: 'voorwaarde',
    word: 'voorwaarde',
    level: 'B1',
    theme: 'overig',
    exampleSentence: 'Onder welke voorwaarde mag het?',
  },
  {
    id: 'gelegenheid',
    word: 'gelegenheid',
    level: 'B1',
    theme: 'overig',
    exampleSentence: 'Bij deze gelegenheid wil ik iets zeggen.',
  },
  {
    id: 'gebeurtenis',
    word: 'gebeurtenis',
    level: 'B1',
    theme: 'overig',
    exampleSentence: 'Het was een bijzondere gebeurtenis.',
  },
  {
    id: 'middel',
    word: 'middel',
    level: 'B1',
    theme: 'overig',
    grammar: '(het)',
    exampleSentence: 'We hebben de middelen om het te doen.',
  },
  {
    id: 'maatregel',
    word: 'maatregel',
    level: 'B1',
    theme: 'overig',
    exampleSentence: 'De regering neemt maatregelen.',
  },
  {
    id: 'kracht',
    word: 'kracht',
    level: 'B1',
    theme: 'overig',
    exampleSentence: 'Zij heeft veel kracht.',
  },
  {
    id: 'macht',
    word: 'macht',
    level: 'B1',
    theme: 'overig',
    exampleSentence: 'De koning heeft symbolische macht.',
  },
  {
    id: 'belang',
    word: 'belang',
    level: 'B1',
    theme: 'overig',
    grammar: '(het)',
    exampleSentence: 'Het is in het belang van iedereen.',
  },
  {
    id: 'behoefte',
    word: 'behoefte',
    level: 'B1',
    theme: 'overig',
    exampleSentence: 'Er is behoefte aan meer woningen.',
  },
  {
    id: 'begrip',
    word: 'begrip',
    level: 'B1',
    theme: 'overig',
    grammar: '(het)',
    exampleSentence: 'Ik heb begrip voor je situatie.',
  },
  {
    id: 'gedrag',
    word: 'gedrag',
    level: 'B1',
    theme: 'overig',
    grammar: '(het)',
    exampleSentence: 'Zijn gedrag is niet acceptabel.',
  },
  {
    id: 'houding',
    word: 'houding',
    level: 'B1',
    theme: 'overig',
    exampleSentence: 'Ze heeft een positieve houding.',
  },
  {
    id: 'inzicht',
    word: 'inzicht',
    level: 'B1',
    theme: 'overig',
    grammar: '(het)',
    exampleSentence: 'Ik heb nu meer inzicht.',
  },
  {
    id: 'opvatting',
    word: 'opvatting',
    level: 'B1',
    theme: 'overig',
    exampleSentence: 'Dat is een moderne opvatting.',
  },
  {
    id: 'vertrouwen',
    word: 'vertrouwen',
    level: 'B1',
    theme: 'overig',
    grammar: '(het)',
    exampleSentence: 'Ik heb vertrouwen in je.',
  },
  {
    id: 'waarschijnlijk',
    word: 'waarschijnlijk',
    level: 'B1',
    theme: 'overig',
    exampleSentence: 'Het regent waarschijnlijk morgen.',
  },
  {
    id: 'uiteindelijk',
    word: 'uiteindelijk',
    level: 'B1',
    theme: 'overig',
    exampleSentence: 'Uiteindelijk is alles goed gekomen.',
  },
  {
    id: 'tegenwoordig',
    word: 'tegenwoordig',
    level: 'B1',
    theme: 'overig',
    exampleSentence: 'Tegenwoordig werken veel mensen thuis.',
  },
  {
    id: 'voorlopig',
    word: 'voorlopig',
    level: 'B1',
    theme: 'overig',
    exampleSentence: 'We blijven voorlopig hier.',
  },
  {
    id: 'inmiddels',
    word: 'inmiddels',
    level: 'B1',
    theme: 'overig',
    exampleSentence: 'Inmiddels weet iedereen het.',
  },
  {
    id: 'overigens',
    word: 'overigens',
    level: 'B1',
    theme: 'overig',
    exampleSentence: 'Overigens, heb je het gehoord?',
  },
  {
    id: 'namelijk',
    word: 'namelijk',
    level: 'B1',
    theme: 'overig',
    exampleSentence: 'Ik kan niet komen, ik ben namelijk ziek.',
  },
  {
    id: 'weliswaar',
    word: 'weliswaar',
    level: 'B1',
    theme: 'overig',
    exampleSentence: 'Het is weliswaar duur, maar goed.',
  },
  {
    id: 'immers',
    word: 'immers',
    level: 'B1',
    theme: 'overig',
    exampleSentence: 'Het is immers niet zijn schuld.',
  },
  {
    id: 'ondanks',
    word: 'ondanks',
    level: 'B1',
    theme: 'overig',
    exampleSentence: 'Ondanks de regen gaan we wandelen.',
  },
  {
    id: 'hoewel',
    word: 'hoewel',
    level: 'B1',
    theme: 'overig',
    exampleSentence: 'Hoewel het regent, ga ik fietsen.',
  },
  {
    id: 'zodra',
    word: 'zodra',
    level: 'B1',
    theme: 'overig',
    exampleSentence: 'Zodra ik klaar ben, bel ik je.',
  },
  {
    id: 'tenzij',
    word: 'tenzij',
    level: 'B1',
    theme: 'overig',
    exampleSentence: 'Ik ga, tenzij het regent.',
  },
  {
    id: 'volkomen',
    word: 'volkomen',
    level: 'B1',
    theme: 'overig',
    exampleSentence: 'Ik ben het volkomen met je eens.',
  },
  {
    id: 'volledig',
    word: 'volledig',
    level: 'B1',
    theme: 'overig',
    exampleSentence: 'Het rapport is volledig.',
  },
  {
    id: 'aanzienlijk',
    word: 'aanzienlijk',
    level: 'B1',
    theme: 'overig',
    exampleSentence: 'De kosten zijn aanzienlijk.',
  },
  {
    id: 'behoorlijk',
    word: 'behoorlijk',
    level: 'B1',
    theme: 'overig',
    exampleSentence: 'Het is behoorlijk koud.',
  },
  {
    id: 'redelijk',
    word: 'redelijk',
    level: 'B1',
    theme: 'overig',
    exampleSentence: 'De prijs is redelijk.',
  },
  {
    id: 'tamelijk',
    word: 'tamelijk',
    level: 'B1',
    theme: 'overig',
    exampleSentence: 'Het is tamelijk ver.',
  },
  {
    id: 'nauwelijks',
    word: 'nauwelijks',
    level: 'B1',
    theme: 'overig',
    exampleSentence: 'Ik heb nauwelijks geslapen.',
  },
  {
    id: 'geleidelijk',
    word: 'geleidelijk',
    level: 'B1',
    theme: 'overig',
    exampleSentence: 'Het verbetert geleidelijk.',
  },
  {
    id: 'voortdurend',
    word: 'voortdurend',
    level: 'B1',
    theme: 'overig',
    exampleSentence: 'De telefoon gaat voortdurend.',
  },
  {
    id: 'onafhankelijk',
    word: 'onafhankelijk',
    level: 'B1',
    theme: 'overig',
    exampleSentence: 'Zij is financieel onafhankelijk.',
  },
  {
    id: 'noodzakelijk',
    word: 'noodzakelijk',
    level: 'B1',
    theme: 'overig',
    exampleSentence: 'Dat is noodzakelijk.',
  },
  {
    id: 'geschikt',
    word: 'geschikt',
    level: 'B1',
    theme: 'overig',
    exampleSentence: 'Dit is een geschikt moment.',
  },
  {
    id: 'ingewikkeld',
    word: 'ingewikkeld',
    level: 'B1',
    theme: 'overig',
    exampleSentence: 'Het probleem is ingewikkeld.',
  },
  {
    id: 'praktisch',
    word: 'praktisch',
    level: 'B1',
    theme: 'overig',
    exampleSentence: 'Dat is een praktische oplossing.',
  },
  {
    id: 'logisch',
    word: 'logisch',
    level: 'B1',
    theme: 'overig',
    exampleSentence: 'Dat is heel logisch.',
  },
  {
    id: 'ernstig',
    word: 'ernstig',
    level: 'B1',
    theme: 'overig',
    exampleSentence: 'Het is een ernstig probleem.',
  },
  {
    id: 'definitief',
    word: 'definitief',
    level: 'B1',
    theme: 'overig',
    exampleSentence: 'Het besluit is definitief.',
  },
  {
    id: 'wetenschap',
    word: 'wetenschap',
    level: 'B1',
    theme: 'overig',
    exampleSentence: 'De wetenschap ontdekt steeds meer.',
  },
  {
    id: 'technisch',
    word: 'technisch',
    level: 'B1',
    theme: 'overig',
    exampleSentence: 'Het is een technisch probleem.',
  },
  {
    id: 'financieel',
    word: 'financieel',
    level: 'B1',
    theme: 'overig',
    exampleSentence: 'De financiële situatie is moeilijk.',
  },
  {
    id: 'internationaal',
    word: 'internationaal',
    level: 'B1',
    theme: 'overig',
    exampleSentence: 'Het is een internationaal bedrijf.',
  },
  {
    id: 'milieu',
    word: 'milieu',
    level: 'B1',
    theme: 'overig',
    grammar: '(het)',
    exampleSentence: 'Het milieu moet beschermd worden.',
  },
  {
    id: 'natuur',
    word: 'natuur',
    level: 'B1',
    theme: 'overig',
    exampleSentence: 'De natuur is prachtig.',
  },
  {
    id: 'klimaat',
    word: 'klimaat',
    level: 'B1',
    theme: 'overig',
    grammar: '(het)',
    exampleSentence: 'Het klimaat verandert.',
  },
  {
    id: 'energie',
    word: 'energie',
    level: 'B1',
    theme: 'overig',
    exampleSentence: 'We moeten energie besparen.',
  },
];
