import type { PronunciationWord } from './types';

export const WORDS_B2: PronunciationWord[] = [
  // maatschappij & politiek
  {
    id: 'politiek-noun',
    word: 'politiek',
    level: 'B2',
    theme: 'maatschappij',
    exampleSentence: 'De politiek is complex.',
  },
  {
    id: 'parlement',
    word: 'parlement',
    level: 'B2',
    theme: 'maatschappij',
    grammar: '(het)',
    exampleSentence: 'Het parlement debatteert over de wet.',
  },
  {
    id: 'kabinet',
    word: 'kabinet',
    level: 'B2',
    theme: 'maatschappij',
    grammar: '(het)',
    exampleSentence: 'Het kabinet vergadert op vrijdag.',
  },
  {
    id: 'ministerie',
    word: 'ministerie',
    level: 'B2',
    theme: 'maatschappij',
    grammar: '(het)',
    exampleSentence: 'Het ministerie van Onderwijs beslist.',
  },
  {
    id: 'provincie',
    word: 'provincie',
    level: 'B2',
    theme: 'maatschappij',
    exampleSentence: 'Elke provincie heeft een eigen bestuur.',
  },
  {
    id: 'grondwet',
    word: 'grondwet',
    level: 'B2',
    theme: 'maatschappij',
    exampleSentence: 'De grondwet beschermt onze rechten.',
  },
  {
    id: 'revolutie',
    word: 'revolutie',
    level: 'B2',
    theme: 'maatschappij',
    exampleSentence: 'De industriële revolutie veranderde alles.',
  },
  {
    id: 'ideaal',
    word: 'ideaal',
    level: 'B2',
    theme: 'maatschappij',
    grammar: '(het)',
    exampleSentence: 'Gelijkheid is een belangrijk ideaal.',
  },
  {
    id: 'subsidie',
    word: 'subsidie',
    level: 'B2',
    theme: 'maatschappij',
    exampleSentence: 'Het project krijgt subsidie van de overheid.',
  },
  {
    id: 'initiatief',
    word: 'initiatief',
    level: 'B2',
    theme: 'maatschappij',
    grammar: '(het)',
    exampleSentence: 'Het is een goed initiatief.',
  },
  {
    id: 'crisis',
    word: 'crisis',
    level: 'B2',
    theme: 'maatschappij',
    exampleSentence: 'Het land zit in een economische crisis.',
  },
  {
    id: 'geweld',
    word: 'geweld',
    level: 'B2',
    theme: 'maatschappij',
    grammar: '(het)',
    exampleSentence: 'Geweld is nooit de oplossing.',
  },
  {
    id: 'verzet',
    word: 'verzet',
    level: 'B2',
    theme: 'maatschappij',
    grammar: '(het)',
    exampleSentence: 'Er was veel verzet tegen het plan.',
  },
  {
    id: 'staking',
    word: 'staking',
    level: 'B2',
    theme: 'maatschappij',
    exampleSentence: 'De werknemers gaan in staking.',
  },
  {
    id: 'individueel',
    word: 'individueel',
    level: 'B2',
    theme: 'maatschappij',
    exampleSentence: 'Dat is een individuele keuze.',
  },
  {
    id: 'gemeenschappelijk',
    word: 'gemeenschappelijk',
    level: 'B2',
    theme: 'maatschappij',
    exampleSentence: 'We hebben een gemeenschappelijk doel.',
  },
  {
    id: 'meerderheid',
    word: 'meerderheid',
    level: 'B2',
    theme: 'maatschappij',
    exampleSentence: 'De meerderheid stemde voor.',
  },
  {
    id: 'tegenstander',
    word: 'tegenstander',
    level: 'B2',
    theme: 'maatschappij',
    exampleSentence: 'De tegenstander is sterk.',
  },
  {
    id: 'voorstander',
    word: 'voorstander',
    level: 'B2',
    theme: 'maatschappij',
    exampleSentence: 'Ik ben voorstander van het plan.',
  },
  // formeel & abstract
  {
    id: 'consequentie',
    word: 'consequentie',
    level: 'B2',
    theme: 'formeel',
    exampleSentence: 'Je moet de consequenties accepteren.',
  },
  {
    id: 'verantwoordelijkheid',
    word: 'verantwoordelijkheid',
    level: 'B2',
    theme: 'formeel',
    exampleSentence: 'Dat is jouw verantwoordelijkheid.',
  },
  {
    id: 'beoordelen',
    word: 'beoordelen',
    level: 'B2',
    theme: 'formeel',
    exampleSentence: 'De jury beoordeelt de kandidaten.',
  },
  {
    id: 'constateren',
    word: 'constateren',
    level: 'B2',
    theme: 'formeel',
    exampleSentence: 'De arts constateert een breuk.',
  },
  {
    id: 'onderscheiden',
    word: 'onderscheiden',
    level: 'B2',
    theme: 'formeel',
    exampleSentence: 'Kun je de twee onderscheiden?',
  },
  {
    id: 'vergelijken',
    word: 'vergelijken',
    level: 'B2',
    theme: 'formeel',
    exampleSentence: 'Je kunt de twee niet vergelijken.',
  },
  {
    id: 'overwegen',
    word: 'overwegen',
    level: 'B2',
    theme: 'formeel',
    exampleSentence: 'Ik overweeg een andere baan.',
  },
  {
    id: 'handhaven',
    word: 'handhaven',
    level: 'B2',
    theme: 'formeel',
    exampleSentence: 'De politie handhaaft de regels.',
  },
  {
    id: 'vestigen',
    word: 'vestigen',
    level: 'B2',
    theme: 'formeel',
    exampleSentence: 'Het bedrijf vestigt zich in Amsterdam.',
  },
  {
    id: 'uitoefenen',
    word: 'uitoefenen',
    level: 'B2',
    theme: 'formeel',
    exampleSentence: 'Hij oefent druk uit.',
  },
  {
    id: 'uitbreiden',
    word: 'uitbreiden',
    level: 'B2',
    theme: 'formeel',
    exampleSentence: 'Het bedrijf wil uitbreiden.',
  },
  {
    id: 'versterken',
    word: 'versterken',
    level: 'B2',
    theme: 'formeel',
    exampleSentence: 'We moeten de samenwerking versterken.',
  },
  {
    id: 'vervangen',
    word: 'vervangen',
    level: 'B2',
    theme: 'formeel',
    exampleSentence: 'De machine moet vervangen worden.',
  },
  {
    id: 'invoeren',
    word: 'invoeren',
    level: 'B2',
    theme: 'formeel',
    exampleSentence: 'De school voert nieuwe regels in.',
  },
  {
    id: 'toepassen',
    word: 'toepassen',
    level: 'B2',
    theme: 'formeel',
    exampleSentence: 'We passen deze methode toe.',
  },
  {
    id: 'vertalen',
    word: 'vertalen',
    level: 'B2',
    theme: 'formeel',
    exampleSentence: 'Kun je dit vertalen?',
  },
  {
    id: 'publiceren',
    word: 'publiceren',
    level: 'B2',
    theme: 'formeel',
    exampleSentence: 'De krant publiceert het artikel.',
  },
  {
    id: 'realiseren',
    word: 'realiseren',
    level: 'B2',
    theme: 'formeel',
    exampleSentence: 'Ik realiseer me dat het moeilijk is.',
  },
  {
    id: 'aanvaarden',
    word: 'aanvaarden',
    level: 'B2',
    theme: 'formeel',
    exampleSentence: 'Ik aanvaard de gevolgen.',
  },
  {
    id: 'beperking',
    word: 'beperking',
    level: 'B2',
    theme: 'formeel',
    exampleSentence: 'Er is een beperking op het aantal.',
  },
  {
    id: 'bijdrage',
    word: 'bijdrage',
    level: 'B2',
    theme: 'formeel',
    exampleSentence: 'Bedankt voor je bijdrage.',
  },
  {
    id: 'overeenkomst',
    word: 'overeenkomst',
    level: 'B2',
    theme: 'formeel',
    exampleSentence: 'We hebben een overeenkomst getekend.',
  },
  {
    id: 'regeling',
    word: 'regeling',
    level: 'B2',
    theme: 'formeel',
    exampleSentence: 'Er is een nieuwe regeling.',
  },
  // mening & redeneren
  {
    id: 'abstract',
    word: 'abstract',
    level: 'B2',
    theme: 'mening',
    exampleSentence: 'Het is een abstract begrip.',
  },
  {
    id: 'objectief',
    word: 'objectief',
    level: 'B2',
    theme: 'mening',
    exampleSentence: 'Probeer objectief te blijven.',
  },
  {
    id: 'subjectief',
    word: 'subjectief',
    level: 'B2',
    theme: 'mening',
    exampleSentence: 'Schoonheid is subjectief.',
  },
  {
    id: 'nuance',
    word: 'nuance',
    level: 'B2',
    theme: 'mening',
    exampleSentence: 'Er zijn veel nuances in dit debat.',
  },
  {
    id: 'paradox',
    word: 'paradox',
    level: 'B2',
    theme: 'mening',
    exampleSentence: 'Het is een interessante paradox.',
  },
  {
    id: 'hypothese',
    word: 'hypothese',
    level: 'B2',
    theme: 'mening',
    exampleSentence: 'De hypothese moet getest worden.',
  },
  {
    id: 'theorie',
    word: 'theorie',
    level: 'B2',
    theme: 'mening',
    exampleSentence: 'In theorie is het mogelijk.',
  },
  {
    id: 'analyse',
    word: 'analyse',
    level: 'B2',
    theme: 'mening',
    exampleSentence: 'De analyse toont interessante resultaten.',
  },
  {
    id: 'interpretatie',
    word: 'interpretatie',
    level: 'B2',
    theme: 'mening',
    exampleSentence: 'Dat is jouw interpretatie.',
  },
  {
    id: 'perspectief',
    word: 'perspectief',
    level: 'B2',
    theme: 'mening',
    grammar: '(het)',
    exampleSentence: 'Vanuit dit perspectief is het logisch.',
  },
  {
    id: 'dilemma',
    word: 'dilemma',
    level: 'B2',
    theme: 'mening',
    grammar: '(het)',
    exampleSentence: 'Het is een moreel dilemma.',
  },
  {
    id: 'complexiteit',
    word: 'complexiteit',
    level: 'B2',
    theme: 'mening',
    exampleSentence: 'De complexiteit is hoog.',
  },
  {
    id: 'betrouwbaar',
    word: 'betrouwbaar',
    level: 'B2',
    theme: 'mening',
    exampleSentence: 'De bron is betrouwbaar.',
  },
  {
    id: 'vermoedelijk',
    word: 'vermoedelijk',
    level: 'B2',
    theme: 'mening',
    exampleSentence: 'Het is vermoedelijk waar.',
  },
  {
    id: 'ongetwijfeld',
    word: 'ongetwijfeld',
    level: 'B2',
    theme: 'mening',
    exampleSentence: 'Dat is ongetwijfeld waar.',
  },
  // wetenschap & kennis
  {
    id: 'wetenschappelijk',
    word: 'wetenschappelijk',
    level: 'B2',
    theme: 'overig',
    exampleSentence: 'Het is wetenschappelijk bewezen.',
  },
  {
    id: 'onderneming',
    word: 'onderneming',
    level: 'B2',
    theme: 'overig',
    exampleSentence: 'Het is een ambitieuze onderneming.',
  },
  {
    id: 'verschijnsel',
    word: 'verschijnsel',
    level: 'B2',
    theme: 'overig',
    grammar: '(het)',
    exampleSentence: 'Het is een natuurlijk verschijnsel.',
  },
  {
    id: 'fenomeen',
    word: 'fenomeen',
    level: 'B2',
    theme: 'overig',
    grammar: '(het)',
    exampleSentence: 'Het is een bijzonder fenomeen.',
  },
  {
    id: 'oorspronkelijk',
    word: 'oorspronkelijk',
    level: 'B2',
    theme: 'overig',
    exampleSentence: 'Het oorspronkelijke plan was anders.',
  },
  {
    id: 'fundamenteel',
    word: 'fundamenteel',
    level: 'B2',
    theme: 'overig',
    exampleSentence: 'Het is een fundamenteel probleem.',
  },
  {
    id: 'wezenlijk',
    word: 'wezenlijk',
    level: 'B2',
    theme: 'overig',
    exampleSentence: 'Er is een wezenlijk verschil.',
  },
  {
    id: 'kenmerkend',
    word: 'kenmerkend',
    level: 'B2',
    theme: 'overig',
    exampleSentence: 'Dat is kenmerkend voor deze stijl.',
  },
  {
    id: 'doorslaggevend',
    word: 'doorslaggevend',
    level: 'B2',
    theme: 'overig',
    exampleSentence: 'Het was doorslaggevend voor het resultaat.',
  },
  {
    id: 'uiterst',
    word: 'uiterst',
    level: 'B2',
    theme: 'overig',
    exampleSentence: 'Het is uiterst belangrijk.',
  },
  {
    id: 'uitsluitend',
    word: 'uitsluitend',
    level: 'B2',
    theme: 'overig',
    exampleSentence: 'Dit is uitsluitend voor leden.',
  },
  {
    id: 'voornamelijk',
    word: 'voornamelijk',
    level: 'B2',
    theme: 'overig',
    exampleSentence: 'Het bestaat voornamelijk uit hout.',
  },
  {
    id: 'hoofdzakelijk',
    word: 'hoofdzakelijk',
    level: 'B2',
    theme: 'overig',
    exampleSentence: 'De bevolking is hoofdzakelijk stedelijk.',
  },
  {
    id: 'anderzijds',
    word: 'anderzijds',
    level: 'B2',
    theme: 'overig',
    exampleSentence: 'Enerzijds is het goed, anderzijds niet.',
  },
  {
    id: 'enerzijds',
    word: 'enerzijds',
    level: 'B2',
    theme: 'overig',
    exampleSentence: 'Enerzijds begrijp ik het.',
  },
  {
    id: 'desondanks',
    word: 'desondanks',
    level: 'B2',
    theme: 'overig',
    exampleSentence: 'Desondanks gaan we door.',
  },
  {
    id: 'niettemin',
    word: 'niettemin',
    level: 'B2',
    theme: 'overig',
    exampleSentence: 'Het is moeilijk; niettemin probeer ik het.',
  },
  {
    id: 'aldus',
    word: 'aldus',
    level: 'B2',
    theme: 'overig',
    exampleSentence: 'Aldus de minister.',
  },
  {
    id: 'derhalve',
    word: 'derhalve',
    level: 'B2',
    theme: 'overig',
    exampleSentence: 'Derhalve is het niet mogelijk.',
  },
  {
    id: 'wellicht',
    word: 'wellicht',
    level: 'B2',
    theme: 'overig',
    exampleSentence: 'Wellicht is er een andere oplossing.',
  },
  {
    id: 'vanzelfsprekend',
    word: 'vanzelfsprekend',
    level: 'B2',
    theme: 'overig',
    exampleSentence: 'Het is niet vanzelfsprekend.',
  },
  {
    id: 'onvermijdelijk',
    word: 'onvermijdelijk',
    level: 'B2',
    theme: 'overig',
    exampleSentence: 'De verandering was onvermijdelijk.',
  },
  {
    id: 'onomkeerbaar',
    word: 'onomkeerbaar',
    level: 'B2',
    theme: 'overig',
    exampleSentence: 'De schade is onomkeerbaar.',
  },
  {
    id: 'duurzaam',
    word: 'duurzaam',
    level: 'B2',
    theme: 'overig',
    exampleSentence: 'We streven naar duurzame energie.',
  },
  {
    id: 'eventueel',
    word: 'eventueel',
    level: 'B2',
    theme: 'overig',
    exampleSentence: 'Ik kan eventueel helpen.',
  },
  {
    id: 'geleidelijk-b2',
    word: 'geleidelijk',
    level: 'B2',
    theme: 'overig',
    exampleSentence: 'De verandering gaat geleidelijk.',
  },
  {
    id: 'ingrijpend',
    word: 'ingrijpend',
    level: 'B2',
    theme: 'overig',
    exampleSentence: 'Het is een ingrijpende beslissing.',
  },
  {
    id: 'omvangrijk',
    word: 'omvangrijk',
    level: 'B2',
    theme: 'overig',
    exampleSentence: 'Het project is omvangrijk.',
  },
  {
    id: 'veelzijdig',
    word: 'veelzijdig',
    level: 'B2',
    theme: 'overig',
    exampleSentence: 'Zij is een veelzijdig persoon.',
  },
  {
    id: 'uitvoerig',
    word: 'uitvoerig',
    level: 'B2',
    theme: 'overig',
    exampleSentence: 'Het rapport is zeer uitvoerig.',
  },
  {
    id: 'zorgvuldig',
    word: 'zorgvuldig',
    level: 'B2',
    theme: 'overig',
    exampleSentence: 'We moeten zorgvuldig te werk gaan.',
  },
  {
    id: 'betrekkelijk',
    word: 'betrekkelijk',
    level: 'B2',
    theme: 'overig',
    exampleSentence: 'Het is betrekkelijk eenvoudig.',
  },
  {
    id: 'onmiddellijk',
    word: 'onmiddellijk',
    level: 'B2',
    theme: 'overig',
    exampleSentence: 'Het effect is onmiddellijk zichtbaar.',
  },
  {
    id: 'voorzichtig',
    word: 'voorzichtig',
    level: 'B2',
    theme: 'overig',
    exampleSentence: 'Wees voorzichtig met die informatie.',
  },
  {
    id: 'verstandig',
    word: 'verstandig',
    level: 'B2',
    theme: 'overig',
    exampleSentence: 'Dat is een verstandige beslissing.',
  },
  {
    id: 'merkwaardig',
    word: 'merkwaardig',
    level: 'B2',
    theme: 'overig',
    exampleSentence: 'Het is een merkwaardig verhaal.',
  },
  {
    id: 'opmerkelijk',
    word: 'opmerkelijk',
    level: 'B2',
    theme: 'overig',
    exampleSentence: 'De groei is opmerkelijk.',
  },
  {
    id: 'uitstekend',
    word: 'uitstekend',
    level: 'B2',
    theme: 'overig',
    exampleSentence: 'Het resultaat is uitstekend.',
  },
  {
    id: 'schitterend',
    word: 'schitterend',
    level: 'B2',
    theme: 'overig',
    exampleSentence: 'Het uitzicht is schitterend.',
  },
];
