import type { PronunciationWord } from './types';

export const WORDS_A1: PronunciationWord[] = [
  // kennismaken
  {
    id: 'hallo',
    word: 'hallo',
    level: 'A1',
    theme: 'kennismaken',
    exampleSentence: 'Hallo, hoe gaat het?',
  },
  {
    id: 'goedemorgen',
    word: 'goedemorgen',
    level: 'A1',
    theme: 'kennismaken',
    exampleSentence: 'Goedemorgen, hoe gaat het?',
  },
  {
    id: 'goedemiddag',
    word: 'goedemiddag',
    level: 'A1',
    theme: 'kennismaken',
    exampleSentence: 'Goedemiddag, kan ik u helpen?',
  },
  {
    id: 'goedenavond',
    word: 'goedenavond',
    level: 'A1',
    theme: 'kennismaken',
    exampleSentence: 'Goedenavond, welkom in het restaurant.',
  },
  {
    id: 'goedendag',
    word: 'goedendag',
    level: 'A1',
    theme: 'kennismaken',
    exampleSentence: 'Goedendag, ik ben Jan.',
  },
  {
    id: 'goedenacht',
    word: 'goedenacht',
    level: 'A1',
    theme: 'kennismaken',
    exampleSentence: 'Goedenacht, slaap lekker.',
  },
  {
    id: 'welterusten',
    word: 'welterusten',
    level: 'A1',
    theme: 'kennismaken',
    exampleSentence: 'Welterusten, tot morgen.',
  },
  {
    id: 'naam',
    word: 'naam',
    level: 'A1',
    theme: 'kennismaken',
    exampleSentence: 'Mijn naam is Maria.',
  },
  {
    id: 'heten',
    word: 'heten',
    level: 'A1',
    theme: 'kennismaken',
    exampleSentence: 'Ik heet Jan.',
  },
  {
    id: 'kennen',
    word: 'kennen',
    level: 'A1',
    theme: 'kennismaken',
    exampleSentence: 'Ken je mijn buurman?',
  },
  {
    id: 'kennismaken',
    word: 'kennismaken',
    level: 'A1',
    theme: 'kennismaken',
    exampleSentence: 'Leuk om kennis te maken.',
  },
  {
    id: 'meneer',
    word: 'meneer',
    level: 'A1',
    theme: 'kennismaken',
    exampleSentence: 'Goedemorgen, meneer.',
  },
  {
    id: 'mevrouw',
    word: 'mevrouw',
    level: 'A1',
    theme: 'kennismaken',
    exampleSentence: 'Dag mevrouw, hoe gaat het?',
  },
  {
    id: 'juffrouw',
    word: 'juffrouw',
    level: 'A1',
    theme: 'kennismaken',
    exampleSentence: 'De juffrouw helpt ons.',
  },
  {
    id: 'sorry',
    word: 'sorry',
    level: 'A1',
    theme: 'kennismaken',
    exampleSentence: 'Sorry, dat was mijn fout.',
  },
  {
    id: 'pardon',
    word: 'pardon',
    level: 'A1',
    theme: 'kennismaken',
    exampleSentence: 'Pardon, waar is de uitgang?',
  },
  {
    id: 'alsjeblieft',
    word: 'alsjeblieft',
    level: 'A1',
    theme: 'kennismaken',
    exampleSentence: 'Hier is je koffie, alsjeblieft.',
  },
  {
    id: 'alstublieft',
    word: 'alstublieft',
    level: 'A1',
    theme: 'kennismaken',
    exampleSentence: 'Uw rekening, alstublieft.',
  },
  { id: 'dank', word: 'dank', level: 'A1', theme: 'kennismaken', exampleSentence: 'Dank je wel!' },
  {
    id: 'danken',
    word: 'danken',
    level: 'A1',
    theme: 'kennismaken',
    exampleSentence: 'Ik wil je danken voor je hulp.',
  },
  {
    id: 'dankbaar',
    word: 'dankbaar',
    level: 'A1',
    theme: 'kennismaken',
    exampleSentence: 'Ik ben heel dankbaar.',
  },
  {
    id: 'groet',
    word: 'groet',
    level: 'A1',
    theme: 'kennismaken',
    exampleSentence: 'Doe de groeten aan je moeder.',
  },
  {
    id: 'groeten',
    word: 'groeten',
    level: 'A1',
    theme: 'kennismaken',
    exampleSentence: 'Ik groet mijn buren elke dag.',
  },
  {
    id: 'ja',
    word: 'ja',
    level: 'A1',
    theme: 'kennismaken',
    exampleSentence: 'Ja, ik wil koffie.',
  },
  {
    id: 'jawel',
    word: 'jawel',
    level: 'A1',
    theme: 'kennismaken',
    exampleSentence: 'Jawel, ik heb het gezien.',
  },
  { id: 'nee', word: 'nee', level: 'A1', theme: 'kennismaken', exampleSentence: 'Nee, dank je.' },
  // familie
  {
    id: 'familie',
    word: 'familie',
    level: 'A1',
    theme: 'familie',
    exampleSentence: 'Mijn familie woont in Leiden.',
  },
  {
    id: 'vader',
    word: 'vader',
    level: 'A1',
    theme: 'familie',
    exampleSentence: 'Mijn vader werkt in Amsterdam.',
  },
  {
    id: 'moeder',
    word: 'moeder',
    level: 'A1',
    theme: 'familie',
    exampleSentence: 'Mijn moeder kookt elke dag.',
  },
  { id: 'pa', word: 'pa', level: 'A1', theme: 'familie', exampleSentence: 'Pa, kom je eten?' },
  {
    id: 'papa',
    word: 'papa',
    level: 'A1',
    theme: 'familie',
    exampleSentence: 'Papa leest de krant.',
  },
  { id: 'ma', word: 'ma', level: 'A1', theme: 'familie', exampleSentence: 'Ma, waar is mijn jas?' },
  {
    id: 'mama',
    word: 'mama',
    level: 'A1',
    theme: 'familie',
    exampleSentence: 'Mama helpt met huiswerk.',
  },
  {
    id: 'broer',
    word: 'broer',
    level: 'A1',
    theme: 'familie',
    exampleSentence: 'Mijn broer is tien jaar oud.',
  },
  {
    id: 'zus',
    word: 'zus',
    level: 'A1',
    theme: 'familie',
    exampleSentence: 'Mijn zus woont in Den Haag.',
  },
  {
    id: 'zuster',
    word: 'zuster',
    level: 'A1',
    theme: 'familie',
    exampleSentence: 'Mijn zuster is verpleegster.',
  },
  {
    id: 'kind',
    word: 'kind',
    level: 'A1',
    theme: 'familie',
    grammar: '(het)',
    exampleSentence: 'Het kind speelt in de tuin.',
  },
  { id: 'baby', word: 'baby', level: 'A1', theme: 'familie', exampleSentence: 'De baby slaapt.' },
  {
    id: 'zoon',
    word: 'zoon',
    level: 'A1',
    theme: 'familie',
    exampleSentence: 'Mijn zoon gaat naar school.',
  },
  {
    id: 'dochter',
    word: 'dochter',
    level: 'A1',
    theme: 'familie',
    exampleSentence: 'Mijn dochter houdt van lezen.',
  },
  { id: 'oma', word: 'oma', level: 'A1', theme: 'familie', exampleSentence: 'Oma bakt een taart.' },
  {
    id: 'opa',
    word: 'opa',
    level: 'A1',
    theme: 'familie',
    exampleSentence: 'Opa vertelt verhalen.',
  },
  {
    id: 'oom',
    word: 'oom',
    level: 'A1',
    theme: 'familie',
    exampleSentence: 'Mijn oom woont in Rotterdam.',
  },
  {
    id: 'tante',
    word: 'tante',
    level: 'A1',
    theme: 'familie',
    exampleSentence: 'Tante komt morgen op bezoek.',
  },
  {
    id: 'man',
    word: 'man',
    level: 'A1',
    theme: 'familie',
    exampleSentence: 'Mijn man werkt bij de bank.',
  },
  {
    id: 'vrouw',
    word: 'vrouw',
    level: 'A1',
    theme: 'familie',
    exampleSentence: 'De vrouw leest een boek.',
  },
  {
    id: 'vriend',
    word: 'vriend',
    level: 'A1',
    theme: 'familie',
    exampleSentence: 'Mijn vriend heet Pieter.',
  },
  {
    id: 'vriendin',
    word: 'vriendin',
    level: 'A1',
    theme: 'familie',
    exampleSentence: 'Mijn vriendin komt uit België.',
  },
  {
    id: 'ouder',
    word: 'ouder',
    level: 'A1',
    theme: 'familie',
    exampleSentence: 'Mijn ouders wonen in Utrecht.',
  },
  {
    id: 'buur',
    word: 'buur',
    level: 'A1',
    theme: 'familie',
    exampleSentence: 'De buur is heel aardig.',
  },
  {
    id: 'jongen',
    word: 'jongen',
    level: 'A1',
    theme: 'familie',
    exampleSentence: 'De jongen speelt buiten.',
  },
  {
    id: 'meisje',
    word: 'meisje',
    level: 'A1',
    theme: 'familie',
    grammar: '(het)',
    exampleSentence: 'Het meisje zingt een liedje.',
  },
  {
    id: 'mens',
    word: 'mens',
    level: 'A1',
    theme: 'familie',
    exampleSentence: 'De mens leeft op aarde.',
  },
  {
    id: 'dame',
    word: 'dame',
    level: 'A1',
    theme: 'familie',
    exampleSentence: 'De dame draagt een rode jas.',
  },
  {
    id: 'heer',
    word: 'heer',
    level: 'A1',
    theme: 'familie',
    exampleSentence: 'De heer wacht bij de deur.',
  },
  {
    id: 'trouwen',
    word: 'trouwen',
    level: 'A1',
    theme: 'familie',
    exampleSentence: 'Zij gaan volgend jaar trouwen.',
  },
  {
    id: 'getrouwd',
    word: 'getrouwd',
    level: 'A1',
    theme: 'familie',
    exampleSentence: 'Ik ben al tien jaar getrouwd.',
  },
  // wonen
  {
    id: 'huis',
    word: 'huis',
    level: 'A1',
    theme: 'wonen',
    grammar: '(het)',
    exampleSentence: 'Ons huis is groot.',
  },
  {
    id: 'wonen',
    word: 'wonen',
    level: 'A1',
    theme: 'wonen',
    exampleSentence: 'Ik woon in Leiden.',
  },
  {
    id: 'woning',
    word: 'woning',
    level: 'A1',
    theme: 'wonen',
    exampleSentence: 'De woning heeft drie kamers.',
  },
  {
    id: 'kamer',
    word: 'kamer',
    level: 'A1',
    theme: 'wonen',
    exampleSentence: 'De kamer is gezellig.',
  },
  {
    id: 'huiskamer',
    word: 'huiskamer',
    level: 'A1',
    theme: 'wonen',
    exampleSentence: 'We zitten in de huiskamer.',
  },
  {
    id: 'keuken',
    word: 'keuken',
    level: 'A1',
    theme: 'wonen',
    exampleSentence: 'Ik kook in de keuken.',
  },
  {
    id: 'bad',
    word: 'bad',
    level: 'A1',
    theme: 'wonen',
    grammar: '(het)',
    exampleSentence: 'Het bad is warm.',
  },
  {
    id: 'douche',
    word: 'douche',
    level: 'A1',
    theme: 'wonen',
    exampleSentence: 'Ik neem een douche.',
  },
  {
    id: 'bed',
    word: 'bed',
    level: 'A1',
    theme: 'wonen',
    grammar: '(het)',
    exampleSentence: 'Ik ga naar bed.',
  },
  {
    id: 'stoel',
    word: 'stoel',
    level: 'A1',
    theme: 'wonen',
    exampleSentence: 'Ga op de stoel zitten.',
  },
  {
    id: 'tafel',
    word: 'tafel',
    level: 'A1',
    theme: 'wonen',
    exampleSentence: 'Het eten staat op de tafel.',
  },
  { id: 'deur', word: 'deur', level: 'A1', theme: 'wonen', exampleSentence: 'Doe de deur dicht.' },
  {
    id: 'raam',
    word: 'raam',
    level: 'A1',
    theme: 'wonen',
    grammar: '(het)',
    exampleSentence: 'Het raam is open.',
  },
  {
    id: 'dak',
    word: 'dak',
    level: 'A1',
    theme: 'wonen',
    grammar: '(het)',
    exampleSentence: 'Het dak is rood.',
  },
  { id: 'muur', word: 'muur', level: 'A1', theme: 'wonen', exampleSentence: 'De muur is wit.' },
  {
    id: 'vloer',
    word: 'vloer',
    level: 'A1',
    theme: 'wonen',
    exampleSentence: 'De vloer is schoon.',
  },
  { id: 'trap', word: 'trap', level: 'A1', theme: 'wonen', exampleSentence: 'Ik loop de trap op.' },
  {
    id: 'tuin',
    word: 'tuin',
    level: 'A1',
    theme: 'wonen',
    exampleSentence: 'De kinderen spelen in de tuin.',
  },
  {
    id: 'flat',
    word: 'flat',
    level: 'A1',
    theme: 'wonen',
    exampleSentence: 'Ik woon in een flat.',
  },
  {
    id: 'buurt',
    word: 'buurt',
    level: 'A1',
    theme: 'wonen',
    exampleSentence: 'De buurt is rustig.',
  },
  {
    id: 'straat',
    word: 'straat',
    level: 'A1',
    theme: 'wonen',
    exampleSentence: 'De straat is lang.',
  },
  {
    id: 'adres',
    word: 'adres',
    level: 'A1',
    theme: 'wonen',
    grammar: '(het)',
    exampleSentence: 'Wat is je adres?',
  },
  {
    id: 'sleutel',
    word: 'sleutel',
    level: 'A1',
    theme: 'wonen',
    exampleSentence: 'Waar is de sleutel?',
  },
  { id: 'lamp', word: 'lamp', level: 'A1', theme: 'wonen', exampleSentence: 'Doe de lamp aan.' },
  {
    id: 'kast',
    word: 'kast',
    level: 'A1',
    theme: 'wonen',
    exampleSentence: 'De kleren hangen in de kast.',
  },
  {
    id: 'gordijn',
    word: 'gordijn',
    level: 'A1',
    theme: 'wonen',
    grammar: '(het)',
    exampleSentence: 'Doe het gordijn dicht.',
  },
  {
    id: 'spiegel',
    word: 'spiegel',
    level: 'A1',
    theme: 'wonen',
    exampleSentence: 'Ik kijk in de spiegel.',
  },
  {
    id: 'klok',
    word: 'klok',
    level: 'A1',
    theme: 'wonen',
    exampleSentence: 'De klok hangt aan de muur.',
  },
  {
    id: 'bureau',
    word: 'bureau',
    level: 'A1',
    theme: 'wonen',
    grammar: '(het)',
    exampleSentence: 'Mijn computer staat op het bureau.',
  },
  { id: 'wc', word: 'wc', level: 'A1', theme: 'wonen', exampleSentence: 'Waar is de wc?' },
  { id: 'huren', word: 'huren', level: 'A1', theme: 'wonen', exampleSentence: 'Ik huur een huis.' },
  {
    id: 'huur',
    word: 'huur',
    level: 'A1',
    theme: 'wonen',
    exampleSentence: 'De huur is vijfhonderd euro.',
  },
  // eten
  {
    id: 'eten-noun',
    word: 'eten',
    level: 'A1',
    theme: 'eten',
    grammar: '(het)',
    exampleSentence: 'Het eten is lekker.',
  },
  {
    id: 'eten-verb',
    word: 'eten',
    level: 'A1',
    theme: 'eten',
    exampleSentence: 'Ik eet een boterham.',
  },
  {
    id: 'drinken',
    word: 'drinken',
    level: 'A1',
    theme: 'eten',
    exampleSentence: 'Ik drink water.',
  },
  {
    id: 'water',
    word: 'water',
    level: 'A1',
    theme: 'eten',
    grammar: '(het)',
    exampleSentence: 'Mag ik een glas water?',
  },
  {
    id: 'brood',
    word: 'brood',
    level: 'A1',
    theme: 'eten',
    grammar: '(het)',
    exampleSentence: 'Ik eet brood met kaas.',
  },
  {
    id: 'broodje',
    word: 'broodje',
    level: 'A1',
    theme: 'eten',
    grammar: '(het)',
    exampleSentence: 'Ik wil een broodje ham.',
  },
  {
    id: 'boterham',
    word: 'boterham',
    level: 'A1',
    theme: 'eten',
    exampleSentence: 'Ik eet een boterham met pindakaas.',
  },
  {
    id: 'kaas',
    word: 'kaas',
    level: 'A1',
    theme: 'eten',
    exampleSentence: 'Nederlandse kaas is lekker.',
  },
  {
    id: 'melk',
    word: 'melk',
    level: 'A1',
    theme: 'eten',
    exampleSentence: 'Het kind drinkt melk.',
  },
  {
    id: 'koffie',
    word: 'koffie',
    level: 'A1',
    theme: 'eten',
    exampleSentence: 'Wil je een kopje koffie?',
  },
  {
    id: 'thee',
    word: 'thee',
    level: 'A1',
    theme: 'eten',
    exampleSentence: 'Ik drink thee met suiker.',
  },
  {
    id: 'bier',
    word: 'bier',
    level: 'A1',
    theme: 'eten',
    grammar: '(het)',
    exampleSentence: 'Hij drinkt een glas bier.',
  },
  {
    id: 'wijn',
    word: 'wijn',
    level: 'A1',
    theme: 'eten',
    exampleSentence: 'Wil je rode of witte wijn?',
  },
  {
    id: 'suiker',
    word: 'suiker',
    level: 'A1',
    theme: 'eten',
    exampleSentence: 'Hoeveel suiker wil je?',
  },
  {
    id: 'zout',
    word: 'zout',
    level: 'A1',
    theme: 'eten',
    grammar: '(het)',
    exampleSentence: 'Geef me het zout, alsjeblieft.',
  },
  {
    id: 'ei',
    word: 'ei',
    level: 'A1',
    theme: 'eten',
    grammar: '(het)',
    exampleSentence: 'Ik eet een gekookt ei.',
  },
  { id: 'appel', word: 'appel', level: 'A1', theme: 'eten', exampleSentence: 'De appel is rood.' },
  {
    id: 'citroen',
    word: 'citroen',
    level: 'A1',
    theme: 'eten',
    exampleSentence: 'De citroen is zuur.',
  },
  {
    id: 'fruit',
    word: 'fruit',
    level: 'A1',
    theme: 'eten',
    grammar: '(het)',
    exampleSentence: 'Fruit is gezond.',
  },
  {
    id: 'groente',
    word: 'groente',
    level: 'A1',
    theme: 'eten',
    exampleSentence: 'Ik eet elke dag groente.',
  },
  {
    id: 'aardappel',
    word: 'aardappel',
    level: 'A1',
    theme: 'eten',
    exampleSentence: 'We eten aardappelen bij het vlees.',
  },
  {
    id: 'vlees',
    word: 'vlees',
    level: 'A1',
    theme: 'eten',
    grammar: '(het)',
    exampleSentence: 'Ik eet geen vlees.',
  },
  {
    id: 'vis',
    word: 'vis',
    level: 'A1',
    theme: 'eten',
    exampleSentence: 'We eten vis op vrijdag.',
  },
  { id: 'kip', word: 'kip', level: 'A1', theme: 'eten', exampleSentence: 'De kip is bijna klaar.' },
  {
    id: 'rijst',
    word: 'rijst',
    level: 'A1',
    theme: 'eten',
    exampleSentence: 'Wij eten rijst met groente.',
  },
  {
    id: 'sla',
    word: 'sla',
    level: 'A1',
    theme: 'eten',
    exampleSentence: 'Ik maak een salade met sla.',
  },
  {
    id: 'friet',
    word: 'friet',
    level: 'A1',
    theme: 'eten',
    exampleSentence: 'Ik wil friet met mayo.',
  },
  {
    id: 'koek',
    word: 'koek',
    level: 'A1',
    theme: 'eten',
    exampleSentence: 'Wil je een stuk koek?',
  },
  {
    id: 'ijs',
    word: 'ijs',
    level: 'A1',
    theme: 'eten',
    grammar: '(het)',
    exampleSentence: 'In de zomer eet ik graag ijs.',
  },
  {
    id: 'snoep',
    word: 'snoep',
    level: 'A1',
    theme: 'eten',
    exampleSentence: 'De kinderen eten snoep.',
  },
  {
    id: 'lekker',
    word: 'lekker',
    level: 'A1',
    theme: 'eten',
    exampleSentence: 'Het eten is heel lekker.',
  },
  { id: 'koken', word: 'koken', level: 'A1', theme: 'eten', exampleSentence: 'Ik kook vanavond.' },
  { id: 'honger', word: 'honger', level: 'A1', theme: 'eten', exampleSentence: 'Ik heb honger.' },
  { id: 'dorst', word: 'dorst', level: 'A1', theme: 'eten', exampleSentence: 'Ik heb dorst.' },
  {
    id: 'ontbijt',
    word: 'ontbijt',
    level: 'A1',
    theme: 'eten',
    grammar: '(het)',
    exampleSentence: 'Het ontbijt is om acht uur.',
  },
  {
    id: 'maaltijd',
    word: 'maaltijd',
    level: 'A1',
    theme: 'eten',
    exampleSentence: 'De warme maaltijd is klaar.',
  },
  {
    id: 'bord',
    word: 'bord',
    level: 'A1',
    theme: 'eten',
    grammar: '(het)',
    exampleSentence: 'Zet het bord op tafel.',
  },
  {
    id: 'glas',
    word: 'glas',
    level: 'A1',
    theme: 'eten',
    grammar: '(het)',
    exampleSentence: 'Mag ik een glas water?',
  },
  {
    id: 'mes',
    word: 'mes',
    level: 'A1',
    theme: 'eten',
    grammar: '(het)',
    exampleSentence: 'Snijd het brood met een mes.',
  },
  {
    id: 'vork',
    word: 'vork',
    level: 'A1',
    theme: 'eten',
    exampleSentence: 'Ik eet met mes en vork.',
  },
  {
    id: 'lepel',
    word: 'lepel',
    level: 'A1',
    theme: 'eten',
    exampleSentence: 'Ik eet soep met een lepel.',
  },
  { id: 'kop', word: 'kop', level: 'A1', theme: 'eten', exampleSentence: 'Wil je een kop thee?' },
  {
    id: 'fles',
    word: 'fles',
    level: 'A1',
    theme: 'eten',
    exampleSentence: 'De fles water is leeg.',
  },
  { id: 'pot', word: 'pot', level: 'A1', theme: 'eten', exampleSentence: 'De soep zit in de pot.' },
  // boodschappen
  {
    id: 'winkel',
    word: 'winkel',
    level: 'A1',
    theme: 'boodschappen',
    exampleSentence: 'Ik ga naar de winkel.',
  },
  {
    id: 'supermarkt',
    word: 'supermarkt',
    level: 'A1',
    theme: 'boodschappen',
    exampleSentence: 'De supermarkt is dichtbij.',
  },
  {
    id: 'kopen',
    word: 'kopen',
    level: 'A1',
    theme: 'boodschappen',
    exampleSentence: 'Ik wil brood kopen.',
  },
  {
    id: 'betalen',
    word: 'betalen',
    level: 'A1',
    theme: 'boodschappen',
    exampleSentence: 'Ik wil graag betalen.',
  },
  {
    id: 'geld',
    word: 'geld',
    level: 'A1',
    theme: 'boodschappen',
    grammar: '(het)',
    exampleSentence: 'Ik heb geen geld bij me.',
  },
  {
    id: 'prijs',
    word: 'prijs',
    level: 'A1',
    theme: 'boodschappen',
    exampleSentence: 'Wat is de prijs?',
  },
  {
    id: 'duur',
    word: 'duur',
    level: 'A1',
    theme: 'boodschappen',
    exampleSentence: 'Dit is te duur.',
  },
  {
    id: 'goedkoop',
    word: 'goedkoop',
    level: 'A1',
    theme: 'boodschappen',
    exampleSentence: 'Deze schoenen zijn goedkoop.',
  },
  {
    id: 'gratis',
    word: 'gratis',
    level: 'A1',
    theme: 'boodschappen',
    exampleSentence: 'Het water is gratis.',
  },
  {
    id: 'boodschap',
    word: 'boodschap',
    level: 'A1',
    theme: 'boodschappen',
    exampleSentence: 'Ik doe boodschappen.',
  },
  {
    id: 'tas',
    word: 'tas',
    level: 'A1',
    theme: 'boodschappen',
    exampleSentence: 'Heb je een tas nodig?',
  },
  {
    id: 'bakker',
    word: 'bakker',
    level: 'A1',
    theme: 'boodschappen',
    exampleSentence: 'Ik koop brood bij de bakker.',
  },
  {
    id: 'slager',
    word: 'slager',
    level: 'A1',
    theme: 'boodschappen',
    exampleSentence: 'De slager heeft vers vlees.',
  },
  {
    id: 'groenteman',
    word: 'groenteman',
    level: 'A1',
    theme: 'boodschappen',
    exampleSentence: 'De groenteman staat op de markt.',
  },
  {
    id: 'markt',
    word: 'markt',
    level: 'A1',
    theme: 'boodschappen',
    exampleSentence: 'Op zaterdag ga ik naar de markt.',
  },
  {
    id: 'cent',
    word: 'cent',
    level: 'A1',
    theme: 'boodschappen',
    exampleSentence: 'Het kost vijftig cent.',
  },
  { id: 'bon', word: 'bon', level: 'A1', theme: 'boodschappen', exampleSentence: 'Wilt u de bon?' },
  // dagelijks leven
  {
    id: 'dag',
    word: 'dag',
    level: 'A1',
    theme: 'dagelijks',
    exampleSentence: 'Vandaag is een mooie dag.',
  },
  {
    id: 'ochtend',
    word: 'ochtend',
    level: 'A1',
    theme: 'dagelijks',
    exampleSentence: 'Ik sta vroeg op in de ochtend.',
  },
  {
    id: 'middag',
    word: 'middag',
    level: 'A1',
    theme: 'dagelijks',
    exampleSentence: "We eten om twaalf uur 's middags.",
  },
  {
    id: 'avond',
    word: 'avond',
    level: 'A1',
    theme: 'dagelijks',
    exampleSentence: 'In de avond kijk ik tv.',
  },
  {
    id: 'nacht',
    word: 'nacht',
    level: 'A1',
    theme: 'dagelijks',
    exampleSentence: 'In de nacht slaap ik.',
  },
  {
    id: 'vandaag',
    word: 'vandaag',
    level: 'A1',
    theme: 'dagelijks',
    exampleSentence: 'Vandaag is het maandag.',
  },
  {
    id: 'morgen-adv',
    word: 'morgen',
    level: 'A1',
    theme: 'dagelijks',
    exampleSentence: 'Morgen ga ik naar school.',
  },
  {
    id: 'gisteren',
    word: 'gisteren',
    level: 'A1',
    theme: 'dagelijks',
    exampleSentence: 'Gisteren was het mooi weer.',
  },
  { id: 'nu', word: 'nu', level: 'A1', theme: 'dagelijks', exampleSentence: 'Ik ben nu thuis.' },
  {
    id: 'altijd',
    word: 'altijd',
    level: 'A1',
    theme: 'dagelijks',
    exampleSentence: 'Ik drink altijd koffie.',
  },
  {
    id: 'soms',
    word: 'soms',
    level: 'A1',
    theme: 'dagelijks',
    exampleSentence: 'Soms ga ik met de bus.',
  },
  {
    id: 'nooit',
    word: 'nooit',
    level: 'A1',
    theme: 'dagelijks',
    exampleSentence: 'Ik eet nooit vlees.',
  },
  {
    id: 'vaak',
    word: 'vaak',
    level: 'A1',
    theme: 'dagelijks',
    exampleSentence: 'Ik kook vaak zelf.',
  },
  {
    id: 'tijd',
    word: 'tijd',
    level: 'A1',
    theme: 'dagelijks',
    exampleSentence: 'Ik heb geen tijd.',
  },
  {
    id: 'uur',
    word: 'uur',
    level: 'A1',
    theme: 'dagelijks',
    grammar: '(het)',
    exampleSentence: 'Het is drie uur.',
  },
  {
    id: 'week',
    word: 'week',
    level: 'A1',
    theme: 'dagelijks',
    exampleSentence: 'Volgende week heb ik vakantie.',
  },
  {
    id: 'maandag',
    word: 'maandag',
    level: 'A1',
    theme: 'dagelijks',
    exampleSentence: 'Op maandag werk ik.',
  },
  {
    id: 'dinsdag',
    word: 'dinsdag',
    level: 'A1',
    theme: 'dagelijks',
    exampleSentence: 'Op dinsdag ga ik sporten.',
  },
  {
    id: 'woensdag',
    word: 'woensdag',
    level: 'A1',
    theme: 'dagelijks',
    exampleSentence: 'Woensdag is mijn vrije dag.',
  },
  {
    id: 'donderdag',
    word: 'donderdag',
    level: 'A1',
    theme: 'dagelijks',
    exampleSentence: 'Op donderdag heb ik les.',
  },
  {
    id: 'vrijdag',
    word: 'vrijdag',
    level: 'A1',
    theme: 'dagelijks',
    exampleSentence: 'Vrijdag is het bijna weekend.',
  },
  {
    id: 'zaterdag',
    word: 'zaterdag',
    level: 'A1',
    theme: 'dagelijks',
    exampleSentence: 'Op zaterdag ga ik winkelen.',
  },
  {
    id: 'zondag',
    word: 'zondag',
    level: 'A1',
    theme: 'dagelijks',
    exampleSentence: 'Op zondag rust ik uit.',
  },
  {
    id: 'jaar',
    word: 'jaar',
    level: 'A1',
    theme: 'dagelijks',
    grammar: '(het)',
    exampleSentence: 'Ik ben dertig jaar oud.',
  },
  {
    id: 'januari',
    word: 'januari',
    level: 'A1',
    theme: 'dagelijks',
    exampleSentence: 'In januari is het koud.',
  },
  {
    id: 'februari',
    word: 'februari',
    level: 'A1',
    theme: 'dagelijks',
    exampleSentence: 'Februari is een korte maand.',
  },
  {
    id: 'maart',
    word: 'maart',
    level: 'A1',
    theme: 'dagelijks',
    exampleSentence: 'In maart begint de lente.',
  },
  {
    id: 'april',
    word: 'april',
    level: 'A1',
    theme: 'dagelijks',
    exampleSentence: 'In april regent het vaak.',
  },
  {
    id: 'mei',
    word: 'mei',
    level: 'A1',
    theme: 'dagelijks',
    exampleSentence: 'In mei zijn er veel bloemen.',
  },
  {
    id: 'juni',
    word: 'juni',
    level: 'A1',
    theme: 'dagelijks',
    exampleSentence: 'De zomer begint in juni.',
  },
  {
    id: 'juli',
    word: 'juli',
    level: 'A1',
    theme: 'dagelijks',
    exampleSentence: 'In juli is het warm.',
  },
  {
    id: 'augustus',
    word: 'augustus',
    level: 'A1',
    theme: 'dagelijks',
    exampleSentence: 'In augustus heb ik vakantie.',
  },
  {
    id: 'september',
    word: 'september',
    level: 'A1',
    theme: 'dagelijks',
    exampleSentence: 'In september begint school.',
  },
  {
    id: 'oktober',
    word: 'oktober',
    level: 'A1',
    theme: 'dagelijks',
    exampleSentence: 'In oktober vallen de bladeren.',
  },
  {
    id: 'november',
    word: 'november',
    level: 'A1',
    theme: 'dagelijks',
    exampleSentence: 'In november is het donker.',
  },
  {
    id: 'december',
    word: 'december',
    level: 'A1',
    theme: 'dagelijks',
    exampleSentence: 'In december vieren we Kerstmis.',
  },
  {
    id: 'datum',
    word: 'datum',
    level: 'A1',
    theme: 'dagelijks',
    grammar: '(het)',
    exampleSentence: 'Wat is de datum vandaag?',
  },
  { id: 'laat', word: 'laat', level: 'A1', theme: 'dagelijks', exampleSentence: 'Het is al laat.' },
  {
    id: 'vroeg',
    word: 'vroeg',
    level: 'A1',
    theme: 'dagelijks',
    exampleSentence: 'Ik sta vroeg op.',
  },
  {
    id: 'slapen',
    word: 'slapen',
    level: 'A1',
    theme: 'dagelijks',
    exampleSentence: 'Ik slaap acht uur per nacht.',
  },
  {
    id: 'wakker',
    word: 'wakker',
    level: 'A1',
    theme: 'dagelijks',
    exampleSentence: 'Ik word om zeven uur wakker.',
  },
  { id: 'thuis', word: 'thuis', level: 'A1', theme: 'dagelijks', exampleSentence: 'Ik ben thuis.' },
  {
    id: 'dagelijks',
    word: 'dagelijks',
    level: 'A1',
    theme: 'dagelijks',
    exampleSentence: 'Ik sport dagelijks.',
  },
  // lichaam
  {
    id: 'hoofd',
    word: 'hoofd',
    level: 'A1',
    theme: 'lichaam',
    grammar: '(het)',
    exampleSentence: 'Ik heb pijn in mijn hoofd.',
  },
  {
    id: 'haar-body',
    word: 'haar',
    level: 'A1',
    theme: 'lichaam',
    grammar: '(het)',
    exampleSentence: 'Zij heeft lang haar.',
  },
  {
    id: 'oog',
    word: 'oog',
    level: 'A1',
    theme: 'lichaam',
    grammar: '(het)',
    exampleSentence: 'Hij heeft blauwe ogen.',
  },
  {
    id: 'oor',
    word: 'oor',
    level: 'A1',
    theme: 'lichaam',
    grammar: '(het)',
    exampleSentence: 'Mijn oor doet pijn.',
  },
  {
    id: 'neus',
    word: 'neus',
    level: 'A1',
    theme: 'lichaam',
    exampleSentence: 'Mijn neus is rood.',
  },
  { id: 'mond', word: 'mond', level: 'A1', theme: 'lichaam', exampleSentence: 'Doe je mond open.' },
  {
    id: 'tand',
    word: 'tand',
    level: 'A1',
    theme: 'lichaam',
    exampleSentence: 'Ik poets mijn tanden.',
  },
  {
    id: 'lip',
    word: 'lip',
    level: 'A1',
    theme: 'lichaam',
    exampleSentence: 'Haar lippen zijn rood.',
  },
  { id: 'hand', word: 'hand', level: 'A1', theme: 'lichaam', exampleSentence: 'Was je handen.' },
  {
    id: 'vinger',
    word: 'vinger',
    level: 'A1',
    theme: 'lichaam',
    exampleSentence: 'Ik heb mijn vinger gesneden.',
  },
  { id: 'arm', word: 'arm', level: 'A1', theme: 'lichaam', exampleSentence: 'Mijn arm doet pijn.' },
  {
    id: 'been',
    word: 'been',
    level: 'A1',
    theme: 'lichaam',
    grammar: '(het)',
    exampleSentence: 'Mijn been is gebroken.',
  },
  {
    id: 'voet',
    word: 'voet',
    level: 'A1',
    theme: 'lichaam',
    exampleSentence: 'Ik loop op blote voeten.',
  },
  {
    id: 'knie',
    word: 'knie',
    level: 'A1',
    theme: 'lichaam',
    exampleSentence: 'Mijn knie doet pijn.',
  },
  { id: 'buik', word: 'buik', level: 'A1', theme: 'lichaam', exampleSentence: 'Ik heb buikpijn.' },
  { id: 'rug', word: 'rug', level: 'A1', theme: 'lichaam', exampleSentence: 'Mijn rug doet pijn.' },
  {
    id: 'borst',
    word: 'borst',
    level: 'A1',
    theme: 'lichaam',
    exampleSentence: 'Hij heeft pijn op de borst.',
  },
  {
    id: 'hart',
    word: 'hart',
    level: 'A1',
    theme: 'lichaam',
    grammar: '(het)',
    exampleSentence: 'Mijn hart klopt snel.',
  },
  { id: 'keel', word: 'keel', level: 'A1', theme: 'lichaam', exampleSentence: 'Ik heb keelpijn.' },
  {
    id: 'schouder',
    word: 'schouder',
    level: 'A1',
    theme: 'lichaam',
    exampleSentence: 'Mijn schouder is stijf.',
  },
  {
    id: 'teen',
    word: 'teen',
    level: 'A1',
    theme: 'lichaam',
    exampleSentence: 'Ik heb mijn teen gestoten.',
  },
  {
    id: 'lichaam',
    word: 'lichaam',
    level: 'A1',
    theme: 'lichaam',
    grammar: '(het)',
    exampleSentence: 'Het lichaam heeft rust nodig.',
  },
  {
    id: 'gezicht',
    word: 'gezicht',
    level: 'A1',
    theme: 'lichaam',
    grammar: '(het)',
    exampleSentence: 'Was je gezicht.',
  },
  {
    id: 'bloed',
    word: 'bloed',
    level: 'A1',
    theme: 'lichaam',
    grammar: '(het)',
    exampleSentence: 'Er komt bloed uit de wond.',
  },
  // kleding
  {
    id: 'jas',
    word: 'jas',
    level: 'A1',
    theme: 'kleding',
    exampleSentence: 'Trek je jas aan, het is koud.',
  },
  {
    id: 'broek',
    word: 'broek',
    level: 'A1',
    theme: 'kleding',
    exampleSentence: 'Ik draag een blauwe broek.',
  },
  {
    id: 'jurk',
    word: 'jurk',
    level: 'A1',
    theme: 'kleding',
    exampleSentence: 'Zij draagt een rode jurk.',
  },
  { id: 'rok', word: 'rok', level: 'A1', theme: 'kleding', exampleSentence: 'De rok is kort.' },
  {
    id: 'trui',
    word: 'trui',
    level: 'A1',
    theme: 'kleding',
    exampleSentence: 'Ik draag een warme trui.',
  },
  {
    id: 'bloes',
    word: 'bloes',
    level: 'A1',
    theme: 'kleding',
    exampleSentence: 'De bloes is wit.',
  },
  {
    id: 'blouse',
    word: 'blouse',
    level: 'A1',
    theme: 'kleding',
    exampleSentence: 'Ze draagt een mooie blouse.',
  },
  {
    id: 'schoen',
    word: 'schoen',
    level: 'A1',
    theme: 'kleding',
    exampleSentence: 'Doe je schoenen aan.',
  },
  {
    id: 'laars',
    word: 'laars',
    level: 'A1',
    theme: 'kleding',
    exampleSentence: 'In de regen draag ik laarzen.',
  },
  {
    id: 'sok',
    word: 'sok',
    level: 'A1',
    theme: 'kleding',
    exampleSentence: 'Waar is mijn andere sok?',
  },
  {
    id: 'kous',
    word: 'kous',
    level: 'A1',
    theme: 'kleding',
    exampleSentence: 'Zij draagt zwarte kousen.',
  },
  {
    id: 'pet',
    word: 'pet',
    level: 'A1',
    theme: 'kleding',
    exampleSentence: 'De jongen draagt een pet.',
  },
  {
    id: 'hoed',
    word: 'hoed',
    level: 'A1',
    theme: 'kleding',
    exampleSentence: 'Opa draagt een hoed.',
  },
  {
    id: 'sjaal',
    word: 'sjaal',
    level: 'A1',
    theme: 'kleding',
    exampleSentence: 'In de winter draag ik een sjaal.',
  },
  {
    id: 'bril',
    word: 'bril',
    level: 'A1',
    theme: 'kleding',
    exampleSentence: 'Ik draag een bril.',
  },
  {
    id: 'kleren',
    word: 'kleren',
    level: 'A1',
    theme: 'kleding',
    exampleSentence: 'Doe schone kleren aan.',
  },
  {
    id: 'dragen',
    word: 'dragen',
    level: 'A1',
    theme: 'kleding',
    exampleSentence: 'Ik draag een warm jasje.',
  },
  {
    id: 'aantrekken',
    word: 'aantrekken',
    level: 'A1',
    theme: 'kleding',
    exampleSentence: 'Trek je jas aan.',
  },
  {
    id: 'jasje',
    word: 'jasje',
    level: 'A1',
    theme: 'kleding',
    grammar: '(het)',
    exampleSentence: 'Doe je jasje uit.',
  },
  // weer
  {
    id: 'weer',
    word: 'weer',
    level: 'A1',
    theme: 'weer',
    grammar: '(het)',
    exampleSentence: 'Het weer is mooi vandaag.',
  },
  { id: 'zon', word: 'zon', level: 'A1', theme: 'weer', exampleSentence: 'De zon schijnt.' },
  {
    id: 'regen',
    word: 'regen',
    level: 'A1',
    theme: 'weer',
    exampleSentence: 'Het regent vandaag.',
  },
  {
    id: 'regenen',
    word: 'regenen',
    level: 'A1',
    theme: 'weer',
    exampleSentence: 'Het gaat morgen regenen.',
  },
  { id: 'wind', word: 'wind', level: 'A1', theme: 'weer', exampleSentence: 'De wind waait hard.' },
  { id: 'warm', word: 'warm', level: 'A1', theme: 'weer', exampleSentence: 'Het is warm buiten.' },
  { id: 'koud', word: 'koud', level: 'A1', theme: 'weer', exampleSentence: 'Het is koud vandaag.' },
  {
    id: 'winter',
    word: 'winter',
    level: 'A1',
    theme: 'weer',
    exampleSentence: 'In de winter sneeuwt het.',
  },
  {
    id: 'zomer',
    word: 'zomer',
    level: 'A1',
    theme: 'weer',
    exampleSentence: 'In de zomer is het warm.',
  },
  {
    id: 'lente',
    word: 'lente',
    level: 'A1',
    theme: 'weer',
    exampleSentence: 'De lente begint in maart.',
  },
  {
    id: 'herfst',
    word: 'herfst',
    level: 'A1',
    theme: 'weer',
    exampleSentence: 'In de herfst vallen de bladeren.',
  },
  {
    id: 'donker',
    word: 'donker',
    level: 'A1',
    theme: 'weer',
    exampleSentence: 'In de winter is het vroeg donker.',
  },
  {
    id: 'licht-adj',
    word: 'licht',
    level: 'A1',
    theme: 'weer',
    exampleSentence: 'Het wordt licht buiten.',
  },
  {
    id: 'nat',
    word: 'nat',
    level: 'A1',
    theme: 'weer',
    exampleSentence: 'Mijn jas is nat van de regen.',
  },
  {
    id: 'droog',
    word: 'droog',
    level: 'A1',
    theme: 'weer',
    exampleSentence: 'Het is vandaag droog.',
  },
  { id: 'lucht', word: 'lucht', level: 'A1', theme: 'weer', exampleSentence: 'De lucht is blauw.' },
  {
    id: 'waaien',
    word: 'waaien',
    level: 'A1',
    theme: 'weer',
    exampleSentence: 'Het waait vandaag hard.',
  },
  {
    id: 'boom',
    word: 'boom',
    level: 'A1',
    theme: 'weer',
    exampleSentence: 'De boom verliest zijn bladeren.',
  },
  { id: 'bloem', word: 'bloem', level: 'A1', theme: 'weer', exampleSentence: 'De bloem is mooi.' },
  {
    id: 'gras',
    word: 'gras',
    level: 'A1',
    theme: 'weer',
    grammar: '(het)',
    exampleSentence: 'Het gras is groen.',
  },
  {
    id: 'aarde',
    word: 'aarde',
    level: 'A1',
    theme: 'weer',
    exampleSentence: 'De plant groeit in de aarde.',
  },
  { id: 'zee', word: 'zee', level: 'A1', theme: 'weer', exampleSentence: 'We gaan naar de zee.' },
  {
    id: 'strand',
    word: 'strand',
    level: 'A1',
    theme: 'weer',
    grammar: '(het)',
    exampleSentence: 'De kinderen spelen op het strand.',
  },
  // vrije tijd
  {
    id: 'spelen',
    word: 'spelen',
    level: 'A1',
    theme: 'vrije_tijd',
    exampleSentence: 'De kinderen spelen buiten.',
  },
  {
    id: 'sport',
    word: 'sport',
    level: 'A1',
    theme: 'vrije_tijd',
    exampleSentence: 'Ik hou van sport.',
  },
  {
    id: 'voetballen',
    word: 'voetballen',
    level: 'A1',
    theme: 'vrije_tijd',
    exampleSentence: 'De jongens voetballen in het park.',
  },
  {
    id: 'zwemmen',
    word: 'zwemmen',
    level: 'A1',
    theme: 'vrije_tijd',
    exampleSentence: 'Ik ga graag zwemmen.',
  },
  {
    id: 'zwembad',
    word: 'zwembad',
    level: 'A1',
    theme: 'vrije_tijd',
    exampleSentence: 'Het zwembad is open.',
  },
  {
    id: 'fietsen',
    word: 'fietsen',
    level: 'A1',
    theme: 'vrije_tijd',
    exampleSentence: 'In Nederland fietsen we veel.',
  },
  {
    id: 'fiets',
    word: 'fiets',
    level: 'A1',
    theme: 'vrije_tijd',
    exampleSentence: 'Mijn fiets is blauw.',
  },
  {
    id: 'lezen',
    word: 'lezen',
    level: 'A1',
    theme: 'vrije_tijd',
    exampleSentence: 'Ik lees een boek.',
  },
  {
    id: 'boek',
    word: 'boek',
    level: 'A1',
    theme: 'vrije_tijd',
    grammar: '(het)',
    exampleSentence: 'Dit boek is interessant.',
  },
  {
    id: 'film',
    word: 'film',
    level: 'A1',
    theme: 'vrije_tijd',
    exampleSentence: 'We gaan een film kijken.',
  },
  {
    id: 'televisie',
    word: 'televisie',
    level: 'A1',
    theme: 'vrije_tijd',
    exampleSentence: 'Ik kijk televisie.',
  },
  {
    id: 'muziek',
    word: 'muziek',
    level: 'A1',
    theme: 'vrije_tijd',
    exampleSentence: 'Ik luister naar muziek.',
  },
  {
    id: 'zingen',
    word: 'zingen',
    level: 'A1',
    theme: 'vrije_tijd',
    exampleSentence: 'Zij zingt een mooi lied.',
  },
  {
    id: 'dansen',
    word: 'dansen',
    level: 'A1',
    theme: 'vrije_tijd',
    exampleSentence: 'Wij dansen op het feest.',
  },
  {
    id: 'feest',
    word: 'feest',
    level: 'A1',
    theme: 'vrije_tijd',
    grammar: '(het)',
    exampleSentence: 'Er is een feest vanavond.',
  },
  {
    id: 'foto',
    word: 'foto',
    level: 'A1',
    theme: 'vrije_tijd',
    exampleSentence: 'Ik maak een foto.',
  },
  {
    id: 'park',
    word: 'park',
    level: 'A1',
    theme: 'vrije_tijd',
    grammar: '(het)',
    exampleSentence: 'We wandelen in het park.',
  },
  {
    id: 'wandelen',
    word: 'wandelen',
    level: 'A1',
    theme: 'vrije_tijd',
    exampleSentence: 'Ik wandel elke dag.',
  },
  {
    id: 'vakantie',
    word: 'vakantie',
    level: 'A1',
    theme: 'vrije_tijd',
    exampleSentence: 'In de vakantie ga ik naar Spanje.',
  },
  {
    id: 'cadeau',
    word: 'cadeau',
    level: 'A1',
    theme: 'vrije_tijd',
    grammar: '(het)',
    exampleSentence: 'Ik heb een cadeau voor je.',
  },
  {
    id: 'radio',
    word: 'radio',
    level: 'A1',
    theme: 'vrije_tijd',
    exampleSentence: 'Ik luister naar de radio.',
  },
  {
    id: 'piano',
    word: 'piano',
    level: 'A1',
    theme: 'vrije_tijd',
    exampleSentence: 'Zij speelt piano.',
  },
  {
    id: 'bioscoop',
    word: 'bioscoop',
    level: 'A1',
    theme: 'vrije_tijd',
    exampleSentence: 'We gaan naar de bioscoop.',
  },
  // dieren
  { id: 'hond', word: 'hond', level: 'A1', theme: 'dieren', exampleSentence: 'De hond blaft.' },
  {
    id: 'kat',
    word: 'kat',
    level: 'A1',
    theme: 'dieren',
    exampleSentence: 'De kat slaapt op de bank.',
  },
  {
    id: 'vogel',
    word: 'vogel',
    level: 'A1',
    theme: 'dieren',
    exampleSentence: 'De vogel zingt in de boom.',
  },
  {
    id: 'koe',
    word: 'koe',
    level: 'A1',
    theme: 'dieren',
    exampleSentence: 'De koe staat in de wei.',
  },
  {
    id: 'paard',
    word: 'paard',
    level: 'A1',
    theme: 'dieren',
    grammar: '(het)',
    exampleSentence: 'Het paard loopt in het veld.',
  },
  {
    id: 'dier',
    word: 'dier',
    level: 'A1',
    theme: 'dieren',
    grammar: '(het)',
    exampleSentence: 'De hond is mijn lievelingsdier.',
  },
  {
    id: 'beest',
    word: 'beest',
    level: 'A1',
    theme: 'dieren',
    grammar: '(het)',
    exampleSentence: 'Dat is een groot beest.',
  },
  // overig — common A1 words
  { id: 'zijn', word: 'zijn', level: 'A1', theme: 'overig', exampleSentence: 'Ik ben blij.' },
  {
    id: 'hebben',
    word: 'hebben',
    level: 'A1',
    theme: 'overig',
    exampleSentence: 'Ik heb een hond.',
  },
  { id: 'gaan', word: 'gaan', level: 'A1', theme: 'overig', exampleSentence: 'Ik ga naar huis.' },
  { id: 'komen', word: 'komen', level: 'A1', theme: 'overig', exampleSentence: 'Kom je morgen?' },
  {
    id: 'doen',
    word: 'doen',
    level: 'A1',
    theme: 'overig',
    exampleSentence: 'Wat doe je vandaag?',
  },
  {
    id: 'maken',
    word: 'maken',
    level: 'A1',
    theme: 'overig',
    exampleSentence: 'Ik maak het eten klaar.',
  },
  {
    id: 'willen',
    word: 'willen',
    level: 'A1',
    theme: 'overig',
    exampleSentence: 'Ik wil een kopje thee.',
  },
  {
    id: 'kunnen',
    word: 'kunnen',
    level: 'A1',
    theme: 'overig',
    exampleSentence: 'Kan ik je helpen?',
  },
  {
    id: 'moeten',
    word: 'moeten',
    level: 'A1',
    theme: 'overig',
    exampleSentence: 'Ik moet naar school.',
  },
  {
    id: 'mogen',
    word: 'mogen',
    level: 'A1',
    theme: 'overig',
    exampleSentence: 'Mag ik naar buiten?',
  },
  { id: 'zien', word: 'zien', level: 'A1', theme: 'overig', exampleSentence: 'Ik zie een vogel.' },
  { id: 'horen', word: 'horen', level: 'A1', theme: 'overig', exampleSentence: 'Ik hoor muziek.' },
  {
    id: 'luisteren',
    word: 'luisteren',
    level: 'A1',
    theme: 'overig',
    exampleSentence: 'Luister je naar mij?',
  },
  {
    id: 'kijken',
    word: 'kijken',
    level: 'A1',
    theme: 'overig',
    exampleSentence: 'Kijk, daar is de trein!',
  },
  {
    id: 'spreken',
    word: 'spreken',
    level: 'A1',
    theme: 'overig',
    exampleSentence: 'Ik spreek een beetje Nederlands.',
  },
  {
    id: 'praten',
    word: 'praten',
    level: 'A1',
    theme: 'overig',
    exampleSentence: 'We praten over het weer.',
  },
  { id: 'zeggen', word: 'zeggen', level: 'A1', theme: 'overig', exampleSentence: 'Wat zeg je?' },
  {
    id: 'vragen',
    word: 'vragen',
    level: 'A1',
    theme: 'overig',
    exampleSentence: 'Mag ik je iets vragen?',
  },
  {
    id: 'antwoorden',
    word: 'antwoorden',
    level: 'A1',
    theme: 'overig',
    exampleSentence: 'Kun je antwoorden?',
  },
  {
    id: 'antwoord',
    word: 'antwoord',
    level: 'A1',
    theme: 'overig',
    grammar: '(het)',
    exampleSentence: 'Ik weet het antwoord niet.',
  },
  {
    id: 'schrijven',
    word: 'schrijven',
    level: 'A1',
    theme: 'overig',
    exampleSentence: 'Ik schrijf een brief.',
  },
  {
    id: 'leren',
    word: 'leren',
    level: 'A1',
    theme: 'overig',
    exampleSentence: 'Ik leer Nederlands.',
  },
  {
    id: 'beginnen',
    word: 'beginnen',
    level: 'A1',
    theme: 'overig',
    exampleSentence: 'De les begint om negen uur.',
  },
  {
    id: 'helpen',
    word: 'helpen',
    level: 'A1',
    theme: 'overig',
    exampleSentence: 'Kan ik je helpen?',
  },
  {
    id: 'geven',
    word: 'geven',
    level: 'A1',
    theme: 'overig',
    exampleSentence: 'Ik geef je een cadeau.',
  },
  { id: 'nemen', word: 'nemen', level: 'A1', theme: 'overig', exampleSentence: 'Ik neem de bus.' },
  {
    id: 'zitten',
    word: 'zitten',
    level: 'A1',
    theme: 'overig',
    exampleSentence: 'Ik zit op de bank.',
  },
  {
    id: 'staan',
    word: 'staan',
    level: 'A1',
    theme: 'overig',
    exampleSentence: 'Ik sta bij de deur.',
  },
  {
    id: 'liggen',
    word: 'liggen',
    level: 'A1',
    theme: 'overig',
    exampleSentence: 'Het boek ligt op tafel.',
  },
  {
    id: 'lopen',
    word: 'lopen',
    level: 'A1',
    theme: 'overig',
    exampleSentence: 'Ik loop naar school.',
  },
  {
    id: 'rijden',
    word: 'rijden',
    level: 'A1',
    theme: 'overig',
    exampleSentence: 'Ik rijd op de fiets.',
  },
  {
    id: 'brengen',
    word: 'brengen',
    level: 'A1',
    theme: 'overig',
    exampleSentence: 'Ik breng de kinderen naar school.',
  },
  {
    id: 'halen',
    word: 'halen',
    level: 'A1',
    theme: 'overig',
    exampleSentence: 'Ik haal brood bij de bakker.',
  },
  {
    id: 'vinden',
    word: 'vinden',
    level: 'A1',
    theme: 'overig',
    exampleSentence: 'Ik vind het leuk.',
  },
  {
    id: 'denken',
    word: 'denken',
    level: 'A1',
    theme: 'overig',
    exampleSentence: 'Ik denk dat het klopt.',
  },
  {
    id: 'weten',
    word: 'weten',
    level: 'A1',
    theme: 'overig',
    exampleSentence: 'Ik weet het niet.',
  },
  {
    id: 'voelen',
    word: 'voelen',
    level: 'A1',
    theme: 'overig',
    exampleSentence: 'Ik voel me goed.',
  },
  {
    id: 'wachten',
    word: 'wachten',
    level: 'A1',
    theme: 'overig',
    exampleSentence: 'Wacht even, ik kom eraan.',
  },
  {
    id: 'stoppen',
    word: 'stoppen',
    level: 'A1',
    theme: 'overig',
    exampleSentence: 'De bus stopt hier.',
  },
  {
    id: 'openen',
    word: 'openen',
    level: 'A1',
    theme: 'overig',
    exampleSentence: 'Ik open de deur.',
  },
  {
    id: 'sluiten',
    word: 'sluiten',
    level: 'A1',
    theme: 'overig',
    exampleSentence: 'De winkel sluit om zes uur.',
  },
  {
    id: 'groot',
    word: 'groot',
    level: 'A1',
    theme: 'overig',
    exampleSentence: 'Het huis is groot.',
  },
  { id: 'klein', word: 'klein', level: 'A1', theme: 'overig', exampleSentence: 'De kat is klein.' },
  {
    id: 'goed',
    word: 'goed',
    level: 'A1',
    theme: 'overig',
    exampleSentence: 'Het gaat goed met mij.',
  },
  {
    id: 'slecht',
    word: 'slecht',
    level: 'A1',
    theme: 'overig',
    exampleSentence: 'Het weer is slecht.',
  },
  { id: 'mooi', word: 'mooi', level: 'A1', theme: 'overig', exampleSentence: 'De bloem is mooi.' },
  {
    id: 'lelijk',
    word: 'lelijk',
    level: 'A1',
    theme: 'overig',
    exampleSentence: 'De tekening is lelijk.',
  },
  {
    id: 'nieuw',
    word: 'nieuw',
    level: 'A1',
    theme: 'overig',
    exampleSentence: 'Ik heb een nieuw boek.',
  },
  {
    id: 'oud',
    word: 'oud',
    level: 'A1',
    theme: 'overig',
    exampleSentence: 'Het huis is heel oud.',
  },
  {
    id: 'jong',
    word: 'jong',
    level: 'A1',
    theme: 'overig',
    exampleSentence: 'De kinderen zijn jong.',
  },
  { id: 'lang', word: 'lang', level: 'A1', theme: 'overig', exampleSentence: 'De man is lang.' },
  { id: 'kort', word: 'kort', level: 'A1', theme: 'overig', exampleSentence: 'De rok is kort.' },
  { id: 'dik', word: 'dik', level: 'A1', theme: 'overig', exampleSentence: 'Het boek is dik.' },
  { id: 'dun', word: 'dun', level: 'A1', theme: 'overig', exampleSentence: 'Het papier is dun.' },
  { id: 'snel', word: 'snel', level: 'A1', theme: 'overig', exampleSentence: 'De trein is snel.' },
  {
    id: 'langzaam',
    word: 'langzaam',
    level: 'A1',
    theme: 'overig',
    exampleSentence: 'Praat alsjeblieft langzaam.',
  },
  { id: 'blij', word: 'blij', level: 'A1', theme: 'overig', exampleSentence: 'Ik ben blij.' },
  { id: 'boos', word: 'boos', level: 'A1', theme: 'overig', exampleSentence: 'Mama is boos.' },
  {
    id: 'bang',
    word: 'bang',
    level: 'A1',
    theme: 'overig',
    exampleSentence: 'Ik ben bang voor honden.',
  },
  { id: 'moe', word: 'moe', level: 'A1', theme: 'overig', exampleSentence: 'Ik ben moe.' },
  { id: 'ziek', word: 'ziek', level: 'A1', theme: 'overig', exampleSentence: 'Ik ben ziek.' },
  {
    id: 'gezond',
    word: 'gezond',
    level: 'A1',
    theme: 'overig',
    exampleSentence: 'Fruit is gezond.',
  },
  { id: 'leuk', word: 'leuk', level: 'A1', theme: 'overig', exampleSentence: 'Het feest is leuk.' },
  {
    id: 'fijn',
    word: 'fijn',
    level: 'A1',
    theme: 'overig',
    exampleSentence: 'Wat fijn dat je er bent.',
  },
  { id: 'rood', word: 'rood', level: 'A1', theme: 'overig', exampleSentence: 'De auto is rood.' },
  {
    id: 'blauw',
    word: 'blauw',
    level: 'A1',
    theme: 'overig',
    exampleSentence: 'De lucht is blauw.',
  },
  {
    id: 'groen',
    word: 'groen',
    level: 'A1',
    theme: 'overig',
    exampleSentence: 'Het gras is groen.',
  },
  { id: 'geel', word: 'geel', level: 'A1', theme: 'overig', exampleSentence: 'De zon is geel.' },
  { id: 'wit', word: 'wit', level: 'A1', theme: 'overig', exampleSentence: 'De muur is wit.' },
  { id: 'zwart', word: 'zwart', level: 'A1', theme: 'overig', exampleSentence: 'De kat is zwart.' },
  {
    id: 'bruin',
    word: 'bruin',
    level: 'A1',
    theme: 'overig',
    exampleSentence: 'De hond is bruin.',
  },
  {
    id: 'grijs',
    word: 'grijs',
    level: 'A1',
    theme: 'overig',
    exampleSentence: 'Opa heeft grijs haar.',
  },
  {
    id: 'oranje',
    word: 'oranje',
    level: 'A1',
    theme: 'overig',
    exampleSentence: 'Nederland speelt in het oranje.',
  },
  {
    id: 'paars',
    word: 'paars',
    level: 'A1',
    theme: 'overig',
    exampleSentence: 'De bloem is paars.',
  },
  { id: 'auto', word: 'auto', level: 'A1', theme: 'overig', exampleSentence: 'De auto is rood.' },
  { id: 'bus', word: 'bus', level: 'A1', theme: 'overig', exampleSentence: 'Ik neem de bus.' },
  {
    id: 'trein',
    word: 'trein',
    level: 'A1',
    theme: 'overig',
    exampleSentence: 'De trein vertrekt om drie uur.',
  },
  {
    id: 'tram',
    word: 'tram',
    level: 'A1',
    theme: 'overig',
    exampleSentence: 'De tram komt eraan.',
  },
  { id: 'taxi', word: 'taxi', level: 'A1', theme: 'overig', exampleSentence: 'Ik neem een taxi.' },
  {
    id: 'telefoon',
    word: 'telefoon',
    level: 'A1',
    theme: 'overig',
    exampleSentence: 'Mijn telefoon gaat over.',
  },
  {
    id: 'computer',
    word: 'computer',
    level: 'A1',
    theme: 'overig',
    exampleSentence: 'Ik werk op de computer.',
  },
  {
    id: 'pen',
    word: 'pen',
    level: 'A1',
    theme: 'overig',
    exampleSentence: 'Ik schrijf met een pen.',
  },
  {
    id: 'papier',
    word: 'papier',
    level: 'A1',
    theme: 'overig',
    grammar: '(het)',
    exampleSentence: 'Ik heb een stuk papier nodig.',
  },
  {
    id: 'nummer',
    word: 'nummer',
    level: 'A1',
    theme: 'overig',
    grammar: '(het)',
    exampleSentence: 'Wat is je telefoonnummer?',
  },
  {
    id: 'land',
    word: 'land',
    level: 'A1',
    theme: 'overig',
    grammar: '(het)',
    exampleSentence: 'Nederland is een klein land.',
  },
  {
    id: 'stad',
    word: 'stad',
    level: 'A1',
    theme: 'overig',
    exampleSentence: 'Amsterdam is een grote stad.',
  },
  {
    id: 'dorp',
    word: 'dorp',
    level: 'A1',
    theme: 'overig',
    grammar: '(het)',
    exampleSentence: 'Ik woon in een klein dorp.',
  },
  { id: 'weg', word: 'weg', level: 'A1', theme: 'overig', exampleSentence: 'De weg is lang.' },
  {
    id: 'brug',
    word: 'brug',
    level: 'A1',
    theme: 'overig',
    exampleSentence: 'We lopen over de brug.',
  },
  { id: 'hier', word: 'hier', level: 'A1', theme: 'overig', exampleSentence: 'Ik woon hier.' },
  {
    id: 'daar',
    word: 'daar',
    level: 'A1',
    theme: 'overig',
    exampleSentence: 'Het station is daar.',
  },
  { id: 'links', word: 'links', level: 'A1', theme: 'overig', exampleSentence: 'Ga naar links.' },
  {
    id: 'rechts',
    word: 'rechts',
    level: 'A1',
    theme: 'overig',
    exampleSentence: 'De winkel is rechts.',
  },
  {
    id: 'dicht',
    word: 'dicht',
    level: 'A1',
    theme: 'overig',
    exampleSentence: 'De deur is dicht.',
  },
  { id: 'open', word: 'open', level: 'A1', theme: 'overig', exampleSentence: 'Het raam is open.' },
  { id: 'samen', word: 'samen', level: 'A1', theme: 'overig', exampleSentence: 'We eten samen.' },
  {
    id: 'alleen',
    word: 'alleen',
    level: 'A1',
    theme: 'overig',
    exampleSentence: 'Ik woon alleen.',
  },
  {
    id: 'veel',
    word: 'veel',
    level: 'A1',
    theme: 'overig',
    exampleSentence: 'Er zijn veel mensen.',
  },
  {
    id: 'weinig',
    word: 'weinig',
    level: 'A1',
    theme: 'overig',
    exampleSentence: 'Er is weinig tijd.',
  },
  { id: 'meer', word: 'meer', level: 'A1', theme: 'overig', exampleSentence: 'Ik wil meer water.' },
  {
    id: 'minder',
    word: 'minder',
    level: 'A1',
    theme: 'overig',
    exampleSentence: 'Ik heb minder tijd.',
  },
  {
    id: 'alle',
    word: 'alle',
    level: 'A1',
    theme: 'overig',
    exampleSentence: 'Alle kinderen spelen buiten.',
  },
  { id: 'ook', word: 'ook', level: 'A1', theme: 'overig', exampleSentence: 'Ik wil ook mee.' },
  { id: 'nog', word: 'nog', level: 'A1', theme: 'overig', exampleSentence: 'Wil je nog koffie?' },
  { id: 'al', word: 'al', level: 'A1', theme: 'overig', exampleSentence: 'Ik ben al klaar.' },
  { id: 'echt', word: 'echt', level: 'A1', theme: 'overig', exampleSentence: 'Het is echt waar.' },
  { id: 'heel', word: 'heel', level: 'A1', theme: 'overig', exampleSentence: 'Het is heel mooi.' },
  { id: 'erg', word: 'erg', level: 'A1', theme: 'overig', exampleSentence: 'Het is erg koud.' },
  { id: 'toch', word: 'toch', level: 'A1', theme: 'overig', exampleSentence: 'Kom je toch?' },
  {
    id: 'maar',
    word: 'maar',
    level: 'A1',
    theme: 'overig',
    exampleSentence: 'Ik wil wel, maar ik kan niet.',
  },
  { id: 'en', word: 'en', level: 'A1', theme: 'overig', exampleSentence: 'Ik en mijn broer.' },
  { id: 'of', word: 'of', level: 'A1', theme: 'overig', exampleSentence: 'Wil je thee of koffie?' },
  {
    id: 'want',
    word: 'want',
    level: 'A1',
    theme: 'overig',
    exampleSentence: 'Ik blijf thuis, want het regent.',
  },
  {
    id: 'omdat',
    word: 'omdat',
    level: 'A1',
    theme: 'overig',
    exampleSentence: 'Ik ben blij omdat je er bent.',
  },
  {
    id: 'als',
    word: 'als',
    level: 'A1',
    theme: 'overig',
    exampleSentence: 'Als het regent, blijf ik thuis.',
  },
  {
    id: 'wanneer',
    word: 'wanneer',
    level: 'A1',
    theme: 'overig',
    exampleSentence: 'Wanneer kom je?',
  },
  { id: 'waar-adv', word: 'waar', level: 'A1', theme: 'overig', exampleSentence: 'Waar woon je?' },
  { id: 'wie', word: 'wie', level: 'A1', theme: 'overig', exampleSentence: 'Wie is dat?' },
  { id: 'wat', word: 'wat', level: 'A1', theme: 'overig', exampleSentence: 'Wat doe je?' },
  { id: 'hoe', word: 'hoe', level: 'A1', theme: 'overig', exampleSentence: 'Hoe gaat het?' },
  {
    id: 'waarom',
    word: 'waarom',
    level: 'A1',
    theme: 'overig',
    exampleSentence: 'Waarom ben je boos?',
  },
  {
    id: 'hoeveel',
    word: 'hoeveel',
    level: 'A1',
    theme: 'overig',
    exampleSentence: 'Hoeveel kost dit?',
  },
  { id: 'niet', word: 'niet', level: 'A1', theme: 'overig', exampleSentence: 'Ik weet het niet.' },
  { id: 'geen', word: 'geen', level: 'A1', theme: 'overig', exampleSentence: 'Ik heb geen geld.' },
  {
    id: 'iets',
    word: 'iets',
    level: 'A1',
    theme: 'overig',
    exampleSentence: 'Wil je iets drinken?',
  },
  {
    id: 'niets',
    word: 'niets',
    level: 'A1',
    theme: 'overig',
    exampleSentence: 'Er is niets aan de hand.',
  },
  {
    id: 'iemand',
    word: 'iemand',
    level: 'A1',
    theme: 'overig',
    exampleSentence: 'Is daar iemand?',
  },
  {
    id: 'niemand',
    word: 'niemand',
    level: 'A1',
    theme: 'overig',
    exampleSentence: 'Er is niemand thuis.',
  },
  {
    id: 'ander',
    word: 'ander',
    level: 'A1',
    theme: 'overig',
    exampleSentence: 'Geef me een ander boek.',
  },
  { id: 'zelf', word: 'zelf', level: 'A1', theme: 'overig', exampleSentence: 'Ik doe het zelf.' },
  {
    id: 'weer-adv',
    word: 'weer',
    level: 'A1',
    theme: 'overig',
    exampleSentence: 'Ik ben weer thuis.',
  },
  {
    id: 'misschien',
    word: 'misschien',
    level: 'A1',
    theme: 'overig',
    exampleSentence: 'Misschien komt hij morgen.',
  },
  {
    id: 'klaar',
    word: 'klaar',
    level: 'A1',
    theme: 'overig',
    exampleSentence: 'Het eten is klaar.',
  },
  {
    id: 'dichtbij',
    word: 'dichtbij',
    level: 'A1',
    theme: 'overig',
    exampleSentence: 'De school is dichtbij.',
  },
  { id: 'ver', word: 'ver', level: 'A1', theme: 'overig', exampleSentence: 'De stad is ver weg.' },
  { id: 'even', word: 'even', level: 'A1', theme: 'overig', exampleSentence: 'Wacht even.' },
  // Additional A1 words
  {
    id: 'dokter',
    word: 'dokter',
    level: 'A1',
    theme: 'gezondheid',
    exampleSentence: 'Ik ga naar de dokter.',
  },
  {
    id: 'pijn',
    word: 'pijn',
    level: 'A1',
    theme: 'gezondheid',
    exampleSentence: 'Ik heb pijn in mijn buik.',
  },
  {
    id: 'medicijn',
    word: 'medicijn',
    level: 'A1',
    theme: 'gezondheid',
    grammar: '(het)',
    exampleSentence: 'Ik neem een medicijn tegen hoofdpijn.',
  },
  {
    id: 'ziekenhuis',
    word: 'ziekenhuis',
    level: 'A1',
    theme: 'gezondheid',
    grammar: '(het)',
    exampleSentence: 'Mijn oma ligt in het ziekenhuis.',
  },
  {
    id: 'apotheek',
    word: 'apotheek',
    level: 'A1',
    theme: 'gezondheid',
    exampleSentence: 'Ik haal medicijnen bij de apotheek.',
  },
  {
    id: 'wassen',
    word: 'wassen',
    level: 'A1',
    theme: 'dagelijks',
    exampleSentence: 'Ik was mijn handen.',
  },
  {
    id: 'schoon',
    word: 'schoon',
    level: 'A1',
    theme: 'dagelijks',
    exampleSentence: 'De keuken is schoon.',
  },
  {
    id: 'vies',
    word: 'vies',
    level: 'A1',
    theme: 'dagelijks',
    exampleSentence: 'Mijn schoenen zijn vies.',
  },
  {
    id: 'werken',
    word: 'werken',
    level: 'A1',
    theme: 'werk',
    exampleSentence: 'Ik werk op een kantoor.',
  },
  {
    id: 'werk',
    word: 'werk',
    level: 'A1',
    theme: 'werk',
    grammar: '(het)',
    exampleSentence: 'Ik ga naar mijn werk.',
  },
  {
    id: 'kantoor',
    word: 'kantoor',
    level: 'A1',
    theme: 'werk',
    grammar: '(het)',
    exampleSentence: 'Het kantoor is dichtbij.',
  },
  {
    id: 'baan',
    word: 'baan',
    level: 'A1',
    theme: 'werk',
    exampleSentence: 'Ik zoek een nieuwe baan.',
  },
  { id: 'baas', word: 'baas', level: 'A1', theme: 'werk', exampleSentence: 'Mijn baas is aardig.' },
  {
    id: 'collega',
    word: 'collega',
    level: 'A1',
    theme: 'werk',
    exampleSentence: 'Mijn collega helpt mij.',
  },
  {
    id: 'school',
    word: 'school',
    level: 'A1',
    theme: 'school',
    exampleSentence: 'De kinderen gaan naar school.',
  },
  {
    id: 'les',
    word: 'les',
    level: 'A1',
    theme: 'school',
    exampleSentence: 'De les begint om negen uur.',
  },
  {
    id: 'leraar',
    word: 'leraar',
    level: 'A1',
    theme: 'school',
    exampleSentence: 'De leraar legt het uit.',
  },
  {
    id: 'leerling',
    word: 'leerling',
    level: 'A1',
    theme: 'school',
    exampleSentence: 'De leerling maakt huiswerk.',
  },
  {
    id: 'taal',
    word: 'taal',
    level: 'A1',
    theme: 'school',
    exampleSentence: 'Nederlands is een mooie taal.',
  },
  {
    id: 'woord',
    word: 'woord',
    level: 'A1',
    theme: 'school',
    grammar: '(het)',
    exampleSentence: 'Ik ken dit woord niet.',
  },
  {
    id: 'brief',
    word: 'brief',
    level: 'A1',
    theme: 'school',
    exampleSentence: 'Ik schrijf een brief.',
  },
  {
    id: 'tekenen',
    word: 'tekenen',
    level: 'A1',
    theme: 'school',
    exampleSentence: 'Het kind tekent een huis.',
  },
  {
    id: 'lied',
    word: 'lied',
    level: 'A1',
    theme: 'vrije_tijd',
    grammar: '(het)',
    exampleSentence: 'Zij zingt een mooi lied.',
  },
  {
    id: 'spel',
    word: 'spel',
    level: 'A1',
    theme: 'vrije_tijd',
    grammar: '(het)',
    exampleSentence: 'De kinderen doen een spel.',
  },
  {
    id: 'bal',
    word: 'bal',
    level: 'A1',
    theme: 'vrije_tijd',
    exampleSentence: 'De jongen gooit de bal.',
  },
  {
    id: 'rennen',
    word: 'rennen',
    level: 'A1',
    theme: 'vrije_tijd',
    exampleSentence: 'De kinderen rennen in het park.',
  },
  {
    id: 'reis',
    word: 'reis',
    level: 'A1',
    theme: 'reizen',
    exampleSentence: 'De reis duurt twee uur.',
  },
  {
    id: 'reizen',
    word: 'reizen',
    level: 'A1',
    theme: 'reizen',
    exampleSentence: 'Ik reis graag naar Spanje.',
  },
  {
    id: 'station',
    word: 'station',
    level: 'A1',
    theme: 'reizen',
    grammar: '(het)',
    exampleSentence: 'De trein vertrekt van het station.',
  },
  {
    id: 'vliegtuig',
    word: 'vliegtuig',
    level: 'A1',
    theme: 'reizen',
    grammar: '(het)',
    exampleSentence: 'Het vliegtuig vliegt naar Parijs.',
  },
  {
    id: 'boot',
    word: 'boot',
    level: 'A1',
    theme: 'reizen',
    exampleSentence: 'We gaan met de boot.',
  },
  {
    id: 'hotel',
    word: 'hotel',
    level: 'A1',
    theme: 'reizen',
    grammar: '(het)',
    exampleSentence: 'We slapen in een hotel.',
  },
  {
    id: 'kaart',
    word: 'kaart',
    level: 'A1',
    theme: 'reizen',
    exampleSentence: 'Ik koop een kaart voor de trein.',
  },
  {
    id: 'parkeren',
    word: 'parkeren',
    level: 'A1',
    theme: 'reizen',
    exampleSentence: 'Je kunt hier parkeren.',
  },
  { id: 'euro', word: 'euro', level: 'A1', theme: 'geld', exampleSentence: 'Het kost vijf euro.' },
  {
    id: 'rekening',
    word: 'rekening',
    level: 'A1',
    theme: 'geld',
    exampleSentence: 'Mag ik de rekening, alstublieft?',
  },
  {
    id: 'pinnen',
    word: 'pinnen',
    level: 'A1',
    theme: 'geld',
    exampleSentence: 'Ik wil graag pinnen.',
  },
  {
    id: 'kosten',
    word: 'kosten',
    level: 'A1',
    theme: 'geld',
    exampleSentence: 'Hoeveel kost dit?',
  },
  {
    id: 'restaurant',
    word: 'restaurant',
    level: 'A1',
    theme: 'eten',
    grammar: '(het)',
    exampleSentence: 'We eten in een restaurant.',
  },
  { id: 'soep', word: 'soep', level: 'A1', theme: 'eten', exampleSentence: 'De soep is warm.' },
  {
    id: 'boter',
    word: 'boter',
    level: 'A1',
    theme: 'eten',
    exampleSentence: 'Ik doe boter op mijn brood.',
  },
  {
    id: 'taart',
    word: 'taart',
    level: 'A1',
    theme: 'eten',
    exampleSentence: 'Oma bakt een taart.',
  },
  {
    id: 'tomaat',
    word: 'tomaat',
    level: 'A1',
    theme: 'eten',
    exampleSentence: 'De tomaat is rood.',
  },
  {
    id: 'doos',
    word: 'doos',
    level: 'A1',
    theme: 'wonen',
    exampleSentence: 'De schoenen zitten in een doos.',
  },
  {
    id: 'bank-meubel',
    word: 'bank',
    level: 'A1',
    theme: 'wonen',
    exampleSentence: 'Ik zit op de bank.',
  },
  {
    id: 'kussen',
    word: 'kussen',
    level: 'A1',
    theme: 'wonen',
    grammar: '(het)',
    exampleSentence: 'Het kussen op het bed is zacht.',
  },
  {
    id: 'zeep',
    word: 'zeep',
    level: 'A1',
    theme: 'dagelijks',
    exampleSentence: 'Was je handen met zeep.',
  },
  {
    id: 'handdoek',
    word: 'handdoek',
    level: 'A1',
    theme: 'dagelijks',
    exampleSentence: 'Geef me een schone handdoek.',
  },
  {
    id: 'tandenborstel',
    word: 'tandenborstel',
    level: 'A1',
    theme: 'dagelijks',
    exampleSentence: 'Ik poets mijn tanden met een tandenborstel.',
  },
  {
    id: 'lachen',
    word: 'lachen',
    level: 'A1',
    theme: 'overig',
    exampleSentence: 'De kinderen lachen hard.',
  },
  { id: 'huilen', word: 'huilen', level: 'A1', theme: 'overig', exampleSentence: 'De baby huilt.' },
  {
    id: 'vergeten',
    word: 'vergeten',
    level: 'A1',
    theme: 'overig',
    exampleSentence: 'Ik vergeet altijd mijn sleutel.',
  },
  {
    id: 'proberen',
    word: 'proberen',
    level: 'A1',
    theme: 'overig',
    exampleSentence: 'Ik probeer het nog een keer.',
  },
  {
    id: 'zoeken',
    word: 'zoeken',
    level: 'A1',
    theme: 'overig',
    exampleSentence: 'Ik zoek mijn telefoon.',
  },
  {
    id: 'pakken',
    word: 'pakken',
    level: 'A1',
    theme: 'overig',
    exampleSentence: 'Pak je jas van de stoel.',
  },
  {
    id: 'leggen',
    word: 'leggen',
    level: 'A1',
    theme: 'overig',
    exampleSentence: 'Ik leg het boek op tafel.',
  },
  {
    id: 'hangen',
    word: 'hangen',
    level: 'A1',
    theme: 'overig',
    exampleSentence: 'De jas hangt aan de kapstok.',
  },
  {
    id: 'vallen',
    word: 'vallen',
    level: 'A1',
    theme: 'overig',
    exampleSentence: 'De bladeren vallen van de boom.',
  },
  {
    id: 'roepen',
    word: 'roepen',
    level: 'A1',
    theme: 'overig',
    exampleSentence: 'Mama roept de kinderen.',
  },
  {
    id: 'bellen',
    word: 'bellen',
    level: 'A1',
    theme: 'overig',
    exampleSentence: 'Ik bel mijn moeder.',
  },
  {
    id: 'sturen',
    word: 'sturen',
    level: 'A1',
    theme: 'overig',
    exampleSentence: 'Ik stuur een bericht.',
  },
  {
    id: 'krijgen',
    word: 'krijgen',
    level: 'A1',
    theme: 'overig',
    exampleSentence: 'Ik krijg een cadeau.',
  },
  {
    id: 'nodig',
    word: 'nodig',
    level: 'A1',
    theme: 'overig',
    exampleSentence: 'Ik heb hulp nodig.',
  },
  {
    id: 'gezellig',
    word: 'gezellig',
    level: 'A1',
    theme: 'overig',
    exampleSentence: 'Het is gezellig hier.',
  },
  {
    id: 'rustig',
    word: 'rustig',
    level: 'A1',
    theme: 'overig',
    exampleSentence: 'De straat is rustig.',
  },
  {
    id: 'moeilijk',
    word: 'moeilijk',
    level: 'A1',
    theme: 'overig',
    exampleSentence: 'Nederlands is soms moeilijk.',
  },
  {
    id: 'makkelijk',
    word: 'makkelijk',
    level: 'A1',
    theme: 'overig',
    exampleSentence: 'Dit is makkelijk.',
  },
  {
    id: 'belangrijk',
    word: 'belangrijk',
    level: 'A1',
    theme: 'overig',
    exampleSentence: 'Water is belangrijk.',
  },
  {
    id: 'lief',
    word: 'lief',
    level: 'A1',
    theme: 'overig',
    exampleSentence: 'De kat is heel lief.',
  },
  {
    id: 'aardig',
    word: 'aardig',
    level: 'A1',
    theme: 'overig',
    exampleSentence: 'De buurvrouw is aardig.',
  },
  {
    id: 'roze',
    word: 'roze',
    level: 'A1',
    theme: 'overig',
    exampleSentence: 'Het meisje draagt een roze jurk.',
  },
  { id: 'hoog', word: 'hoog', level: 'A1', theme: 'overig', exampleSentence: 'De boom is hoog.' },
  { id: 'laag', word: 'laag', level: 'A1', theme: 'overig', exampleSentence: 'De tafel is laag.' },
  { id: 'leeg', word: 'leeg', level: 'A1', theme: 'overig', exampleSentence: 'Het glas is leeg.' },
  { id: 'vol', word: 'vol', level: 'A1', theme: 'overig', exampleSentence: 'De bus is vol.' },
];
