import type { PronunciationWord } from './types';

export const WORDS_A2: PronunciationWord[] = [
  // reizen
  {
    id: 'reis',
    word: 'reis',
    level: 'A2',
    theme: 'reizen',
    exampleSentence: 'De reis duurt twee uur.',
  },
  {
    id: 'reizen',
    word: 'reizen',
    level: 'A2',
    theme: 'reizen',
    exampleSentence: 'Ik reis graag naar Italië.',
  },
  {
    id: 'reiziger',
    word: 'reiziger',
    level: 'A2',
    theme: 'reizen',
    exampleSentence: 'De reiziger wacht op de trein.',
  },
  {
    id: 'station',
    word: 'station',
    level: 'A2',
    theme: 'reizen',
    grammar: '(het)',
    exampleSentence: 'Het station is vlakbij.',
  },
  {
    id: 'vliegen',
    word: 'vliegen',
    level: 'A2',
    theme: 'reizen',
    exampleSentence: 'We vliegen naar Spanje.',
  },
  {
    id: 'vliegtuig',
    word: 'vliegtuig',
    level: 'A2',
    theme: 'reizen',
    grammar: '(het)',
    exampleSentence: 'Het vliegtuig vertrekt om tien uur.',
  },
  {
    id: 'boot',
    word: 'boot',
    level: 'A2',
    theme: 'reizen',
    exampleSentence: 'We gaan met de boot.',
  },
  {
    id: 'vertrekken',
    word: 'vertrekken',
    level: 'A2',
    theme: 'reizen',
    exampleSentence: 'De trein vertrekt om drie uur.',
  },
  {
    id: 'aankomen',
    word: 'aankomen',
    level: 'A2',
    theme: 'reizen',
    exampleSentence: 'We komen om vijf uur aan.',
  },
  {
    id: 'aankomst',
    word: 'aankomst',
    level: 'A2',
    theme: 'reizen',
    exampleSentence: 'De aankomst is om acht uur.',
  },
  {
    id: 'vertrek',
    word: 'vertrek',
    level: 'A2',
    theme: 'reizen',
    grammar: '(het)',
    exampleSentence: 'Het vertrek is vertraagd.',
  },
  {
    id: 'kaart',
    word: 'kaart',
    level: 'A2',
    theme: 'reizen',
    exampleSentence: 'Ik heb een kaart van de stad.',
  },
  {
    id: 'bagage',
    word: 'bagage',
    level: 'A2',
    theme: 'reizen',
    exampleSentence: 'Mijn bagage is zwaar.',
  },
  {
    id: 'koffer',
    word: 'koffer',
    level: 'A2',
    theme: 'reizen',
    exampleSentence: 'Ik pak mijn koffer in.',
  },
  {
    id: 'hotel',
    word: 'hotel',
    level: 'A2',
    theme: 'reizen',
    grammar: '(het)',
    exampleSentence: 'We slapen in een hotel.',
  },
  {
    id: 'toerist',
    word: 'toerist',
    level: 'A2',
    theme: 'reizen',
    exampleSentence: 'De toerist maakt een foto.',
  },
  {
    id: 'richting',
    word: 'richting',
    level: 'A2',
    theme: 'reizen',
    exampleSentence: 'In welke richting moet ik?',
  },
  {
    id: 'retour',
    word: 'retour',
    level: 'A2',
    theme: 'reizen',
    grammar: '(het)',
    exampleSentence: 'Ik wil een retour naar Amsterdam.',
  },
  {
    id: 'brommer',
    word: 'brommer',
    level: 'A2',
    theme: 'reizen',
    exampleSentence: 'Hij rijdt op een brommer.',
  },
  {
    id: 'varen',
    word: 'varen',
    level: 'A2',
    theme: 'reizen',
    exampleSentence: 'We varen over de gracht.',
  },
  {
    id: 'haven',
    word: 'haven',
    level: 'A2',
    theme: 'reizen',
    exampleSentence: 'De haven van Rotterdam is groot.',
  },
  {
    id: 'parkeren',
    word: 'parkeren',
    level: 'A2',
    theme: 'reizen',
    exampleSentence: 'Je mag hier niet parkeren.',
  },
  {
    id: 'kruispunt',
    word: 'kruispunt',
    level: 'A2',
    theme: 'reizen',
    grammar: '(het)',
    exampleSentence: 'Stop bij het kruispunt.',
  },
  {
    id: 'oversteken',
    word: 'oversteken',
    level: 'A2',
    theme: 'reizen',
    exampleSentence: 'Kijk uit als je oversteekt.',
  },
  {
    id: 'instappen',
    word: 'instappen',
    level: 'A2',
    theme: 'reizen',
    exampleSentence: 'We stappen in de trein.',
  },
  {
    id: 'uitstappen',
    word: 'uitstappen',
    level: 'A2',
    theme: 'reizen',
    exampleSentence: 'Ik stap uit bij het volgende station.',
  },
  {
    id: 'afstand',
    word: 'afstand',
    level: 'A2',
    theme: 'reizen',
    exampleSentence: 'De afstand is tien kilometer.',
  },
  {
    id: 'kilometer',
    word: 'kilometer',
    level: 'A2',
    theme: 'reizen',
    exampleSentence: 'Het is twee kilometer lopen.',
  },
  {
    id: 'chauffeur',
    word: 'chauffeur',
    level: 'A2',
    theme: 'reizen',
    exampleSentence: 'De chauffeur rijdt de bus.',
  },
  // werk
  {
    id: 'werk',
    word: 'werk',
    level: 'A2',
    theme: 'werk',
    grammar: '(het)',
    exampleSentence: 'Ik ga naar mijn werk.',
  },
  {
    id: 'werken',
    word: 'werken',
    level: 'A2',
    theme: 'werk',
    exampleSentence: 'Ik werk in een winkel.',
  },
  {
    id: 'baan',
    word: 'baan',
    level: 'A2',
    theme: 'werk',
    exampleSentence: 'Ik zoek een nieuwe baan.',
  },
  {
    id: 'kantoor',
    word: 'kantoor',
    level: 'A2',
    theme: 'werk',
    grammar: '(het)',
    exampleSentence: 'Ik werk op kantoor.',
  },
  { id: 'baas', word: 'baas', level: 'A2', theme: 'werk', exampleSentence: 'De baas is aardig.' },
  {
    id: 'collega',
    word: 'collega',
    level: 'A2',
    theme: 'werk',
    exampleSentence: 'Mijn collega helpt mij.',
  },
  {
    id: 'chef',
    word: 'chef',
    level: 'A2',
    theme: 'werk',
    exampleSentence: 'De chef geeft opdrachten.',
  },
  {
    id: 'directeur',
    word: 'directeur',
    level: 'A2',
    theme: 'werk',
    exampleSentence: 'De directeur leidt het bedrijf.',
  },
  {
    id: 'bedrijf',
    word: 'bedrijf',
    level: 'A2',
    theme: 'werk',
    grammar: '(het)',
    exampleSentence: 'Het bedrijf heeft veel werknemers.',
  },
  {
    id: 'fabriek',
    word: 'fabriek',
    level: 'A2',
    theme: 'werk',
    exampleSentence: 'Hij werkt in een fabriek.',
  },
  {
    id: 'beroep',
    word: 'beroep',
    level: 'A2',
    theme: 'werk',
    grammar: '(het)',
    exampleSentence: 'Wat is je beroep?',
  },
  {
    id: 'ervaring',
    word: 'ervaring',
    level: 'A2',
    theme: 'werk',
    exampleSentence: 'Ik heb twee jaar ervaring.',
  },
  {
    id: 'loon',
    word: 'loon',
    level: 'A2',
    theme: 'werk',
    grammar: '(het)',
    exampleSentence: 'Het loon is goed.',
  },
  {
    id: 'verdienen',
    word: 'verdienen',
    level: 'A2',
    theme: 'werk',
    exampleSentence: 'Ik verdien genoeg geld.',
  },
  {
    id: 'arts',
    word: 'arts',
    level: 'A2',
    theme: 'werk',
    exampleSentence: 'De arts onderzoekt de patiënt.',
  },
  {
    id: 'dokter',
    word: 'dokter',
    level: 'A2',
    theme: 'werk',
    exampleSentence: 'Ik ga naar de dokter.',
  },
  {
    id: 'leraar',
    word: 'leraar',
    level: 'A2',
    theme: 'werk',
    exampleSentence: 'De leraar geeft les.',
  },
  {
    id: 'agent',
    word: 'agent',
    level: 'A2',
    theme: 'werk',
    exampleSentence: 'De agent helpt de mensen.',
  },
  {
    id: 'boer',
    word: 'boer',
    level: 'A2',
    theme: 'werk',
    exampleSentence: 'De boer werkt op het land.',
  },
  {
    id: 'kapper',
    word: 'kapper',
    level: 'A2',
    theme: 'werk',
    exampleSentence: 'Ik ga naar de kapper.',
  },
  {
    id: 'soldaat',
    word: 'soldaat',
    level: 'A2',
    theme: 'werk',
    exampleSentence: 'De soldaat draagt een uniform.',
  },
  {
    id: 'werkgever',
    word: 'werkgever',
    level: 'A2',
    theme: 'werk',
    exampleSentence: 'Mijn werkgever is tevreden.',
  },
  {
    id: 'werknemer',
    word: 'werknemer',
    level: 'A2',
    theme: 'werk',
    exampleSentence: 'Het bedrijf heeft honderd werknemers.',
  },
  // gezondheid
  {
    id: 'gezondheid',
    word: 'gezondheid',
    level: 'A2',
    theme: 'gezondheid',
    exampleSentence: 'Gezondheid is belangrijk.',
  },
  {
    id: 'pijn',
    word: 'pijn',
    level: 'A2',
    theme: 'gezondheid',
    exampleSentence: 'Ik heb pijn in mijn rug.',
  },
  {
    id: 'ziekenhuis',
    word: 'ziekenhuis',
    level: 'A2',
    theme: 'gezondheid',
    grammar: '(het)',
    exampleSentence: 'Hij ligt in het ziekenhuis.',
  },
  {
    id: 'ziekte',
    word: 'ziekte',
    level: 'A2',
    theme: 'gezondheid',
    exampleSentence: 'Het is een ernstige ziekte.',
  },
  {
    id: 'medicijn',
    word: 'medicijn',
    level: 'A2',
    theme: 'gezondheid',
    grammar: '(het)',
    exampleSentence: 'Ik neem mijn medicijn.',
  },
  {
    id: 'apotheek',
    word: 'apotheek',
    level: 'A2',
    theme: 'gezondheid',
    exampleSentence: 'Ik haal medicijnen bij de apotheek.',
  },
  {
    id: 'patiënt',
    word: 'patiënt',
    level: 'A2',
    theme: 'gezondheid',
    exampleSentence: 'De patiënt wacht op de dokter.',
  },
  {
    id: 'verkouden',
    word: 'verkouden',
    level: 'A2',
    theme: 'gezondheid',
    exampleSentence: 'Ik ben verkouden.',
  },
  {
    id: 'dood',
    word: 'dood',
    level: 'A2',
    theme: 'gezondheid',
    exampleSentence: 'De plant is dood.',
  },
  {
    id: 'leven-noun',
    word: 'leven',
    level: 'A2',
    theme: 'gezondheid',
    grammar: '(het)',
    exampleSentence: 'Het leven is mooi.',
  },
  {
    id: 'leven-verb',
    word: 'leven',
    level: 'A2',
    theme: 'gezondheid',
    exampleSentence: 'Mijn oma leeft nog.',
  },
  {
    id: 'sterven',
    word: 'sterven',
    level: 'A2',
    theme: 'gezondheid',
    exampleSentence: 'De bloem sterft zonder water.',
  },
  {
    id: 'blind',
    word: 'blind',
    level: 'A2',
    theme: 'gezondheid',
    exampleSentence: 'De man is blind.',
  },
  {
    id: 'rust',
    word: 'rust',
    level: 'A2',
    theme: 'gezondheid',
    exampleSentence: 'Je hebt rust nodig.',
  },
  {
    id: 'rusten',
    word: 'rusten',
    level: 'A2',
    theme: 'gezondheid',
    exampleSentence: 'Ik ga even rusten.',
  },
  // school
  {
    id: 'school',
    word: 'school',
    level: 'A2',
    theme: 'school',
    exampleSentence: 'De kinderen gaan naar school.',
  },
  {
    id: 'les',
    word: 'les',
    level: 'A2',
    theme: 'school',
    exampleSentence: 'De les begint om negen uur.',
  },
  {
    id: 'leerling',
    word: 'leerling',
    level: 'A2',
    theme: 'school',
    exampleSentence: 'Er zijn dertig leerlingen in de klas.',
  },
  {
    id: 'student',
    word: 'student',
    level: 'A2',
    theme: 'school',
    exampleSentence: 'De student studeert geneeskunde.',
  },
  {
    id: 'studeren',
    word: 'studeren',
    level: 'A2',
    theme: 'school',
    exampleSentence: 'Ik studeer Nederlands.',
  },
  {
    id: 'studie',
    word: 'studie',
    level: 'A2',
    theme: 'school',
    exampleSentence: 'Mijn studie duurt vier jaar.',
  },
  {
    id: 'examen',
    word: 'examen',
    level: 'A2',
    theme: 'school',
    grammar: '(het)',
    exampleSentence: 'Ik heb morgen examen.',
  },
  {
    id: 'diploma',
    word: 'diploma',
    level: 'A2',
    theme: 'school',
    grammar: '(het)',
    exampleSentence: 'Ik heb mijn diploma gehaald.',
  },
  {
    id: 'oefenen',
    word: 'oefenen',
    level: 'A2',
    theme: 'school',
    exampleSentence: 'Ik oefen elke dag Nederlands.',
  },
  {
    id: 'taal',
    word: 'taal',
    level: 'A2',
    theme: 'school',
    exampleSentence: 'Nederlands is een mooie taal.',
  },
  {
    id: 'tekst',
    word: 'tekst',
    level: 'A2',
    theme: 'school',
    exampleSentence: 'Lees de tekst hardop.',
  },
  {
    id: 'letter',
    word: 'letter',
    level: 'A2',
    theme: 'school',
    exampleSentence: 'Het alfabet heeft 26 letters.',
  },
  {
    id: 'woord',
    word: 'woord',
    level: 'A2',
    theme: 'school',
    grammar: '(het)',
    exampleSentence: 'Dit is een nieuw woord.',
  },
  {
    id: 'cijfer',
    word: 'cijfer',
    level: 'A2',
    theme: 'school',
    grammar: '(het)',
    exampleSentence: 'Ik heb een goed cijfer.',
  },
  { id: 'klas', word: 'klas', level: 'A2', theme: 'school', exampleSentence: 'De klas is groot.' },
  {
    id: 'universiteit',
    word: 'universiteit',
    level: 'A2',
    theme: 'school',
    exampleSentence: 'Hij studeert aan de universiteit.',
  },
  {
    id: 'cursus',
    word: 'cursus',
    level: 'A2',
    theme: 'school',
    exampleSentence: 'Ik volg een cursus Nederlands.',
  },
  {
    id: 'kennis',
    word: 'kennis',
    level: 'A2',
    theme: 'school',
    exampleSentence: 'Kennis is belangrijk.',
  },
  {
    id: 'begrijpen',
    word: 'begrijpen',
    level: 'A2',
    theme: 'school',
    exampleSentence: 'Ik begrijp het niet.',
  },
  {
    id: 'uitleggen',
    word: 'uitleggen',
    level: 'A2',
    theme: 'school',
    exampleSentence: 'Kun je dat uitleggen?',
  },
  {
    id: 'opleiding',
    word: 'opleiding',
    level: 'A2',
    theme: 'school',
    exampleSentence: 'Welke opleiding heb je?',
  },
  {
    id: 'herhalen',
    word: 'herhalen',
    level: 'A2',
    theme: 'school',
    exampleSentence: 'Kun je dat herhalen?',
  },
  // winkelen
  {
    id: 'winkelen',
    word: 'winkelen',
    level: 'A2',
    theme: 'boodschappen',
    exampleSentence: 'Ik ga winkelen in de stad.',
  },
  {
    id: 'passen',
    word: 'passen',
    level: 'A2',
    theme: 'boodschappen',
    exampleSentence: 'Mag ik deze broek passen?',
  },
  {
    id: 'maat',
    word: 'maat',
    level: 'A2',
    theme: 'boodschappen',
    exampleSentence: 'Welke maat draag je?',
  },
  {
    id: 'klant',
    word: 'klant',
    level: 'A2',
    theme: 'boodschappen',
    exampleSentence: 'De klant wacht bij de kassa.',
  },
  {
    id: 'bestellen',
    word: 'bestellen',
    level: 'A2',
    theme: 'boodschappen',
    exampleSentence: 'Ik wil graag bestellen.',
  },
  {
    id: 'rekening',
    word: 'rekening',
    level: 'A2',
    theme: 'boodschappen',
    exampleSentence: 'Mag ik de rekening?',
  },
  {
    id: 'kosten',
    word: 'kosten',
    level: 'A2',
    theme: 'boodschappen',
    exampleSentence: 'Hoeveel kost dit?',
  },
  {
    id: 'verkopen',
    word: 'verkopen',
    level: 'A2',
    theme: 'boodschappen',
    exampleSentence: 'De winkel verkoopt schoenen.',
  },
  {
    id: 'reserveren',
    word: 'reserveren',
    level: 'A2',
    theme: 'boodschappen',
    exampleSentence: 'Ik wil een tafel reserveren.',
  },
  {
    id: 'restaurant',
    word: 'restaurant',
    level: 'A2',
    theme: 'boodschappen',
    grammar: '(het)',
    exampleSentence: 'We eten in een restaurant.',
  },
  {
    id: 'café',
    word: 'café',
    level: 'A2',
    theme: 'boodschappen',
    grammar: '(het)',
    exampleSentence: 'We zitten in het café.',
  },
  // geld
  { id: 'bank', word: 'bank', level: 'A2', theme: 'geld', exampleSentence: 'Ik ga naar de bank.' },
  {
    id: 'rekenen',
    word: 'rekenen',
    level: 'A2',
    theme: 'geld',
    exampleSentence: 'Ik kan goed rekenen.',
  },
  {
    id: 'bedrag',
    word: 'bedrag',
    level: 'A2',
    theme: 'geld',
    grammar: '(het)',
    exampleSentence: 'Het bedrag is honderd euro.',
  },
  {
    id: 'belasting',
    word: 'belasting',
    level: 'A2',
    theme: 'geld',
    exampleSentence: 'Iedereen betaalt belasting.',
  },
  {
    id: 'lenen',
    word: 'lenen',
    level: 'A2',
    theme: 'geld',
    exampleSentence: 'Mag ik je pen lenen?',
  },
  // dagelijks
  {
    id: 'afspraak',
    word: 'afspraak',
    level: 'A2',
    theme: 'dagelijks',
    exampleSentence: 'Ik heb een afspraak bij de dokter.',
  },
  {
    id: 'telefoneren',
    word: 'telefoneren',
    level: 'A2',
    theme: 'dagelijks',
    exampleSentence: 'Ik moet even telefoneren.',
  },
  {
    id: 'bellen',
    word: 'bellen',
    level: 'A2',
    theme: 'dagelijks',
    exampleSentence: 'Ik bel je morgen.',
  },
  {
    id: 'opbellen',
    word: 'opbellen',
    level: 'A2',
    theme: 'dagelijks',
    exampleSentence: 'Ik bel je vanavond op.',
  },
  {
    id: 'post',
    word: 'post',
    level: 'A2',
    theme: 'dagelijks',
    exampleSentence: 'Er is post voor je.',
  },
  {
    id: 'brief',
    word: 'brief',
    level: 'A2',
    theme: 'dagelijks',
    exampleSentence: 'Ik schrijf een brief.',
  },
  {
    id: 'bericht',
    word: 'bericht',
    level: 'A2',
    theme: 'dagelijks',
    grammar: '(het)',
    exampleSentence: 'Ik stuur je een bericht.',
  },
  {
    id: 'informatie',
    word: 'informatie',
    level: 'A2',
    theme: 'dagelijks',
    exampleSentence: 'Ik zoek informatie.',
  },
  {
    id: 'probleem',
    word: 'probleem',
    level: 'A2',
    theme: 'dagelijks',
    grammar: '(het)',
    exampleSentence: 'Er is een probleem.',
  },
  {
    id: 'oplossing',
    word: 'oplossing',
    level: 'A2',
    theme: 'dagelijks',
    exampleSentence: 'We zoeken een oplossing.',
  },
  {
    id: 'keuze',
    word: 'keuze',
    level: 'A2',
    theme: 'dagelijks',
    exampleSentence: 'Je hebt een goede keuze gemaakt.',
  },
  {
    id: 'kiezen',
    word: 'kiezen',
    level: 'A2',
    theme: 'dagelijks',
    exampleSentence: 'Je mag zelf kiezen.',
  },
  {
    id: 'wassen',
    word: 'wassen',
    level: 'A2',
    theme: 'dagelijks',
    exampleSentence: 'Ik was mijn handen.',
  },
  {
    id: 'schoonmaken',
    word: 'schoonmaken',
    level: 'A2',
    theme: 'dagelijks',
    exampleSentence: 'Ik maak het huis schoon.',
  },
  {
    id: 'schoon',
    word: 'schoon',
    level: 'A2',
    theme: 'dagelijks',
    exampleSentence: 'De keuken is schoon.',
  },
  {
    id: 'vuil',
    word: 'vuil',
    level: 'A2',
    theme: 'dagelijks',
    exampleSentence: 'De vloer is vuil.',
  },
  {
    id: 'aankleden',
    word: 'aankleden',
    level: 'A2',
    theme: 'dagelijks',
    exampleSentence: 'Ik kleed me snel aan.',
  },
  {
    id: 'uitkleden',
    word: 'uitkleden',
    level: 'A2',
    theme: 'dagelijks',
    exampleSentence: 'De kinderen kleden zich uit.',
  },
  {
    id: 'opstaan',
    word: 'opstaan',
    level: 'A2',
    theme: 'dagelijks',
    exampleSentence: 'Ik sta om zeven uur op.',
  },
  {
    id: 'thuiskomen',
    word: 'thuiskomen',
    level: 'A2',
    theme: 'dagelijks',
    exampleSentence: 'Ik kom om zes uur thuis.',
  },
  {
    id: 'uitnodigen',
    word: 'uitnodigen',
    level: 'A2',
    theme: 'dagelijks',
    exampleSentence: 'Ik nodig je uit voor het feest.',
  },
  {
    id: 'bezoek',
    word: 'bezoek',
    level: 'A2',
    theme: 'dagelijks',
    grammar: '(het)',
    exampleSentence: 'We krijgen bezoek.',
  },
  {
    id: 'bezoeken',
    word: 'bezoeken',
    level: 'A2',
    theme: 'dagelijks',
    exampleSentence: 'Ik bezoek mijn oma.',
  },
  {
    id: 'verhuizen',
    word: 'verhuizen',
    level: 'A2',
    theme: 'dagelijks',
    exampleSentence: 'We verhuizen naar een nieuw huis.',
  },
  {
    id: 'regel',
    word: 'regel',
    level: 'A2',
    theme: 'dagelijks',
    exampleSentence: 'Dat is de regel.',
  },
  {
    id: 'regelen',
    word: 'regelen',
    level: 'A2',
    theme: 'dagelijks',
    exampleSentence: 'Ik regel alles voor het feest.',
  },
  // mening & gevoelens
  {
    id: 'blij-a2',
    word: 'blij',
    level: 'A2',
    theme: 'mening',
    exampleSentence: 'Ik ben blij met het cadeau.',
  },
  {
    id: 'gelukkig',
    word: 'gelukkig',
    level: 'A2',
    theme: 'mening',
    exampleSentence: 'Ik ben heel gelukkig.',
  },
  {
    id: 'verdriet',
    word: 'verdriet',
    level: 'A2',
    theme: 'mening',
    grammar: '(het)',
    exampleSentence: 'Ik heb veel verdriet.',
  },
  {
    id: 'bedroefd',
    word: 'bedroefd',
    level: 'A2',
    theme: 'mening',
    exampleSentence: 'Zij is bedroefd.',
  },
  {
    id: 'angstig',
    word: 'angstig',
    level: 'A2',
    theme: 'mening',
    exampleSentence: 'Het kind is angstig.',
  },
  {
    id: 'angst',
    word: 'angst',
    level: 'A2',
    theme: 'mening',
    exampleSentence: 'Ik heb angst voor spinnen.',
  },
  {
    id: 'eenzaam',
    word: 'eenzaam',
    level: 'A2',
    theme: 'mening',
    exampleSentence: 'De oude man voelt zich eenzaam.',
  },
  {
    id: 'zenuwachtig',
    word: 'zenuwachtig',
    level: 'A2',
    theme: 'mening',
    exampleSentence: 'Ik ben zenuwachtig voor het examen.',
  },
  {
    id: 'tevreden',
    word: 'tevreden',
    level: 'A2',
    theme: 'mening',
    exampleSentence: 'Ik ben tevreden met mijn werk.',
  },
  {
    id: 'trots',
    word: 'trots',
    level: 'A2',
    theme: 'mening',
    exampleSentence: 'Ik ben trots op mijn kinderen.',
  },
  {
    id: 'liefde',
    word: 'liefde',
    level: 'A2',
    theme: 'mening',
    exampleSentence: 'Liefde is mooi.',
  },
  { id: 'lief', word: 'lief', level: 'A2', theme: 'mening', exampleSentence: 'Wat lief van je!' },
  {
    id: 'hopen',
    word: 'hopen',
    level: 'A2',
    theme: 'mening',
    exampleSentence: 'Ik hoop dat het goed gaat.',
  },
  {
    id: 'hoop',
    word: 'hoop',
    level: 'A2',
    theme: 'mening',
    exampleSentence: 'Ik heb hoop voor de toekomst.',
  },
  {
    id: 'geloven',
    word: 'geloven',
    level: 'A2',
    theme: 'mening',
    exampleSentence: 'Ik geloof je.',
  },
  {
    id: 'mening',
    word: 'mening',
    level: 'A2',
    theme: 'mening',
    exampleSentence: 'Wat is jouw mening?',
  },
  {
    id: 'vreugde',
    word: 'vreugde',
    level: 'A2',
    theme: 'mening',
    exampleSentence: 'Het was een dag vol vreugde.',
  },
  {
    id: 'geluk',
    word: 'geluk',
    level: 'A2',
    theme: 'mening',
    grammar: '(het)',
    exampleSentence: 'Ik wens je veel geluk.',
  },
  {
    id: 'spijten',
    word: 'spijten',
    level: 'A2',
    theme: 'mening',
    exampleSentence: 'Het spijt me.',
  },
  {
    id: 'jammer',
    word: 'jammer',
    level: 'A2',
    theme: 'mening',
    exampleSentence: 'Jammer dat je niet kunt komen.',
  },
  {
    id: 'vrolijk',
    word: 'vrolijk',
    level: 'A2',
    theme: 'mening',
    exampleSentence: 'Het is een vrolijk feest.',
  },
  {
    id: 'somber',
    word: 'somber',
    level: 'A2',
    theme: 'mening',
    exampleSentence: 'Het weer is somber vandaag.',
  },
  {
    id: 'gezellig',
    word: 'gezellig',
    level: 'A2',
    theme: 'mening',
    exampleSentence: 'Het is gezellig bij jullie.',
  },
  {
    id: 'interessant',
    word: 'interessant',
    level: 'A2',
    theme: 'mening',
    exampleSentence: 'Het boek is heel interessant.',
  },
  {
    id: 'belangrijk',
    word: 'belangrijk',
    level: 'A2',
    theme: 'mening',
    exampleSentence: 'Dit is heel belangrijk.',
  },
  {
    id: 'moeilijk',
    word: 'moeilijk',
    level: 'A2',
    theme: 'mening',
    exampleSentence: 'Nederlands is soms moeilijk.',
  },
  {
    id: 'makkelijk',
    word: 'makkelijk',
    level: 'A2',
    theme: 'mening',
    exampleSentence: 'Dit is heel makkelijk.',
  },
  {
    id: 'eerlijk',
    word: 'eerlijk',
    level: 'A2',
    theme: 'mening',
    exampleSentence: 'Wees eerlijk.',
  },
  {
    id: 'aardig',
    word: 'aardig',
    level: 'A2',
    theme: 'mening',
    exampleSentence: 'Zij is heel aardig.',
  },
  {
    id: 'vriendelijk',
    word: 'vriendelijk',
    level: 'A2',
    theme: 'mening',
    exampleSentence: 'De buren zijn heel vriendelijk.',
  },
  {
    id: 'beleefd',
    word: 'beleefd',
    level: 'A2',
    theme: 'mening',
    exampleSentence: 'Het is beleefd om te groeten.',
  },
  {
    id: 'slim',
    word: 'slim',
    level: 'A2',
    theme: 'mening',
    exampleSentence: 'Dat is een slimme oplossing.',
  },
  {
    id: 'dom',
    word: 'dom',
    level: 'A2',
    theme: 'mening',
    exampleSentence: 'Dat was een domme fout.',
  },
  {
    id: 'sterk',
    word: 'sterk',
    level: 'A2',
    theme: 'mening',
    exampleSentence: 'Hij is heel sterk.',
  },
  { id: 'zwak', word: 'zwak', level: 'A2', theme: 'mening', exampleSentence: 'Ik voel me zwak.' },
  { id: 'rustig', word: 'rustig', level: 'A2', theme: 'mening', exampleSentence: 'Blijf rustig.' },
  {
    id: 'druk',
    word: 'druk',
    level: 'A2',
    theme: 'mening',
    exampleSentence: 'Ik heb het heel druk.',
  },
  {
    id: 'veilig',
    word: 'veilig',
    level: 'A2',
    theme: 'mening',
    exampleSentence: 'Dit is een veilige buurt.',
  },
  {
    id: 'gevaarlijk',
    word: 'gevaarlijk',
    level: 'A2',
    theme: 'mening',
    exampleSentence: 'Dat is gevaarlijk!',
  },
  {
    id: 'lachen',
    word: 'lachen',
    level: 'A2',
    theme: 'mening',
    exampleSentence: 'De kinderen lachen hard.',
  },
  {
    id: 'huilen',
    word: 'huilen',
    level: 'A2',
    theme: 'mening',
    exampleSentence: 'Het kind huilt.',
  },
  {
    id: 'schreeuwen',
    word: 'schreeuwen',
    level: 'A2',
    theme: 'mening',
    exampleSentence: 'Niet zo schreeuwen!',
  },
  {
    id: 'fluisteren',
    word: 'fluisteren',
    level: 'A2',
    theme: 'mening',
    exampleSentence: 'Ze fluistert een geheim.',
  },
  // overig — common A2 words
  {
    id: 'proberen',
    word: 'proberen',
    level: 'A2',
    theme: 'overig',
    exampleSentence: 'Ik probeer het opnieuw.',
  },
  {
    id: 'lukken',
    word: 'lukken',
    level: 'A2',
    theme: 'overig',
    exampleSentence: 'Het lukt me niet.',
  },
  {
    id: 'vergeten',
    word: 'vergeten',
    level: 'A2',
    theme: 'overig',
    exampleSentence: 'Ik ben mijn sleutel vergeten.',
  },
  {
    id: 'herinneren',
    word: 'herinneren',
    level: 'A2',
    theme: 'overig',
    exampleSentence: 'Ik herinner me die dag.',
  },
  {
    id: 'bewegen',
    word: 'bewegen',
    level: 'A2',
    theme: 'overig',
    exampleSentence: 'Je moet meer bewegen.',
  },
  {
    id: 'rennen',
    word: 'rennen',
    level: 'A2',
    theme: 'overig',
    exampleSentence: 'De kinderen rennen door het park.',
  },
  {
    id: 'klimmen',
    word: 'klimmen',
    level: 'A2',
    theme: 'overig',
    exampleSentence: 'De kat klimt in de boom.',
  },
  {
    id: 'vallen',
    word: 'vallen',
    level: 'A2',
    theme: 'overig',
    exampleSentence: 'Pas op dat je niet valt!',
  },
  {
    id: 'breken',
    word: 'breken',
    level: 'A2',
    theme: 'overig',
    exampleSentence: 'Ik heb een glas gebroken.',
  },
  {
    id: 'gooien',
    word: 'gooien',
    level: 'A2',
    theme: 'overig',
    exampleSentence: 'Gooi de bal naar mij.',
  },
  {
    id: 'draaien',
    word: 'draaien',
    level: 'A2',
    theme: 'overig',
    exampleSentence: 'Draai naar links.',
  },
  {
    id: 'trekken',
    word: 'trekken',
    level: 'A2',
    theme: 'overig',
    exampleSentence: 'Trek aan de deur.',
  },
  {
    id: 'duwen',
    word: 'duwen',
    level: 'A2',
    theme: 'overig',
    exampleSentence: 'Duw de deur open.',
  },
  {
    id: 'vullen',
    word: 'vullen',
    level: 'A2',
    theme: 'overig',
    exampleSentence: 'Ik vul het glas met water.',
  },
  {
    id: 'snijden',
    word: 'snijden',
    level: 'A2',
    theme: 'overig',
    exampleSentence: 'Ik snijd het brood.',
  },
  {
    id: 'kloppen',
    word: 'kloppen',
    level: 'A2',
    theme: 'overig',
    exampleSentence: 'Er klopt iemand op de deur.',
  },
  {
    id: 'zoeken',
    word: 'zoeken',
    level: 'A2',
    theme: 'overig',
    exampleSentence: 'Ik zoek mijn sleutel.',
  },
  {
    id: 'ontdekken',
    word: 'ontdekken',
    level: 'A2',
    theme: 'overig',
    exampleSentence: 'Ik heb een leuk restaurant ontdekt.',
  },
  {
    id: 'ontmoeten',
    word: 'ontmoeten',
    level: 'A2',
    theme: 'overig',
    exampleSentence: 'Ik ontmoet mijn vriend.',
  },
  {
    id: 'veranderen',
    word: 'veranderen',
    level: 'A2',
    theme: 'overig',
    exampleSentence: 'Het weer kan snel veranderen.',
  },
  {
    id: 'verliezen',
    word: 'verliezen',
    level: 'A2',
    theme: 'overig',
    exampleSentence: 'Ik heb mijn portemonnee verloren.',
  },
  {
    id: 'winnen',
    word: 'winnen',
    level: 'A2',
    theme: 'overig',
    exampleSentence: 'Nederland heeft gewonnen.',
  },
  {
    id: 'gebruiken',
    word: 'gebruiken',
    level: 'A2',
    theme: 'overig',
    exampleSentence: 'Ik gebruik de computer.',
  },
  {
    id: 'betekenen',
    word: 'betekenen',
    level: 'A2',
    theme: 'overig',
    exampleSentence: 'Wat betekent dit woord?',
  },
  {
    id: 'geluid',
    word: 'geluid',
    level: 'A2',
    theme: 'overig',
    grammar: '(het)',
    exampleSentence: 'Wat is dat geluid?',
  },
  {
    id: 'stilte',
    word: 'stilte',
    level: 'A2',
    theme: 'overig',
    exampleSentence: 'Er is stilte in de kamer.',
  },
  {
    id: 'ruimte',
    word: 'ruimte',
    level: 'A2',
    theme: 'overig',
    exampleSentence: 'Er is genoeg ruimte.',
  },
  {
    id: 'richting-a2',
    word: 'richting',
    level: 'A2',
    theme: 'overig',
    exampleSentence: 'We lopen in de richting van het park.',
  },
  {
    id: 'hoek',
    word: 'hoek',
    level: 'A2',
    theme: 'overig',
    exampleSentence: 'De winkel is om de hoek.',
  },
  {
    id: 'vorm',
    word: 'vorm',
    level: 'A2',
    theme: 'overig',
    exampleSentence: 'Wat is de vorm van het gebouw?',
  },
  {
    id: 'gewoon',
    word: 'gewoon',
    level: 'A2',
    theme: 'overig',
    exampleSentence: 'Het is heel gewoon.',
  },
  {
    id: 'speciaal',
    word: 'speciaal',
    level: 'A2',
    theme: 'overig',
    exampleSentence: 'Dit is een speciale dag.',
  },
  {
    id: 'bijzonder',
    word: 'bijzonder',
    level: 'A2',
    theme: 'overig',
    exampleSentence: 'Het was een bijzondere avond.',
  },
  { id: 'direct', word: 'direct', level: 'A2', theme: 'overig', exampleSentence: 'Ik kom direct.' },
  {
    id: 'eindelijk',
    word: 'eindelijk',
    level: 'A2',
    theme: 'overig',
    exampleSentence: 'Eindelijk is het weekend!',
  },
  {
    id: 'ongeveer',
    word: 'ongeveer',
    level: 'A2',
    theme: 'overig',
    exampleSentence: 'Het duurt ongeveer een uur.',
  },
  {
    id: 'precies',
    word: 'precies',
    level: 'A2',
    theme: 'overig',
    exampleSentence: 'Het is precies drie uur.',
  },
  {
    id: 'vooral',
    word: 'vooral',
    level: 'A2',
    theme: 'overig',
    exampleSentence: 'Ik hou vooral van kaas.',
  },
  {
    id: 'eigenlijk',
    word: 'eigenlijk',
    level: 'A2',
    theme: 'overig',
    exampleSentence: 'Eigenlijk wil ik thuis blijven.',
  },
  {
    id: 'natuurlijk',
    word: 'natuurlijk',
    level: 'A2',
    theme: 'overig',
    exampleSentence: 'Natuurlijk mag dat.',
  },
  {
    id: 'inderdaad',
    word: 'inderdaad',
    level: 'A2',
    theme: 'overig',
    exampleSentence: 'Ja, inderdaad.',
  },
  {
    id: 'bovendien',
    word: 'bovendien',
    level: 'A2',
    theme: 'overig',
    exampleSentence: 'Het is lekker, en bovendien gezond.',
  },
  {
    id: 'trouwens',
    word: 'trouwens',
    level: 'A2',
    theme: 'overig',
    exampleSentence: 'Trouwens, hoe gaat het met je?',
  },
  {
    id: 'anders',
    word: 'anders',
    level: 'A2',
    theme: 'overig',
    exampleSentence: 'Dit is anders dan ik dacht.',
  },
  {
    id: 'dezelfde',
    word: 'dezelfde',
    level: 'A2',
    theme: 'overig',
    exampleSentence: 'Wij wonen in dezelfde straat.',
  },
  {
    id: 'elk',
    word: 'elk',
    level: 'A2',
    theme: 'overig',
    exampleSentence: 'Elk kind krijgt een cadeau.',
  },
  {
    id: 'ieder',
    word: 'ieder',
    level: 'A2',
    theme: 'overig',
    exampleSentence: 'Ieder mens is anders.',
  },
  {
    id: 'iedereen',
    word: 'iedereen',
    level: 'A2',
    theme: 'overig',
    exampleSentence: 'Iedereen is welkom.',
  },
  { id: 'alles', word: 'alles', level: 'A2', theme: 'overig', exampleSentence: 'Alles is goed.' },
  {
    id: 'ergens',
    word: 'ergens',
    level: 'A2',
    theme: 'overig',
    exampleSentence: 'Het moet ergens liggen.',
  },
  {
    id: 'nergens',
    word: 'nergens',
    level: 'A2',
    theme: 'overig',
    exampleSentence: 'Ik kan het nergens vinden.',
  },
  {
    id: 'overal',
    word: 'overal',
    level: 'A2',
    theme: 'overig',
    exampleSentence: 'Er zijn overal bloemen.',
  },
  {
    id: 'steeds',
    word: 'steeds',
    level: 'A2',
    theme: 'overig',
    exampleSentence: 'Het wordt steeds beter.',
  },
  {
    id: 'daarna',
    word: 'daarna',
    level: 'A2',
    theme: 'overig',
    exampleSentence: 'Eerst eten, daarna afwassen.',
  },
  {
    id: 'daarom',
    word: 'daarom',
    level: 'A2',
    theme: 'overig',
    exampleSentence: 'Het regent, daarom blijf ik thuis.',
  },
  {
    id: 'terwijl',
    word: 'terwijl',
    level: 'A2',
    theme: 'overig',
    exampleSentence: 'Ik lees terwijl het regent.',
  },
  {
    id: 'totdat',
    word: 'totdat',
    level: 'A2',
    theme: 'overig',
    exampleSentence: 'Wacht totdat ik klaar ben.',
  },
  {
    id: 'sinds',
    word: 'sinds',
    level: 'A2',
    theme: 'overig',
    exampleSentence: 'Ik woon hier sinds 2020.',
  },
  {
    id: 'tijdens',
    word: 'tijdens',
    level: 'A2',
    theme: 'overig',
    exampleSentence: 'Niet praten tijdens de les.',
  },
  {
    id: 'nodig',
    word: 'nodig',
    level: 'A2',
    theme: 'overig',
    exampleSentence: 'Ik heb hulp nodig.',
  },
  {
    id: 'klaar-a2',
    word: 'klaar',
    level: 'A2',
    theme: 'overig',
    exampleSentence: 'Ben je klaar met eten?',
  },
  {
    id: 'eigen',
    word: 'eigen',
    level: 'A2',
    theme: 'overig',
    exampleSentence: 'Ik heb mijn eigen kamer.',
  },
  {
    id: 'voorbeeld',
    word: 'voorbeeld',
    level: 'A2',
    theme: 'overig',
    grammar: '(het)',
    exampleSentence: 'Geef een voorbeeld.',
  },
  {
    id: 'bijvoorbeeld',
    word: 'bijvoorbeeld',
    level: 'A2',
    theme: 'overig',
    exampleSentence: 'Ik hou van fruit, bijvoorbeeld appels.',
  },
  {
    id: 'situatie',
    word: 'situatie',
    level: 'A2',
    theme: 'overig',
    exampleSentence: 'Het is een lastige situatie.',
  },
  { id: 'reden', word: 'reden', level: 'A2', theme: 'overig', exampleSentence: 'Wat is de reden?' },
  {
    id: 'idee',
    word: 'idee',
    level: 'A2',
    theme: 'overig',
    grammar: '(het)',
    exampleSentence: 'Ik heb een goed idee.',
  },
  {
    id: 'plan',
    word: 'plan',
    level: 'A2',
    theme: 'overig',
    grammar: '(het)',
    exampleSentence: 'Wat is het plan voor vandaag?',
  },
  {
    id: 'verschil',
    word: 'verschil',
    level: 'A2',
    theme: 'overig',
    grammar: '(het)',
    exampleSentence: 'Wat is het verschil?',
  },
  {
    id: 'soort',
    word: 'soort',
    level: 'A2',
    theme: 'overig',
    grammar: '(het)',
    exampleSentence: 'Welk soort brood wil je?',
  },
  {
    id: 'deel',
    word: 'deel',
    level: 'A2',
    theme: 'overig',
    grammar: '(het)',
    exampleSentence: 'Dit is een deel van het plan.',
  },
  {
    id: 'begin',
    word: 'begin',
    level: 'A2',
    theme: 'overig',
    grammar: '(het)',
    exampleSentence: 'Het begin is moeilijk.',
  },
  {
    id: 'einde',
    word: 'einde',
    level: 'A2',
    theme: 'overig',
    grammar: '(het)',
    exampleSentence: 'Het einde van de film was mooi.',
  },
  {
    id: 'plaats',
    word: 'plaats',
    level: 'A2',
    theme: 'overig',
    exampleSentence: 'Is deze plaats vrij?',
  },
  {
    id: 'punt',
    word: 'punt',
    level: 'A2',
    theme: 'overig',
    grammar: '(het)',
    exampleSentence: 'Dat is een goed punt.',
  },
  {
    id: 'moment',
    word: 'moment',
    level: 'A2',
    theme: 'overig',
    grammar: '(het)',
    exampleSentence: 'Een moment, alstublieft.',
  },
  {
    id: 'keer',
    word: 'keer',
    level: 'A2',
    theme: 'overig',
    exampleSentence: 'Dit is de eerste keer.',
  },
  {
    id: 'manier',
    word: 'manier',
    level: 'A2',
    theme: 'overig',
    exampleSentence: 'Op welke manier doe je dat?',
  },
  {
    id: 'ding',
    word: 'ding',
    level: 'A2',
    theme: 'overig',
    grammar: '(het)',
    exampleSentence: 'Wat is dat voor ding?',
  },
  {
    id: 'stuk',
    word: 'stuk',
    level: 'A2',
    theme: 'overig',
    grammar: '(het)',
    exampleSentence: 'Mag ik een stuk taart?',
  },
  {
    id: 'kant',
    word: 'kant',
    level: 'A2',
    theme: 'overig',
    exampleSentence: 'Aan welke kant is de deur?',
  },
  {
    id: 'hoog',
    word: 'hoog',
    level: 'A2',
    theme: 'overig',
    exampleSentence: 'Het gebouw is heel hoog.',
  },
  {
    id: 'laag',
    word: 'laag',
    level: 'A2',
    theme: 'overig',
    exampleSentence: 'De tafel is te laag.',
  },
  {
    id: 'breed',
    word: 'breed',
    level: 'A2',
    theme: 'overig',
    exampleSentence: 'De rivier is breed.',
  },
  { id: 'smal', word: 'smal', level: 'A2', theme: 'overig', exampleSentence: 'De straat is smal.' },
  { id: 'hard', word: 'hard', level: 'A2', theme: 'overig', exampleSentence: 'Het regent hard.' },
  {
    id: 'zacht',
    word: 'zacht',
    level: 'A2',
    theme: 'overig',
    exampleSentence: 'Het kussen is zacht.',
  },
  {
    id: 'zwaar',
    word: 'zwaar',
    level: 'A2',
    theme: 'overig',
    exampleSentence: 'De koffer is zwaar.',
  },
  {
    id: 'licht-a2',
    word: 'licht',
    level: 'A2',
    theme: 'overig',
    exampleSentence: 'De tas is heel licht.',
  },
  { id: 'vol', word: 'vol', level: 'A2', theme: 'overig', exampleSentence: 'De bus is vol.' },
  { id: 'leeg', word: 'leeg', level: 'A2', theme: 'overig', exampleSentence: 'De fles is leeg.' },
  { id: 'juist', word: 'juist', level: 'A2', theme: 'overig', exampleSentence: 'Dat is juist.' },
  { id: 'fout', word: 'fout', level: 'A2', theme: 'overig', exampleSentence: 'Dat is een fout.' },
  {
    id: 'duidelijk',
    word: 'duidelijk',
    level: 'A2',
    theme: 'overig',
    exampleSentence: 'Is het duidelijk?',
  },
  {
    id: 'mogelijk',
    word: 'mogelijk',
    level: 'A2',
    theme: 'overig',
    exampleSentence: 'Is dat mogelijk?',
  },
  {
    id: 'onmogelijk',
    word: 'onmogelijk',
    level: 'A2',
    theme: 'overig',
    exampleSentence: 'Dat is onmogelijk!',
  },
  {
    id: 'bekend',
    word: 'bekend',
    level: 'A2',
    theme: 'overig',
    exampleSentence: 'Amsterdam is een bekende stad.',
  },
  { id: 'vreemd', word: 'vreemd', level: 'A2', theme: 'overig', exampleSentence: 'Dat is vreemd.' },
  {
    id: 'prachtig',
    word: 'prachtig',
    level: 'A2',
    theme: 'overig',
    exampleSentence: 'Het uitzicht is prachtig.',
  },
  {
    id: 'geweldig',
    word: 'geweldig',
    level: 'A2',
    theme: 'overig',
    exampleSentence: 'Dat is geweldig nieuws!',
  },
  {
    id: 'verschrikkelijk',
    word: 'verschrikkelijk',
    level: 'A2',
    theme: 'overig',
    exampleSentence: 'Het weer is verschrikkelijk.',
  },
  {
    id: 'enorm',
    word: 'enorm',
    level: 'A2',
    theme: 'overig',
    exampleSentence: 'Het gebouw is enorm.',
  },
  {
    id: 'beetje',
    word: 'beetje',
    level: 'A2',
    theme: 'overig',
    grammar: '(het)',
    exampleSentence: 'Ik spreek een beetje Nederlands.',
  },
  {
    id: 'genoeg',
    word: 'genoeg',
    level: 'A2',
    theme: 'overig',
    exampleSentence: 'Ik heb genoeg gegeten.',
  },
  {
    id: 'bijna',
    word: 'bijna',
    level: 'A2',
    theme: 'overig',
    exampleSentence: 'We zijn er bijna.',
  },
  {
    id: 'net',
    word: 'net',
    level: 'A2',
    theme: 'overig',
    exampleSentence: 'Ik ben net thuisgekomen.',
  },
  {
    id: 'tenminste',
    word: 'tenminste',
    level: 'A2',
    theme: 'overig',
    exampleSentence: 'Het is tenminste droog.',
  },
  {
    id: 'helemaal',
    word: 'helemaal',
    level: 'A2',
    theme: 'overig',
    exampleSentence: 'Ik ben helemaal klaar.',
  },
  { id: 'meteen', word: 'meteen', level: 'A2', theme: 'overig', exampleSentence: 'Ik kom meteen.' },
  {
    id: 'plotseling',
    word: 'plotseling',
    level: 'A2',
    theme: 'overig',
    exampleSentence: 'Plotseling begon het te regenen.',
  },
  {
    id: 'straks',
    word: 'straks',
    level: 'A2',
    theme: 'overig',
    exampleSentence: 'Ik ga straks naar huis.',
  },
  {
    id: 'binnenkort',
    word: 'binnenkort',
    level: 'A2',
    theme: 'overig',
    exampleSentence: 'Binnenkort ga ik op vakantie.',
  },
  {
    id: 'volgens',
    word: 'volgens',
    level: 'A2',
    theme: 'overig',
    exampleSentence: 'Volgens mij klopt dat.',
  },
];
